Sage/carbon

README.md
Replace relative path with absolute path so that it renders correctly on https://www.npmjs.com/package/carbon.js
=> Fix 404 for the carbon logo on npm

package.json
Bumps to RC3 as RC2 was missing the lib folder and had already been published to npm so can't overwrite.
=> Bump to RC3

src/utils/service/__spec__.js
Add `done` callback, and append to the response data in the call to `service.setTransformResponse` (instead of overwriting it).
=> Fix failing asynchronous test

CHANGELOG.md, package.json
Update `carbon-factory` to v0.3.6, which includes the `envify` fix to addresses the `illegal export declaration` error.
=> Illegal export declaration fix

CHANGELOG.md, src/components/confirm/confirm.js, src/components/dialog-full-screen/dialog-full-screen.js, src/components/dialog/dialog.js, src/components/flash/__spec__.js, src/components/flash/flash.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the modal components to pre-emptively resolve the errors.
- Alert (no linting errors found)
- Confirm
- Dialog
- DialogFullScreen
- Flash
There are no functional changes to the components.
Most of the changes are minor. The biggest were to the `Flash` component where I removed the usage of `bind` for `toggleDialog`. This required some updates to the specs where that function was being tested directly. I also introduced a default for the `timeout` prop of zero.
=> Modal component linting fixes

CHANGELOG.md, demo/utils/definition/table-definition/table-definition.js, src/components/action-toolbar/README.md, src/components/action-toolbar/__spec__.js, src/components/action-toolbar/action-toolbar.js, src/components/table-ajax/table-ajax.js, src/components/table/table-cell/definition.js, src/components/table/table-cell/table-cell.js, src/components/table/table-header/__spec__.js, src/components/table/table-header/definition.js, src/components/table/table-header/table-header.js, src/components/table/table-row/definition.js, src/components/table/table-row/table-row.js, src/components/table/table-subheader/definition.js, src/components/table/table.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `table` components to pre-emptively resolve the errors.
Updated components:
- ActionToolbar 
- Table
- TableAjax
- TableCell
- TableHeader
- TableRow
- TableSubHeader (no linting errors)
The biggest change is removing the usage of `.bind` in `ActionToolbar`. I added a spec to test the existing behaviour as the onClick handler allowed as part of the actions prop was not currently tested. I then added a separate commit to refactor out the usage of `.bind`.
=> Table component linting fixes

demo/i18n/en.js, demo/views/common/page-header-large/page-header-large.js
Swaps the hard coded text for the current version of `carbon-react` for a http://shields.io/ badge.
* Run demo site locally
* Observe change present as per screenshot above.
=> Swap version text for npm shields image

CHANGELOG.md, src/components/dropdown-filter-ajax/__spec__.js, src/components/dropdown-filter-ajax/dropdown-filter-ajax.js, src/components/dropdown-filter/__spec__.js, src/components/dropdown-filter/dropdown-filter.js, src/components/dropdown/__spec__.js, src/components/dropdown/dropdown.js, src/components/dropdown/dropdown.scss, src/style-config/mixins.scss
Currently, dropdown selects only render the options list if the
component is focused. This makes testing applications using browser
automation difficult as these options cannot be selected.
This PR ensures that the options are always rendered within the DOM, but
makes them hidden unless the component is focused.
* Note that a lot of the changes are fixes for associated tests where an array containing a single blank JS object was being passed as the options array.
=> Change dropdowns to always keep options in the DOM

src/components/alert/definition.js, src/components/confirm/definition.js, src/components/dialog/definition.js
Add the prop type and description for `subtitle` to the `Alert`, `Confirm`, and `Dialog` components.
Also sorted the prop types and descriptions in `Confirm`.
=> Add subtitle prop type and descriptions for demo site

src/components/drag-and-drop/with-drag/with-drag.js, src/components/drag-and-drop/with-drop/with-drop.js, src/components/table/draggable-table-cell/draggable-table-cell.scss
Clear the selected text in the drop target `hover` function, instead of in the drag source `endDrag` function. This fixes the issue where text was still selected during the drag operation in IE11.
Also increased the size of the drag handle: removed the padding from the `.draggable-table-cell` and applied it to the drag icon instead.
**NB** QA for this will be done on the main `dnd` branch
=> Fix drag and drop text selection issue in IE11

README.md
Use `master` image from shields.io - otherwise it just shows the status of the last build that codeship ran.
=> Fix codeship build image to use master branch

CHANGELOG.md, src/components/date-range/date-range.js, src/components/date/__spec__.js, src/components/date/date.js, src/components/date/definition.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `date` components to pre-emptively resolve the errors.
Updated components:
- Date
- DateRange
After QA feedback I have updated the props of the input to set disabled to true on the input if either `disabled` or `readOnly` are set to true by the developer.
**BEFORE**
**AFTER**
=> Date linting updates

CHANGELOG.md, src/components/app-wrapper/app-wrapper.js, src/components/content/content.js, src/components/detail/definition.js, src/components/detail/detail.js, src/components/heading/definition.js, src/components/heading/heading.js, src/components/i18n/i18n.js, src/components/mount-in-app/mount-in-app.js, src/components/pod/__spec__.js, src/components/pod/definition.js, src/components/pod/pod.js, src/components/pod/pod.scss, src/components/row/column/column.js, src/components/row/column/definition.js, src/components/row/definition.js, src/components/row/row.js, src/components/settings-row/settings-row.js, src/components/show-edit-pod/definition.js, src/components/show-edit-pod/show-edit-pod.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `layout` components to pre-emptively resolve the errors.
**Column**
The `column` component had `columnAlign`, `columnOffset`, `columnSpan` and `columnDivide` prop types all declared but these were not used.
**ShowEditPod**
After exploring the alternatives, I have ignored the rule for using `ReactDOM.findDOMNode`. In this instance the inputs are passed in as a prop and thus would need to be interrogated to pull out the first one to call focus on it. This feels more fragile than using `findDOMNode` to call focus on the Pod component.
Arguably setting auto focus on the inputs passed in should not be the responsibility of this …
=> Layout components linting updates

CHANGELOG.md, src/components/dropdown-filter-ajax/__spec__.js, src/components/dropdown-filter-ajax/dropdown-filter-ajax.js, src/components/dropdown-filter/dropdown-filter.js, src/components/dropdown/__spec__.js, src/components/dropdown/definition.js, src/components/dropdown/dropdown.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `dropdown` components to pre-emptively resolve the errors.
There are no functional changes to the components.
The Dropdown component was not specifically handling key presses other than `up`, `down` and `return`. The linter wanted a default case added to the case statement, so I've set it to set highlighted as null (previously it was setting it to undefined). This should not change the behaviour but I did need to add a spec to keep the coverage at 100%.
=> Dropdown component linting fixes

CHANGELOG.md, src/components/checkbox/checkbox.js, src/components/checkbox/definition.js, src/components/fieldset/fieldset.js, src/components/grouped-character/definition.js, src/components/grouped-character/grouped-character.js, src/components/radio-button/definition.js, src/components/radio-button/radio-button.js, src/components/textarea/__spec__.js, src/components/textarea/definition.js, src/components/textarea/textarea.js, src/components/textbox/textbox.js
To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `form` components to pre-emptively resolve the errors.
- I've set Checkbox `checked` and `value` prop types as boolean. Not 100% sure that is correct as it feels like some developers might have set them as strings.
- Form
- FormSummary
Linting updates for these components have been included in commit https://github.com/Sage/carbon/pull/1243/commits/92600a999d9acf09444ca7583e97614621e0fc97 which is in a separate PR.
=> Form linting updates

CHANGELOG.md, src/components/decimal/__spec__.js, src/components/decimal/decimal.js, src/components/decimal/definition.js
Add `name`, `value`, `onBlur`, and `onKeyDown` to props, and add `onBlur` and
`onKeyDown` to the definition's `hiddenProps`.
Fix whitespace issues.
Use `const` over `let`.
Disable the warning about the unused align prop, as it is used by the `Input`
decorator that is applied to this component.
Changes to some props, and how `refs` are referenced, caused some tests to
fail. These have been fixed.
=> Fix ESLint errors in Decimal component

CHANGELOG.md, src/components/create/create.js
Move `render` function to the end of the component, and use `const` over `let`.
Update release notes.
=> Fix ESLint errors in Create component

CHANGELOG.md, src/components/help/definition.js, src/components/help/help.js
Add `className` to props, add spaces before curly braces, replace double quotes with single quotes, and add `rel="noopener noreferrer"` to the link that opens in a new window.
=> Fix ESLint errors in Help component

CHANGELOG.md, src/components/number/definition.js, src/components/number/number.js
Add missing props, use `const` over `let`, fix whitespace issues.
Add `hiddenProps`, and `propDescriptions` to definition.
Update release notes.
=> Fix ESLint errors in Number component

CHANGELOG.md, src/components/icon/__spec__.js, src/components/icon/definition.js, src/components/icon/icon.js
Absolute imports before relative, missing props, whitespace, `const` over `let`, and line length.
Disabled the `react/no-danger` rule when using `dangerouselySetInnerHtml` when rendering the icon.
=> Fix ESLint errors in the Icon component

CHANGELOG.md, src/utils/flux/__spec__.js, src/utils/flux/flux.js, src/utils/logger/logger.js, src/utils/promises/promises.js, src/utils/router/router.js, src/utils/service/service.js
* In the flux.js there was a clash with the way the file is built (and used amongst the user base) that meant a line had to be over-ridden
* Point at the branch in an app like GAC and sense check a carbon area of the app, such as 'contacts' (this will cover the flux updates which aren't used in the demo site)
* Use this branch in s1_artefact_ui in order to test the services object (again, sense check)
* The rest can be covered by GAC / demo site sen checking
=> Five more linting files in Utils

CHANGELOG.md, src/utils/helpers/tags/__spec__.js, src/utils/helpers/tags/tags.js
* The root of the component is the correct place for a `data-component` tag, but if the user provides one, the Carbon defaults will be applied instead.
In the following example:
```
<Wrapper>
<AppComp data-role='x'/>
<AppComp data-role='x'/>
<AppComp data-role='z/>
<OtherComp data-role='1' />
<OtherComp data-role='2' />
</Wrapper>
```
If all five child components had `Pod` at their root level then they would all show up as `data-component='pod'` when `data-component='app-comp'` and `data-component='other-comp'` makes more sense.
The role needs to be kept unique, for identifying each individually and the element relates to the component's position within it's parent, so neither are correct.
Therefore, the `data-component` on the Carbon component should be over-ridden by a user provided …
=> data-component is now over-ridden if provided by the user

CHANGELOG.md, src/components/dropdown/__spec__.js, src/components/dropdown/dropdown.js
Link to original PR: https://github.com/Sage/carbon/pull/1336
Allowing dropdown list to use a function passed as a prop to render list items if prop present.
Otherwise option.name will be used
=> Dropdown list item renderer

CHANGELOG.md, src/components/menu/menu-item/menu-item.scss
=> Fix bug with focus outline on MenuItem component

CHANGELOG.md, src/components/form/__spec__.js, src/components/form/cancel-button/__spec__.js, src/components/form/cancel-button/cancel-button.js, src/components/form/cancel-button/package.json, src/components/form/definition.js, src/components/form/form-summary/form-summary.js, src/components/form/form-summary/form-summary.scss, src/components/form/form.js, src/components/form/form.scss, src/components/form/save-button/__spec__.js, src/components/form/save-button/package.json, src/components/form/save-button/save-button.js
This PR replaces the default `Save` and `Cancel` buttons in the form with functional stateless `SaveButton` and `CancelButton` components. The `SaveButton` can now be overridden with a user passing a `customSaveButton` node prop into the component.
This can be tested by ensuring that nothing has changed with default form behaviour. Additionally that the `customSaveButton` prop replaces the default `SaveButton` and functions correctly in the context of the form.
=> Refactor Form Buttons

CHANGELOG.md, docs/guides/a-basic-example.md, docs/guides/decorators.md, docs/guides/flux.md, docs/guides/handlers.md, docs/guides/immutable.md, docs/guides/retrieving-data.md, docs/guides/validations.md
Due to open sourcing, import statements must refer to `carbon-react`.  This PR updates the getting started guides to reflect this.
=> Update guides to use `carbon-react` in imports

CHANGELOG.md, package.json, src/utils/helpers/i18n/__spec__.js, src/utils/helpers/i18n/i18n.js
This PR resolves the i18nhelper to use the locale for the separator and delimiter values, in the same way that unit and format already do.
=> Fix i18nhelper

CHANGELOG.md, src/utils/decorators/input-validation/__spec__.js, src/utils/decorators/input-validation/input-validation.js, src/utils/decorators/input/input.scss
`InputValidation`: now accepts a `info` prop to display info-styled icon and message attached to an input.
https://github.com/Sage/sage_one_advanced/pull/12325
=> Add an 'info' prop in input to display info-styled icon and message

src/components/table/definition.js
Resolved the following warning that appeared in the console when viewing the Table component on the Carbon demo site:
```
Warning: Failed prop type: Invalid prop `value` of type `string` supplied to `Checkbox`, expected `boolean`.
```
Note the error only appeared when running the app locally in development mode.
=> CARBON-696 Fix Table component props warning in carbon demo

src/components/dialog-full-screen/__spec__.js, src/components/dialog-full-screen/dialog-full-screen.js, src/components/dialog-full-screen/dialog-full-screen.scss, src/components/dialog/dialog.js, src/components/modal/modal.js
Use the dialog `onOpening` and `onClosing` functions to add and remove
a `data-fullscreendialogopen` attribute to the `<html>` tag: the data
attribute is added when the dialog is open, and removed when the dialog
is closed.
Add the CSS to set `overflow: hidden` using the
`[data-fullscreendialogopen]` selector.
Change the `onOpening` and `onClosing` getters defined in `Modal` to
functions, as they aren't really getters.
Remove the `carbon-dialog-full-screen__dialog--open` code and CSS.
**NB** merging into SE-2333_dialog_full_screen, so no QA required here (QA will be done in SE-2333_dialog_full_screen). Also no release notes required here for the same reason.
=> Apply overflow hidden to <html> when dialog open

src/components/date-range/date-range.js
These were accidentally removed as part of linting updates.
Note I have disabled eslint check because of the way the prop names are used dynamically and thus the linter doesn't detect that they are actually used in the code.
=> Re-enable endLabel and startLabel prop types on DateRange

CHANGELOG.md, src/components/multi-action-button/multi-action-button.scss
Ticket: CARBON-686
The Primary button does not change colour on hover. However, the Secondary style button was changing colour on hover.
The Secondary button has now been updated so it does not change colour on hover.
**Before:**
**After:**
=> CARBON-686 MultiActionButton – update secondary button hover style

CHANGELOG.md, demo/definitions.js, demo/utils/component-code-builder/component-code-builder.js, gulpfile.js, src/components/dialog-full-screen/__spec__.js, src/components/dialog-full-screen/definition.js, src/components/dialog-full-screen/dialog-full-screen-variables.scss, src/components/dialog-full-screen/dialog-full-screen.js, src/components/dialog-full-screen/dialog-full-screen.scss, src/components/dialog-full-screen/full-screen-heading/full-screen-heading.js, src/components/dialog-full-screen/full-screen-heading/full-screen-heading.scss, src/components/dialog-full-screen/full-screen-heading/package.json, src/components/dialog/__spec__.js, src/components/dialog/dialog.js, src/components/dialog/dialog.scss, src/components/pages/__spec__.js, src/components/pages/definition.js, src/components/pages/package.json, src/components/pages/page/__spec__.js, src/components/pages/page/definition.js, src/components/pages/page/package.json, src/components/pages/page/page.js, src/components/pages/page/page.scss, src/components/pages/pages.js, src/components/pages/pages.scss, src/utils/helpers/browser/__spec__.js, src/utils/helpers/browser/browser.js
* Makes `DialogFullScreen` scrollable if the content goes beyond the height of the browser.
* Adds `Pages` and `Page` components to enable paginated content for full screen views.
```
const headingOne = (
<Heading title="My First Page" />
);
const headingTwo = (
<Heading title="My Second Page" />
);
return (
<DialogFullScreen>
<Pages slideIndex={ 0 }>
<Page title={ headingOne }>
Content for the first page.
</Page>
<Page title={ headingTwo }>
Content for the second page.
</Page>
</Pages>
</DialogFullScreen>
);
```
=> Scrollable full screen dialog

src/components/table/table.scss
Because this component relies on calculating the height accurately to match the header, we need to fix the box-sizing to content-box to ensure it remains consistent.
More info on box-sizing: https://developer.mozilla.org/en/docs/Web/CSS/box-sizing
**Before**
**After**
=> Fix table configure cog layout

gulpfile.js, src/components/form/__spec__.js, src/components/form/cancel-button/cancel-button.js, src/components/form/form-summary/__spec__.js, src/components/form/form-summary/form-summary.js, src/components/form/form.js, src/components/form/form.scss, src/components/form/save-button/__spec__.js, src/components/form/save-button/save-button.js
**BEFORE**:
**AFTER**
Puts grey background around summary rather than just save button.
* Also fixes some linter warnings by re-ordering methods. lowers errors to 46.
=> CARBON-887 move error state to form-summary from save-button

src/components/form/form.js, src/components/form/form.scss
this reverts the footer class name made in a recent PR, this is because some applications use this class to apply custom CSS and it was breaking.
=> revert footer classname

CHANGELOG.md, src/components/table/table-header/table-header.js, src/components/table/table-header/table-header.scss
Replace absolute positioning with float.
Re-order the HTML so the icon comes first inside the `<th>`, otherwise
the mis-alignment got worse in Firefox.
Update release notes.
#1132
=> CARBON-700 Fix mis-aligned sort icon in IE11

CHANGELOG.md, demo/utils/definition/table-definition/table-definition.js, src/components/table/__spec__.js, src/components/table/package.json, src/components/table/table--secondary-theme.scss, src/components/table/table.js
* Uses primary and secondary as the theme names to keep it consistent with Buttons
* Uses prop name of `theme` unlike Button because `as` is ambiguous and used elsewhere - this should be addressed with https://github.com/Sage/carbon/issues/1005
Also, this demonstrates how an issue can link up to a PR as a way to do our work in the open source context - see how the commits tag the issue and the issue itself links to the PR and commits. Our proprietary ticketing system links into this and keeps app specific QA instructions there.
#1374 
* Use the demo site
=> #1374 alternate table theme

CHANGELOG.md, src/components/dialog-full-screen/__spec__.js, src/components/dialog-full-screen/dialog-full-screen.js
The `carbon-dialog-full-screen--open` class is now applied to the `html` element instead of the `body`.
https://jira-sage.valiantyscloud.net/secure/ViewSession.jspa?testSessionId=42734
=> Apply carbon-dialog-full-screen--open to html instead of body

gulpfile.js, src/components/table/table.js, src/utils/decorators/tooltip-decorator/tooltip-decorator.js, src/utils/flux/store/store.js
When the table component is being loaded, there were warnings appearing in the console and test logs due to using react.proptypes. This removes them and a couple others.
=> Resolve warnings appearing in console and test

CHANGELOG.md, src/utils/decorators/input/input.scss
Prefix was hidden when there was a error present on the input. I have also fixed #1230 in the process
=> Input prefix disappears on error

CHANGELOG.md, src/components/dialog/__spec__.js, src/components/dialog/definition.js, src/components/dialog/dialog.js
Add a `autoFocus` prop to `Dialog`. This helps control how focus is handled by the dialog:
* If `autoFocus` is true then the dialog element receives keyboard focus when the dialog opens
* If `autoFocus` is false then the dialog element doesn't receive keyboard focus when the dialog opens. Instead the developer is free to set the focus on e.g. a form field within the dialog.
In addition the close icon has been moved so it is the last child of the dialog. This should help manage the focus within the dialog better, as when focus leaves the close icon you should be safe to return focus to the dialog element without skipping any other child elements that can receive keyboard focus.
=> CARBON-903 Add autoFocus prop to Dialog

CHANGELOG.md, package.json, src/components/table/table-cell/table-cell.scss
This fixes a regression in tables where highlights are incorrectly applied to table rows when hovered.
This gif illustrates the bug:
This shows the bug fixed:
Verify that drag and drop behaviour is not affected.
=> Do not apply hover CSS to table rows if they are selected

docs/tutorials/carbon-rails/introducing-data.md
This will be needed when we update the generated package.json to use the node version of carbon, where the package is called 'carbon-react' instead of 'carbon'. You cannot complete the tutorial with the current code.
Fixes issue #1419
=> Update imports from 'carbon' to 'carbon-react' - fixes #1419

CHANGELOG.md, src/utils/helpers/poller/__spec__.js, src/utils/helpers/poller/poller.js
Poller helper no longer uses promises. Instead, it just calls itself via `setTimeout` as before __without__ being wrapped in a `Promise`.
Fix Poller tests so they work without promises.
=> CARBON-913 Refactor Poller to no longer use promises

src/components/form/__spec__.js, src/components/form/form.js
Refactor the `generateCSRFToken` function to use `querySelector` instead of `getElementsByTagName`. This means we don't need the `for` loop any longer, and can remove the `if` statement that was causing the code coverage to fail.
=> CARBON-918 Fix Form tests coverage in Jest

CHANGELOG.md, package.json, src/components/form/form.scss
A bug was found in the new `Dialog` behaviour in Safari `9.x` which rendered the sticky footer incorrectly. This solves it rendering incorrectly on page load for Safari `9.x`. There remains a wider issue around Safari logged [here](https://github.com/Sage/carbon/issues/1432)
=> Amend min & max width to avoid fixed width bug

CHANGELOG.md, src/components/form/__spec__.js, src/components/form/definition.js, src/components/form/form.js, src/components/form/form.scss
`Form` now has additional props of `leftAlignedActions` and `rightAlignedActions` which allows developers to add additional nodes in line with the default form actions.
=> added additional form actions

CHANGELOG.md, demo/actions/component/component.js, demo/constants/component/component.js, demo/definitions.js, demo/stores/component/component.js, src/components/configurable-items/README.md, src/components/configurable-items/__spec__.js, src/components/configurable-items/configurable-item-row/__spec__.js, src/components/configurable-items/configurable-item-row/configurable-item-row.js, src/components/configurable-items/configurable-item-row/configurable-item-row.scss, src/components/configurable-items/configurable-item-row/definition.js, src/components/configurable-items/configurable-item-row/package.json, src/components/configurable-items/configurable-items.js, src/components/configurable-items/configurable-items.scss, src/components/configurable-items/definition.js, src/components/configurable-items/package.json, src/utils/helpers/poller/__spec__.js
Introduces new `ConfigurableItems` and `ConfigurableItemRow` components.
These can be combined to form a list of Items with checkboxes that can be dragged and dropped. Designed to be used in tandem with the onConfigure prop in the table component.
Ticket: CARBON-828
=> New ConfigurableItems component

CHANGELOG.md, src/components/button-toggle/__spec__.js, src/components/button-toggle/button-toggle.js, src/components/button-toggle/button-toggle.scss, src/style-config/mixins.scss, src/utils/decorators/input/input.scss
Change the CSS used to hide the radio buttons so the radio buttons are
still accessible to screen readers, and can be tabbed via the keyboard:
instead of using `display: none` the `visually-hidden` mixin is applied
instead.
Add CSS outline to the ButtonToggle so users can see visually that the
component has received focus:
* The outline effect is the same as that used on existing input elements
* The existing CSS for the outline has been moved to a mixin
=> Allow ButtonToggle to be toggled via the keyboard

.travis.yml
Make use of Travis CI automated deployments to deploy the carbon website when changes are added to the `release` branch.
A future decision point might be if we decide to do this on the `master` branch instead.
=> Use TravisCI to automate carbon demo site deployments

.travis.yml, CHANGELOG.md, src/components/dialog/dialog.scss
* This specificity is introduced to ensure that the Dialog maintains the layout of it's close icon even if the CSS loads in a different order
https://github.com/Sage/carbon/issues/1450
Demostrate the fix in our app:
* The above screen shots should demonstrate that it's fixed in our app, so I've checked that as done on the issue
* There should be no change to demo site functionality
=> Ensures close icon positioning in dialog #1450

.travis.yml, CHANGELOG.md, src/components/decimal/__spec__.js, src/components/decimal/decimal.js, src/utils/validations/numeral/__spec__.js, src/utils/validations/numeral/numeral-type/numeral-type.js
Update the regex used for decimal validation to allow values that are
entered _without_ a leading zero.
The regex has been updated in both `Decimal` and `NumeralTypeValidator`.
Update release notes.
=> CARBON-937 Allow decimals without a leading leading zero

CHANGELOG.md, package.json, src/components/menu/__definition__.js, src/components/menu/menu-item/__definition__.js, src/components/menu/menu-item/__spec__.js, src/components/menu/menu-item/menu-item.js, src/components/menu/menu-item/menu-item.scss, src/components/menu/submenu-block/submenu-block.scss
reverts the alternate prop work done in this PR https://github.com/Sage/carbon/pull/936
this was because the original PR introduces some regressions with the original functionality, and essentially achieves the same as `SubMenuBlock` which is already supported.
=> reverted menu alternate prop

CHANGELOG.md, package.json, src/components/heading/heading.scss
Top padding was interfering with the layout in various use cases of heading. Checked dialogs etc where heading is used, they all override this value anyway.
This is required for a fix in global navigation.
=> removed top padding from heading

CHANGELOG.md, src/patterns/configurable-items/__definition__.js, src/patterns/configurable-items/__spec__.js, src/patterns/configurable-items/configurable-items.js
This prop means the functionality of the reset button can be specified and is no longer hard-coded. It will first close the dialog and then execute the callback. Previously it would reset the ConfigurableItems pattern store from the point the dialog was opened.
In the ConfigurableItems pattern demo, the dialog will close when the reset button is pressed.
=> onReset prop can be passed into ConfigurableItems

CHANGELOG.md, package.json, src/utils/decorators/input-validation/input-validation.js
`this._target` was only defined on Textboxes - so instead we lookup the dom node using ReactDOM.
=> Fixed validation error in modals

CHANGELOG.md, src/dispatcher/index.js, src/patterns/configurable-items/actions/__spec__.js, src/patterns/configurable-items/actions/actions.js, src/patterns/configurable-items/store/store.js
Ticket: CARBON-925
The dispatcher used by the configurable-items pattern was temporary. This has been switched to use the one provided in utils/flux.
**Testing** 
The Configurable Items pattern just needs a sanity check. No functional changes.
=> Update configurable-items pattern to use utils flux Dispatcher

CHANGELOG.md, src/components/table-ajax/__spec__.js, src/components/table-ajax/table-ajax.js, src/components/table/table.js
**Data Attributes**
The data-state attribute has been added to track the current state of the process of loading data for the table. This will help with writing automated tests that can rely on a data attribute that should remain more constant and robust than relying on class names or markup structure.
The states for the attribute are:
- idle _(before the component has requested data)_
- requested
- loaded
- errored
**Aria Busy**
The `aria-busy` attribute is now set to true when the ajax request is processing and set to false after the request has finished.
Ticket: CARBON-935
=> CARBON-935 TableAjax component now uses the data-state attribute

CHANGELOG.md, demo/i18n/config.js, demo/main.js, package-lock.json, package.json, src/components/date/__definition__.js, src/components/date/__spec__.js, src/components/date/date.js, src/components/date/date.scss, src/components/date/navbar/__spec__.js, src/components/date/navbar/navbar.js, src/components/date/navbar/navbar.scss, src/components/date/navbar/package.json, src/utils/helpers/date/__spec__.js, src/utils/helpers/date/date.js
Switched from `react-date-picker` to `react-day-picker` as the old library is no longer being maintained.
- http://react-day-picker.js.org
- https://github.com/gpbl/react-day-picker
- Check keyboard support is the same (hitting tab closes the picker rather than giving it focus)
- Visit http://localhost:8095/components/date-input?locale=fr to test the picker showing the months in French. Note French is the only locale other than English supported on the Carbon demo site.
- Carbon demo has been updated so maxDate and minDate can be set to test the disabled dates functionality.
=> [CARBON-938] Update the DatePicker to use a new library

CHANGELOG.md, src/components/configurable-items/configurable-item-row/configurable-item-row.scss, src/patterns/configurable-items/__spec__.js, src/patterns/configurable-items/configurable-items.js
- ConfigurableItems pattern dialog now uses stickyFormFooter
- Make Configurable Item Row vertically centered
Ticket: PF-3381
=> ConfigurableItems tweaks

CHANGELOG.md, src/components/animated-menu-button/__spec__.js, src/components/animated-menu-button/animated-menu-button.js, src/components/animated-menu-button/animated-menu-button.scss, src/utils/decorators/input-validation/input-validation.js
Following on from https://github.com/Sage/carbon/pull/1513 This PR resolves more of the a11y linting errors that would be raised by the `eslint-plugin-jsx-a11y` plugin if it was turned on for Carbon.
- The `AnimatedMenuButton` will now close when pressing the enter key.
- Removed `onMouseOver` and `onMouseOut` from validation message itself in the input validation decorator
https://github.com/Sage/carbon/pull/1513
- The AnimatedMenuButton close button has keyboard support (press enter to close) but this is only visible on touch devices.
=> More ARIA updates

src/components/tabs/__spec__.js, src/components/tabs/tab/__definition__.js, src/components/tabs/tab/tab.js, src/components/tabs/tabs.js
- The element that serves as the container for the set of tabs has role `tablist`
- The `tablist` has `aria-orientation` set to `vertical` when the tabs aligned left of the content.
- Each element that serves as a tab has role `tab`
- Each tab has the `aria-selected` attribute true/false based on the selected state
- Each tab content container has a role of `tabpanel`
- Each tabpanel has the `aria-labelledby` attribute pointing at the relevant `tab` id
- Left and right arrow keyboard support added to move focus between tabs (see gif below).
- Up and down arrow keyboard support added to move focus between vertical tabs.
- When using keys to navigate between tabs, it will loop back around as per the w3 spec.
- The currently visible `tabpanel` has a `tabIndex` added to make it tabbable by …
=> Tabs ARIA updates

src/components/inline-inputs/inline-inputs.js, src/components/multi-step-wizard/multi-step-wizard.js
Looking for opinions if this is ok. Originally i added these as TODO's and wanted to add some deprecations so the user had to provide a key.
After some investigation it seems that keys are only really needed if the items are going to be re-ordered in some way or there might be issues when dynamically pushing/unsetting. With these two components i very much doubt there will be any re-ordering however there may be a case of dynamically adding fields to the inline inputs set?
=> remove uneeded carbon-todo

CHANGELOG.md, src/components/message/message.js
- `children` prop is now optional
- `title` prop type changed from string to node
https://github.com/Sage/carbon/issues/1543
=> 1543 Message props updated

CHANGELOG.md, src/components/grouped-character/__spec__.js, src/components/grouped-character/grouped-character.js
* Store formatted value in state so value always displayed with separators. This means values passed in from a store on first render will be correctly formatted.
=> Store formatted value in state for grouped character

CHANGELOG.md, src/utils/decorators/input-validation/input-validation.js, src/utils/helpers/browser/__spec__.js, src/utils/helpers/browser/browser.js, src/utils/helpers/browser/node/__spec__.js
Update `Browser.getWindow()` to return `global.window`. This should return the browser `window` object in a browser environment, and return `undefined` in a node environment.
This is tested using the `testEnvironment` setting, which can be set per
file using the [`@jest-environment` docblock](https://github.com/facebook/jest/blob/master/docs/en/Configuration.md#testenvironment-string).
Update the input validation decorator to use `Browser.getWindow()` to get its `window` reference, rather than reference `window` directly.
#1540
=> CARBON-964 Remove explicit window reference from input validation decorator

src/components/row/__snapshots__/__spec__.js.snap, src/components/row/__spec__.js, src/components/row/row.js
React.Children.map(this.props.children) does not strip out null children.
React.Children.toArray(this.props.children).map does.
Do we include release notes for RC changes.
=> Allow Row to have null column in V2

CHANGELOG.md, src/components/button/button.scss
Default alignment of text on buttons should always be center. This change resolves an issue where Button would inherit the text-align of the parent component.
https://github.com/Sage/carbon/issues/1561
_**Before**_
_**After**_
=> Update default text alignment on Button

CHANGELOG.md, package-lock.json, package.json, src/components/help/__definition__.js, src/components/icon/__spec__.js, src/components/portal/__spec__.js, src/components/portal/package.json, src/components/portal/portal.js, src/components/tooltip/tooltip.scss, src/utils/decorators/tooltip-decorator/__spec__.js, src/utils/decorators/tooltip-decorator/tooltip-decorator.js
The Portal component pulls a component out into the top level of the DOM. The benefit of this is so that it is not effected by it’s position in the markup and cascading styles.
I have set the z-index of the tooltip to 1 + `z-dialog` to ensure it appears above modals.
The underlying functionality is provided by the library: https://github.com/tajo/react-portal
CARBON-948
Test that the Help and Icon tooltips remain positioned in the same way when tweaking the props for the position of the tooltip.
=> [CARBON-948] Add the Portal component and apply to the Tooltip decorator

CHANGELOG.md, src/components/date/__spec__.js, src/components/date/date.js, src/components/portal/portal.js
The Date Picker now uses Portal to handle the layout.
Note that in order to write the specs I needed to add a ref to the Portal component itself. This is so that the content inside the Portal can be found using Enzyme as the content has been pulled out of the dom tree of the parent component.
PR that introduces Portal: https://github.com/Sage/carbon/pull/1542
CARBON-967
No visible changes, ensure the date picker behaves as it currently does.
=> Add Portal to the Date component

CHANGELOG.md, package.json
Add the `react-addons-perf` to devDependencies. This will give us access to the `Perf` object in development mode, which we can use to profile / analyse Carbon's performance.
=> Add react-addons-perf to devDependencies

CHANGELOG.md, src/patterns/configurable-items/__spec__.js, src/patterns/configurable-items/configurable-items.js
`ConfigurableItemsPattern` current requires the `itemsData` prop whereas GAC does not always provide it and it's causes a warning in the console. This fix makes the prop optional and only applies it when it's provided.
=> Allow itemsData to be undefined

CHANGELOG.md, demo/utils/definition/input-definition/input-definition.js, src/utils/decorators/input-label/input-label.js
Updated input-label to change fieldHelp prop from type String to type Node to allow the input to include JSX.
=> Switch fieldHelp prop to type Node

CHANGELOG.md, package-lock.json, package.json
This removes the last createClass warning from the demo site.
Just a devDependency so can go in anywhere. No release notes required?
=> upgrade react-highlight for demo

CHANGELOG.md, src/components/dropdown-filter/__definition__.js, src/components/dropdown-filter/__spec__.js, src/components/dropdown-filter/dropdown-filter.js, src/components/dropdown-filter/dropdown-filter.scss
Update the Create functionality of the Dropdown Filter component.
Use a Link component inside of the Create action button.
Allow customized create-text to be added via props on Dropdown Filter.
Allow customized icon-type to be added via props on Dropdown Filter.
Create button styling has subtle highlighting on hover, grey-dark-blue text and a blue icon.
Update `__spec__` and `__definition__` with these changes.
just pull down this branch and run `gulp`, then go to Dropdown Filter component in the Demo site and click "create" checkbox.
=> update Create action to use Link component with Icon

CHANGELOG.md, package-lock.json, package.json, src/utils/flux/__spec__.js, src/utils/flux/flux.js
Ensures that `displayName` is set to the original component's name when connecting to a store using Carbon's flux helper. We have noticed Jest snapshot's have started to default to `View` when connected to a store using our flux connector, this change will ensure the display name is maintained.
=> ensure displayName is maintained when connecting to a store

CHANGELOG.md, package.json, src/components/table-ajax/table-ajax.js
The data state on a table-ajax component is being set to loaded before the on change event is happening. 
This is causing random failures when running automation and the response is a little slow.
Moving the update of the data state to when the total records are set ensures this is set at at a point when the table is fully loaded.
=> Ensure table-ajax data state sets loaded on last update

package-lock.json, package.json
Upgraded to Carbon Factory v2.2.0
* Sourcemaps are now available.
* Node v8 is now supported.
Added a new script to debug tests `npm run debug` - requires Node v8 (also recommend [installing NiM](https://chrome.google.com/webstore/detail/nodejs-v8-inspector-manag/gnhhdgbaldcilmgcpfddgdbkhjohddkj))
=> upgraded to carbon-factory v2.2.0

CHANGELOG.md, src/components/dialog/dialog.scss
Discussions with members of UX, the bottom of the dialog should have 30px bottom padding.
_**Old dialog with less bottom padding**_
_**New dialog with more bottom padding**_
=> Address padding based on UX changes.

CHANGELOG.md, src/components/menu/__definition__.js, src/components/menu/menu-item/menu-item.js
As well as a child, pass on the `icon` prop to the `Link` so it can be used in that way.
=> MenuItem supports icon prop

.eslintrc, CHANGELOG.md, src/components/alert/__snapshots__/__spec__.js.snap, src/components/confirm/__snapshots__/__spec__.js.snap, src/components/dialog/__snapshots__/__spec__.js.snap, src/components/modal/__snapshots__/__spec__.js.snap, src/components/modal/__spec__.js, src/components/modal/modal.js, src/components/sidebar/__snapshots__/__spec__.js.snap
Add data state to modal to aid in test running.
This change ensures the data state is updated once all transitions have fininshed.
Selenium was attempting to select dialogs before they had finished rendering on the page, causing false failures.
=> Add data-state to modal

CHANGELOG.md, src/components/dialog/dialog.scss
A UX request to reduce the spacing between the dialog header and the line spacer.
_**Original**_
_**New**_
At desk demonstration done with UX.
=> UX improvement to address padding in dialogs

docs/tutorials/carbon-rails/hello-world.md
Was previously erroring as 
`Error Cannot find module 'carbon/lib/utils/router' from '.../ui/src'
`
=> Update hello-world.md to fix main.js instruction

CHANGELOG.md, src/components/portrait/__spec__.js, src/components/portrait/portrait.js
Update the `Portrait` component so that can render empty `alt` attributes: when it receives the empty string for the `alt` prop it will render it as an empty `alt` attribute on the `<img>` tag.
Set the `defaultValue` for the `alt` prop to `''`.
=> Allow Portrait to render an empty alt attribute

CHANGELOG.md, src/components/portrait/__spec__.js, src/components/portrait/portrait.js, src/components/profile/__spec__.js, src/components/profile/profile.js, src/components/profile/profile.scss
Update the text colour for `Profile`,  and the background colour used for `darkBackground={ true }` in the `Portrait` component, to `$onyx`.
Update the `Portrait` component used by `Profile` to use `darkBackground={ true }`.
=> Update Portrait and Profile CSS

CHANGELOG.md, src/utils/flux/__spec__.js, src/utils/service/__spec__.js, src/utils/service/service.js
* We take an empty string in response data and convert it to an object
* This ensures 204 responses with empty data will still be correctly parsed
https://github.com/Sage/carbon/issues/1631
=> Ensure response data is an object #1631

package.json
Normally this is generated after running `gulp`, and is already present when publishing. However occasionally it can be missed from some published builds, this ensures it is present.
=> ensure assets file is generated on publish

CHANGELOG.md, src/utils/service/__spec__.js, src/utils/service/service.js
Adding a transform to an instance of a service class was applying the transform to all other instances. This change ensures the transform is only applied to the specific instance.
=> fixes transforms on service class

CHANGELOG.md, src/utils/css/modules/utility-classes.scss
* This results in a space being added which pushes layouts out of line as it has a measurable size
* Not being exhibited in the demo site, but a space is not needed to make the clearfix effective and we can't be sure that it won't be rendered as a space in different contexts
**Before:**
**After:**
=> Remove space from clearfix psuedos

CHANGELOG.md, package-lock.json, src/components/settings-row/settings-row.scss
Sets a max-width on the left hand segment of the SettingRow component, to ensure the content has the majority of the width of larger screens.
=> max-width on setting-row

CHANGELOG.md, src/components/date/__spec__.js, src/components/date/date.js
Previously this component would not retain an invalid date value, we now keep the value and throw a validation error on the input.
=> Date component now keeps an invalid value and throw a validation error on the input.

CHANGELOG.md, src/components/checkbox/checkbox.scss
Checkbox should not cover the last two letters and the full stop of the Help field text (see screenshots).
=> CheckBox inline bug

CHANGELOG.md, src/utils/decorators/input/input.scss
Sometimes the input width is not 100% which means the border hover is being applied when the user is not actually over the input.
Ticket: PF-3737
=> Apply :hover style to input rather than container

CHANGELOG.md, src/utils/flux/store/__spec__.js, src/utils/flux/store/store.js
* I chose 50, which would allow for a complex layout with several store on some of it's children, this should be enough room to manoeuvre for a varied array of applications without allowing anything really silly to happen with exponentials
https://github.com/Sage/carbon/issues/1700
* Has been dev checked in the context where it was happening
=> Increase maxListeners #1700

CHANGELOG.md, demo/utils/site-map-helper/generate-menu/generate-menu.js
Add keys to the top-level `MenuListItem` components used in the sidebar. This removes the warning 'Each child in an array or iterator should have a unique "key" prop' that was appearing in the browser console.
=> Add keys to top-level MenuListItem components

CHANGELOG.md, demo/site-map.js
Tutorials are numbered incorrectly in the Carbon sidebar.
http://carbon.sage.com
Navigate to specified area.
Expand "Tutorials" section in sidebar.
Rails Part 1
Rails Part 2
Rails Part 3
Rails Part 1
Rails Part 2
Rails Part 2
=> Renamed tutorial numbers

CHANGELOG.md, demo/views/pages/document/document.js, src/components/animated-menu-button/animated-menu-button.js, src/components/carousel/carousel.js, src/components/flash/flash.js, src/components/flash/flash.scss, src/components/show-edit-pod/show-edit-pod.js, src/components/table/table.js, src/components/toast/__snapshots__/__spec__.js.snap, src/components/toast/toast.js
Pass the `component='div'` prop to all instances of `CSSTransitionGroup` that contain block-level content.
By default `CSSTransitionGroup` uses a `<span>` tag, which can lead to invalid HTML such as:
```html
<span>
<div>
My component
</div>
</span>
```
By setting the `component` prop to the string `div` we ensure that the component HTML is valid HTML and doesn't include incorrectly nested tags.
=> Fix invalid HTML when using CSSTransitionGroup

CHANGELOG.md, src/components/form/form-summary/form-summary.js
Currently the `FormSummary` component uses manual interpolation to set the default translations. This stops us from being able to add localisation for these translations. The fix allows `I18n` to handle that stuff so we can add override localisations as normal.
=> Remove manual interpolation on FormSummary to allow override

.travis.yml, CHANGELOG.md
https://jira-sage.valiantyscloud.net/browse/CARBON-1045
> We're getting console errors/warnings on the demo site in prod. These should be disabled when running with `--production`. Need to look into why this is happening and resolve it.
Locally run `gulp deploy --build --production`
`npm install http-server -g`
`cd deploy`
`http-server`
Navigate to `http://127.0.0.1:8080`
Ensure warnings / errors don't appear in inspector-console
=> [CARBON-1045] Demo Site - fix typo to run in production mode

CHANGELOG.md, package-lock.json, package.json, src/components/dropdown/dropdown.js
* The code was using `x` and `y` instead of `left` and `top` and those two values are not reported by the IE's none standard object returned by `getBoundingClientRect` - switching to `left` and `top` fixes the problem.
* https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect
=> Portal ie fix

CHANGELOG.md, src/utils/decorators/input/input.scss
Prevent the hover styles being applied to readonly and disabled inputs.
=> Fix issue with hover styles on readonly and disabled inputs

CHANGELOG.md, src/components/textarea/textarea.scss
#1718
Moves the label for the textarea to the top of the component.
=> Position textarea label at the top

CHANGELOG.md, src/components/flash/__spec__.js, src/components/flash/flash.js
Resolves #1741.
Set `this.state.open` to `this.props.open` in the constructor, so that if `this.props.open` is set to `true` the `Flash` component will open on initial render.
=> Fix Flash component not opening on initial render

CHANGELOG.md, src/components/drag-and-drop/custom-drag-layer/__spec__.js, src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.js
For draggable lines work I require to extend to apply className to customDragLayer component - this would be a neat feature to have in Carbon to make customLayer even more custom.
=> [1767] CustomDragLayer can now take className prop

CHANGELOG.md, src/components/dialog-full-screen/__snapshots__/__spec__.js.snap, src/components/icon/icon.js, src/components/portal/__snapshots__/__spec__.js.snap, src/utils/helpers/browser/__spec__.js
Do not render the `type` prop as a `type` attribute, as this is invalid HTML.
=> Stop rendering a type attribute for the Icon's type prop

CHANGELOG.md, src/utils/helpers/browser/__spec__.js, src/utils/helpers/browser/browser.js
Add `redirectAfter` to the `Browser` class. This method takes 2 arguments: url, and seconds.
It redirects to the given URL after the given number of seconds have elapsed e.g. if you need to redirect after displaying a `Flash` message.
=> Add redirectAfter method to Browser

CHANGELOG.md, src/components/drag-and-drop/with-drop/__spec__.js, src/components/drag-and-drop/with-drop/with-drop.js, src/components/table/draggable-table-cell/__spec__.js, src/components/table/draggable-table-cell/draggable-table-cell.js, src/components/table/table-row/__spec__.js, src/components/table/table-row/table-row.js
Extending functionality to determine if a an item can be dropped on. This fixes an issue where line items could be dragged below the last existing line item, causing an issue shown in the screenshot below.
Before:
After:
=> Extending Draggable Context functionality

CHANGELOG.md, change_log/next/date_input_info.yml, src/components/date/__spec__.js, src/components/date/date.js, src/components/date/date.scss, src/utils/decorators/input-icon/input-icon.js, src/utils/decorators/input-icon/input-icon.scss
DateInput component not displaying `info` prop when used. 
https://github.com/Sage/carbon/issues/1778
before:
after:
=> 1778: Date Input component - info prop not working.

change_log/next/CARBON-1079.yml, src/components/pod/__spec__.js, src/components/pod/pod.js
This PR is a fix for issue #1709.  There were a few lines of code in the render function that was causing a title attribute, equal to the title prop passed to the Pod component, to be added to the Pod component's containing div element.  I removed that bit of code and added a test case that ensures none of the html elements that are rendered has a title attribute equal to that of the title property passed to the Pod component.  
N/A
N/A
N/A
Either run npm test or run npm start and go to http://localhost:8095/components/pod .  Fill out the title field in the Pod form.  Hover mouse above the generated pod component to ensure the title attribute tooltip does not appear.  
When I pulled master and ran tests there was one failing test case from commit 12d43b7f89031a6d739fe78fd5f93cb6677e9b23 . …
=> Addressing erroneous title attribute in Pod component

docs/guides/releasing.md
After doing a minor version release, @chrisbarber86 and me noticed that there is a missing step in release step document.
Missing step was `PR to merge master into release` after release a minor version from master.
Also we think that releases should be always cut from `release`
=> Add missing release step

change_log/next/1868.yml, src/components/form/form.js, src/components/show-edit-pod/__snapshots__/__spec__.js.snap
Fixes #1868 
Fixes a warning from triggering in development where a boolean value was being used a string.
=> Fixes #1868 - boolean warning from Form component

change_log/next/FE-1196_bug_fix.yml, src/utils/helpers/date/date.js
Fixes Bug FE-1196 where users in western timezones would see date and date range components display values for the day before when using the text input and tabbing out.
=> FE-1196 fixes timezone bug with datepickers

src/__experimental__/components/input/__snapshots__/input.spec.js.snap, src/__experimental__/components/input/index.js, src/__experimental__/components/input/input.component.js, src/__experimental__/components/input/input.spec.js
The new Input component now supports auto-selecting all text on focus and surfaces it's input HTML element via a forwarded ref.
=> input now selects value on focus

package.json
A change was made in the previous tag which updated the scripts, however separating the `NODE_ENV` variable set between `&&` and the next command loses the env variable. This resulted in the assets for the demo site being in development mode and 25mb. Removing the `&&` fixes the issue reducing the assets down to <1mb.
=> fixed production assets for demo site

change_log/next/S1T-1617.yml, demo/utils/definition/table-definition/table-definition.js, src/components/table/__spec__.js, src/components/table/table.js
* At the moment, when using the TableAjax provided by Carbon if you want to change the experience of when the Table is empty, you lose the loading functionality.
* To prevent reimplementing all the logic for if the Table is in a loading state, this is allowing a backward compatibility of easily extending table.
Agreement with @andrewjtait to extend Carbon for this functionality.
1. Create a TableAjax in the demo wrapper with no data
1. - [x] Observe that it is showing the default no records found 
1. Create a TableAjax in the demo wrapper with no data and a customEmptyRow
1. - [x] Observe that it is showing the custom empty row.
=> Extend Table component for custom empty row

change_log/next/FE-1279-i18n-peer-dep.yml, package-lock.json, package.json
We have changed i18n-js into a peer dependency. This means developers will need to install and manage which version of i18n-js they want to use in their own applications. We have done this as some applications using Carbon require an older version of i18n-js, while some would like to use newer versions.
=> i18n peer dep

change_log/next/menu-list-item-style-fix.yml, src/components/menu-list/menu-list-item/menu-list-item.scss
When I tried to import the MenuListItem component I got the following error from Webpack:
```ERROR in projectDir/node_modules/carbon-react/lib/components/menu-list/menu-list-item/menu-list-item.scss (projectDir/node_modules/css-loader!projectDir/node_modules/sass-loader/lib/loader.js!projectDir/node_modules/carbon-react/lib/components/menu-list/menu-list-item/menu-list-item.scss)
Module build failed (from projectDir/node_modules/sass-loader/lib/loader.js):
@import 'colors.scss';
^
File to import not found or unreadable: colors.scss.
in projectDir/node_modules/carbon-react/lib/components/menu-list/menu-list-item/menu-list-item.scss (line 1, column 1)
@ projectDir/node_modules/carbon-react/lib/components/menu-list/menu-list-item/menu-list-item.scss 2:14-124
@ …
```
=> MenuListItem SCSS import fix

change_log/next/common-input-message.yml, src/utils/decorators/input/input.scss
Currently the `.common-input__message` style that is applied to all inputs is set to `text-align: center;`. This PR changes that to `left`. Applies to `error`, `warning` and `info` validation messages.
=> Change default text-align for common input message

change_log/v6_3_2/select-async-defaults.yml, release_notes/v6_3_2.html.md, src/__experimental__/components/select-async/select-async.component.js, src/__experimental__/components/select-async/select-async.spec.js
Sets default Accept header for SelectAsync requests to 'application/json'.
=> SelectAsync default Accept header

src/components/filter/filter.stories.js
Renames the `Filter` story in Storybook as a workaround for the following error:
=> FE-1397 - Renames Filter Story to Prevent Storybook Error

change_log/next/FE-1399 extend type defintitions.yml, src/components/button/button.d.ts, src/components/decimal/decimal.d.ts, src/components/flash/flash.d.ts, src/components/link/link.d.ts, src/components/textbox/textbox.d.ts
Addresses https://github.com/Sage/carbon/issues/1968 where type definitions were missing the default html events (onclick etc) which blocked Carbon being used in any strict Typescript projects
=> Adds intersections to component types

change_log/v7_0_1/revert-date-formatter.yml, package-lock.json, package.json, release_notes/v7_0_1.html.md, src/utils/helpers/date/date.js
Reverts formatter back as `utc` function is forcing locale to format to UK
=> revert formatter

change_log/next/tooltip-update.yml, src/components/tooltip/tooltip.js, src/components/tooltip/tooltip.scss, src/utils/decorators/tooltip-decorator/__spec__.js, src/utils/decorators/tooltip-decorator/tooltip-decorator.js
Tooltip now supports 'type' prop to add color, it also now repositions itself automatically if rendered off screen.
No QA required as this is part of a feature branch that will be tested together (`validation-branch`).
=> updated tooltip to support types and offscreen

change_log/next/S1T-1852.yml, src/__experimental__/components/select/select.component.js
When a search filter was applied to the multi select dropdown component and an item was selected, the search text was not being cleared. The changes made here now clear the text once an item has been selected. The items will stay filtered until a new filter is applied, or deselecting and selecting the dropdown again.
https://jira.sage.com/browse/S1T-1852
=> S1T-1852: Removes search text on multi select dropdown after selecting item

change_log/next/FE-1424-google-analytics-bug.yml, src/utils/router/__spec__.js, src/utils/router/router.js
Analytics is tracked only when React Router triggers the URL change (not a true page load, just a SPA page load).
=> Fe 1424 - Google Analytics Double Counting

__mocks__/superagent.js, change_log/next/extend-table-ajax-for-post-requests.yml, src/components/table-ajax/__definition__.js, src/components/table-ajax/__spec__.js, src/components/table-ajax/table-ajax.js
Extends TableAjax to allow for post requests.
Followed pattern of mocking superagent for post and get based on another Sage repository. Pending comments from reviewers, I could change the mocks to match? Unless there is another way of testing `Request.post` was called.
=> Extend table ajax for post

src/components/table/table.stories.js
Fixes the error being thrown when theme is toggled to none in storybook and a row was missing the required `uniqueID`
=> fixes uniqueID error

change_log/next/S1T-1897.yml, src/components/table-ajax/__definition__.js, src/components/table-ajax/__spec__.js, src/components/table-ajax/table-ajax.js
Adding `withCredentials` support to the TableAjax component.
> *withCredentials()* makes your browser include cookies and authentication headers in your XHR request. If your service depends on any cookie (including session cookies), it will only work with this option set.
=> S1T-1897 - Add withCredentials support to TableAjax

src/components/table/table-cell/table-cell.style.js, src/components/table/table.style.js
Fixes the styling defects found in the base PR: removes the border on the table wrapper, sets a width for the date input when the table is `large` and adjusts the date picker icon so it is aligned vertically in the input
=> fixes styling defects

src/components/tooltip/__definition__.js
This was removed in error when replacing the old Tooltip files with the new ones - adding back in so that the old Carbon site builds correctly.
=> Adds __definition__.js file back in - removed in error

src/__experimental__/components/form/form.component.js, src/__experimental__/components/form/form.spec.js, src/__experimental__/components/form/form.stories.js
Replaces the `fetch` post call with `axios` as it is not supported by IE11
Refactors test and story to fit with the above changes
=> FE-1806 implements axios post instead of fetch

src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-svg.component.js
Chrome and Safari allow an [SVG `circle`](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle) to be created without an initial radius:
```svg
<circle cx='7.5' cy='7.5' />
```
and then the [radius](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/r) can be set later via CSS:
```css
circle {
r: 5;
}
```
But in IE, Edge and Firefox, if an initial radius isn't supplied, then the `circle` will never render, even if the radius is later set via CSS :warning:
This PR fixes the bug by supplying an initial radius.
=> FE-1835 RadioButton SVG bug on IE/Edge/Firefox

src/__experimental__/components/select/select.component.js, src/components/validations/with-validation.hoc.js
[This line](https://github.com/Sage/carbon/blob/c84f4d7/src/__experimental__/components/select/select.component.js#L171):
```js
if (!this.props.filterable) return undefined;
```
was added to `<Select>`'s `value()` method in https://github.com/Sage/carbon/pull/2163 for FE-1420 (see [commit `f0bbf4e`](https://github.com/Sage/carbon/pull/2163/commits/f0bbf4e#diff-c3877e0d6c511e983d6356c0354b2c8eR159) on 1st July).
It looks like this has broken [the `withValidation()` functionality](https://github.com/Sage/carbon/blob/4e046b7/src/__experimental__/components/textbox/textbox.component.js#L99) of [`<Select>`'s `<Textbox>`](https://github.com/Sage/carbon/blob/4e046b7/src/__experimental__/components/select/select.component.js#L289) when `this.props.filterable === false` :warning:
Specifically, …
=> FE-1844 Select component validation bug

src/__experimental__/components/checkable-input/__snapshots__/hidden-checkable-input.spec.js.snap, src/__experimental__/components/checkable-input/checkable-input.component.js, src/__experimental__/components/checkable-input/checkable-input.spec.js, src/__experimental__/components/checkable-input/hidden-checkable-input.component.js, src/__experimental__/components/checkable-input/hidden-checkable-input.spec.js, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/checkbox/checkbox.component.js, src/__experimental__/components/checkbox/checkbox.spec.js, src/__experimental__/components/checkbox/checkbox.stories.js, src/__experimental__/components/form-field/form-field.component.js, src/__experimental__/components/label/label.component.js, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.spec.js, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__experimental__/components/switch/switch.component.js, src/__experimental__/components/switch/switch.spec.js, src/__experimental__/components/switch/switch.stories.js, src/components/help/help.component.js
- updates to Help, when used within a RadioButton group, as discussed with UX
- to preserve normal RadioButtonGroup UX, it has been agreed that the Help component will NOT be tabbable when it appears alongside a RadioButton
- in these cases, it is made accessible via aria-describedby instead. To facilitate this, overrides for the tabIndex and tag type have been added to the Help component, along with an id prop
- this commit also makes some refactors to the CheckableInput, and the components which use this, to ensure that props such as value, label and type are only applied to the input element (the HiddenCheckableInput)
=> FE-1830 / FE-1833 RadioButton Help accessibility and tabbing

change_log/next/FE-1906-pill.yml, src/components/pill/pill.style.js
Added CSS margin to equal 0 on the Pill close button, to resolve the stylistic mismatch on Safari compared with other browsers.
=> FE-1906 Pill close button

.travis.yml
Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves so we need to add new package to download on Ubuntu for cypress tests
=> added new package to download on Ubuntu for cypress tests

change_log/next/FE-1915-configurable-items.yml, src/components/configurable-items/configurable-items.stories.js, src/components/configurable-items/configurable-items.style.js
- fix visibility of component in the storybook
- fix for styling of the component
- The issue with `Accessibility` (`ul` ,`li`) is familiar but we have to omit it because it is caused by DnD library specifications
=> FE-1915 - fix Configurable Items component in the storybook

change_log/next/FE-1876-help-component.yml, src/components/help/help.component.js, src/components/help/help.style.js, src/components/toast/toast.stories.js
- added missing outline
- Open storybook
- Open Help component
- Change the theme to S/M/L
- Press twice Tab button
=> FE-1876 - add missing outline to the Help Component

cypress/features/regression/confirm.feature, cypress/features/regression/dialog.feature, cypress/locators/dialog/locators.js, cypress/support/step-definitions/confirm-steps.js, cypress/support/step-definitions/dialog-steps.js
Cypress tests:
- fix for stickyFormFooter for `Dialog` component;
- fix for `Confirm` component (deleted tests with stickyFormFooter, enabled test for confirm button)
=> Cypress - fix for stickyFormFooter, fix for Confirm component

change_log/next/FE-1901-theme-overrides.yml, src/style/themes/theme.stories.js
Adds an example to the Storybook showing how to override or extend the provided themes.
1. `npm run storybook`
1. Theme > Overrides
=> docs: add docs on how to override the theme FE-1901

src/components/dialog/dialog.component.js, src/components/dialog/dialog.spec.js
This fixes the issue in the release candidate where dialogs with one or more falsey children failes to render.
=> fix: dialog should not render falsey children FE-2024

src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js
Tests fail in GAC when children are undefined for split and multi action buttons, adds filter to fix
=> Fix for Split Button when children are undefined

src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.spec.js, src/__experimental__/components/radio-button/radio-button.stories.js
Currently setting a RadioButton to `checked` is ignored when it is in a RadioButtonGroup, I have added some code to ensure it is respected and applied when it is passed
=> Hot fix to allow default checked radio

src/components/table/draggable-table-cell/draggable-table-cell.component.js, src/components/table/draggable-table-cell/draggable-table-cell.spec.js, src/components/table/table-row/__snapshots__/table-row.spec.js.snap, src/components/table/table-row/table-row-modern.style.js
In commit 23a1e4a in branch [`FE-1569-react-dnd-and-dls-table-row`](https://github.com/Sage/carbon/commits/FE-1569-react-dnd-and-dls-table-row), some CSS code was added to `src/components/table/table-row/table-row-modern.style.js` for the styling of icons in table cells. That approach was incorrect.
This PR reverts that change (4c542bf) and then implements the correct functionality (8411478) by selecting the DraggableTableCell's icon according to the current theme.
=> FE-2075 Bug: table row icons rotated

change_log/next/FE-2077-tables-downArrow-missing-color.yml, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/multi-action-button/multi-action-button.component.js, src/components/split-button/split-button.component.js
Currently downArrow color does not change to the corresponding theme color when theme is changed.
=> FE-2077 Storybook - Tables -> downArrow has no theming color

src/components/drag-and-drop/draggable-context/__spec__.js, src/components/drag-and-drop/draggable-context/draggable-context.js, src/components/drag-and-drop/with-drop/with-drop.js, src/components/table/draggable-table-cell/draggable-table-cell.spec.js, src/components/table/draggable-table-cell/draggable-table-cell.style.js, src/components/table/table-row/__snapshots__/table-row.spec.js.snap, src/components/table/table-row/table-row-classic.style.js, src/components/table/table-row/table-row-modern.style.js, src/components/table/table-row/table-row.spec.js, src/components/table/table-row/table-row.style.js, src/utils/helpers/dnd/item-target/__spec__.js, src/utils/helpers/dnd/item-target/item-target.js
attempts to resolve the React DnD flickering issue
Resolves flicker issue with crossover of draggable items by measuring difference of the  "Y" distance from the moment of cross over and pointer Y (cursor traveled distance). = offsetDrifferenceY
Currently 1px is used for divider line that acts as point of crossover between two list items.
For as long as offsetDrifferenceY is <= 1px the onDrag will not switch over allowing for 1px "dead zone".
Crossover zone of 1px causes flicker of two items. This happens if drag is in crosover zone and drag continues on X-axis (horizontal) as item A and B are alternated for every pixel of mouse move. 
Depending on different implementation cases two draggable items overlap each other (elements touch) as they share border space (divider line) to resolve …
=> Fe 2076 dc flickering

src/components/validations/validation-icon.style.js
Fixes checkbox icon focus outline for modern theme.
=> FE-2062 fixed checkbox icon focus outline on modern theme

src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.spec.js, src/__experimental__/components/radio-button/radio-button-svg.component.js, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.spec.js, src/__experimental__/components/radio-button/radio-button.stories.js
A defect was raised for missing keyboard control. However, this is supported natively by the browser and was a defect in the story implementation.
The `tabIndex` code was also removed to allow the browser to control the tab index. The browser changes the tab order depending on which way the user is tabbing (`Tab` vs `Shift+Tab`). There was a bug where using a `falsey` value would incorrectly set the tab index on the first item. This bug is no longer present as we're not controlling `tabIndex` you can see this in the storybook as the default value has changed from `undefined` to `null`.
The experimental radio button stories should now support keyboard control.
=> fix: radio button keyboard control FE-2060

change_log/next/FE-2153-focus-icon-third-click.yml, src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/checkbox/checkbox-svg.component.js
Fixes IE11 bug where checkbox help icon get's focused on 3rd tab instead of 2nd
=> FE-2153 Focus on icon is visible after the third click tab button

src/__experimental__/components/decimal/decimal.component.js, src/__experimental__/components/decimal/decimal.spec.js, src/__experimental__/components/decimal/decimal.stories.js
Implemented a new `onBlur()` prop for the Experimental Decimal component. The callback receives two arguments:
1. The React `SyntheticEvent` object for the `blur` event.
2. The undelimited value (as a string). For example, if the component's displayed value is `"1,000.0"`, then the undelimited value is `"1000.0"`.
=> FE-2167 Decimal does not implement onBlur

CONTRIBUTING.md, rfcs/README.md, rfcs/template.md
To define clear channels for collaboration, we have introduced a "request for comments" process.
This will streamline the process for making any substantial changes that require input from the wider audience.
=> chore: define rfc process FE-2234

src/__experimental__/components/decimal/decimal.stories.js, src/__experimental__/components/decimal/docgenInfo.json, src/__experimental__/components/form/docgenInfo.json, src/__experimental__/components/radio-button/docgenInfo.json, src/__experimental__/components/radio-button/index.js, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.stories.js, src/__experimental__/components/select/docgenInfo.json, src/__experimental__/components/select/option.component.js, src/__experimental__/components/switch/docgenInfo.json, src/__experimental__/components/switch/switch.component.js, src/__experimental__/components/textarea/docgenInfo.json, src/__experimental__/components/textarea/textarea.component.js, src/__experimental__/components/textbox/docgenInfo.json, src/__experimental__/components/textbox/textbox.component.js
Updates and repairs to docgenInfo and story js files to correct Prop Types tables in storybook. Only the RadioButton is worthy of noting as here as I exported the component as a named variable in a state before it was wrapped by the React.memo HOC. This was necessary for the react-docgen module to see the component.
Release notes not required IMO.
=> FE-2267 experimental docgeninfo updates

src/__experimental__/components/grouped-character/grouped-character.component.js
It seems that this functionality broke in commit 7b94f1e in #2405 (FE-2175).
In that commit, the props of `<GroupedCharacter>` became destructured like this:
```diff
- const GroupedCharacter = (props) => {
+ const GroupedCharacter = ({
+   groups,
+   value: externalValue,
+   defaultValue,
+   onChange,
+   separator: rawSeparator,
+   ...rest
+ }) => {
```
This meant the `value` prop became excluded from `...rest`, so the `value` prop is no longer passed to `<Textbox>` (where the `withValidation` HOC is applied):
```diff
- <Textbox { ...props }
+ <Textbox { ...rest }
```
Since `withValidation` is no longer receiving the `value` prop, it can't run the validations.
This PR resolves the issue by simply restoring the `value` prop to the `<Textbox>`.
=> FE-2261 Fix GroupedCharacter validation

src/components/action-popover/documentation/info.js
Minor update to keyboard documentation for action-popover.
Functionality is correct and the description is wrong.
=> docs: update action-popover keyboard information

change_log/next/FE-2217-select-list-loop.yml, src/__experimental__/components/select/__snapshots__/select.spec.js.snap, src/__experimental__/components/select/select-list.component.js, src/__experimental__/components/select/select.component.js, src/__experimental__/components/select/select.stories.js, src/__spec_helper__/test-utils.js, src/components/scrollable-list/scrollable-list.component.js, src/components/scrollable-list/scrollable-list.spec.js
This PR fixes incorrect Select list behaviour where traversing the list with `up` and `down` keyboard arrow buttons resulted in looping the whole list without stopping at the last or first item. However to enable this behaviour in case someone wants the Select to work like that there is a `isLoopable` prop available to be passed to the `Select` component.
Also in this PR I've implemented support for traversing the Select list using `home` and `end` button to select either first or the last selectable item.
=> FE-2217 Select list looping / Select home and end buttons support

change_log/next/FE-1865-allow-empty-date-value.yml, fixtures/src/components/controlled/date.js, fixtures/src/components/uncontrolled/date.js, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js, src/__experimental__/components/date/date.stories.js, src/__experimental__/components/date/docgenInfo.json
```
New Features:
- allow an empty value using the `allowEmptyValue` prop, this will default to '' instead of '01/11/2011'
```
=> FE-1865 allow empty date value

src/__spec_helper__/enzyme-snapshot-helper.js
When generating a snapshot of an Enzyme wrapper with an object passed as a prop, that object will be rendered in a snapshot, obfuscating the result.
With this helper we could render snapshots with these objects replaced by `[ <prop name> object ]`.
Previously we have avoided this issue by using `TestRenderer.Create`, this helper will allow us to not mix various test tools.
To remove theme object:
`expect(noThemeSnapshot(wrapper)).toMatchSnapshot()`
To remove a custom object/objects:
`expect(snapshotWithoutProps(wrapper, 'propName')).toMatchSnapshot()`
`expect(snapshotWithoutProps(wrapper, ['firstProp', 'secondProp'])).toMatchSnapshot()`
=> FE-2428 Enzyme Snapshot Helper

src/components/button/button.component.js, src/components/button/index.js, src/components/split-button/__snapshots__/split-button.spec.js.snap, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js
Ref forwarding on default export in Button caused a lot of issues in unit tests of applications that are already using Carbon. Ref forwarding is not required for a standalone Button to work properly, that functionality is required for SplitButton and MultiActionButton, so it could be used there as named export.
Additional changes:
- Fixed SplitButton issue: handleKeyDown eventListener not removed on button unmount.
- Simplified SplitButton component snapshots.
=> FE-2429 removed forwardRef from Button default export

change_log/next/FE-2405-move-validation-array-out-of-render.yml, src/__experimental__/components/date-range/date-range.component.js, src/__experimental__/components/date-range/date-range.stories.js, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js
The current implementation assigns the validation array on each render which causes it to infinite loop when in a form. To fix this the validation array is now stored in state unless it is part of a `date-range`. The array is only updated when a change is detected in `componentDidUpdate`
=> FE-2405 move validation array out of render method

change_log/next/FE-2281-remove-tabs-child-tooltip.yml, src/components/tabs/tab/tab.component.js
There is a tooltip on the child of a Tab that has the Tab title as content, which should not be visible. This refactor removes the title attribute from the StyledDiv which causes this behaviour.
=> refactor: removes title attribute from Tab StyledDiv to remove obtrusive tooltip

change_log/next/FE-2444-remove-allowEmptyValue-knob-from-every-story.yml, src/__experimental__/components/date/date.stories.js
Fixes bug where `allowEmptyValue` knob was present in every component story. (Component: DateInput Story)
=> Fe 2444 fix allowEmptyValue prop in every story

src/__experimental__/components/decimal/decimal.stories.js
```
// When the allowEmptyValue knob changes we want to force the component to re-create
// allowEmptyValue is only used in the constructor and it is not currently supported to change during the lifetime
// of the component
```
=> docs: update decimal story to support allow empty value knob FE-2462

change_log/next/FE-2468-decimal-wiggle-readOnly-animation.yml, src/__experimental__/components/decimal/decimal.component.js, src/__experimental__/components/decimal/decimal.spec.js
Fixed an issue where wiggle animation started even when `readOnly` prop was passed as true to the component.
=> FE-2468 - Fixed invalid animation behaviour on Decimal

change_log/next/FE-2471-checkable-input-onBlur-fired-3-times.yml, src/__experimental__/components/checkable-input/checkable-input.component.js, src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/checkbox/checkbox.component.js, src/__experimental__/components/checkbox/checkbox.stories.js, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__experimental__/components/switch/switch.component.js, src/__experimental__/components/switch/switch.stories.js
Fixed onBlur event on inputs using CheckableInput (Checkbox, Switch, RadioButton) which was incorrectly invoked multiple times instead of just once.
Can be easily checked in either fixtures on component stories.
=> FE-2471 - Fixed incorrect onBlur behaviour on checkable input

change_log/next/issue-2556.yml, src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.spec.js
When conditionally removing an ActionPopoverItem, a javascript error was occurring.
This ensures we handle when the child object is null.
[GitHub issue](https://github.com/Sage/carbon/issues/2556)
=> fixes 2556 ActionPopover having conditional children

.github/ISSUE_TEMPLATE/bug_report.md
This PR adds a bug template. When users create a new issue they can choose from this template or a blank one.
=> chore: add bug template FE-2023

change_log/next/onchange-type-definitions.yml, src/__experimental__/components/checkbox/checkbox.d.ts, src/__experimental__/components/radio-button/radio-button.d.ts, src/__experimental__/components/switch/switch.d.ts
As reported in #2576, I added the missing event parameter for the `onChange` prop of the experimental Checkbox component.
Besides of that, I had a look for other `onChange` functions that were specified without a parameter. I verified that these get passed to an `input` element as well and added the parameter for them too.
Related issue: #2576 
No additional tests added.
=> Add missing event parameter in onChange type definitions

README.md
Remove Codeship badge from Github README. We have disabled the Codeship integration in favour of Travis.
There is a status bade on the Github README.
<del> - [ ] Release notes (renogen)</del>
<del> - [ ] Unit tests</del>
<del> - [ ] Cypress automation tests</del>
<del> - [ ] Storybook added or updated</del>
<del> - [ ] Theme support</del>
<del> - [ ] Typescript `d.ts` file added or updated</del>
Codeship is faster but does not run pull requests from forks. For this reason, we're going to use Travis which does run pull requests from forks. We will look to parallelise some of the Travis steps to speed up the build.
View the README.md file.
=> docs: remove codeship badge

src/components/pager/pager-navigation.component.js
Fixes https://github.com/Sage/carbon/issues/2584 where Pager does not use I18n for the "First" label. This change is backwards compatible as it maintains a defaultValue of 'First'.
Currently the Pager navLinkConfig object contains labels for first/last/next/previous but the first label does not use I18n.
<del>- [ ] <del>Cypress automation tests</del>
<del>- [ ] <del>Storybook added or updated</del>
<del>- [ ] <del>Theme support</del>
<del>- [ ] <del>Typescript `d.ts` file added or updated</del>
https://github.com/Sage/carbon/issues/2584
=> fix(pager): add I18n translation to First option 

.travis.yml, package.json
I have parallelised many of the stages in the Travis build reducing the time from 14 mins to 6.
- Only `pr` check is important for PR's the `push` one is not because we only care about the condition of the code after the merge.
- `push` is not important for PR's we could make some more time savings here but it wouldn't help the speed of the `pr` check. 
- I looked to prevent the double builds that we see in a PR, but this would mean we have to explicitly state which branches to build. This would make it difficult to do a maintenance release so for now we still have two builds for each PR.
- `npm run test-carbon-build` only runs on `pull_request` because on the `push` job we will be doing it in the `deploy` stage.
All steps are run in sequence, but they do not depend upon each other. …
=> ci: parallelize travis FE-2511

src/__experimental__/components/date-range/date-range.component.js, src/__experimental__/components/date-range/date-range.spec.js, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js
The component should support runtime updates of the value when used in controlled manner and display the new value formatted in the both the input and calendar
Only the selected date value is updated in the calendar/ date picker, the visible value does not update
Fixes #2604, FE-2514
Test experimental date and date range components in storybook
=> fix(date): support for runtime value update FE-2514

change_log/next/FE-2452-gutter-prop.yml, src/components/inline-inputs/__definition__.js, src/components/inline-inputs/docgenInfo.json, src/components/inline-inputs/inline-inputs.component.js, src/components/inline-inputs/inline-inputs.spec.js, src/components/inline-inputs/inline-inputs.stories.js, src/components/inline-inputs/inline-inputs.style.js
Added gutter prop to InlineInputs component to provide gutter support. The prop is directly passed down to the Row component. 
In this case the gutter is visually demonstrating that the **values relate to each other but differ in behaviour and input type.**
_There are other cases where the UI might look better when there is a gap between the input fields._
=> feat: Added gutter prop to InlineInputs component

cypress/features/regression/showEditPod.feature, cypress/features/regression/showEditPodClassic.feature, cypress/features/regression/sidebarWithButton.feature, cypress/locators/show-edit-pod/locators.js, cypress/locators/sidebar/locators.js, cypress/support/step-definitions/show-edit-pod-steps.js
Add missing tests for Sidebar With Button and Show Edit Pod default. Refactor Show Edit Pod Classic
FE-2357
Add missing features for Sidebar With Button, Show Edit Pod default.
Refactor Show Edit Pod classic
Missing Sidebar With Button component and Show Edit Pod default component
<del>- [ ] Release notes (Conventional Commits) </del>
<del> - [ ] Storybook added or updated </del>
<del> - [ ] Theme support </del>
<del> - [ ] Typescript `d.ts` file added or updated </del>
run: `./node_modules/.bin/cypress run --spec './cypress/features/regression/showEditPod*.feature', './cypress/features/regression/sidebar*.feature' --reporter spec`
=> test(sidebar, showeditpod): add missing tests

cypress/features/regression/configurableItems.feature, cypress/features/regression/configurableItemsEvents.feature, cypress/features/regression/confirm.feature, cypress/features/regression/draggableContext.feature, cypress/locators/configurable-items/index.js, cypress/locators/configurable-items/locators.js, cypress/locators/draggable-context/index.js, cypress/locators/draggable-context/locators.js, cypress/support/helper.js, cypress/support/step-definitions/configurable-items-steps.js, cypress/support/step-definitions/confirm-steps.js, cypress/support/step-definitions/draggable-context-steps.js
Allow feature files to run in Cypress for `configurableItems`, `draggableContext` and `confirm` components for both default and classic stories with tests for events.
The `configurableItems` and `draggableContext` files currently fail and the `confirm` file had no tests for action events.
<del>[ ] Unit tests
<del>[ ] Storybook added or updated
<del>[ ] Theme support
<del>[ ] Typescript `d.ts` file added or updated
FE-2347
Run the feature files in Cypress
Tests run successfully with no errors
=> test(configurable items, draggable context, confirm): fix and add new tests

cypress/features/regression/experimental/textbox.feature, cypress/locators/textbox/index.js, cypress/support/step-definitions/textbox-steps.js, src/__experimental__/components/textbox/docgenInfo.json, src/__experimental__/components/textbox/textbox.component.js, src/__experimental__/components/textbox/textbox.spec.js, src/__experimental__/components/textbox/textbox.stories.js
A new iconOnClick prop has been added to allow for onClick events on the Icon to be handled separately from the onClick on the input.
Currently Textbox only supports a single onClick handler, which is consumed by the Input and Icon. 
<del>- [ ] Storybook added or updated </del>
<del>- [ ] Theme support </del>
<del>- [ ] Typescript `d.ts` file added or updated </del>
This work is needed to unblock development of new search component
Test that current behaviour of select component on master branch still remains.
=> feat(textbox): add icon onclick prop to textbox

src/components/portrait/documentation/info.js, src/components/preview/documentation/info.js, src/components/profile/documentation/info.js, src/components/split-button/documentation/info.js
Hi, 
I noticed that the library name was incorrect in the documentation while I copy and pasted an import line, it caused good 15 minutes while I understood why I couldn't import the given component, I hope this PR will save time for someone else
- [N/A] Unit tests
- [N/A] Cypress automation tests
- [ N/A] Theme support
- [N/A] Typescript `d.ts` file added or updated
=> docs: fixed library name in documentation

src/__experimental__/components/form/__snapshots__/form.spec.js.snap, src/__experimental__/components/form/form.component.js, src/__experimental__/components/form/form.spec.js
`data-element` has been added to `StyledFormFooter`, part of the `Form` component. This is to allow the user to access the element within Selenium, then scroll the page by the hight of the sticky footer.
The sticky footer can obscure other controls rendered on the form which then prevents Selenium from selecting them.
FE-2486
You can see the attribute `data-element="sticky-footer"` in the DOM when running the `Form` stories in storybook.
=> feat(Form): add data-element attribute

src/components/card/card.component.js, src/components/card/card.style.js
Update the component to render a div instead of a button
Currently the card renders a button, which causes illegal DOM nesting  when a button is passed to it
as a child
A number of users have raised the issue of illegal DOM nesting when trying to render a 'Button` inside a `Card`
`card.stories.js` to ensure all previous functionality is retained
=> fix(card): update card to render div instead of button

rfcs/text/formik.md
WIP/draft RFC for integrating Formik into Carbon.
Also includes:
* **FE-2088**  –  Example of wiring up Formik's `dirty` state to React Router via `history.block()`.
=> docs: integrating Formik into Carbon FE-2283

src/components/alert/alert.component.js, src/components/alert/alert.spec.js, src/components/confirm/confirm.spec.js, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.spec.js, src/components/dialog/dialog.component.js, src/components/dialog/dialog.spec.js, src/components/dialog/dialog.stories.js, src/components/flash/__snapshots__/flash-legacy.spec.js.snap, src/components/modal/modal.component.js, src/components/sidebar/sidebar.component.js, src/components/sidebar/sidebar.spec.js, src/components/sidebar/sidebar.stories.js, src/utils/helpers/element-resize/element-resize.js, src/utils/helpers/focus-trap/focus-trap.js, src/utils/helpers/focus-trap/focus-trap.spec.js, src/utils/helpers/focus-trap/index.js
- Add a new behavior called focus-trap. It allows keeping focus inside of the selected element and it focuses first focusable element. Focus-trap also has protection - if no focusable component occurs then dialog should not lose focus also.
- go to storybook/dialog 
- open dialog with keyboard
- the focus should be placed on the first focusable element if elements exist
- tabbing or shift tabbing shouldn't leave the selected element (dialog)
=> feat(Dialog, Sidebar): Create focus-trap util and adapt it to the components

src/components/help/help.component.js, src/components/help/help.spec.js, src/components/help/help.stories.js
We would like to have the ability to choose another icon for the help icon on a textbox.
So I added a "type" props in the help component.
There is a way to pass the icon we want through the labelHelpIcon props.
From the textbox through the form-field componant to the label componant :https://github.com/Sage/carbon/blob/0241195de9006711b110a500831372bae278e131/src/__experimental__/components/form-field/form-field.component.js#L56
Then from the label to the help component :https://github.com/Sage/carbon/blob/0241195de9006711b110a500831372bae278e131/src/__experimental__/components/label/label.component.js#L66
But in the help component, the icon is hard coded :https://github.com/Sage/carbon/blob/0241195de9006711b110a500831372bae278e131/src/components/help/help.component.js#L70
I just …
=> fix(help): allow to set different icon on help component

package-lock.json
npm run storybook will no longer display warning for Browserslist depedency caniuse being out of date.
npm run storybook displays console warning "Browserslist: caniuse-lite is outdated. Please run next command `npm update`"
=> build: updated browserslist depedency of babel/preset-env - FE-2509

src/components/pager/__snapshots__/pager.spec.js.snap, src/components/pager/pager.component.js
Adds translation feature to the pager component
Word "Show" is not translateable
Add a translation file and change the translation
=> feat: Added translation support for "show" in pager component FE-2544

src/components/card/card.component.js, src/components/card/card.spec.js
Allow consumer to pass data-role prop
data-role can not be passed to Card
=> fix(card): add data role prop for automation

README.md
Remove IE 11 from the supported bowser section.
IE11 is currently in the supported browser list.
<del>- [ ] Release notes (Conventional Commits) </del>
N/A
N/A
=> docs: remove IE11 from browser support

cypress/features/regression/pager.feature, cypress/features/regression/tableClassic.feature, cypress/features/regression/tableWithInputs.feature, cypress/locators/pager/index.js, cypress/locators/pager/locators.js, cypress/locators/table/index.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/pager-steps.js, src/components/pager/__snapshots__/pager.spec.js.snap, src/components/pager/pager.component.js, src/components/pager/pager.spec.js, src/components/pager/pager.stories.js
1. Add tests for existing I18n translations in `Pager`.
1. Add singular/plural translations fo records, the default translation will now display `0 items`, `1 item`, `10 items`.
1. Use the page size value for the translation of page size instead of total records.
1. There are no tests for translations.
1. If they are using the default translations and `totalRecords=1` it will say `1 items`.
1.  If
1. `totalRecords=1 pageSize=10` it will say `Show 10 item`.
1. `totalRecords=100 pageSize=1` it will say `Show 1 items`.
The singular/plural translations currently work if the user defines their own translation. However, the page size and total records both use the `totalRecords` prop …
=> fix(pager): add singular/plural translation FE-2510

src/__experimental__/components/form/form.component.js, src/__experimental__/components/form/form.stories.js, src/components/validations/textbox-validations.stories.js, src/components/validations/validations.stories.js, src/components/validations/with-validation.hoc.js
Add deprecation warnings to `Form` and `Inputs` that have validations.
Although we have merged the RFC new teams are still starting implementations using Form. This is to discourage that further. We need to keep the implementation until there is at least one version where we can use the FormFooter/StickyFooter without Form.
I've also added a banner to the storybook stories that use show Form/validations.
No warnings are displayed
Fixes FE-2569 #2481
* npm run storybook
* Go to http://localhost:9001/?path=/story/experimental-form--default
* View console
=> chore: add form deprecation warnings

.eslintrc
Moves `es-lint` config into carbon
Currently extends config from `carbon-factory`
Part of removing `carbon-factory`, the `es-lint` dependency will be added to `carbon` art that stage
Linter will not run if config is incorrect
=> chore: move es lint config into carbon

src/__experimental__/components/checkbox/checkbox.stories.js
Clicking on label of a given Checkbox should check this particular checkbox
Clicking on label in Experimental/Checkbox/validations always checks first checkbox no matter which of the checkboxes label is clicked
Storybook -> Experimental -> Checkbox -> validations
=> fix(checkbox): restore proper checkbox behaviour in validations story - FE-2579

src/__deprecated__/components/form/form.spec.js, src/__experimental__/components/form/form.spec.js, src/utils/router/__spec__.js
Removes jsdom related console warnings in the Jest Test Console.
~~- [ ] Storybook added or updated~~
=> test: fix jsdom related console warnings (FE-2490)

README.md
Provides information on the getting stated and coding guides.
The links in the readme file are dead as the guides have been removed.
=> docs(readme): remove broken links to guides fixes #2704

cypress/features/regression/dialog.feature, cypress/features/regression/dialogClassic.feature, cypress/features/regression/message.feature, cypress/locators/confirm/locators.js, cypress/locators/locators.js, cypress/support/step-definitions/common-steps.js, src/components/dialog/__snapshots__/dialog.spec.js.snap, src/components/dialog/dialog.component.js, src/components/dialog/dialog.spec.js, src/components/dialog/dialog.style.js, src/components/icon/icon.spec.js
Update the Dialog close icon, when using a modern theme the icon will have a gold outline.
The icon has a blue outline.
<del>- [] Storybook added or updated
<del>- [] Theme support
There are other outstanding PR's related to close icon.
#2691 #2692 #2693 #2694 
1. `npm start`
1. Go to http://localhost:9001/?path=/story/dialog--default
=> fix(dialog): close button styling

cypress/features/regression/experimental/radioButtonGroup.feature, cypress/features/regression/experimental/radioButtonGroupClassic.feature, cypress/locators/radioButton/index.js, cypress/locators/radioButton/locators.js, cypress/support/step-definitions/radio-button-steps.js, src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap, src/__experimental__/components/fieldset/docgenInfo.json, src/__experimental__/components/fieldset/fieldset.component.js, src/__experimental__/components/fieldset/fieldset.spec.js, src/__experimental__/components/fieldset/fieldset.style.js, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/docgenInfo.json, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.spec.js, src/__experimental__/components/radio-button/radio-button-group.style.js, src/__experimental__/components/radio-button/radio-button.spec.js, src/__experimental__/components/radio-button/radio-button.stories.js, src/__experimental__/components/radio-button/radio-button.style.js, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
We would like to have the ability to display the RadioButton inline. I added 2 props `inline` and `labelInline`.
`inline` is used on the radio-button component to put the radio-button in one line. 
`labelInline` is used in Fieldset to put the legend in the same line of the radio-button.
It is possible to set both `inline` and `labelInline`
Currently the radio-button group is displayed in a column.
That modification will be useful for Client Management :
- `npm start`
- Go to http://localhost:9001/?path=/story/experimental-radiobutton--default
- In `Addons > Knobs` check `inline` prop. That should display the radio buttons inline.
- In `Addons > Knobs` check `labelInline` prop. That should display the legend inline with the radio buttons still in a column.
- In `Addons > Knobs` check …
=> feat(radio-button): add support for inline radio buttons

.travis.yml
We build PR's and branches, this tells Travis to only build on the master branch or PR's that target the master branch.
We build all PR's and branches. Having a double build is causing a worker contention. There is no need to build the pull request branch and the result of the merge. We can just build the result of the merge because that is what we care about in almost if not all cases.
https://docs.travis-ci.com/user/pull-requests/#double-builds-on-pull-requests
This PR should only have one Travis job.
=> ci(travis): only build on master branch

.storybook/welcome-page/components-demo/demo/demo.component.js, src/components/button/button-types.style.js, src/components/button/button.component.js, src/components/button/button.spec.js, src/components/button/button.stories.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/button/documentation/info.js, src/utils/helpers/options-helper/__spec__.js, src/utils/helpers/options-helper/options-helper.js
`<Button buttonType="destructive"/>` has been deprecated in favour of `<Button buttonType="primary" destructive />`.
There is a codemod available to assist with this upgrade `npx carbon-codemod button-destructive <target>`.
See https://github.com/Sage/carbon-codemod for more information.
`<Button buttonType="destructive"/>` displays a primary destructive button. The DLS states that we need secondary and tertiary destructive buttons. These are controlled by the same prop.
`<Button buttonType="secondary"/>`, `<Button buttonType="tertiary"/>`. Adding more `buttonTypes` would introduce further complexity.
https://github.com/Sage/carbon-codemod/tree/master/transforms/button-destructiv …
=> feat(button): add destructive prop FE-2615

.storybook/main.js, .storybook/style/story-root.scss
Fix broken Icons in storybook demos, load Lato from cdn
Icons are not loading and lato font is not found
<del>- [x] Storybook added or updated<del>
This a temporary fix whilst an investigation is undertaken to work out why the original one has failed
=> docs(storybook): load lato from cdn and remove url loader

cypress/features/regression/actionPopoverIFrame.feature, cypress/features/regression/experimental/simpleColorPicker.feature, cypress/fixtures/simpleColorPicker.json, cypress/fixtures/simpleColorPickerNew.json, cypress/locators/simple-color-picker/index.js, cypress/locators/simple-color-picker/locators.js, cypress/support/step-definitions/action-popover-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/simple-color-picker-steps.js, src/__experimental__/components/radio-button/radio-button-mapper.component.js, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__experimental__/components/simple-color-picker/simple-color-picker.component.js, src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js, src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js, src/__experimental__/components/simple-color-picker/simple-color-picker.style.js
ArrowUp will move selection up if possible.
ArrowDown will move selection down if possible.
ArrowUp behaviour is identical to ArrowLeft, moves selection to previous element.
ArrowDown behaviour is identical to ArrowRight, moves selection to next element.
=> feat(simple-color-picker): keyboard accessbility, up and down navigation - FE-2578

cypress/features/regression/sidebar.feature, src/components/sidebar/sidebar-classic.style.js, src/components/sidebar/sidebar.component.js, src/components/sidebar/sidebar.spec.js, src/components/sidebar/sidebar.style.js
Update the Toast close icon, when using a modern theme the icon will have a gold outline.
The icon has a blue outline.
<del>- [x] Storybook added or updated
<del>- [x] Theme support
There are other outstanding PR's related to close icon.
#2690 #2691 #2692 #2694 
1. `npm start`
1. Go to http://localhost:9001/?path=/story/sidebar--with-button
=> fix(sidebar): close button styling

rfcs/text/remove-classic.md
This RFC describes the plan to remove the Classic theme.
---
This is a RFC and it is important to note that this PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/2163a70006e4e7853d6b4fe05703a2348a979f3e/rfcs/README.md).
Please use 👍 if you approve.
=> docs(rfc): remove classic theme

cypress/features/accessibility/accessibility.feature, cypress/features/build/build.feature, cypress/features/regression/test/batchSelection.feature, cypress/locators/batch-selection/index.js, cypress/locators/batch-selection/locators.js, cypress/support/step-definitions/batch-selection-steps.js, src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap, src/components/batch-selection/batch-selection.component.d.ts, src/components/batch-selection/batch-selection.component.js, src/components/batch-selection/batch-selection.spec.js, src/components/batch-selection/batch-selection.stories.js, src/components/batch-selection/batch-selection.stories.mdx, src/components/batch-selection/batch-selection.style.js, src/components/batch-selection/index.js, src/style/themes/base/base-theme.config.js, src/utils/helpers/options-helper/options-helper.js
Batch Selection component could be used to select multiple items, and apply a common action to all the items selected.
This pattern is also intended to replace the 'Selectable' configuration of the existing Table component: https://carbon.sage.com/storybook/?path=/story/table--default.
=> feat: add new BatchSelection component (FE-2457)

cypress/support/step-definitions/anchor-navigation-steps.js, cypress/support/step-definitions/simple-color-picker-steps.js
- `beforeEach(() => {
cy.viewport(1366, 500);
});` should be removed from `simpleColorPicker.feature` and `anchorNavigation.feature` to make tests run without unnecessary re-rendering of viewport.
- added `{ force: true }` to make test run and pass.
- In Simple Color Picker and in Anchor Navigation we have beforeEach function where we are re-writting `cy.viewport`, it just loads all tests before.
- Simple Color Picker test fails because cypress doesn't see full input for `json` value insertion.
<del> - [ ] Release notes (Conventional Commits)  </del> 
<del> - [ ] Storybook added or updated</del>
<del> - [ ] Theme support</del>
<del> - [ ] Typescript `d.ts` file added or updated</del>
run:
`npm start` > `npm run test-cypress` and run separately …
=> test: remove unnecesary viewport in beforeEach

cypress/features/regression/experimental/select.feature, cypress/support/step-definitions/select-steps.js, src/__experimental__/components/select/select.component.js, src/__experimental__/components/select/select.spec.js, src/__experimental__/components/select/select.stories.js, src/__experimental__/components/select/select.style.js
New variant of the Select Component to allow it to be displayed as transparent and right aligned.
Select Component could be rendered with standard input background and border, and it's text is left aligned in relation to the dropdown icon.
Required as part of Address Fieldset.
* npm start
* Go to http://localhost:9001/?path=/story/experimental-select--default
* Check the `transparent` knob
=> feat(select): add transparent variant (FE-2630)

cypress.env.json, cypress/features/regression/test/textboxStyleOverrideNoIFrame.feature, cypress/locators/index.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/textbox-steps.js, src/__experimental__/components/form-field/form-field.component.js, src/__experimental__/components/form-field/form-field.style.js, src/__experimental__/components/input/input-presentation.component.js, src/__experimental__/components/input/input-presentation.style.js, src/__experimental__/components/input/input.style.js, src/__experimental__/components/label/label.component.js, src/__experimental__/components/label/label.d.ts, src/__experimental__/components/label/label.style.js, src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap, src/__experimental__/components/textbox/textbox.component.js, src/__experimental__/components/textbox/textbox.spec.js, src/__experimental__/components/textbox/textbox.stories.mdx
Textbox component should have a functionality to override it's styles, e.g.: set fixed width of the input or change it's background. 
Textbox styles cannot be overriden by Carbon user.
Required to set fixed width of post code field in Address Fieldset
* npm start
* Go to http://localhost:9001/?path=/story/test-textbox--styles-overriden
=> feat(textbox): add override styles functionality (FE-2631)

cypress/features/regression/button.feature, cypress/features/regression/buttonAsSibling.feature, src/components/button/button.component.js, src/components/button/button.spec.js
`<Button buttonType="primary" destructive />` will display destructive button.
`<Button buttonType="destructive"/>` will fail prop type validation.
```
BREAKING CHANGE: `<Button buttonType="destructive"/>` has been
removed in favour of `<Button buttonType="primary" destructive />`.
There is a codemod available to assist with this upgrade `npx
carbon-codemod button-destructive <target>`.
See https://github.com/Sage/carbon-codemod for more information.
```
These changes have already been made to support the new interface. Currently both
`<Button buttonType="destructive"/>` and `<Button buttonType="primary" destructive />` will display a destructive button.
<del>- [ ] Typescript `d.ts` file …
=> chore(button): remove destructive button type

src/components/button/button-types.style.js, src/components/button/button.spec.js, src/components/button/button.stories.mdx
Add destructive secondary and tertiary buttons.
Fixes FE-2553
|State|Carbon|DLS|
|-|-|-|
|Text| ![image](https://user-images.githubusercontent.com/2328042/77651230-60394480-6f64-11ea-8cee-a2dda3d38dc7.png)| ![image](https://user-images.githubusercontent.com/2328042/77651510-ce7e0700-6f64-11ea-83cb-3ccb98d0a565.png)|
|Text `:hover`| ![image](https://user-images.githubusercontent.com/2328042/77651337-8eb71f80-6f64-11ea-8312-bda2ec79b1cd.png)|![image](https://user-images.githubusercontent.com/2328042/77651581-ea81a880-6f64-11ea-8a91-c0d07d591ada.png)|
|Text `:focus`| ![image](https://user-images.githubusercontent.com/2328042/77654634-36cee780-6f69-11ea-9386-d197557579f8.png)|![image](https://user-images.githubusercontent.com/2328042/77651620-f79e9780-6f64-11ea-9eae-6e76386b579b.png)
|Text …
=> feat(button): add destructive secondary buttons FE-2553

src/__experimental__/components/fieldset/fieldset-examples.stories.mdx
Examples of address filedsets for various regions.
Required as part of Address Fieldset Story
* npm start
* Go to http://localhost:9001/?path=/docs/design-system-fieldset-address-fieldset-examples--canada
=> docs(fieldset): add address fieldset examples (FE-2633)

.codesandbox/ci.json
Add a configuration for CodeSandbox CI in preparation for enabling https://codesandbox.io/docs/ci
CodeSandbox CI is not enabled.
There is no way to test this configuration yet. However, I have tested it on a clone of carbon and it worked successfully.
=> ci: add codesandbox configuration

src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap, src/components/icon-button/icon-button.style.js
Change z-index of focused Icon Button to render over it's siblings.
When there is multiple icon buttons next to each other, one is focused, hovering over adjacent buttons their background will cover the focus outline.
~~- [ ] Storybook added or updated~~
* npm start
* Go to http://localhost:9001/?path=/docs/design-system-batch-selection--basic
* Focus on one of the Icon Buttons and hover over another
=> fix(icon-button): hover background over focus outline (FE-2634)

src/__experimental__/components/input/input.component.js, src/__experimental__/components/input/input.spec.js
The input component should not break when it receives focus and rerenders.
If the component re renders too quickly after receiving focus, it may break due to a missing null check.
=> fix(input): add null check to input focus handler

src/__deprecated__/components/form/__snapshots__/form.spec.js.snap, src/__experimental__/components/form/__snapshots__/form.spec.js.snap, src/components/button/__snapshots__/button.spec.js.snap, src/components/button/button.component.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/button/docgenInfo.json, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/split-button/__snapshots__/split-button.spec.js.snap
Add new `styleOverride` prop to allow consumers to override the default styling of Button
The way the margin is applied to a sibling button has also been updated to use `margin-left`
Styles cannot be overriden.
All buttons have `margin-right`
Ensure spacing is correct for buttons after `margin-right` was removed
=> feat(button): add support for style override object

cypress/features/regression/portrait.feature, cypress/features/regression/profile.feature
add ignore tag for tests in profile and portrait components which doesn't work properly for CI
The following tests fail for CI
Portrait component:
1. Change Portrait initials
2. Enable darkBackground checkbox for a Portrait component
Profile component:
1. Get initials from name
2. Set initials to
In the future, we'll try to fix this test cases or we'll remove
=> test(profile, portrait): add ignore tag

src/components/batch-selection/batch-selection.stories.mdx
The button outline should not cover the link part
In the documentation for Batch Selection, IconButton outline is overlapping the link part
1. run: npm start
2. open https://carbon.sage.com/?path=/docs/design-system-batch-selection--basic
3. click Tab until first IconButton is focused
=> docs(batch-selection): fix button outline over link part (FE-2653)

.travis.yml
Build branches in the format `1.x`, `1.x.x`, `1.2.x`, all of these formats are protected branches and can only be made by a maintainer.
This will make patching older versions easier in the future.
We only build master, to build any other branches we would have to modify the Travis config on that branch.
This PR is an example that targeted an old version #2756.
This PR build because at the time we were building all branches.
When creating these branches they still need `GH_TOKEN` and `NPM_TOKEN` for `semantic-release` to trigger. These are added by a maintainer in the Travis UI.
No need for QA, developers the travis …
=> ci(travis): build x.x.x branches

src/components/action-popover/__snapshots__/action-popover.spec.js.snap, src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.d.ts, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.style.js
Passing the `rightAlignMenu` prop will allow the `Menu` to align to the right of the `MenuButton`, by default the `Menu` will continue to open to the left
Currently the Menu opens to the left of the button
Further PR will allow a custom `MenuButton` to be passed into the Popover by a consumer, I thought it best to separate the work.
Default behaviour with no prop set:
Custom behaviour with prop set:
https://github.com/Sage/carbon/pull/2765#issuecomment-606117514
=> feat(action-popover): support for aligning menu to right of button

cypress/features/regression/test/accordionGrouped.feature, cypress/features/regression/test/actionPopoverNoIFrame.feature, cypress/features/regression/test/advancedColorPicker.feature, cypress/features/regression/test/advancedColorPickerNoIFrame.feature, cypress/locators/advanced-color-picker/index.js, cypress/locators/advanced-color-picker/locators.js, cypress/support/step-definitions/advanced-color-picker-steps.js, cypress/support/step-definitions/common-steps.js, jest.conf.json, src/__experimental__/components/simple-color-picker/color-sample-box/checker-board.svg, src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.spec.js, src/__experimental__/components/simple-color-picker/color-sample-box/color-sample-box.style.js, src/components/advanced-color-picker/__snapshots__/advanced-color-picker.spec.js.snap, src/components/advanced-color-picker/advanced-color-picker-cell.style.js, src/components/advanced-color-picker/advanced-color-picker.component.js, src/components/advanced-color-picker/advanced-color-picker.d.ts, src/components/advanced-color-picker/advanced-color-picker.spec.js, src/components/advanced-color-picker/advanced-color-picker.stories.js, src/components/advanced-color-picker/advanced-color-picker.stories.mdx, src/components/advanced-color-picker/advanced-color-picker.style.js, src/components/advanced-color-picker/index.js, src/components/dialog/dialog.component.js, src/components/dialog/dialog.style.js, src/components/modal/modal.component.js, src/utils/helpers/focus-trap/focus-trap.js, src/utils/helpers/focus-trap/focus-trap.spec.js, svgTransform.js
#2746
New component, color selection through dialog popup with preview ability.
Supports keyboard navigation.
=> feat(advanced-color-picker): dialog popup colour picker FE-2334

cypress/features/regression/test/search.feature, src/__experimental__/components/search/search.component.js, src/__experimental__/components/search/search.style.js
Close icon should be replaced by the search icon when the text is cleared.
When the text field is cleared using the close button, the close button is not replaced by the search icon.
~~- [ ] Storybook added or updated~~
1. run: npm start
2. go to: http://localhost:9001/?path=/story/test-search--basic
3. uncheck the `searchButton` knob
4. type `test` in the text field
5. click on the `close` button in the field
=> fix(search): close icon persists when field is empty (FE-2638)

cypress/features/regression/test/radioButtonGroupStyleOverrideNoIFrame.feature, cypress/locators/radioButton/index.js, cypress/locators/radioButton/locators.js, cypress/support/step-definitions/radio-button-steps.js, src/__experimental__/components/fieldset/fieldset.component.js, src/__experimental__/components/fieldset/fieldset.style.js, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.d.ts, src/__experimental__/components/radio-button/radio-button-group.spec.js, src/__experimental__/components/radio-button/radio-button-group.style.js, src/__experimental__/components/radio-button/radio-button.stories.mdx
RadioButtonGroup Component should have the option to override it's legend and content styles to match other form element styles.
RadioButtonGroup styles cannot be overriden by a Carbon User.
* npm start
* Go to http://localhost:9001/?path=/story/test-radiobuttongroup--styles-overriden
=> feat(radio-button-group): add style override

cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature, cypress/locators/button/index.js, cypress/support/step-definitions/action-popover-steps.js, src/components/action-popover/__snapshots__/action-popover.spec.js.snap, src/components/action-popover/action-popover-item.d.ts, src/components/action-popover/action-popover-menu.component.js, src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.d.ts, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.stories.js, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.style.js, src/components/button/button.style.js
A new renderButton prop has been added to allow the menu button to be overriden with a custom
component passed in by the consumer.
The component does not support a custom button, it renders only the Icon
I have built a demo of how to use the `ActionPopover` component to deliver a `ServicesColumn`
The demo is available in `test-action-popover--services-column` in storybook.
I will demonstrate the custom button functionality using the codesandbox demo link create as part of the build
Services Column closed with custom button:
Services Column open:
=> feat(action-popover): add support for custom menu button override FE-2329

package-lock.json, package.json
The previous upgrade to `react-day-picker` has caused some undesired style regressions so it is being
reverted
The picker styling is out of alignment see screenshot
Current:
After revert:
=> chore(dependency): revert react day picker upgrade

src/components/action-popover/__snapshots__/action-popover.spec.js.snap, src/components/action-popover/action-popover.style.js
When the submenu is positioned to the right in safari the right chevron icon is aligned to high,
this fix adds 8px to the top position to fix it
The right chevron is aligned incorrectly
Testable by visiting on safari `design-system-actionpopover--with-submenu-aligned-right`
=> fix(action-popover): add top position when menu right aligned in safari

.github/CODEOWNERS
In advance of the planned increase in contributions from outside the team we have implemented a
`CODEOWNERS` file to manage permissions and reviews
There is no `CODEOWNERS` file
=> chore(codeowners): add a codeowner file for carbon repo

src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/style/themes/base/base-theme.config.js
Updates hover colour to be aligned with DLS, added `flatTable` object and a `default` `hover` property to theme
Colour is not what is described in DLS
=> fix(flat-table): update hover color for flat table row and cell

package-lock.json, package.json
After cypress-cucumber-preprocessor package updates their version to 2.3.1 and fix the issue with cypress & cucumber we no more need to have this script "preinstall": "npx npm-force-resolutions"
While updating the dev dependency we were facing the issue:<img width="834" alt="Screenshot 2020-04-22 at 09 43 38" src="https://user-images.githubusercontent.com/34001198/79956699-c8eee080-8480-11ea-9ef9-73839505c7ec.png">
<del> - [ ] Release notes (Conventional Commits)  </del>
<del> - [ ] Cypress automation tests </del>
<del> - [ ] Storybook added or updated </del>
<del> - [ ] Theme support </del>
<del> - [ ] Typescript `d.ts` file added or updated </del>
=> test: update version for cucumber preprocessor

cypress.env.json, cypress/features/regression/test/flatTableSortable.feature, cypress/locators/flat-table/index.js, cypress/locators/flat-table/locators.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/flat-table-steps.js, src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.js, src/components/flat-table/flat-table.stories.mdx, src/components/flat-table/flat-table.style.js, src/components/flat-table/index.js, src/components/flat-table/sort/index.js, src/components/flat-table/sort/sort.component.js, src/components/flat-table/sort/sort.d.ts, src/components/flat-table/sort/sort.spec.js, src/components/flat-table/sort/sort.style.js, src/style/themes/base/base-theme.config.js, src/utils/helpers/options-helper/options-helper.js
- Add new component <Sort/> to create possibility of sorting in the Flat Table
- Added support for themes: 'dark' and 'light'
- open storybook
- go to test/flat-table/sortable
=> feat(flat-table): add new component <Sort /> - FE-2482

cypress/features/regression/experimental/dateInput.feature, cypress/support/step-definitions/date-input-steps.js, src/__experimental__/components/date/date.component.js
Clicking on calendar icon should open the Date Picker
Clicking on calendar icon opens Date Picker for a fraction of second and closes it instantly
Storybook -> Experimental -> Date Input -> Default
=> fix(date): allow to open date picker by clicking on calendar icon - FE-2680

src/components/accordion/accordion.component.js, src/components/accordion/accordion.spec.js, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.style.js
After adding, removing or modifying Accordions content it should adjust its height properly
Currently, accordion resize content only on constructor or when you expend the accordion.
Closes #2848
Storybook -> Design System -> Accordion -> With dynamic content
=> fix(accordion): lack of accordion resize when content size changes

cypress.env.json, cypress/features/regression/drawer.feature, cypress/locators/drawer/index.js, cypress/locators/drawer/locators.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/drawer-steps.js, src/components/drawer/drawer.component.js, src/components/drawer/drawer.d.ts, src/components/drawer/drawer.stories.mdx, src/components/drawer/drawer.style.js, src/components/drawer/index.js, src/style/themes/base/base-theme.config.js
Drawer component, a simple two container layout that allows for left hand side container to expand and collapse as per user choice/settings white the right hand side container adjusts reflows its content based on available space.
=> feat(drawer): create drawer component

script/docker/cypress.sh
Split the for `cypress.sh --regression` tag for two separate steps in TeamCity:
- run regression
- generate report
In this case when the `regression` suite fails the next one step will generate results but should mark the build as failed
Currently if we have failing tests our regression suite isn't marked as `failed`
=> ci(cypress.sh): split for run script and generate results

src/components/anchor-navigation/anchor-navigation.component.js, src/components/anchor-navigation/anchor-navigation.spec.js
After clicking on one of the navigation menu items window should be scrolled to the proper section.
After clicking on one of the navigation menu items on Firefox section is scrolled instantly and section is only partially visible
For more information including a video check FE-2611
Storybook -> Test -> AnchorNavigation -> Basic
=> fix(anchor-navigation): incorrect scroll animation in firefox - FE-2611

src/components/card/__snapshots__/card.spec.js.snap, src/components/card/card-footer/card-footer.style.js, src/components/card/card.spec.js, src/style/themes/base/base-theme.config.js
Fixes #2900
Only content that is interactive should be green in the card footer
All text content in the footer is green
Proposed Change:
Current:
=> fix(card-footer): update the footer non interactive text colour to black

cypress.env.json, cypress/features/regression/designSystem/popoverContainerDS.feature, cypress/features/regression/test/popoverContainer.feature, cypress/locators/popover-container/index.js, cypress/locators/popover-container/locators.js, cypress/support/helper.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/popover-container-steps.js, src/components/popover-container/index.js, src/components/popover-container/popover-container.component.js, src/components/popover-container/popover-container.d.ts, src/components/popover-container/popover-container.spec.js, src/components/popover-container/popover-container.stories.js, src/components/popover-container/popover-container.stories.mdx, src/components/popover-container/popover-container.style.js
iconType is no longer supported
- isOpen
- onClose
- renderOpenComponent
- shouldCoverButton
- renderCloseComponent
- ariaDescribedBy
- iconType
- It allows the user to use custom element to open popover-container
- popover-container will be only in controlled mode
- hardcoded Icon that opens component
- uncontrolled 
1: Open storybook
2: Go to TEST/popover-container
=> feat(popover-container): support to be controlled and uncontrolled 

cypress.env.json, cypress/features/regression/designSystem/popoverContainerDS.feature, cypress/features/regression/test/popoverContainer.feature, cypress/locators/popover-container/index.js, cypress/locators/popover-container/locators.js, cypress/support/helper.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/popover-container-steps.js, src/components/popover-container/index.js, src/components/popover-container/popover-container.component.js, src/components/popover-container/popover-container.d.ts, src/components/popover-container/popover-container.spec.js, src/components/popover-container/popover-container.stories.js, src/components/popover-container/popover-container.stories.mdx, src/components/popover-container/popover-container.style.js
This commit is a revert of the revert commit in #2904. It re-introduces the `BREAKING CHANGE` but this time it will trigger a `MAJOR` version bump.
I used `git revert -m 1 c33cef2a57bb8027cabd2b8d45306143a112eaf1` to create this PR from the master branch.
Functionality was reverted in https://github.com/Sage/carbon/pull/2904
`git diff v17.5.0`
=> feat(popover-container): add render props and support controlled usage

cypress/features/regression/button.feature, cypress/support/step-definitions/button-steps.js, src/components/button/button-types.style.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.mdx, src/style/themes/base/base-theme.config.js, src/utils/helpers/options-helper/__spec__.js, src/utils/helpers/options-helper/options-helper.js
Adds dashed button style to the choice of Buttons. 
Currently dashed button does not exist as an option in the Button component
N/A
- Open storybook.
- Navigate to Button component.
- Select Knobs version of Button (URL should appear similar to `http://localhost:9001/?path=/story/button--knobs` depending on which port you are using.).
- Go to Knobs tab and click the buttonType dropdown menu.
- Select 'dashed' from the choice of buttonType props.
=> feat(button): add dashed button FE-2655

docs/getting-started.md, package-lock.json, package.json
It's not possible to use two instances of the same version of `styled-components` (it removes all styles). Moving `styled-components` to a peer-dependency resolves this.
We install a specific version of `styled-components` as a dependency.
- Users can not use the same version of `styled-components` in their project.
- It's not possible to have two versions of `carbon-react` on the page at the same time because of `styled-components`. This may be required when adopting micro frontends.
<del>- [ ] Release notes (Conventional Commits) 
:warning: …
=> chore: make styled-component a peer dependency

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.d.ts, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-header/flat-table-header.component.d.ts, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.mdx
The colspan and rowspan props have been added to the FlatTableCell and FlatTableHeader components to allow to specify a cell that spans multiple rows/cells like in the HTML Table element.
There is no possibility to pass colspan and rowspan to rendered HTML th and td elements.
1. run npm start locally.
2. open http://localhost:9001/?path=/docs/design-system-flat-table--with-colspan
3. open http://localhost:9001/?path=/docs/design-system-flat-table--with-rowspan
=> feat(flat-table): add colspan and rowspan props (FE-2744)

src/__experimental__/components/fieldset/fieldset.component.js, src/__experimental__/components/form-field/form-field.component.js, src/__experimental__/components/input/input-presentation.component.js, src/__experimental__/components/label/label.component.js, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/textbox/textbox.component.js, src/components/accordion/accordion.component.js, src/components/action-popover/action-popover.component.js, src/components/anchor-navigation/anchor-navigation.component.js, src/components/button/button.component.js
Going to following components should show deprecated warning in the dev console 
- Fieldset: src/_experimental_/components/fieldset/
- FormField: src/_experimental_/components/form-field/
- Input & InputPresentation: src/_experimental_/components/input/
- Label: rc/_experimental_/components/label/
- RadioButtonGroup: src/_experimental_/components/radio-button/
- Textbox : src/_experimental_/components/textbox/
- Accordion: src/components/accordion/
- ActionPopover: src/components/action-popover/
- AnchorNavigation: src/components/anchor-navigation/
- Button: src/components/button/
=> refactor: Add info about deprecated styleOverride - FE-2745

src/components/link/link.component.js, src/components/menu/docgenInfo.json, src/components/menu/menu-item/__definition__.js, src/components/menu/menu-item/__spec__.js, src/components/menu/menu-item/docgenInfo.json, src/components/menu/menu-item/menu-item.js
When the Link component had React Router removed in version 17 of Carbon, the Menu component was not updated to handle the new prop expectation of routerLink.
This now passes the routerLink element prop to the Link component.
The prop type expectation has been updated to allow direct passing of Link from React Router without needing to wrap in a function.
The Menu Item does not pass the routerLink prop to the rendered Link component.
A warning appears in the stating the React Router Link element is not a function.
Example codesandbox can be found here: https://github.com/Sage/carbon/issues/2924
<del>- [ ] Typescript `d.ts` file added or …
=> fix(menu): add routerLink prop as no longer provided by link component

.github/workflows/cypress-parallel.yml
Fixed in this [PR](https://github.com/cypress-io/github-action/pull/146) and we need to update `cypress-io/github-action@v1.24.2` up to `cypress-io/github-action@v1.24.3`
Only one warning left with `spec` for cypress actions
=> ci: update for cypress action version

cypress/features/regression/link.feature, cypress/support/step-definitions/link-steps.js, src/components/link/docgenInfo.json, src/components/link/link.component.js, src/components/link/link.d.ts, src/components/link/link.spec.js, src/components/link/link.stories.js
Link component should render with target property if it is provided.
Fixes #2921
When target property is provided Link does not render that property. Because of that user is not able to specify that link should open in new tab for example.
This codesandbox demo that shows that `target` prop is not working.
https://codesandbox.io/s/link-target-issue-jjgwl?file=/src/index.js
http://localhost:9001/?path=/docs/link--default
=> fix(link): add target prop - FE-2793

.github/workflows/cypress-parallel.yml, .travis.yml, package-lock.json, package.json
- removed 4th and 5th threads from cypress run to unblock `travis` runs;
- update ubuntu to the `latest` version;
- add caching stages for correct restoring `cache`;
- update `actions/checkout@v1` to `actions/checkout@v2.2.0`;
- update `cypress` to version 4.7.0.
To unblock `travis` runs to make it faster we need to remove 4th and 5th threads from cypress run
=> ci: remove unnecessary threads

cypress/features/visual/toast.feature, cypress/support/step-definitions/common-steps.js, src/components/toast/toast.stories.js
Adds story for visual tests for applitool
N/A
=> test(toast): add visual story

cypress.env.json, cypress/features/regression/designSystem/tileSelect.feature, cypress/features/visual/tileSelect.feature, cypress/locators/tileSelect/index.js, cypress/locators/tileSelect/locators.js, cypress/support/helper.js, cypress/support/step-definitions/themes-steps.js, cypress/support/step-definitions/tile-select-step.js, src/components/tile-select/index.js, src/components/tile-select/tile-select-group.component.js, src/components/tile-select/tile-select-group.d.ts, src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.d.ts, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js, src/style/themes/base/base-theme.config.js
This PR introduces new `TileSelect` component
- <del>[ ] Screenshots are included in the PR</del>
Is a copy of https://github.com/Sage/carbon/pull/2942
Storybook -> Design System -> TileSelect
=> feat(tile-select): create tile-select component - FE-2667

cypress/features/regression/test/grid.feature, cypress/features/visual/grid.feature, cypress/support/step-definitions/grid-steps.js, src/components/grid/__snapshots__/grid.spec.js.snap, src/components/grid/grid-item/grid-item.component.js, src/components/grid/grid-item/grid-item.style.js, src/components/grid/grid-item/index.d.ts, src/components/grid/grid.spec.js, src/components/grid/grid.stories.js, src/components/grid/grid.stories.mdx
User should be able to set alignSelf and justifySelf on Griditem level.
User can only set alignSelf and justifySelf through responsiveSettings which is limiting.
http://localhost:9001/?path=/docs/design-system-grid--justify
=> feat(grid-item): add align and justify props - FE-2764

docs/getting-started.md
We want to discourage custom CSS (at the request of Sage). The aim is for `carbon-react` to provide all the styling required. This PR will change the documentation to favour other methods over having a custom CSS file.
- Change the CSS `@import` to be an external stylesheet.
- Document `webfontloader` to deal with FOUT.
- Document alternative approaches instead of webpack.
- Make it clear the you need to load the `CarbonIcons` font and it is not available on a CDN (yet).
We state to add `@import` to your CSS.
<del>- [ ] Storybook added or …
=> docs: add documentation on webfontloader

.storybook/theme-selector/register.js
Fixes the alignment of the theme selector dropdown
The theme selector dropdown is misaligned
<del>- [ ] All themes are supported<del>
<del>- [ ] Unit tests added or updated<del>
<del>- [ ] Cypress automation tests added or updated<del>
Before:
After:
=> fix(storybook): fix alignment of theme selector FE-2832

src/components/button-toggle/button-toggle-input.component.js, src/components/button-toggle/button-toggle.component.js, src/components/button-toggle/button-toggle.spec.js, src/components/button-toggle/button-toggle.stories.js, src/components/button-toggle/docgenInfo.json
`onBlur` prop should be passed to the underlying `input` element in ButtonToggle component
`onBlur` prop is not passed to the underlying `input` element
<del>- [ ] Screenshots are included in the PR</del>
Storybook -> Button Toggle -> default 
Focus on one of the ButtonToggles -> blur it -> check `actions` tab
=> fix(button-toggle): onBlur not being passed on button toggle input - FE-2860

.github/workflows/chromatic-branch.yml, .github/workflows/chromatic-release.yml, .github/workflows/ci.yml
We need to auto-accept chromatic baselines on upstream branches.
It's documented here, but not clear that it's mandatory
https://www.chromatic.com/docs/ci#github-squash-rebase-merge-and-the-master-branch
I've created two new CI scripts:
- chromatic-branch.yml - runs on each push to non release branches
- chromatic-release.yml - runs on each push to release branches, and auto-accepts the changes.
I contacted support and they said they might auto-accept on our behalf in the future to save us on CI usage.
Without this the dashboard will always say there are ~300 changes
<del>- [ ] …
=> ci: update chromatic baselines

.github/workflows/chromatic-pr.yml, .github/workflows/chromatic-push.yml, .github/workflows/ci.yml, .github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml, CONTRIBUTING.md, README.md
Update `CONTRIBUTING.md` to explain how we run CI on forked PR's.
- run on `pull_request`, skip if it is a pr from a fork
- run on `push` to `test-integration`, used to update pr's from forks
- run on `pull_request`, skip if it is a pr from a fork
- run on `push` to `test-integration`, used to update pr's from forks
- run on `pull_request`, including forks
- Forked PR's not documented
- We run CI on push to any branch, so its not possible for developers to save their interim work on the remote without triggering CI.
<del>- [ ] Storybook …
=> ci: run workflows on pr where possible

src/__experimental__/components/checkbox/checkbox.stories.js, src/__experimental__/components/select/select.stories.js, src/__experimental__/components/textarea/textarea.stories.js, src/__experimental__/components/textbox/textbox.stories.js
Make the initial `guid` in stories static.
The `guid` changes on every test resulting in false positives.
N/A
Check chromatic, the diff should show the new baselines are a string instead of a guid.
=> docs: prevent guid changing in chromatic

cypress/features/regression/button.feature, cypress/features/regression/create.feature, cypress/features/regression/designSystem/drawer.feature, cypress/features/regression/designSystem/duellingPicklist.feature, cypress/features/regression/designSystem/tileSelect.feature, cypress/features/regression/help.feature, cypress/features/regression/showEditPod.feature, cypress/features/regression/test/accordion.feature, cypress/features/regression/test/actionPopoverStyleOverrideNoIFrame.feature, cypress/features/regression/test/badge.feature, cypress/features/regression/test/batchSelection.feature, cypress/features/regression/test/search.feature
Removed no needed test cases and comments
We have in the code comments `will be removed when Applitools will be implemented`. We are using Chromatic now, instead of Applitools, so
- we need to remove these comments,
- remove test cases covered by Chromatic
=> test(cypress): remove no needed test cases and comments

src/__experimental__/components/date/date.stories.js, src/__experimental__/components/select/select.stories.js, src/components/portrait/portrait.stories.js, src/components/rainbow/rainbow.stories.js, src/components/table-ajax/table-ajax.stories.js
Prevent screenshots on these components
- Rainbow (soon to be deprecated)
- Select (being re-written)
- Date (possible re-write coming soon, false positive possible related to portal or font-loading)
- Portrait (we need to fix this)
I've delayed the `TableAjax` story to allow for data to load.
Chromatic detects a 1px change in the `Portal` and the font moves in `Rainbow`.
N/A
Review chromatic dashboard and ensure the components listed above have been …
=> chore: prevent chromatic false positives

.github/workflows/semantic-release.yml, src/__deprecated__/components/fieldset/__definition__.js, src/__deprecated__/components/fieldset/__spec__.js, src/__deprecated__/components/fieldset/docgenInfo.json, src/__deprecated__/components/fieldset/documentation/notes.md, src/__deprecated__/components/fieldset/fieldset.js, src/__deprecated__/components/fieldset/fieldset.scss, src/__deprecated__/components/fieldset/fieldset.stories.js, src/__deprecated__/components/fieldset/package.json, src/__deprecated__/components/radio-button/__definition__.js, src/__deprecated__/components/radio-button/__spec__.js, src/__deprecated__/components/radio-button/docgenInfo.json, src/__deprecated__/components/radio-button/documentation/index.js, src/__deprecated__/components/radio-button/documentation/info.js, src/__deprecated__/components/radio-button/documentation/notes.md, src/__deprecated__/components/radio-button/notes.md, src/__deprecated__/components/radio-button/package.json, src/__deprecated__/components/radio-button/radio-button.js, src/__deprecated__/components/radio-button/radio-button.scss, src/__deprecated__/components/radio-button/radio-button.stories.js
Revert #3013 and #3012 
Use `persist-credentials: false` so `semantic-release` uses the `GH_TOKEN` to push to the repo.
`semantic-release` is using the checkout token that does not have push access.
https://github.com/semantic-release/git/issues/196
Merge to master and check the `semantic-release` job.
=> ci: prevent credentials being stored from checkout

.storybook/welcome-page/header/header.component.js
Ignore the npm badge on the welcome page.
The npm badge on the welcome page updates causing a diff every time we release.
N/A
Compare the visual diff of the master build after the next release.
=> ci(chromatic): ignore npm badge

docs/documentation-styleguide.md
Create a Documentation styleguide to aid with creating and maintaining documents throughout the repository with a consistent style.
There is no Documentation styleguide for contributors to follow.
Check links work in the document.
=> docs: add documentation styleguide

src/components/dialog/dialog.stories.js
Make the date in dialog stories static to prevent false positives.
The date component in Dialog stories always uses todays date, so the first build of each day will change the baseline.
https://www.chromatic.com/snapshot?appId=5ecf782fe724630022d27d7d&id=5ef489a19df5b8002256699d
Check pr's made after this change is merged don't show a diff for Dialog. You can't test until this is merged.
=> test(chromatic): make the date static in dialog stories

src/__experimental__/components/date-range/date-range.component.js, src/__experimental__/components/date-range/date-range.stories.js
When the labelsInline prop is true on the DateRange component the validation icons should be displayed on the same line as the label text like this: 
The validation icons are being displayed on a second line underneath the label: 
- <del>[ ] Unit tests added or updated</del>
- <del>[ ] Cypress automation tests added or updated</del>
- <del>[ ] Storybook added or updated</del>
- <del>[ ] Typescript `d.ts` file added or updated</del>
=> fix: increase width on validation labels

src/components/anchor-navigation/anchor-navigation-item.component.js, src/components/anchor-navigation/anchor-navigation-item.d.ts
This PR adds missing `target` prop definition both to propTypes and type declaration file.
Currently `target` prop is not defined which causes compilation errors in typescript projects
<del>- [ ] Screenshots are included in the PR</del>
<del>- [ ] Carbon implementation and Design System documentation are congruent</del>
<del>- [ ] All themes are supported</del>
<del>- [ ] Unit tests added or updated</del>
<del>- [ ] Cypress automation tests added or updated</del>
Closes #3030
=> fix(anchor-navigation): add missing target prop definition

README.md
Remove the cypress badge from the README.md
There is a badge but it says the build is failing. This is because the badge reports the status of the master branch, we don't run the cypress tests on the master branch.
=> docs: remove cypress badge

src/components/alert/alert.stories.js
This PR replaces #3032
Removal of classic theme from storybook.
Currently, component has classic theme storybook examples.
<del>- [ ] Screenshots are included in the PR </del>
<del>- [ ] Unit tests added or updated </del>
<del>- [ ] Typescript `d.ts` file added or updated </del>
N/A
Open storybook.
Check that Alert component has no Classic Theme storybook examples.
=> docs(alert): remove classic theme stories 

src/__experimental__/components/switch/__snapshots__/switch-slider.spec.js.snap, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__experimental__/components/switch/switch-slider.style.js
<del>- [ ] Cypress automation tests added or updated</del>
Storybook -> Switch -> Validations -> change `error size` knob to `large`
=> fix(switch): fix misaligned validation icon on large switch - FE-2863

src/components/animated-menu-button/animated-menu-button.js
Adds a deprecation warning to the console.
<del>- [ ] Carbon implementation and Design System documentation are congruent</del>
<del>- [ ] All themes are supported</del>
<del>- [ ] Unit tests added or updated</del>
<del>- [ ] Cypress automation tests added or updated</del>
N/A
Pull down branch.
Open storybook.
Inspect console for deprecation warning.
=> chore(animated menu button): add deprecation warning

.github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml
Setup max timeout `25m` for a `cypress run` step instead `360m` (as it is by `default`) before the build will be canceled;
Cypress tests are taking more than `6h (360m)` before the build will be canceled if cypress will hang.
=> ci(cypress tests): add timeout before build will be canceled

cypress.env.json, cypress/features/regression/accessibility/accessibilityDesignSystem.feature, package-lock.json, src/components/note/__internal__/note.component.js, src/components/note/__internal__/note.d.ts, src/components/note/__internal__/note.spec.js, src/components/note/__internal__/note.stories.mdx, src/components/note/__internal__/note.style.js, src/components/note/__internal__/status-with-tooltip/index.js, src/components/note/__internal__/status-with-tooltip/status.component.js, src/components/note/__internal__/status-with-tooltip/status.spec.js, src/components/note/__internal__/status-with-tooltip/status.style.js, src/components/note/index.d.ts, src/components/note/index.js, src/style/themes/base/base-theme.config.js
Component supports some features not present in `Tile`, such as a composable inline control, title and footer content including a status with tooltip. The component uses the `draftjs` editor in `readOnly` mode to support rendering of both plain and rich text content.
The meta content has intentionally been omitted as it may be possible to simply render that as part of the `draft-js` `Editor`'s content
This is a new component
With plain text:
With Rich text:
With title:
With inline control:
With footer:
Can be tested on storybook
`http://localhost:9001/?path=/docs/design-system-note--`...
https://codesandbox.io/s/carbon-quickstart-hwssk?file=/src/index.js
=> feat(note): create component and tooltip status FE-2825

docs/getting-started.stories.mdx, docs/using-draft-js.stories.mdx
Adds a guide to inform consumers how to use the `EditorState` and `ContentState` static methods to
manipulate the `TextEditor` component's content. The `install` command has also been added to the peer-dependency section of the `getting started` guide
No guide exists
<del>- [ ] Screenshots are included in the PR<del>
<del>- [ ] All themes are supported<del>
<del>- [ ] Unit tests added or updated<del>
<del>- [ ] Cypress automation tests added or updated<del>
The `TextEditor` and `Note` components rely on the `Draft.js` framework so this document aims to help them get to grips with formatting the content correctly
No QA required
=> docs: create guide on draft js editorstate and contentstate FE-2943

cypress/features/regression/tableWithInputs.feature, src/components/table/table.stories.js
Add two new stories that show the configuration that the cypress test was setting with knobs. These will be screenshotted and added to chromatic where we will check for visual regressions.
The cypress tests fails intermittently, this is wasting a lot of CI minutes.
https://github.com/cypress-io/cypress/issues/7918
Fixes FE-2934
Ensure two new screenshots are added to chromatic.
=> test: convert intermittently failing cypress test to be a chromatic test

cypress.env.json, cypress/features/regression/alert.feature, cypress/features/regression/alertActions.feature, cypress/features/regression/test/badge.feature, cypress/features/regression/test/badgeActions.feature, cypress/fixtures/commonComponents/alert.json, cypress/fixtures/test/badge.json, cypress/locators/badge/index.js, cypress/locators/confirm/index.js, cypress/locators/dialog/index.js, cypress/locators/index.js, cypress/support/helper.js, cypress/support/step-definitions/alert-steps.js, cypress/support/step-definitions/badge-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/confirm-steps.js
Implemented new approach for passing `parameters` via `url`. This approach allows us:
- do not load components using `iFrame`
- not typing any characters in `Knobs`
- have already prepared `component` / `element` in proper `condition` / `state`
- only make an `assertion` using `cypress`
- decrease run time for tests: 
-- `Alert` previously took approx. `02:26` and now -> `00:54`;
-- `Badge` previously took approx. `01:00` and now -> `00:23`;
It is only the `POC` for new `approach` and I didn't do a major refactor for all components. Just made changes for 2 components to compare timing and discuss.
Currently we are passing all `parameters` using `Knobs`. Storybook takes a lot of time to be fully loaded and sometimes cypress fails to pass all `params` properly, that's why `cypress` tests …
=> test(helper): function to pass parameters via url

CONTRIBUTING.md
General advice on avoiding unnecessary builds.
We often trigger builds, only to trigger another build immediately after.
N/A
N/A
=> docs(contributing): preventing unnecessary builds

cypress/features/regression/designSystem/numeralDate.feature, cypress/features/regression/experimental/checkbox.feature, cypress/features/regression/experimental/dateInput.feature, cypress/features/regression/experimental/dateRange.feature, cypress/fixtures/experimental/checkbox.json, cypress/fixtures/experimental/dateInput.json, cypress/fixtures/experimental/dateRange.json, cypress/fixtures/test/numeralDate.json, cypress/locators/checkbox/index.js, cypress/locators/date-input/index.js, cypress/locators/date-range/index.js, cypress/locators/date-range/locators.js, cypress/locators/index.js, cypress/locators/numeralDate/index.js, cypress/locators/numeralDate/locators.js, cypress/support/step-definitions/checkbox-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/date-input-steps.js, cypress/support/step-definitions/date-range-steps.js, cypress/support/step-definitions/numeral-date-steps.js
`Design System:`
- Numeral Date (`timing`: was `1:42` -> `00:30`).
`Experimental:`
- Checkbox (`timing`: was `3:19` -> `1:05`).
- Date Input (`timing`: was `5:26` -> `2:01`).
- Date Range (`timing`: was `1:13` -> `00:30`).
=> test(numeraldate,checkbox,dateinput,daterange): update tests with a new approach

cypress/features/regression/experimental/textarea.feature, cypress/features/regression/experimental/textbox.feature, cypress/features/regression/experimental/textboxActions.feature, cypress/features/regression/experimental/textboxMultiple.feature, cypress/fixtures/experimental/textarea.json, cypress/fixtures/experimental/textbox.json, cypress/locators/index.js, cypress/locators/textarea/index.js, cypress/locators/textbox/index.js, cypress/support/step-definitions/button-toggle-group-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/text-area-steps.js, cypress/support/step-definitions/textbox-steps.js
Apply new `url` approach in  tests for:
`Experimental:`
`TextArea` (timing: was `5:00`- > `01:36`),
`TextBox` (timing: was `03:34` -> `00:45`),
`TextBox Actions` (timing: `00:14`),
`TextBox-multiple` (timing: was `03:13` -> `00:50`).
=> test(textarea): update with new approach

src/components/hr/hr.stories.mdx
`Hr` component stories will be in the Design System folder on Storybook.
They're currently just in the root folder.
- <del>[ ] Screenshots are included in the PR</del>
- <del>[ ] All themes are supported</del>
- <del>[ ] Unit tests added or updated</del>
- <del>[ ] Cypress automation tests added or updated</del>
- <del>[ ] Typescript `d.ts` file added or updated</del>
=> docs(hr): move hr stories to design system folder

src/components/note/__internal__/note.component.js, src/components/note/__internal__/note.d.ts, src/components/note/__internal__/note.spec.js, src/components/note/__internal__/note.stories.mdx, src/components/note/__internal__/note.style.js, src/components/note/__internal__/status-with-tooltip/status.style.js
Add default theme.
The following props are now required for the Note component.
- noteContent
- name
- createdDate
- status.text if status is provided
- status.timeStamp if status is provided
- inlineControl must be an instance of ActionPopover
Ensure typescript prop types match the react prop types.
MDX examples have also been simplified.
`noteContent` defaults to an empty value, in practice this will not be used and is likely an error.
`name` and `createdDate` are optional but both are required for anything to be displayed. The DLS shows that both of these should be present.
It is possible to provide `status.timeStamp` without `status.text`, but nothing will be displayed.
It is possible to provide `status.text` without `status.timeStamp` but this is not featured in the DLS. …
=> fix(notes): update prop types

rfcs/text/i18n.md
Introduce first class support for internationalisation and localisation within `carbon-react`.
---
This PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/master/rfcs/README.md).
Please use 👍  if you approve.
=> docs(rfc): propose i18n upgrade

cypress/features/regression/configurableItems.feature, cypress/features/regression/draggableContext.feature, cypress/features/regression/experimental/decimalInput.feature, cypress/features/regression/experimental/groupedCharacter.feature, cypress/features/regression/experimental/numberInput.feature, cypress/features/regression/experimental/numberInputActions.feature, cypress/features/regression/experimental/radioButtonGroup.feature, cypress/features/regression/experimental/textarea.feature, cypress/features/regression/experimental/textbox.feature, cypress/features/regression/test/badge.feature, cypress/features/regression/test/draggableNoIFrame.feature, cypress/fixtures/experimental/groupedCharacter.json, cypress/fixtures/experimental/numberInput.json, cypress/fixtures/experimental/radioButtonGroup.json, cypress/locators/radioButton/index.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/configurable-items-steps.js, cypress/support/step-definitions/detail-steps.js, cypress/support/step-definitions/grouped-character-steps.js, cypress/support/step-definitions/number-input-steps.js, cypress/support/step-definitions/radio-button-steps.js, cypress/support/step-definitions/text-area-steps.js
`Experimental:`
- Group Character(`timing`: was `6:59` -> `2:29`).
- Number Input (`timing`: was `6:41` -> `1:11`).
- RadioButton Group(`timing`: was `0:54` -> `00:21`).
=> test(radiobuttongroup,groupedcharacter, numberinput): update tests

package-lock.json
Update prismjs as per dependabots security alert. It was unable to do it automatically, I think because prismjs wasn't explicitly in our package.json as a dep.
- <del>[ ] Screenshots are included in the PR</del>
- <del>[ ] Carbon implementation and Design System documentation are congruent</del>
- <del>[ ] All themes are supported</del>
- <del>[ ] Unit tests added or updated</del>
- <del>[ ] Cypress automation tests added or updated</del>
- <del>[ ] Storybook added or updated</del>
- <del>[ ] Typescript `d.ts` file added or updated</del>
=> build(deps): [security] bump prismjs up to 1.21.0

cypress/features/regression/table.feature, cypress/features/regression/tableActions.feature, cypress/features/regression/tableAjax.feature, cypress/features/regression/tableWithInputs.feature, cypress/features/regression/test/pager.feature, cypress/fixtures/commonComponents/table.json, cypress/fixtures/test/pager.json, cypress/locators/pager/index.js, cypress/locators/table/index.js, cypress/locators/table/locators.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/pager-steps.js, cypress/support/step-definitions/table-steps.js
`Table` (timing: was `3:04`- > `01:02`),
`Table Action` (timing: `00:31`),
`Table with inputs` (timing: was `02:46` -> `01:04`),
`Pager` (timing: was `02:17` -> `00:50`).
=> test(table/tableActions/tableWithInputs/Pager): apply new url approach

src/components/note/__internal__/note.spec.js, src/components/note/__internal__/note.style.js
The missing `box-sizing: border-box` and has
a `min-width` have been added, this means it aligns with a `fullWidth` `Button` for example. The footer has also been updated to allow the content to wrap at smaller screen sizes.
Currently the `Note` component overflows its parent as it is missing `box-sizing: border-box` and has
a `min-width`. The footer does not wrap as there is a min-width on the component
<del>- [ ] Cypress automation tests added or updated<del>
Example of mis-align with Button:
Overflowing parent: 
No longer overflowing:
codesandbox of changes:
https://codesandbox.io/s/carbon-quickstart-5q11p?file=/src/index.js
=> fix(note): remove min width to allow note to size dynamically

.github/CODEOWNERS
Assign `cypress.json`and `cypress.env.json` to be owned by QA team
`cypress.json`and `cypress.env.json` are not owned by QA team
<del>- [ ] Screenshots are included in the PR<del>
<del>- [ ] All themes are supported<del>
<del>- [ ] Unit tests added or updated<del>
<del>- [ ] Cypress automation tests added or updated<del>
=> chore(codeowners): assign cypress json files to be owned by qa

cypress/features/regression/experimental/checkbox.feature, cypress/features/regression/experimental/switch.feature, cypress/features/regression/tile.feature, cypress/fixtures/commonComponents/tile.json, cypress/fixtures/experimental/switch.json, cypress/locators/switch/index.js, cypress/locators/switch/locators.js, cypress/locators/tile/index.js, cypress/locators/tile/locators.js, cypress/support/step-definitions/checkbox-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/switch-steps.js, cypress/support/step-definitions/tile-steps.js
`tile` (timing: was `1:00` -> `0:22` ),
`switch` (timing: `1:02` ).
=> test(tile, switch): update cypress tests with a new URL approach

cypress.json, cypress/features/regression/confirmActions.feature, cypress/features/regression/dialogFullScreen.feature, cypress/features/regression/experimental/textbox.feature, cypress/features/regression/experimental/textboxMultiple.feature, cypress/features/regression/message.feature, cypress/features/regression/test/search.feature, cypress/locators/dialog/index.js, cypress/plugins/index.js, cypress/support/index.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/dialog-steps.js, cypress/support/step-definitions/select-steps.js, package-lock.json, package.json
- updated `cypress` version from `4.10.0` to `5.0`;
- remove `deprecated` -> `cypress-plugin-retries`;
- refactor `cypress.json` file to apply new built-in approach for retries.
After update cypress version to `5.0`, we need to remove `cypress-plugin-retries` as it is became a deprecated. And apply built-in approach.
=> test(cypress): upgrade version to 5.0

cypress/features/regression/splitButton.feature, cypress/features/regression/stepSequence.feature, cypress/features/regression/stepSequenceItem.feature, cypress/fixtures/commonComponents/splitButton.json, cypress/fixtures/commonComponents/stepSequence.json, cypress/locators/split-button/index.js, cypress/locators/step-sequence/index.js, cypress/support/step-definitions/button-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/split-button-steps.js, cypress/support/step-definitions/step-sequence-steps.js
`splitButton` (timing: was `02:13` -> `00:49`),
`stepSequence` (timing: was  `00:12` -> `00:05`),
`stepSequenceItem` (timing  `01:25` -> `00:51`).
=> test(split-button/step-sequence/step-sequence-item): apply new url approach

.storybook/welcome-page/header/header.component.js, .storybook/welcome-page/welcome.stories.js, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__experimental__/components/switch/switch.component.js, src/__experimental__/components/switch/switch.spec.js, src/__experimental__/components/switch/switch.style.js
When `labelInline = true` and `reverse = false` validation icon is forced to be displayed on label.
Also ensure field help is correctly aligned with the label when fieldhelp is inline but label is not: 
Described here https://github.com/Sage/carbon/issues/3022
Closes #3022 
Storybook -> Switch -> Validations
=> fix(switch): fix switch validation icon overlapping the label - FE-2905

cypress/features/regression/preview.feature, cypress/features/regression/profile.feature, cypress/features/regression/row.feature, cypress/fixtures/commonComponents/preview.json, cypress/fixtures/commonComponents/profile.json, cypress/fixtures/commonComponents/row.json, cypress/locators/preview/index.js, cypress/locators/profile/index.js, cypress/locators/row/index.js, cypress/support/step-definitions/preview-steps.js, cypress/support/step-definitions/profile-steps.js
`row` (timing: was `02:03` -> `00:33`),
`preview` (timing: was  `01:20` -> `00:26`),
`profile` (timing  `01:25` -> `00:21`).
=> test(preview/profile/row): apply new url approach

cypress/features/regression/message.feature, cypress/features/regression/multiActionButton.feature, cypress/features/regression/pages.feature, cypress/features/regression/pagesActions.feature, cypress/fixtures/commonComponents/message.json, cypress/fixtures/commonComponents/multiActionButton.json, cypress/fixtures/commonComponents/pages.json, cypress/locators/button/index.js, cypress/locators/index.js, cypress/locators/message/index.js, cypress/locators/multi-action-button/index.js, cypress/locators/pages/index.js, cypress/support/step-definitions/button-steps.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/message-steps.js, cypress/support/step-definitions/multi-action-button-steps.js, cypress/support/step-definitions/pages-steps.js
`message` (timing: was `01:19` -> `0:26` ),
`multiactionbutton` (timing: was  `01:33` -> `0:29` ),
`pages` (timing  `01:27` -> `0:14` ),
`pagesActions` (timing `0:32`)
=> test(message, multiactionbutton, pages): update test with new approach

package-lock.json, package.json, src/__experimental__/components/select/select.component.js, src/__experimental__/components/select/select.spec.js, src/__experimental__/components/select/select.stories.js, src/__internal__/DeprecationWarning.js
Encourage users to use the new Select component and clear up confusion over deprecated/experimental and design system implementations of Select component.
There is now a warning in storybook
and a warning in the console.
There are some missing features that prevent us from removing this Select component.
FE-3034
View the `experimental-select/default` story in storybook preview.
=> chore(select): deprecate the experimental select component

cypress/features/regression/designSystem/inlineInputs.feature, cypress/features/regression/i18nComponent.feature, cypress/fixtures/commonComponents/i18n.json, cypress/fixtures/designSystem/inlineInputs.json, cypress/locators/i18n/index.js, cypress/locators/inline-inputs/index.js, cypress/locators/inline-inputs/locators.js, cypress/support/step-definitions/common-steps.js, cypress/support/step-definitions/i18n-steps.js, cypress/support/step-definitions/inline-inputs-steps.js
`i18n` (timing: was `00:32` -> `00:08`),
`inline inputs` (timing: was  `00:49` -> `00:14`)
=> test(i18n/inline-inputs): apply new url approach

cypress/features/regression/test/popoverContainer.feature, cypress/features/regression/test/search.feature, cypress/features/regression/test/toast.feature, cypress/fixtures/test/popoverContainer.json, cypress/fixtures/test/search.json, cypress/fixtures/test/toast.json, cypress/locators/popover-container/index.js, cypress/locators/toast/index.js, cypress/support/step-definitions/search-steps.js, cypress/support/step-definitions/toast-steps.js
`Popover Container` (timing: was `00:30` -> `00:05`),
`Search` (timing: was  `00:50` -> `00:40`),
`Toast` (timing  was `00:22` -> `00:10`).
=> test(popover-container/search/toast): apply new url approach

package-lock.json, package.json, src/__experimental__/components/checkbox/checkbox.component.js, src/__experimental__/components/checkbox/checkbox.style.js, src/__experimental__/components/radio-button/radio-button.style.js, src/style/themes/base/base-theme.config.js
Use `styled-system` to give all components the same spacing options. This can be used in any component like this: 
```
// form.style.js
import styled from 'styled-components';
import { space } from 'styled-system';
const StyledForm = styled.div`
${space}
... other styles
`;
```
In that example `Form` would then have the following props:
The following spacing options (in px) have been added to the theme: 
`space: [0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80]`
All of the props above can either be a number, which is an index of the theme space array, i.e. `ml={1}` relates to `8` in the array (so effectively behaves as a multiplier of 8), or a string, which can be any valid CSS string.
Spacing is currently handled individually in components, and varies from component to component. This is both …
=> feat: add styled system to carbon

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/checkbox/checkbox.style.js, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.d.ts, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.stories.mdx, src/__experimental__/components/radio-button/radio-button.style.js, src/__internal__/fieldset/fieldset.component.js, src/__internal__/fieldset/fieldset.d.ts, src/__internal__/fieldset/fieldset.spec.js, src/__internal__/fieldset/fieldset.style.js, src/components/button/button-sizes.style.js, src/components/button/button.component.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/configurable-items/configurable-items.style.js, src/components/draggable/draggable.stories.mdx, src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js, src/components/form/form.stories.mdx, src/components/form/form.style.js
The `ml` prop on `Button` will just accept a valid CSS string to add a margin left. It will no longer subtract the button padding from it in order to be consistent will other components.
Change the `ml` prop to a string on the `RadioButtonGroup` component, this is the same as the `ml` prop on other components.
Remove extra top margin and padding from checkable components (RadioButton, Checkbox, Switch)
The margin left on button is current calculated as `calc(ml prop - button padding)`.
The `ml` prop on `RadioButtonGroup` is currently a number which is converted to a percentage.
Codesandbox for testing available below: https://codesandbox.io/s/carbon-quickstart-forked-youn8
=> refactor: form alignment minor updates

src/__experimental__/components/numeral-date/numeral-date.d.ts, src/components/button/button.d.ts
Resolves issue (https://github.com/Sage/carbon/issues/3143) by including typescript definitions.
Currently (carbon v38.0.1) when using the Button component, the typescript linter issues a problem when providing a `onClick` prop.
```
No overload matches this call.
Overload 1 of 2, '(props: ButtonProps | HTMLProps<HTMLButtonElement>, context?: any): ReactElement<any, any> | Component<ButtonProps | HTMLProps<...>, any, any> | null', gave the following error.
Type '{ children: TFunctionResult; buttonType: "tertiary"; size: "medium"; "data-role": string; onClick: (event: MouseEvent<HTMLButtonElement, MouseEvent>) => void; }' is not assignable to type '(IntrinsicAttributes & ButtonProps) | (IntrinsicAttributes & HTMLProps<HTMLButtonElement>)'.
Types of property 'onClick' are incompatible.
Type …
```
=> fix(button): update typescript definitions - FE-3039

cypress/features/regression/test/tile.feature, src/components/definition-list/dd.component.js, src/components/definition-list/dd.d.ts, src/components/definition-list/definition-list.spec.js, src/components/definition-list/definition-list.stories.js, src/components/definition-list/definition-list.style.js, src/components/definition-list/dl.component.js, src/components/definition-list/dl.d.ts, src/components/definition-list/dt.component.js, src/components/definition-list/dt.d.ts, src/components/definition-list/index.d.ts, src/components/definition-list/index.js, src/components/tile/tile.stories.js, src/components/tile/tile.stories.mdx, src/style/themes/base/base-theme.config.js
To create a new component called "Definition List" that will be used inside of the existing "Tile" component.
This component does not currently exist. 
The .stories file has been updated to the Component Story Format (CSF) and a new MDX example documentation has been created for Tile too.
- Pull down the branch `FE-2885-right_aligned_content_component`
- `npm start` to start Storybook
- Navigate to Design System -> Tile
- Navigate to the section titled `Tile with Definition List`
- Check that the examples match that specified on design spec
=> feat(definition list): create definition list component - FE-2885

src/components/note/__internal__/note.component.js
Updates the invariant for the `inlineControl` prop to check if  the passed component's constructor,
rather than its string name, is `ActionPopover`. The previous implementation throws an error in production build environments when the code is minified.
Invariant checks `inlineControl.type.name` which works in development but throws in production environment.
=> fix(note): update inline control variant check constructor FE-3134

src/components/tile/tile.stories.mdx
No error in console relating to the value passed to the `orientation` prop
The orientation prop needs to be passed either `horizontal` or `vertical` but the value passed in
the story is `Vertical`. Therefore, there is an error in the console and the story does not render correctly: there is no separating lines between the content blocks
Check `http://localhost:9001/?path=/docs/design-system-tile--vertical` there should be no error in the console relating to the value passed to the `orientation` prop
=> docs(tile): update vertical story

.storybook/preview.js
Exclude `propTypes` from `chromatic` runs.
Currently we are not ignoring `addDecorator(withInfo)` in `chromatic` runs. And when we have changed some of the `propTypes` - we have changed the `baselines` in `chromatic`.
To check if this change works correctly - check the `chromatic` build.
=> test(chromatic): exclude propTypes from chromatic

cypress/support/step-definitions/grid-steps.js, src/components/grid/__snapshots__/grid.spec.js.snap, src/components/grid/grid-container/grid-container.component.js, src/components/grid/grid-container/grid-container.style.js, src/components/grid/grid-container/index.d.ts, src/components/grid/grid-item/grid-item.component.js, src/components/grid/grid-item/grid-item.style.js, src/components/grid/grid-item/index.d.ts, src/components/grid/grid.spec.js, src/components/grid/grid.stories.js, src/components/grid/grid.stories.mdx, src/components/tabs/__internal__/tabs.stories.mdx
grid-container should accept m, ml, mr, mt, mb and gridGap props to allow custom spacings
grid-item should accept p, pl, pr, pt, pb, gridColumn and gridRow props to allow custom spacings
replace gridColumnStart and gridColumnEnd props in the GridItem component with gridColumn styled-system compatible prop
replace gridRowStart and gridRowEnd props in the GridItem component with gridRow styled-system compatible prop
no possibility to set custom spacings
gridColumnStart, gridColumnEnd, gridRowStart and gridRowEnd props not compatible with styled-system
1. run npm start
2. go to http://localhost:9001/?path=/docs/design-system-grid--custom-spacings
=> feat(grid): add styled-system cusom padding and margin props (FE-3025)

.storybook/utils/styled-system-props.js, docs/documentation-styleguide.md, src/__spec_helper__/test-utils.js, src/components/hr/hr.component.js, src/components/hr/hr.d.ts, src/components/hr/hr.spec.js, src/components/hr/hr.stories.mdx, src/components/hr/hr.style.js, src/utils/helpers/options-helper/options-helper.d.ts
Add `styled-system` spacing props to `Hr`.
Add storybook component to generate prop tables for a component, and the `styled-system` spacing props like the below screenshot: 
`Hr` currently has it's own margin props and does not use `styled-system`.
PR codesandbox generated below: https://codesandbox.io/s/divine-butterfly-wux1t
=> feat(hr): add styled-system spacing props

src/__spec_helper__/test-utils.js
Correct the handling of default values in the `testStyledSystemSpacing` util
Currently it does not handle default `m` or `p` correctly. 
Also if a component has no defaults, and no other style rules the util would fail, so that is now catered for.
=> refactor(test-utils): correct spacing util for defaults

.storybook/utils/styled-system-props.js
Sets `spacingDefaults` to an empty object as default if no value is passed in
The `StyledSystemProps` component has no default value for the `spacingDefaults` prop meaning that
it throws an error if nothing is passed to it
=> chore(styled-system): add spacing default value

src/components/step-sequence/step-sequence-item/step-sequence-item.stories.js
Disable `chromatic` for `classic` theme for `Step Sequence Item` component
We need to disable `chromatic` for `classic` theme for `Step Sequence Item` component as we not supporting `classic` theme.
=> test: disable chromatic for classic theme

.github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml
- decreased amount of the containers from `20` to `19` for `cypress` tests to to avoid unnecessary waste of resources.
According to the `cypress` recommendation (shown below on screenshot) - we are using 1 more machine than necessary on CI.
=> ci(cypress): decrease amount of containers

package-lock.json, package.json
- update `cypress` version to `5.3.0`;
- update `cypress-cucumber-preprocessor` to `3.0.0`.
To be up-to-date with new updates for `cypress` and `cypress-cucumber-preprocessor` we need to:
- update `cypress` version to `5.3.0`;
- update `cypress-cucumber-preprocessor` to `3.0.0`.
=> test: update cypress version to 5.3.0 & cypress-cucumber-preprocessor to 3.0.0

src/components/accordion/accordion.component.js, src/components/accordion/accordion.d.ts, src/components/accordion/accordion.spec.js, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.style.js, src/components/definition-list/dd.component.js, src/components/definition-list/definition-list.spec.js, src/components/definition-list/definition-list.style.js, src/components/definition-list/dl.component.js, src/components/grid/grid.stories.mdx, src/components/tile/tile.stories.mdx
Updates `DefinitionList` to `display: grid` in order to support the component being both responsive whilst also maintain alignment between  associated `Dt` and `Dd` components when the content wraps.
Adds an override to ensure the `Accordion` component has dynamic height when rendering a `DefinitionList` as a child.
Adds some examples of the component used inside an `Accordion` and in a `Grid`.
The original implementation used a single dimension to align the `Dt` and `Dd` children in columns
which caused issues with aligning them when some content wrapped. 
http://localhost:9001/?path=/story/design-system-grid--subgrid
http://localhost:9001/?path=/story/design-system-tile--tile-with-definition-list-default
http://localhost:9001/?path=/story/design-system-tile--tile-with-definition-list-wit …
=> fix(definition-list): display as grid to enable content wrapping FE-3160

cypress/features/regression/experimental/checkbox.feature, cypress/features/regression/experimental/switch.feature, cypress/features/regression/test/pager.feature, cypress/features/regression/test/tabs.feature, cypress/fixtures/experimental/checkbox.json, cypress/fixtures/experimental/switch.json, cypress/fixtures/test/pager.json, cypress/fixtures/test/tabs.json, cypress/locators/checkbox/index.js, cypress/locators/checkbox/locators.js, cypress/locators/switch/index.js, cypress/locators/tabs/index.js, cypress/locators/tabs/locators.js, cypress/support/step-definitions/checkbox-steps.js, cypress/support/step-definitions/switch-steps.js, cypress/support/step-definitions/tabs-steps.js
Tests that were duplicated, now are covered only by chromatic
We have tests that are duplicated by cypress tests and chromatic stories in our project. In that situation, we need only one of these to be sure that components are fine.
=> test: remove cypress tests covered by chromatic - FE-3204

src/components/select/simple-select/simple-select.component.js
Fixes: #3262, Fixes FE-3207
Fix https://github.com/Sage/carbon/issues/3262 where Select remains in error, even after choosing a value.
See above issue.
Sandbox here: https://codesandbox.io/s/myformikform-2ysql 
*Look at the PR one generated below for the "after" test*
=>  fix(select): destructure spacing props into style wrapper

src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.style.js
`mergeDeep` can't merge objects that have a Proxy which is needed to support `@styled-system/color`. I've removed the usage of `mergeDeep` because it can be easily simplified.
ActionPopover uses `mergeDeep` to create custom color icons.
FE-3219
Check CI/Chromatic/ActionPopover stories, in particular the icon colour.
=> refactor(action-popover): simplify custom theme FE-3219

cypress/features/regression/designSystem/flatTable.feature, cypress/locators/flat-table/index.js, src/__spec_helper__/test-utils.js, src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.d.ts, src/components/flat-table/flat-table-cell/flat-table-cell.spec.js, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-head/flat-table-head.style.js, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table-header/flat-table-header.d.ts, src/components/flat-table/flat-table-header/flat-table-header.spec.js, src/components/flat-table/flat-table-header/flat-table-header.style.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js, src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.stories.js, src/components/flat-table/flat-table.stories.mdx, src/components/flat-table/flat-table.style.js
Set custom column width by passing number as a `width` to the column headers components.
Set custom cell padding on each cell individually by using the usual spacing props syntax.
Storybook -> Design System -> Flat Table -> with custom cell paddings
Storybook -> Design System -> Flat Table -> with custom column width
Storybook -> Design System -> Flat Table -> Test -> knobs
=> feat(flat-table): add possibility to set column width and cell paddings

src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.spec.js, src/components/select/simple-select/simple-select.stories.mdx
Allow SimpleSelect and FilterableSelect to be cleared when controlled
SimpleSelect and FilterableSelect cannot be cleared when controlled
1. run npm start
2. open http://localhost:9001/?path=/docs/design-system-select--controlled
3. select a value
4. click on clear button
5. open http://localhost:9001/?path=/docs/design-system-select-filterable--controlled
6. select a value
7. click on clear button
=> fix(select): value cannot be cleared (FE-3188)

cypress.env.json, cypress/features/regression/designSystem/accordion.feature, cypress/support/step-definitions/accordion-steps.js, src/components/accordion/accordion.component.js, src/components/accordion/accordion.d.ts, src/components/accordion/accordion.spec.js, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.style.js, src/components/validations/index.js
Add support for rendering the `ValidationIcon` next to the `Accordion` heading by passing a string value to one of the `error`, `warning` or `info` props.
There is no support for rendering `ValidationIcon`.
Updates can be tested locally http://localhost:9001/?path=/story/design-system-accordion--validation-icon
=> feat(accordion): add support to rendering validation icon beside heading FE-3031 

src/components/form/form.stories.mdx
Fixes: #3296
Fix above issue, where clicking on the radio buttons in the second radio group, focuses the radio buttons in the first radio group because they have the same ids.
Also removed the third `Checkbox` from the example to unbloat it a bit
Clicking on the radio buttons in the second radio group, focuses the radio buttons in the first radio group.
Go to story `/story/design-system-form--form-alignment-example` in the built storybook below.
=> docs(form): change radio button ids

.gitignore
remove from `.gitignore` file unnecessary:
`Allure reports`
- allure-report
- allure-results
As we removed `allure-reports` from `cypress` reporting. We need to clear the `.gitignore` file and remove:
`Allure reports`
- allure-report
- allure-results
=> docs: remove allure reports data

src/components/text-editor/__internal__/editor-counter/editor-counter.component.js, src/components/text-editor/__internal__/editor-counter/editor-counter.d.ts, src/components/text-editor/__internal__/editor-counter/editor-counter.spec.js, src/components/text-editor/__internal__/editor-counter/editor-counter.style.js, src/components/text-editor/__internal__/text-editor.component.js, src/components/text-editor/__internal__/text-editor.d.ts, src/components/text-editor/__internal__/text-editor.spec.js, src/components/text-editor/__internal__/text-editor.stories.mdx, src/components/text-editor/__internal__/text-editor.style.js, src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js, src/components/validations/validation-icon.component.js
The `ValidationIcon` is rendered when a string value is passed to either the `error`, `warning` or
`info` prop. The component has been slightly refactored to use outlines instead of borders to
prevent the content jumping when the styling is updated based on the validation state. When the
component is in an error state, the outline and counter text colour are updated to reflect it.
There is no support for rendering the `ValidationIcon` or the error state styling. The component uses borders instead of outlines.
The changes can be tested at http://localhost:9001/?path=/story/design-system-text-editor--with-validation
https://codesandbox.io/s/carbon-quickstart-forked-80btt?file=/src/index.js
This is a basic demo of the intended validation behaviour within a form
=> feat(text-editor): add support for validation icon and error styles FE-3186

src/__experimental__/components/input-icon-toggle/input-icon-toggle.component.js, src/__experimental__/components/input-icon-toggle/input-icon-toggle.spec.js
This fixes a bug where if the a textbox component has a icon and the validation info is an empty string no icon would be displayed.
Fixes #3137
Here is an example of the select component, which uses the textbox component internally, when `info=""` there is no dropdown icon.
FE-3037
See the generated PR from the bug report, each component should display the dropdown icon.
=> fix(inputs): show input icon if info validation is empty string

cypress.env.json, cypress/features/regression/designSystem/filterableSelect.feature, cypress/locators/pages/index.js, cypress/support/step-definitions/dialog-steps.js, cypress/support/step-definitions/select-steps.js, src/components/button/button.component.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/filterable-select/index.d.ts, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/select/list-action-button/list-action-button.component.js, src/components/select/list-action-button/list-action-button.spec.js, src/components/select/list-action-button/list-action-button.style.js, src/components/select/select-list/select-list-container.style.js, src/components/select/select-list/select-list.component.js, src/components/select/select-list/select-list.spec.js, src/components/select/select-list/select-list.style.js, src/components/select/simple-select/simple-select.spec.js, src/components/select/simple-select/simple-select.stories.mdx
A new customizable button in Select List that triggers a user defined action.
1. npm start
2. open http://localhost:9001/?path=/docs/design-system-select-filterable--with-action-button
=> feat(filterable-select): add list action button (FE-3034)

cypress/fixtures/themes/themes.json, src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/components/button/__snapshots__/button.spec.js.snap, src/components/card/__snapshots__/card.spec.js.snap, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap, src/components/icon/icon.spec.js, src/components/link/__snapshots__/link.spec.js.snap, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/pod/__snapshots__/pod.spec.js.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/split-button/__snapshots__/split-button.spec.js.snap, src/style/themes/base/base-theme.config.js, src/style/utils/color.spec.js
I've updated the `theme.colors.primary` too be genericGreenShade(15) as suggested by @sianford.
The original ticket was raised for split button but it will affect every component that uses the primary color.
@sianford raised an issue with the Split Button having an incorrect color when using the base theme. 
The new DLS says the button using the "shared services" theme (aka none/base) should be
Normal: #008200 (genericGreenShade15)
Hover: #006300 (genericGreenShade35)
FE-1634
Check components using the `none` theme in the theme selector.
=> fix(theme): update base/none theme primary color FE-1634

src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/__experimental__/components/date/date-picker.spec.js, src/components/accordion/accordion.component.js, src/components/accordion/accordion.spec.js, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.style.js, src/components/dialog-full-screen/dialog-full-screen.stories.mdx
Add option to have the `Accordion` heading styled as a tertiary button. This includes two new `Accordion` props, `buttonHeading` and `buttonWidth`. `buttonWidth` defaults to 150px.
A third `Accordion` prop `openTitle` has been added for this as well, to allow the title to change when the `Accordion` is expanded.
The `Accordion` heading cannot currently be in the style of a tertiary button
Go to http://localhost:9001/?path=/docs/design-system-accordion--opening-button to view the story
=> feat(accordion): add tertiary button heading styling option

src/components/navigation-bar/navigation-bar.component.js, src/components/navigation-bar/navigation-bar.d.ts, src/components/navigation-bar/navigation-bar.spec.js, src/components/navigation-bar/navigation-bar.stories.mdx, src/components/navigation-bar/navigation-bar.style.js
Adds support for the `styled-system` spacing props to be used to apply custom paddings and margins
to the `NavigationBar`.
No support for custom spacing in `NavigationBar`
A basic example has been added here http://localhost:9001/?path=/story/design-system-navigation-bar--with-custom-spacing
Codesandbox:
https://codesandbox.io/s/carbon-quickstart-forked-rlez8?file=/src/index.js
=> feat(navigation-bar): add support for custom spacing props

src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/dialog-full-screen/content.style.js, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.spec.js, src/components/dialog-full-screen/dialog-full-screen.stories.js, src/components/dialog-full-screen/dialog-full-screen.stories.mdx
- add new prop `disableContentPadding` to have possibility to turn off paddings in Dialog Full Screen
Padding is set by screen size
=> feat(dialog-full-screen): add prop `disableContentPadding` - FE-3281

src/components/dialog/dialog.stories.mdx
Adds an example in storybook of a dialog with an edit state.
No example exists, but the components required do.
Fixes FE-3006
See storybook preview.
=> docs(dialog): add editable fields example FE-3006

src/components/menu/menu-item/menu-item.spec.js, src/components/menu/menu-item/menu-item.style.js, src/components/menu/menu.stories.mdx
fix #3308
Adds a height and line-height when item renders a button
There is no height applied when an onClick prop is passed and button renders
I have updated http://localhost:9001/?path=/docs/design-system-menu--default-story to include some items with onClick props so they render buttons
=>  fix(menu-item): add height when onclick passed and button renders

src/components/dialog-full-screen/dialog-full-screen.stories.mdx
changed the `Open Dialog` button into `Open DialogFullScreen` in `dialogfullscreen.mdx` file
We need to change the `Open Dialog` button into `Open DialogFullScreen` in `dialogfullscreen.mdx` file
=> docs: update the button name

src/components/menu/menu-divider/menu-divider.spec.js, src/components/menu/menu-divider/menu-divider.style.js, src/components/menu/menu-segment-title/menu-segment-title.spec.js, src/components/menu/menu-segment-title/menu-segment-title.style.js
adds default cursor for `menu-segment-title` and `menu-divider`
both components have `cursor: pointer`
Can be tested http://localhost:9001/?path=/story/design-system-menu--dark-theme-alternate-colour
=> fix(menu-divider): add default cursor to passive submenu elements

package-lock.json, package.json, src/components/button/button.stories.js, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/link/link.stories.js
Fix storybook warnings shown below. A couple of incorrect imports from `styled-system` and `Link` was being imported from the wrong package
The `Link` export was moved from `react-router` to `react-router-dom` from v4 onwards
`npm start` and check for any warnings
=> refactor: fix storybook warnings

src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.stories.mdx, src/__experimental__/components/radio-button/radio-button.style.js, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__internal__/fieldset/fieldset.style.js
Align the legend with the first radio button.
---
Align the red asterisk with the line-height of the legend. This results in a tiny visual change ~ 1px but is required to facilitate the other changes in this PR.
---
Remove excess margin between legend and radios when `inline`
---
Remove excess margin below the radio group (below Radio Option 3)
---
The legend is centre aligned.
---
The red asterisk is centre aligned.
---
Excess margin between legend and radios when `inline`
---
Excess margin below the radio group (below Radio Option 3)
---
Fixes FE-3212, Fixes #3269
See the "radio button" and "form-alignment" stories.
https://carbon.sage.com/?path=/story/design-system-form--form-alignment-example
https://carbon.sage.com/?path=/docs/experimental-radiobutton--with-legend-and-labels
=> fix(radio-button): align legend with first radio-button FE-3213

src/components/flat-table/flat-table-body/flat-table-body.d.ts, src/components/flat-table/flat-table-cell/flat-table-cell.d.ts, src/components/flat-table/flat-table-header/flat-table-header.d.ts
fixes #3369
Update TypeScript definition files for FlatTable components
TypeScript definition files for FlatTable components are incorrect
=> fix(flat-table): fix incorrect type definitions

package-lock.json, package.json, src/components/accordion/accordion.stories.mdx, src/components/portrait/portrait.stories.js, src/components/profile/profile.stories.js
- upgraded our version of `chromatic` to the newest `5.3.0`
and added `delay` for a few stories:
- `Accordion` (with-box-component-and-different-paddings story)
- `Profile` (default story)
- `Portrait` (default story)
Due to the new capture cloud infrastructure we need to: 
- upgrade our version of `chromatic` to the newest `5.3.0`
and add `delay` for a few stories:
- `Accordion` (with-box-component-and-different-paddings story)
- `Profile` (default story)
- `Portrait` (default story)
=> test: upgrade chromatic version

.github/workflows/semantic-release.yml
Sign semantic-release commits, releases will be authored by @semantic-release-bot and committed by @carbonci 
Commits are not signed, releases are authored and committed by @semantic-release-bot 
- [Semantic release does not support signing tags](https://github.com/semantic-release/git/issues/214)
- [GitHub does not support signing pushes](https://github.community/t/push-signed/938/4)
I've pinned the version so we can verify the action before upgrading.
Check the next release is signed correctly. This PR will not trigger a release.
=> ci(semantic-release): gpg sign commits

src/components/accordion/accordion.stories.mdx, src/components/portrait/portrait.stories.js, src/components/profile/profile.stories.js
- increase `delay` for `chromatic` snapshots
Few stories still not rendering correctly, we need to increase `delay` for `chromatic` snapshots
=> test: increase chromatic delay

src/components/action-popover/action-popover-item.component.js, src/components/action-popover/action-popover-menu.component.js, src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.d.ts, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.style.js, src/components/flat-table/flat-table.stories.mdx
Allow `ActionPopoverMenu` to open above the menu button when the `placement` prop is set to "top"
There is no prop to support opening the menu above the button
fix #3072
The menu's are positioned absolutely which causes the overflow to account for the space they take up.
http://localhost:9001/?path=/story/design-system-flat-table--paginated-with-sticky-header
=>  feat(action-popover): add support to place menu above button  FE-2956

src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.d.ts, src/components/menu/menu-item/menu-item.spec.js, src/components/menu/menu-item/menu-item.style.js, src/components/menu/menu.stories.mdx
Adds `showDropdownArrow` prop to allow hiding of the drop down arrow for items with submenus, prop
defaults to true. Also adds small fix to correct hover styling for submenu items that have `onClick`
prop passed in light `menuType`.
There is no option to prevent the dropdown arrow from displaying when an item has a submenu. The hover state for a submenu item with onClick is incorrect (see default story in master)
http://localhost:9001/?path=/story/design-system-menu--default-selected has been updated
=> feat(menu-item): add prop to hide dropdown arrow for items with submenu FE-3233

src/__experimental__/components/form-field/form-field.component.js, src/__experimental__/components/form-field/form-field.style.js, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/textbox/docgenInfo.json, src/__experimental__/components/textbox/textbox.component.js, src/__experimental__/components/textbox/textbox.d.ts, src/__experimental__/components/textbox/textbox.spec.js, src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
Add all `styled-system/space` props to `Textbox`.
`Textbox` supports `mb` prop.
I created FE-3370 to address the complexity caused by components passing the same props to multiple child components.
See sandbox in comments below
https://codesandbox.io/s/fe-3306-e0d9r
=> feat(textbox): add space props - FE-3306

src/components/accordion/accordion.stories.mdx, src/components/portrait/portrait.stories.js, src/components/profile/profile.stories.js
disable `chromatic` stories until this [issue](https://github.com/Sage/carbon/issues/3278) will be resolved
Chromatic shows differences on components that were not modified in PR due to loading fonts
=> test: disable chromatic for delayed stories

src/components/action-popover/action-popover-item.d.ts
Change submenu TS type to `React.ReactNode` so it does not throw compiler errors.
=> fix(action-popover): incorrect submenu TS type

package-lock.json, package.json
Remove react-highlight dependency because we don't use it anymore
react-highlight dependency exists
Test regression needed
=> build: remove react-highlight dependency

cypress/locators/flat-table/index.js, src/components/drawer/__internal__/drawer.stories.mdx, src/components/flat-table/flat-table.stories.js, src/components/flat-table/sort/sort.component.js, src/components/flat-table/sort/sort.d.ts, src/components/flat-table/sort/sort.spec.js, src/components/flat-table/sort/sort.style.js
Added possibility to allow screen reader to read sort label
screen reader doesn't read properly
storybook => design system => flat table => test => sort
Turn on Screen Reader => TAB to sort header
=> feat(sort): screen reader accessibility - FE-3291

src/__experimental__/components/date/navbar/__snapshots__/navbar.spec.js.snap, src/__experimental__/components/date/navbar/button.style.js, src/__experimental__/components/date/navbar/navbar.component.js, src/components/advanced-color-picker/advanced-color-picker-cell.style.js, src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap, src/components/carousel/carousel.component.js, src/components/carousel/carousel.style.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/drawer/__internal__/drawer.style.js, src/components/duelling-picklist/duelling-picklist.style.js, src/components/duelling-picklist/picklist-item.component.js, src/components/icon-button/icon-button.style.js, src/components/pager/__internal__/__snapshots__/pager.spec.js.snap, src/components/pager/__internal__/pager.style.js, src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.component.js, src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.js
Change `type` of all the buttons to be `button` instead of the default `submit` value.
Some of the buttons that we use internally does not have a `type` defined meaning that they default to `type="submit"`. If a component that uses this type of button will be placed inside of `<form>` tag this will lead to unintentional form submission.
=> fix: prevent accidental form submission - FE-3336

src/utils/decorators/tooltip-decorator/tooltip-decorator.js
`TooltipDecorator` will soon be deprecated, this PR adds a warning to developer console when the decorator is used.
No warning is displayed when `TooltipDecorator` is used
Any story that uses the decorator (validation stories, icon with tooltip, text editor)
=> refactor(tooltip-decorator): add deprecation warning FE-3437

.storybook/preview.js
changes to the viewport to add config to support storybook having responsive styles and the testing of responsive components. You can now changes the viewport to the sizes recommended in the DLS https://brand.sage.com/d/NdbrveWvNheA/foundations#/grid/grid-system
Default viewports only that do not align to the DLS
- Visit storybook using the chromatic build
- Change the viewport
- Confirm behaviour is as expected
=> chore(storybook): change viewport to align to dls FE-3427

src/components/menu/menu.stories.mdx
Change docs to use `<NavigationBar>` instead of `<NavBar>` to be consistent with the `NavigationBar` stories.
Some users were asking what the difference between `NavBar` and `NavigationBar`.
Look at the source preview of `Full navbar alignment example` story for `Menu`.
=> docs(menu): change NavBar to be NavigationBar

src/components/text-editor/__internal__/text-editor.stories.mdx, src/components/tooltip/__snapshots__/tooltip.spec.js.snap, src/components/tooltip/tooltip.spec.js, src/components/tooltip/tooltip.style.js
Fixes #3468
All tooltips should have `text-align: left`
Currently the `text-align` varies depending on tooltip position and alignment
Just check that various tooltips always have `text-align: left`
=> fix(tooltip): change tooltip text-align to be always left

cypress/features/regression/test/actionPopoverNoIFrame.feature, cypress/locators/action-popover/index.js, cypress/support/step-definitions/action-popover-steps.js, src/components/action-popover/action-popover-context.js, src/components/action-popover/action-popover-item.component.js, src/components/action-popover/action-popover-menu.component.js, src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.stories.js
Clicking, pressing `enter` or `esc` keys on submenu items should close whole ActionPopover
This PR also fixes FE-3414, (https://github.com/Sage/carbon/issues/3476) check sandbox to test if it works properly.
https://codesandbox.io/s/carbon-quickstart-forked-cdb9j?file=/src/index.js
Clicking, pressing `enter` or `esc` keys on submenu items closes only the submenu
http://localhost:9001/?path=/story/design-system-action-popover-test--default
=> fix(action-popover): close action popover when submenu item is clicked - FE-3237/FE-3343/FE-3414

src/components/navigation-bar/navigation-bar.stories.mdx, src/components/navigation-bar/navigation-bar.style.js
Remove min and max width and auto margin, leaving the nav bar to be the full width of the screen.
Add an MDX example to show users how to set a max-width on their nav bar content using `Box`: 
The nav bar has a min and max width, and margin auto for left and right which is causing problems with the max width (I.e. the nav bar not spanning the whole width of the page)
http://localhost:9001/?path=/story/design-system-navigation-bar--content-max-width-using-box
and test the other nav bar stories
=> fix(navbar): remove old styling to allow full width

src/components/menu/__internal__/submenu/submenu.style.js, src/components/menu/menu.stories.mdx
The width of a `MenuItem` should not affect the width of it's underlying submenu
Also add a title to the Menu MDX file.
If a `MenuItem` containing a submenu flexes above it's original width, the submenu's width also grows.
http://localhost:9001/?path=/story/design-system-menu--full-navbar-alignment-example
https://codesandbox.io/s/upbeat-leavitt-pl01n?file=/src/index.js - see the codesandboxbot comment below for the version of this sandbox with the Carbon changes in
=> fix(submenu): stop submenu width from flexing with parent

cypress/features/regression/accessibility/accessibilityCommon.feature
Re-enable some of the accessibility tests in Cypress and remove the `Flash` test case, as the `Flash` component no longer exists in Carbon
A selection of the accessibility tests are not run with an `@ignore` tag
The Cypress builds passing should be enough
=> test(cypress): remove flash accessibility test

cypress/features/regression/designSystem/menu.feature, cypress/locators/menu/index.js, cypress/locators/menu/locators.js, cypress/support/step-definitions/menu-steps.js, src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.context.js, src/components/menu/__internal__/submenu/submenu.spec.js, src/components/menu/__internal__/submenu/submenu.style.js, src/components/menu/index.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.spec.js, src/components/menu/menu.stories.mdx, src/components/menu/scrollable-block/index.js, src/components/menu/scrollable-block/scrollable-block.component.js, src/components/menu/scrollable-block/scrollable-block.spec.js, src/components/menu/scrollable-block/scrollable-block.style.js
New `ScrollableBlock` component for use in submenus. This component extends `Box` so any box prop can be used. 
There is no way to add a scrollable block in a submenu.
http://localhost:9001/?path=/story/design-system-menu--scrollable-submenu
http://localhost:9001/?path=/story/design-system-menu--scrollable-submenu-dark
=> feat(menu): add scrollable block component

docs/getting-started.stories.mdx, package.json
Update the minimum  i18n-js version to be 3.0.1.
We support any 3.x.x version, however 3.0.0 does not exist and has
caused some confusion.
Fixes FE-3470 Fixes #3525
Review files.
=> docs: update i18n-js peer dependency range

src/components/tabs/__internal__/tab-title/tab-title.spec.js, src/components/tabs/__internal__/tab-title/tab-title.style.js
Fixes  #3537
Fixes "large" `size` `Tabs` that have `siblings` and `position` "left" overriding the padding incorrectly
`padding-top` and `padding-bottom` overrides are applied when `Tabs` are `position` "left" and size "large" with `siblings`
Can be tested in this sandbox
https://codesandbox.io/s/carbon-quickstart-forked-mbr0c
=> fix(tabs): prevent padding override for large tabs with siblings

src/components/link/link.stories.mdx
Docs no longer have superfluous `hasOnClick` prop in `onClick` story 
Docs have superfluous `hasOnClick` prop in `onClick` story
=> docs(link): update onclick story to remove incorrect prop usage

cypress/features/regression/pod.feature, cypress/locators/pod/index.js, cypress/support/step-definitions/pod-steps.js, src/components/pod/index.d.ts, src/components/pod/pod-context.js, src/components/pod/pod-manager.component.js, src/components/pod/pod-manager.d.ts, src/components/pod/pod-manager.spec.js, src/components/pod/pod.component.js, src/components/pod/pod.d.ts, src/components/pod/pod.spec.js, src/components/pod/pod.stories.mdx, src/components/pod/pod.style.js
fixes: #3046
add new `pod-manager` component that will allow users to stretch pods without any breaking change
There is no mechanism for setting Pods to equal heights
=> feat: add new `pod-manager` component- FE-2940

src/components/dialog/dialog.stories.mdx, src/utils/helpers/focus-trap/focus-trap.js, src/utils/helpers/focus-trap/focus-trap.spec.js
Expands `querySelectorAll` string to filter out disabled inputs
Disabled inputs are not filtered and can break tab wrapping
https://5ecf782fe724630022d27d7d-zttdnyovdg.chromatic.com/?path=/story/dialog--editable
=> fix(focus-trap): filter disabled inputs in query selector FE-3382

src/__experimental__/components/date/date-picker.component.js, src/__experimental__/components/date/date-picker.spec.js, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js
This PR fixes following two issues:
Fixes #3460
Fixes #3560
Currently Date input crashes when `allowEmptyValue` is set to `true` and user manually either clears the Textbox or tries to manually type new date in Textbox
Storybook -> Experimental -> Date -> Test -> `allowEmptyValue` knob
=> fix(date): fix date crashing when allowEmptyValue is set - FE-3471

.storybook/welcome-page/get-started/get-started.component.js, .storybook/welcome-page/header/header.component.js, src/__experimental__/components/date/date.stories.mdx, src/__experimental__/components/search/search.stories.mdx, src/components/accordion/accordion.stories.mdx, src/components/button/__snapshots__/button.spec.js.snap, src/components/button/button.stories.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/card/card.stories.mdx, src/components/confirm/confirm.component.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/form/form.stories.mdx, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/popover-container/popover-container.stories.mdx, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/sidebar/sidebar.stories.js, src/components/sidebar/sidebar.stories.mdx, src/components/split-button/__snapshots__/split-button.spec.js.snap, src/components/text-editor/__internal__/text-editor.stories.mdx, src/components/tile/tile.stories.mdx
removes the margin-left 16px styling automatically applied to sibling buttons.
BREAKING CHANGE: The margin left 16px styling applied to the sibling buttons has been removed. An
add-prop codemod has been created to help facilitate the adding of the margin left spacing prop and
the value to the buttons in your project.
fixes #3392
Removal of the sibling styling from the Button component.
Button automatically applies `margin-left: 16px` to all sibling buttons.
`add-prop` Codemod has been created and the link for that PR is https://github.com/Sage/carbon-codemod/pull/41 
This PR cannot be merged until the codemod PR has been merged with the codemod repo. The codemod PR will require QA'ing at the same time as this PR.
- All unit tests should pass.
- Cypress tests should pass.
- No styling …
=> chore(button): remove sibling styling for button - FE-3330

cypress.env.json, cypress/features/regression/designSystem/simpleSelect.feature, cypress/locators/select/index.js, cypress/support/step-definitions/select-steps.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/multi-select/index.d.ts, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js, src/components/select/multi-select/multi-select.stories.mdx, src/components/select/select-textbox/select-textbox.component.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.stories.mdx, src/components/select/utils/is-expected-option.js, src/components/select/utils/is-expected-option.spec.js, src/components/select/utils/is-expected-value.js, src/components/select/utils/is-expected-value.spec.js
When the `id` property is set on an Option object value, objects will be compared based on that property (could be used when the list is recreated after an API call). If there is no `id` prop specified on an object, then the exact objects will be compared.
When Option values are defined as objects, the exact objects are compared looking for the selected value.
1. run `npm start`.
2. open http://localhost:9001/?path=/docs/design-system-select--with-object-as-value
3. open http://localhost:9001/?path=/docs/design-system-select-filterable--with-object-as-value
4. open http://localhost:9001/?path=/docs/design-system-select-multiselect--with-object-as-value
=> feat(select): object option comparison tweak (FE-3421)

.npmignore, check-version.js, package.json, src/style/__spec__.js
Remove `check-version.js` completely as it isn't needed anymore.
Replace `RegExp.exec` with a `.match` to avoid a vunerability false positive on Fortify
`check-version.js` exists
=> chore: remove check-version

cypress.env.json, cypress/features/regression/dialog.feature, cypress/locators/dialog/index.js, cypress/locators/dialog/locators.js, cypress/support/step-definitions/dialog-steps.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/dialog-full-screen/content.style.js, src/components/dialog/__snapshots__/dialog.spec.js.snap, src/components/dialog/dialog.style.js, src/components/form/form.component.js, src/components/form/form.spec.js, src/components/form/form.style.js
Fixes: #3563
The sticky footer will now turn into a normal footer when you scroll to the bottom, and pop up when you scroll up
Scrollbar gets hidden behind the sticky footer:
Note this happens for both `Dialog` and `FullScreenDialog`
http://localhost:9001/?path=/story/design-system-form--in-dialog-with-sticky-footer
http://localhost:9001/?path=/story/design-system-form--in-dialog-full-screen-with-sticky-footer
and on the codesandbox from the Github issue, see the codesandbox bot comment below for a built version of that
=> fix(dialog): display scrollbar in front of sticky footer

package-lock.json, package.json
Upgrade `@storybook/addon-info` to fix our latest dependabot alert. It's dependency `nested-object-assign` needs to be upgraded to `1.0.4` which this update does.
N/A
=> chore(deps): upgrade storybook addon info

.eslintrc, package-lock.json, package.json
Add some Eslint rules to assist with security, i.e. to prevent code that could enable code injection attacks, such as the use of `eval` 
See https://github.com/mozilla/eslint-plugin-no-unsanitized for the Mozilla plugin added here
N/A
=> chore(eslint): add security rules

cypress/features/regression/designSystem/filterableSelect.feature, cypress/support/step-definitions/select-steps.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/select-textbox/select-textbox.spec.js
Add open on focus functionality that reflects the same functionality of the SimpleSelect and Multiselect.
1. run `npm start`
2. open http://localhost:9001/?path=/docs/design-system-select-filterable--open-on-focus
=> feat(filterable-select): add open on focus functionality (FE-3366)

src/components/button/button.component.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.js, src/components/button/button.stories.mdx, src/components/button/button.style.js
Ability to prevent text wrapping with noWrap prop.
Button will always wrap text inside in certain cases.
Added noWrap prop which enables ``white-space: nowrap`` on button element.
Example provided with codesandbox
=> feat(button): add noWrap prop - FE-3459

docs/development-roadmap.stories.mdx
As a public open-source project that's now being used by developers outside of Sage, as well as more widely within the organisation we should be publishing a roadmap.
No public development roadmap exists for Carbon.
~- [ ] Screenshots are included in the PR if useful~
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [] Storybook added or updated if required~
View in Documentation/Development Roadmap
=> docs(roadmap): add public development roadmap

.github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml
- increase the timeout in `yml` files to avoid failings in GitHub actions with disconnection from storybook due to passed timeout we need to start running `cypress`.
To avoid failings in GitHub actions with disconnection from storybook due to passed timeout we need to increase it in `yml` files
=> ci: increase timeout for storybook start

docs/usage-with-routing.stories.mdx, package-lock.json, package.json, src/components/button/__snapshots__/button.spec.js.snap, src/components/button/button.component.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/link/link.component.js, src/components/link/link.d.ts, src/components/link/link.spec.js, src/components/link/link.stories.js, src/components/link/link.stories.mdx, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.d.ts, src/components/menu/menu-item/menu-item.spec.js, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/split-button/__snapshots__/split-button.spec.js.snap
Fixes: #1756 
Remove Carbon support for rendering router links in `Button`, `Link` and `MenuItem`. 
Instead provide a documented example of how users can use Carbon components as links in React Router versions 5 and 6. This can be seen at: http://localhost:9001/?path=/docs/documentation-usage-with-routing--page
Also the `onClick` prop for `Link` will no longer render it as a `button` element, it will always render an `a` element now.
Fixed the accessibility for a `Button` rendering as a link. It now has `role="button"` and `draggable="false"` on the `<a>` element and pressing the space bar will follow the link rather than scroll the page
`Button`, `Link` and `MenuItem` have custom implementations on rendering router links via props. …
=> docs(routing): add usage with routing docs

src/__experimental__/components/input/__snapshots__/input.spec.js.snap, src/__experimental__/components/search/search.style.js, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap, src/components/pager/__internal__/__snapshots__/pager.spec.js.snap, src/components/pager/__internal__/pager.style.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js, src/components/select/multi-select/multi-select.stories.mdx, src/components/select/multi-select/multi-select.style.js, src/components/select/select.style.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.spec.js, src/components/select/simple-select/simple-select.stories.mdx, src/style/themes/base/base-theme.config.js
This PR changes placeholder color in `Select`, `MultiSelect` and `Filterable` 
This PR also adds `margin` props support to `MultiSelect` and `Filterable` - FE-3571
This PR also changes placeholder color for all the inputs from `blackOpacity30` to `blackOpacity55`
Fixes #3532
DesignSystem -> Select stories
Margin props - play around with adding margin props in codesandbox
https://codesandbox.io/s/carbon-quickstart-forked-bpotd?file=/src/index.js
=> fix(select): change placeholder color - FE-3551 

.github/workflows/chromatic-pr.yml, .github/workflows/cypress-pr.yml
- disable the `chromatic` run from `CI` when the state of PR is set to `Draft`
To avoid unnecessary waste of resources of chromatic we decided to disable the `chromatic` run from `CI` when the state of PR is set to `Draft`
Check that `chromatic` shouldn't run on Draft
=> ci: ignore chromatic for drafts

.storybook/theme-selector/register.js
Use the primary color for theme selector.
The theme selector is using the base color.
N/A
View storybook preview deployed by chromatic.
=> docs: use primary color for theme selector

.github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml, package-lock.json, package.json
- update `cypress` version to `6.4.0`
- bump the number of containers to be `20` instead of `19` to make `cypress` tests faster
- to be up to date we need to update cypress version to 6.4.0
- we removed Chromatic from a `cypress-pr.yml file`, so we can bump the number of containers to be 20 instead of 19
=> test: update cypress version to 6.4.0

src/components/toast/toast.stories.mdx, src/components/toast/toast.style.js
Fixes: #3640
Fixes #3627 
Add z-index to `Toast` (notification z-index from theme).
`Toast` does not have a z-index applied
See sandbox here: https://codesandbox.io/s/exciting-architecture-zzsxz
=> fix(toast): add z-index

src/utils/helpers/options-helper/options-helper.d.ts
The disconnect icon has been added to the options helper definition file for our TypeScript users.
fixes FE-3381
Add the `disconnect` icon to the list of icons in the definition file.
The `disconnect` icon is currently missing from the definition file.
<del> [ ] Screenshots are included in the PR if useful </del>
<del> [ ] All themes are supported if required </del>
<del> [ ] Unit tests added or updated if required </del>
<del> [ ] Cypress automation tests added or updated if required </del>
<del> [ ] Storybook added or updated if required </del>
N/A
A TypeScript project inside of a Codesandbox has been provided. Disconnect icon has been passed in to icon. No errors in console and icon should display as expected.
https://codesandbox.io/s/dank-pond-to6cv
=> chore(utils): add disconnect icon to options helper definition file - FE-3381

cypress/features/regression/accessibility/accessibilityDesignSystem.feature, src/components/tile/tile-footer/tile-footer.component.js, src/components/tile/tile.stories.mdx
Add mdx example with `Accordion` and `TileFooter`: 
Also tidy up the mdx and story names
No example with `Accordion` and `TileFooter`
http://localhost:9001/?path=/docs/design-system-tile--with-accordion-and-tile-footer
=> docs(tile): add accordion and footer example

src/components/pager/__internal__/pager.component.js, src/components/pager/__internal__/pager.d.ts, src/components/pager/__internal__/pager.spec.js, src/components/pager/__internal__/pager.stories.js, src/components/pager/__internal__/pager.stories.mdx, src/components/pager/__internal__/pager.style.js, src/style/themes/base/base-theme.config.js
Adds `variant` prop to support `alternate` styled `Pager` background
No alternate background is supported
Added an Alternate Pager story
=> feat(pager): add alternate variant styling FE-3415

cypress/features/regression/designSystem/multiSelect.feature, src/components/select/multi-select/index.d.ts, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.stories.mdx
Add `isLoading` prop to `MultiSelect` to allow for the loader to be used on the dropdown. Add new story to show this: 
Loader cannot be used with `MultiSelect`
http://localhost:9001/?path=/docs/design-system-select-multiselect--with-is-loading-prop
=> feat(multi-select): add isLoading prop

src/components/content/content.component.js, src/components/content/content.spec.js
fix #3661
Adds support back into component to allow consumers to pass data tags into the component's root
element
Any data tags passed to `Content` are not applied to the root element
=> fix(content): add support for passing data tags to root of component FE-3710

cypress/features/regression/test/tile.feature, cypress/fixtures/commonComponents/tile.json, src/components/tile/__snapshots__/tile.spec.js.snap, src/components/tile/tile.spec.js, src/components/tile/tile.style.js
fixes #3458
Adds `box-sizing: border-box` to Tile container to prevent it overflowing a parent's width
Tile does not respect the parent width
https://codesandbox.io/s/carbon-quickstart-forked-cwzmv?file=/src/index.js
=> fix(tile): add box sizing to container to ensure it respects parent width FE-3389

docs/getting-started.stories.mdx
Update getting started guide to remove references to base.css, which was removed in https://github.com/Sage/carbon/pull/3642
Getting started incorrectly includes instructions for base.css
~- [ ] Screenshots are included in the PR if useful~
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [ ] Storybook added or updated if required~
n/a
Read the document
=> docs(getting-started): remove base css

src/__experimental__/components/switch/switch.component.js
fixes: #3265
This fix removes isRequired from the prop-type declaration for value
Issue 3265 describes the current behaviour:
https://github.com/Sage/carbon/issues/3265
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [ ] Storybook added or updated if required~
No unit test updates were required
switch.d.ts declaration is already correct
`npm start` 
navigate to  http://localhost:9001/?path=/docs/experimental-switch--default-story
Console will not show a warning about the Switch value prop
=> fix(switch): make value prop optional (FE-3224)

docs/javascript-styleguide.md
Add component folder structure to styleguide.
No folder structure described in styleguide.
https://github.com/Sage/carbon/blob/styleguide_folder_structure/docs/javascript-styleguide.md
=> docs(styleguide): add folder structure

cypress/features/regression/designSystem/filterableSelect.feature, cypress/support/step-definitions/select-steps.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.spec.js
Select visible value should not be cleared on reopening a modal.
Filterable Select should display text value when a default value is set and options are loaded asynchronously.
Filterable Select value should be cleared when the filter does not mach any option.
fix for value displayed on reopening select when in a modal:
https://codesandbox.io/s/carbon-quickstart-forked-f6ws0
fix for value not displayed on async option load:
https://codesandbox.io/s/carbon-quickstart-forked-yfd7c
fix for value not cleared …
=> fix(select): various select fixes (FE-3552, FE-3385, FE-3615)

src/components/button/__snapshots__/button.spec.js.snap, src/components/button/button.component.js, src/components/button/button.d.ts, src/components/button/button.spec.js, src/components/button/button.stories.js, src/components/button/button.stories.mdx, src/components/button/button.style.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/split-button/__snapshots__/split-button.spec.js.snap
Enables button component to allow only an icon to be rendered.
fixes #3236
Allows only an icon to be rendered inside of the button component without any console errors.
If only an icon is rendered inside of a button, this warning is displayed.
`Warning: Failed prop type: The prop `children` is marked as required in `Button`, but its value is `undefined`.`
N/A
- `git checkout FE-3240-button_displays_prop_type_error`
- `npm i`
- `npm start` to start storybook.
- Visit Design System -> Button
- Two new examples have been created. Icon Only Button and Icon Only Button with Tooltip.
=> feat(button): icon only button - FE-3240

src/components/button/button.stories.js
Changes the title of the noWrap button test example to lowercase. This is inline with the rest of
our test examples.
Change the title of the noWrap button example in the Test directory for Button to all lowercase.
`no wrap buttons`
Current title is `No Wrap Buttons`
<del> - [ ] All themes are supported if required </del>
Navigate to Buttons -> Test and noWrap button example should be called `no wrap buttons`
=> docs(button): change no wrap story title to lowercase

src/components/help/help.component.js, src/components/help/help.d.ts, src/components/help/help.stories.js, src/components/help/help.stories.mdx, src/components/help/index.d.ts, src/components/icon/icon.component.js, src/components/icon/icon.d.ts, src/components/icon/icon.stories.js, src/components/icon/icon.stories.mdx, src/components/icon/index.d.ts, src/components/tooltip/tooltip-pointer.style.js, src/components/tooltip/tooltip.component.js, src/components/tooltip/tooltip.d.ts, src/components/tooltip/tooltip.spec.js, src/components/tooltip/tooltip.stories.js, src/components/tooltip/tooltip.stories.mdx, src/components/tooltip/tooltip.style.js
Adds support to `Tooltip` for overriding background and font colour.
Adds support for leveraging the colour overrides in `Icon` and `Help`
Adds `word-break: break-word` to tooltip wrapper to prevent long content strings overflowing to fix `FE-2020`
No colour override support in `Tooltip`, `Icon` and `Help`
Long strings do not wrap in `Tooltip` wrapper
Word wrap FE-2020 fix:
Stories will colour overrides have been added to `Tooltip`, `Icon` and `Help`
https://codesandbox.io/s/carbon-quickstart-forked-f8ist?file=/src/index.js
=> feat(tooltip): add support for background and font color overrides FE-3377

src/utils/helpers/date/__spec__.js, src/utils/helpers/date/date.js
When the format is being specified in translations to `MM/DD/YYYY` the date is converted correctly.
When the format is being specified in translations to `MM/DD/YYYY` day is converted to month when it's less than 12.
E.g.: 3/12/2021 changes to 12/3/2021.
https://codesandbox.io/s/carbon-date-locale-deyrz?file=/src/App.js
https://codesandbox.io/s/carbon-date-locale-11si7
=> fix(date): set format based on translation

src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button-group.d.ts, src/__experimental__/components/radio-button/radio-button-group.style.js, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.d.ts, src/__experimental__/components/radio-button/radio-button.stories.mdx, src/__experimental__/components/radio-button/radio-button.style.js, src/style/utils/filter-styled-system-margin-props.js, src/utils/helpers/filter-object-properties/filter-object-properties.js, src/utils/helpers/filter-object-properties/filter-object-properties.spec.js, src/utils/helpers/filter-object-properties/index.js
Add styled-system margin props to RadioButton and RadioButtonGroup
Filter out props so proper ones are passed to subcomponents in which they should be instead of spreading them.
Add an util to filter out unnecessary object properties.
1. npm start
2. open: http://localhost:9001/?path=/docs/experimental-radiobutton--with-legend-and-labels
=> feat(radio-button): allow use of all styled system margin props (FE-3518)

src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js
Month and year should not change when incorrect date is provided.
When the date is changed to invalid when the DatePicker is open, incorrect year is displayed, e.g.: 31/02/2021 displays January 0031.
1. npm start
2. open http://localhost:9001/?path=/story/experimental-date-input--default-story
3. open the datepicker
4. change the month to February
5. replace the date in input with 31
=> fix(date-input): incorrect year in datepicker when date is not valid (FE-3708)

src/components/tile-select/index.d.ts, src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.d.ts, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js
Adds `customActionButton` render prop that supports overriding the default action button. Adds
`actionButtonAdornment` prop to support rendering components as sibling to action button
No support for overriding action button or rendering any siblings with it
https://codesandbox.io/s/carbon-quickstart-forked-n8z1r?file=/src/index.js
Additional examples have also been added to Tile-Select story
=> feat(tile-select): add props to  override action button and render sibling adornment FE-3042

src/__experimental__/components/numeral-date/numeral-date.component.js, src/__experimental__/components/numeral-date/numeral-date.spec.js, src/__experimental__/components/numeral-date/numeral-date.stories.mdx
fixes #3264
No error is thrown when no `dateFormat` value is passed
When no value is passed to the `dateFormat` prop it throws an error even though it has a default
value assigned in the top level prop destructure of the component. This is because at the point where
the prop types are checked the value is not initialised to the default.
n/a
The `controlled` story for `NumeralDate` has no `dateFormat` passed and instead relies on the default value, no error should be thrown about incorrect formats etc
https://codesandbox.io/s/carbon-quickstart-forked-2elgi?file=/src/index.js
=> fix(numeral-date): prevent error being thrown when default date format is used FE-3225

src/components/definition-list/definition-list.spec.js, src/components/definition-list/definition-list.stories.js, src/components/definition-list/definition-list.stories.mdx, src/components/definition-list/dl.component.js
Add support for conditional rendering with using of `<React.Fragment />` component 
`<React.Fragment />` and content of the component don't render
I also created MDX file as it didn't exist. The MDX is located in storybook: `Design System/Defitnion List`
MDX in storybook 
`Design System/Definition List`
=> fix(dl): support for conditional rendering - FE- 3600

src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/components/icon/icon.component.js, src/components/icon/icon.d.ts, src/components/portal/__snapshots__/__spec__.js.snap
Unnecessary props should not be passed as it could affect the display of the Component.
Typescript definition types should be documented.
All props defined on the Icon Component are being passed to the styled component.
Typescript definition types have no documentation.
Fixes #3709
=> feat(icon): filter out unwanted props (FE-3599)

cypress/features/regression/heading.feature, cypress/locators/heading/index.js, cypress/support/step-definitions/heading-steps.js, src/components/dialog-full-screen/__snapshots__/dialog-full-screen.spec.js.snap, src/components/heading/heading.component.js, src/components/heading/heading.spec.js, src/components/heading/heading.style.js
`StyledHeadingTitle` has `as="span"` from `StyledHeadingTitle` as it is overriding the `Typography` `h1` `variant`
`StyledHeadingTitle` has `as="span"`
=> fix(heading): remove as prop from heading title wrapper FE-3769

src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/radio-button/radio-button.component.js, src/components/card/card-footer/card-footer.component.js, src/components/card/card-row/card-row.component.js, src/components/card/card-row/card-row.spec.js, src/components/card/card-row/card-row.style.js, src/components/card/card.component.js, src/components/card/card.spec.js, src/components/card/card.stories.mdx, src/style/utils/filter-styled-system-padding-props.js, src/style/utils/index.js
fixes: #3519
Replaces margin with `styled-system/padding` in `CardRow`
Described in the linked issue https://github.com/Sage/carbon/issues/3519
~- [ ] Storybook added or updated if required~
N/a
Use the generated codesandbox
https://codesandbox.io/s/carbon-quickstart-forked-yqvpx?file=/src/index.js
=> feat(card): add styled-system padding props (FE-3463)

src/components/action-toolbar/action-toolbar.component.js, src/components/table-ajax/table-ajax.component.js, src/components/table-ajax/table-ajax.stories.mdx, src/components/table/table.component.js, src/components/table/table.stories.mdx
Add deprecation notices to `Table` and `ActionToolbar`, which is only used in `Table` and not documented for usage outside of `Table`
They have been replaced with `FlatTable` and `BatchSelection` respectively.
No deprecation notices on these components.
http://localhost:9001/?path=/docs/table--default-story
=> chore(table): add deprecation notice

.storybook/utils/styled-system-props.js, src/__spec_helper__/test-utils.js, src/style/utils/width.js
This PR adds additional `width` util that uses only `width` prop in styled-system's `layout` styling function.
=> feat(styled-system): add width util - FE-3679

cypress/features/regression/designSystem/toast.feature, src/components/toast/toast.component.js, src/components/toast/toast.stories.js, src/components/toast/toast.stories.mdx
fixes FE-3701
To align with the Design System, toast should be centred by default.
Toast currently opens up on the left hand side of the screen.
The purpose of this change is to align Carbon with the Design System.
- Visit `Design System -> Toast -> default` and the toast component should open in the centre of the page.
- Visit `Design System -> Toast -> left aligned` and the toast component should open to the left of the page.
=> feat(toast): centre toast by default - FE-3701

cypress/support/index.js, cypress/support/step-definitions/date-input-steps.js, package-lock.json, package.json
- bump `cypress` to `v. 6.5.0`
- bump `cypress-cucumber-preprocessor` to `v. 4.0.1`
- replace `moment.js` library with `day.js` because of `moment.js` deprecation
to be up to date we need to update:
- `cypress` to `v. 6.5.0`
- `cypress-cucumber-preprocessor` to `v. 4.0.1`
- `moment.js` library needs to be replaced with `day.js` because of `moment.js` deprecation
=> test: update cypress&cucumber versions

.github/workflows/codeql-analysis.yml
The CodeQL scanning requires scans of the base branch to compare pull requests against, so we need to add a push hook for the master branch to this workflow.
This workflow currently only runs for PRs.
=> ci(codeql): add master push hook

src/components/batch-selection/batch-selection.component.js, src/components/batch-selection/batch-selection.spec.js
Use i18next for the date component
i18n-js
`batch-selection` components should be tested for regression.
=> refactor(batch-selection): replace i18n-js with i18next

src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.spec.js
Use i18next for the date component
https://codesandbox.io/s/carbon-quickstart-forked-yrbkg
i18n-js
`tile-select` components should be tested for regression.
=> refactor(tile-select): replace i18n-js with i18next

CONTRIBUTING.md, docs/typescript-styleguide.md
Add TypeScript style guide and link from contributing docs.
No TypeScript style guide in Carbon.
https://github.com/Sage/carbon/blob/FE-2833_typescript_contributing_docs/docs/typescript-styleguide.md
https://github.com/Sage/carbon/blob/FE-2833_typescript_contributing_docs/CONTRIBUTING.md
=> docs(contributing): add typescript style guide

src/components/form/form-summary.component.js, src/components/form/form.spec.js, src/components/table/table-row/table-row.spec.js
Use i18next for the date component
https://codesandbox.io/s/carbon-quickstart-forked-mmbdi
i18n-js
`form-summary` components should be tested for regression.
=> refactor(form-summary): replace i18n-js with i18next

src/components/button/button.d.ts, src/utils/helpers/options-helper/options-helper.d.ts
This change extracts the union type for the `as` and `buttonType` prop into the options-helper file so that other apps consuming this code can use the definition instead of manually redefining the possible values.
Code needing to have a Typescript definition of either `as` or `buttonType` prop current have to manually declare the possible union types allowed, which could lead to potential bugs if a future Carbon release were to change these in future.
=> refactor(button): extracting  ButtonTypes to options-helper

src/components/select/filterable-select/filterable-select.spec.js, src/components/select/list-action-button/list-action-button.component.js, src/components/select/list-action-button/list-action-button.spec.js, src/components/select/select-list/select-list.spec.js
Use i18next for the `list-action-button` component
i18n-js
`list-action-button` component should be tested for regression.
https://codesandbox.io/s/carbon-quickstart-forked-pk2dj
=> refactor(list-action-button): replace i18n-js with i18next

cypress/features/regression/test/pager.feature, cypress/fixtures/test/pager.json, src/components/pager/__internal__/pager-navigation-link.component.js, src/components/pager/__internal__/pager-navigation.component.js, src/components/pager/__internal__/pager-navigation.spec.js, src/components/pager/pager.component.js, src/components/pager/pager.spec.js, src/components/table-ajax/table-ajax.component.js, src/components/table-ajax/table-ajax.spec.js, src/components/table/table.component.js, src/components/table/table.spec.js
Use i18next for the date component
https://codesandbox.io/s/carbon-quickstart-forked-2o263
i18n-js
`pager`, `pager-navigation`, `pager-navigation-link` components should be tested for regression.
=> refactor(pager): replace i18n-js with i18next

cypress/support/step-definitions/date-input-steps.js, src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/__experimental__/components/date/date-picker.component.js, src/__experimental__/components/date/date-picker.spec.js, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js, src/__experimental__/components/date/day-picker.style.js, src/utils/helpers/options-helper/options-helper.js
Replace the usage of `Portal` in `DatePicker` with `Popover` (using Popper.js).
The `DatePicker` component uses `Portal` to render the picker
Please test all: 
http://localhost:9001/?path=/docs/experimental-date-input--default-story
http://localhost:9001/?path=/story/experimental-date-range--default-story
=> refactor(date-picker): replace portal with popper

src/__experimental__/components/label/label.component.js, src/__experimental__/components/simple-color-picker/simple-color-picker.component.js, src/__experimental__/components/switch/switch-slider.component.js, src/__internal__/fieldset/fieldset.component.js, src/components/button-toggle-group/button-toggle-group.component.js, src/components/button-toggle-group/button-toggle-group.spec.js, src/components/help/help.component.js, src/components/help/help.d.ts, src/components/help/help.spec.js, src/components/help/help.stories.js, src/components/icon/icon.component.js, src/components/icon/icon.d.ts, src/components/icon/icon.spec.js, src/components/icon/icon.stories.js, src/components/icon/icon.stories.mdx, src/components/tooltip/tooltip.component.js, src/components/tooltip/tooltip.d.ts, src/components/tooltip/tooltip.spec.js, src/components/tooltip/tooltip.stories.js, src/components/tooltip/tooltip.stories.mdx, src/components/tooltip/tooltip.style.js, src/components/validations/validation-icon.component.js, src/components/validations/validation-icon.spec.js, src/utils/helpers/options-helper/options-helper.d.ts
Adds `flipOverrides` prop to support passing an array of placements to override the default flip
behaviour: the order of the array sets the precedence of these overrides. See `popper` docs for more
information https://popper.js.org/docs/v2/modifiers/flip/#fallbackplacements
Adds `tooltipFlipOverrides` to `Icon` to support overriding the default flip behaviour of `Tooltip`.
Adds `tooltipFlipOverrides` to `ValidationIcon` to support overriding the default flip behaviour of
`Tooltip`, if no value passed to prop and `isPartOfInput` then the flip behaviour overrides to `["top", "bottom"]`
Adds `tooltipFlipOverrides` to `Help` to support overriding the default flip behaviour of `Tooltip`.
Sets `Tooltip` to flip "top" or " bottom" if `validationOnLabel` is false in `ButtonToggleGroup`
There is …
=> feat(tooltip): add support for overriding default flip placements FE-3771

cypress/features/regression/link.feature, cypress/locators/link/index.js, cypress/locators/link/locators.js, cypress/support/step-definitions/link-steps.js, src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/components/link/link.component.js, src/components/link/link.d.ts, src/components/link/link.spec.js, src/components/link/link.stories.mdx, src/components/link/link.style.js, src/style/themes/base/base-theme.config.js
It allows to create a skip link
Not support for skip link
New story added into storybook
storybook => link => isSkipLink
=> feat(link): add `isSkipLink` prop - FE-3735

src/__internal__/i18n/i18n.component.js, src/__internal__/i18n/i18n.spec.js, src/__internal__/i18n/index.js, src/components/confirm/confirm.component.js, src/components/confirm/confirm.spec.js
Use i18next for the `confirm` component
i18n-js
https://codesandbox.io/s/carbon-quickstart-forked-plk99
`confirm` component should be tested for regression.
=> refactor(confirm): replace i18n-js with i18next

src/components/pod/pod.component.js, src/components/pod/pod.spec.js, src/components/show-edit-pod/show-edit-pod.spec.js
Use i18next for the `pod` component
i18n-js
`pod` component should be tested for regression.
https://codesandbox.io/s/carbon-quickstart-forked-vplvh
=> refactor(pod): replace i18n-js with i18next

src/components/pod/__snapshots__/pod.spec.js.snap, src/components/pod/pod.spec.js, src/components/pod/pod.style.js
fixes #3584
Footer text colour should stay the same colour when `pod` is hovered over.
Footer text colour changes to white making the text unreadable.
<del>- [ ] Cypress automation tests added or updated if required </del>
<del>- [ ] Typescript `d.ts` file added or updated if required </del>
N/A
- Visit Pod -> `With edit button and displayEditButtonOnHover`
- Hover over the `pod` and the text in the Footer should say the same colour. 
- Footer shouldn't have rounded corners.
- `pod` shouldn't have a blue outline once clicked.
=> fix(pod): fix footer text colour when pod is hovered - FE-3505

src/components/configurable-items/configurable-items.component.js, src/components/configurable-items/configurable-items.spec.js
Use i18next for the `configurable-items` component
i18n-js
`configurable-items` component should be tested for regression.
Not able to create code sandbox because of `Could not find module in path: 'react-dnd-legacy' relative to '/node_modules/carbon-react/lib/components/drag-and-drop/with-drop/with-drop.js'` error.
https://codesandbox.io/s/carbon-quickstart-forked-tq5ge?file=/src/index.js
=> refactor(configurable-items): replace i18n-js with i18next

cypress/features/regression/designSystem/menu.feature, cypress/locators/menu/index.js, cypress/locators/menu/locators.js, cypress/support/step-definitions/menu-steps.js
Add missing cypress tests
We have some missing test cases for Menu component
- Large divider
- Segment title
- Default theme alternate colour
- Submenu direction left
=> test(menu): add missing cypress tests

cypress/features/regression/link.feature, cypress/locators/link/index.js, cypress/support/step-definitions/link-steps.js, src/components/link/link.component.js, src/components/link/link.d.ts, src/components/link/link.spec.js, src/components/link/link.stories.mdx
fixes: #3748
It allows users to put `rel` as a property in our link component
rel is a default property supported by `a` tag
no possibility to add rel property
New story added into storybook
Link -> rel
=> feat: add `rel` prop to Link component -  FE-3803

src/components/table/table.component.js
Use i18next for the `table` component
i18n-js
`table` component should be tested for regression.
Not able to create code sandbox because of `Could not find module in path: 'react-dnd-legacy' relative to '/node_modules/carbon-react/lib/components/drag-and-drop/with-drop/with-drop.js'` error.
=> refactor(table): replace i18n-js with i18next

src/components/action-toolbar/action-toolbar.component.js, src/components/action-toolbar/action-toolbar.spec.js, src/components/table/table.spec.js
Use i18next for the `action-toolbar` component
i18n-js
`action-toolbar` component should be tested for regression.
Not able to create code sandbox because of `Could not find module in path: 'react-dnd-legacy' relative to '/node_modules/carbon-react/lib/components/drag-and-drop/with-drop/with-drop.js'` error.
https://codesandbox.io/s/carbon-quickstart-forked-gk4mc?file=/src/index.js:406-411
=> refactor(action-toolbar): replace i18n-js with i18next

src/components/show-edit-pod/show-edit-pod.component.js, src/components/show-edit-pod/show-edit-pod.spec.js
Use i18next for the `show-edit-pod` component
i18n-js
`show-edit-pod` component should be tested for regression.
https://codesandbox.io/s/carbon-quickstart-forked-w75dd?file=/src/index.js:1179-1239
=> refactor(show-edit-pod): replace i18n-js with i18next

cypress/features/regression/experimental/dateInput.feature, cypress/fixtures/experimental/dateInput.json, cypress/locators/date-input/index.js, cypress/support/step-definitions/date-input-steps.js, src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/__experimental__/components/date/date-picker.component.js, src/__experimental__/components/date/date-picker.spec.js, src/__experimental__/components/date/date.stories.js, src/__experimental__/components/date/day-picker.style.js
Auto position date picker pop up top or bottom depending on available space: 
Date picker pop up is always positioned bottom, even if it goes out of it's container.
http://localhost:9001/?path=/docs/experimental-date-input--default-story
=> feat(date-picker): auto position pop up

src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js
Fixes: #3790
Allow null children in `FlatTableRow`. This was previously possible but we had a regression which now causes an error
Trying to have a null child of `FlatTableRow` causes the error: `Cannot read property 'props' of null`.
Use the sandbox from the issue, build with changes in will be in the codesandboxbot comment below
=> fix(flat-table-row): allow null children

cypress/features/regression/themes/themes.feature, cypress/support/step-definitions/themes-steps.js, src/components/drawer/__internal__/drawer.stories.mdx, src/components/tabs/__internal__/tab-title/tab-title.component.js, src/components/tabs/__internal__/tab-title/tab-title.spec.js, src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/__internal__/tabs-header/tabs-header.component.js, src/components/tabs/__internal__/tabs-header/tabs-header.spec.js, src/components/tabs/__internal__/tabs-header/tabs-header.style.js
fix #3352
Adds `overflow-y: auto` to `TabsHeader` to allow `Tabs` to be scrollable when they overflow parent and `position="left"`
fix #3773
Adds border on all sides and a -1px margin to remove the double borders on all `TabTitle` that are
not `first-of-type` when `borders` prop is true, refactors `isTabSelected` styling to use
`box-shadow` instead of borders
No ability to scroll when tabs overflow a parent height
Borders are only applied on one side when they are adjacent to each other, the `isTabSelected` styling has incorrect height and width
All Tabs stories should be tested
Extra tab controls added to the `design-system-drawer--with-tab-controls` story to demonstrate scrollable enhancement
=> fix(tabs-header): allow tabs to be scrollable when position is left and they overflow parent FE-3302

.github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml
Update `chrome` to version `89` in `cypress` tests. We are not using `FireFox` in tests but there is no docker image with only `chrome` installed.
We are using `chrome` in `v87`
Ensure that all CI has passed
=> ci(cypress): update docker image to use chrome v89

cypress/features/regression/designSystem/flatTable.feature, cypress/locators/flat-table/index.js, cypress/locators/flat-table/locators.js, cypress/support/step-definitions/flat-table-steps.js, src/components/pager/pager.component.js, src/components/pager/pager.spec.js, src/components/select/option/option.component.js
Fixes: #3413
Change current behavior to update pager after enter button pressed
Pager updates onChange (if you change page size with your arrow keys)
Newe behaviour can be visible on storybook `paginated` story
=> fix: will update pager after enter key is pressed - FE-3342

src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap, src/__experimental__/components/date/date-picker.component.js, src/__experimental__/components/date/date-picker.spec.js, src/__experimental__/components/date/day-picker.style.js
fix #3838
fixes FE-3988
Removes the css file import from `DatePicker`, all styles for `react-day-picker` are now added directly into the styled-component wrapper instead
Removes theme object from snapshot test
`DatePicker` still has a css file import
Date and DateRange stories compared with master
=> refactor(date-picker): remove css file import and add react day picker styles into styled wrapper

src/components/drawer/__internal__/__snapshots__/drawer.spec.js.snap, src/components/drawer/__internal__/drawer.component.js, src/components/drawer/__internal__/drawer.d.ts, src/components/drawer/__internal__/drawer.spec.js, src/components/drawer/__internal__/drawer.stories.mdx, src/components/drawer/__internal__/drawer.style.js
This commit provide possibility to add custom height prop to our component
fixes: #3792
Allows to set custom height to Drawer component
there is no possibility to set custom height
New storybook story added
Storybook => Drawer => custom height
https://codesandbox.io/s/carbon-quickstart-forked-e530d?file=/src/index.js
=> feat(drawer): allows to use custom height - FE-3825

package.json, postinstall.js
Add a warning into carbon before we merge
https://github.com/Sage/carbon/pull/3855
More information here
Warning message after `npm install`
```
The dependency "i18n-js" will be removed soon. There is nothing for you to do at this time.
Please visit https://github.com/Sage/carbon/blob/master/rfcs/text/i18n.md for details.
```
=> build(npm): add a warning i18n-js will be removed soon

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table-header/flat-table-header.style.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.stories.mdx
fix #3721
fix #3716
fix #3564
Any `FlatTableCell`, `FlatTableCheckbox` or `FlatTableHeader` children that precede a
`FlatTableRowHeader` will also be positioned `sticky`. They will also be passed a callback to
`reportCellWidth` which will allow each column to calculate the correct `left` positioning based on
the sum of the offsetWidths of the columns before it
Fixes focus styling of `FlatTableRowHeader` when a row has focus
Adds `border-left` to the cell directly after a `FlatTableRowHeader` to fix style defect, passes
context from `FlatTable` to `FlatTablerow` to ensure that the border has the correct colour defined
by `colorTheme` prop
Any preceding columns are not made sticky when a `FlatTableRowHeader` is used
Styling is wrong when is incorrect when row has focus a …
=> fix(flat-table-row): ensure any cells preceding row headers are also positioned sticky FE-3763

src/__experimental__/components/search/search.component.js, src/__experimental__/components/search/search.spec.js, src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.spec.js
Fixes: #3830
Stop event propagation when typing characters or numbers into the `Search` input, these should not propagate and affect keyboard nav etc of components further up the tree
Error when typing into `Search` when it's inside of a submenu because the event bubbles up to the keyboard nav in `Submenu` when it shouldn't
Use the sandbox from the attached Github issue and check the console on http://localhost:9001/?path=/story/design-system-menu--submenu-with-search
=> fix(search): stop event propagation for characters and numbers

src/components/definition-list/definition-list.stories.mdx, src/components/tile/tile.stories.mdx
Available example of how to use ActionPopover and Icon within DefinitionList.
No available example of how to use ActionPopover and Icon within DefinitionList.
http://localhost:9001/?path=/docs/design-system-definition-list--action-popover-and-icon-support
=> docs(definition-list): add action popover and icon example - FE-3004

src/__experimental__/components/input-icon-toggle/input-icon-toggle.style.js, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js, src/components/select/multi-select/multi-select.style.js, src/components/select/select.style.js, src/components/select/simple-select/simple-select.spec.js
Icon Dropdown is placed in the bottom-right corner and sometimes jump into bottom-left corner
You can check this behavior by going to 
Storybook => Multi-Select => and then pick some items from a list 
https://codesandbox.io/s/carbon-quickstart-forked-8vt2r
=> fix(simple-select): update icon position - 3824

src/components/select/filterable-select/filterable-select.component.js
fix #3754
Adds a guard to check that `event.target.attributes["data-element"]` is not undefined before
checking if the value is `"input"`
Throws `Uncaught TypeError: Cannot read property 'value' of undefined` when input icon is clicked
`design-system-select-filterable--default-story` click input icon when list is open, no error should be thrown
=> fix(filterable-select): check event has a data element attribute before checking the value FE-3802

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.d.ts, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.mdx, src/components/flat-table/flat-table.style.js
Provides a fix for the gap between table content and sticky footer when certain design decisions are
applied to FlatTable.
fixes #3850
- Fixes the background when height is 100% but the FlatTable doesn't have enough data to fill the 100% height.
- Adds a `hasMaxHeight` prop that makes FlatTable have a max-height of 100%.
N/A
- `git checkout FE-3986-FlatTable_sticky_footer_gap`
- `npm i`
- `npm start` to start Storybook
- visit new story called "with hasMaxHeight"
-  example should match the acceptance criteria of FE-3986.
=> fix(FlatTable): fix gap between table content and sticky footer - FE-3986

src/components/tabs/__internal__/tabs-header/tabs-header.spec.js, src/components/tabs/__internal__/tabs-header/tabs-header.style.js, src/components/tabs/tab/tab.component.js, src/components/tabs/tab/tab.d.ts, src/components/tabs/tab/tab.spec.js, src/components/tabs/tab/tab.style.js, src/components/tabs/tabs.component.js, src/components/tabs/tabs.d.ts, src/components/tabs/tabs.spec.js, src/components/tabs/tabs.stories.mdx, src/components/tabs/tabs.style.js
Adds styled-system/margin interface to `Tabs`. Adds styled-system/padding interface to `Tab`.
Removes margin from `TabsHeader` and achieves same layout by applying default padding to `Tab`
Styled system `margin` and `padding` not supported in `Tabs` and `Tab` respectively.
`TabsHeader` applies margin of 10px to either bottom or right depending on `position`
`design-system-tabs--with-custom-spacing` added to demonstrate custom spacing
https://codesandbox.io/s/carbon-quickstart-forked-kzhj5?file=/src/index.js
=> feat(tabs, tab): surface styled system margin interface in tabs and padding interface in tab FE-3577

src/components/text-editor/text-editor.component.js, src/components/text-editor/text-editor.d.ts, src/components/text-editor/text-editor.spec.js, src/components/text-editor/text-editor.stories.mdx, src/components/text-editor/text-editor.style.js
Surfaces `styled-system/margin` props to allow adjusting of spacing for `TextEditor`
No margin props supported on `TextEditor`
https://codesandbox.io/s/carbon-quickstart-forked-lo9i0?file=/src/index.js
=> feat(text-editor): surface styled system margin props FE-3578

src/components/note/__internal__/note.component.js, src/components/note/__internal__/note.d.ts, src/components/note/__internal__/note.spec.js, src/components/note/__internal__/note.stories.mdx, src/components/note/__internal__/note.style.js
Add styled-system margin props to the `Note` component
Styled-system is not available to the `Note` component
N/A
https://codesandbox.io/s/focused-tree-8c6h1
- apply the styled-system margin props to the Note component. Styles should behave as expected.
=> feat(note): add styled-system margin props - FE-3561

src/components/profile/profile.component.js, src/components/profile/profile.spec.js, src/components/profile/profile.stories.mdx, src/components/profile/profile.style.js
Adds styled-system margin props to the `Profile` component
`Profile` component currently does not have access to the styled-system props
N/A
https://codesandbox.io/s/reverent-elgamal-7mfrf
- apply the styled-system margin props to the Profile component. Styles should behave as expected.
=> feat(profile): add styled-system margin props - FE-3568

src/components/pod/pod.component.js, src/components/pod/pod.spec.js, src/components/pod/pod.stories.js, src/components/pod/pod.stories.mdx, src/components/pod/pod.style.js, src/components/show-edit-pod/show-edit-pod.component.js, src/components/show-edit-pod/show-edit-pod.spec.js, src/components/show-edit-pod/show-edit-pod.stories.mdx
This PR add margin styled system props support to Pod and ShowEditPod
This PR also implements a breaking change where `padding` prop on mentioned components is changed to `size` prop
https://codesandbox.io/s/carbon-quickstart-forked-g83u1?file=/src/index.js
=> feat: add styled system margin to Pod and ShowEditPod - FE-3564 - v3

src/components/hr/hr.component.js, src/components/hr/hr.d.ts, src/components/hr/hr.spec.js, src/components/hr/hr.stories.mdx, src/components/hr/hr.style.js
BREAKING CHANGE: Use margin only. Padding has been removed.
`@styled-system/space` margin only (remove padding - breaking change).
Filter styled system margin props.
Uses no filtered `propTypes.space`.
- Padding props have been removed from story page props section.
- https://codesandbox.io/s/carbon-quickstart-forked-gmr2k?file=/src/index.js
=> refactor(hr): update styled system implementation

src/components/split-button/__snapshots__/split-button.spec.js.snap, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js, src/components/split-button/split-button.stories.mdx, src/components/split-button/split-button.style.js
Surfaces `styled-system/margin` props to allow consumers to adjust spacing of `SplitButton`
`SplitButton` does not support margin props
https://codesandbox.io/s/carbon-quickstart-forked-38b9d?file=/src/index.js
=> feat(split-button): surface styled system margin props

cypress/features/regression/test/tile.feature, cypress/fixtures/commonComponents/tile.json, src/components/detail/detail.stories.mdx, src/components/heading/heading.stories.mdx, src/components/tile/tile-footer/tile-footer.component.js, src/components/tile/tile-footer/tile-footer.d.ts, src/components/tile/tile-footer/tile-footer.spec.js, src/components/tile/tile-footer/tile-footer.style.js, src/components/tile/tile.component.js, src/components/tile/tile.d.ts, src/components/tile/tile.spec.js, src/components/tile/tile.stories.js, src/components/tile/tile.stories.mdx, src/components/tile/tile.style.js, src/components/vertical-divider/vertical-divider.stories.mdx
Updates `TileFooter` to only support `styled-system/padding` and removes support for `margin`
BREAKING CHANGE: `margin` props no longer supported in `TileFooter`
Adds support for `styled-system` width for `Tile` and `TileContent`
BREAKING CHANGE: `pixelWidth` prop has been removed
`TileFooter` supports all `spacing` props
`Tile` does not support `styled-system` `width`, instead has `pixelWidth` and `width` props to handle percentage and pixel dimensions
Tile stories should all be the same as master
https://codesandbox.io/s/carbon-quickstart-forked-d663h?file=/src/index.js
=> refactor(tile-footer): remove support for styled system margin props FE-3579

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.d.ts, src/components/flat-table/flat-table-cell/flat-table-cell.spec.js, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table-header/flat-table-header.spec.js, src/components/flat-table/flat-table-header/flat-table-header.style.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js, src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap, src/components/flat-table/flat-table.stories.mdx
fix #3846
Raises specificity of the `space` styles applied to div container within `FlatTableCell`, `FlatTableRowHeader` and
`FlatTableHeader` so any values passed via `styled-system` props take precedence of the cell-sizes
configs
Adds `width` prop for `FlatTableCell`. Adds `truncate` and `title` props to support styling content
that overflows the width of the column and overriding the text displayed when the mouse hovers over
a cell.
After speaking to @harpalsingh it was decided to remove the `nowrap` styling on cells and only apply it when `truncate` is true
Styled-system props are overridden by the size config
No ability to truncate cell content
`design-system-flat-table--with-truncated-cell-content` has been created
https://codesandbox.io/s/carbon-quickstart-forked-fm951?file=/src/ind …
=> fix(flat-table-cell, flat-table-header): raise specificity of spacing styles FE-3838

cypress/features/regression/designSystem/simpleSelectEvents.feature, src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.spec.js
Hide menu on blur
Menu like Select or FilterableSelect stays open when the tab is changed
https://codesandbox.io/s/dazzling-roentgen-snkff?fontsize=14&hidenavigation=1&theme=dark
Fixes: #3833
https://codesandbox.io/s/carbon-quickstart-forked-lhcqp?file=/src/index.js
=> refactor(multi-select): hide select list on blur

src/components/row/row.stories.mdx
Adds a link to the `Grid` component in the deprecation warning for Row and Column.
No link to component provided. User will have to manually search for the `Grid` component.
Click on the word `Grid` in the deprecation warning in the `Row` MDX example. You should be taken to the `Grid` documentation.
=> docs(row and column): add a link to grid component in deprecation warning

src/components/tile-select/tile-select-group.component.js, src/components/tile-select/tile-select-group.d.ts, src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.d.ts, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js
Surfaces `styled-system/margin` props on `TileSelect` and `TileSelectGroup` components
No margin props surfaced on `TileSelect` and `TileSelectGroup` components
https://codesandbox.io/s/carbon-quickstart-forked-oxbjy?file=/src/index.js
=> feat(tile-select, tile-select-group): surface styled system margin props FE-3580

src/components/scrollable-list/scrollable-list.component.js
Add deprecation warning to `Scrollable List` component.
Component currently has no deprecation warning.
<del> - [ ] Storybook added or updated if required </del>
N/A
https://codesandbox.io/s/carbon-quickstart-forked-jiw0u
- Check console of the linked codesandbox. Console warning should appear as per the screenshot in the `Proposed behaviour`
=> refactor(scrollable-list): add deprecation warning - FE-4004

src/components/popover-container/popover-container.component.js, src/components/popover-container/popover-container.d.ts, src/components/popover-container/popover-container.spec.js, src/components/popover-container/popover-container.stories.mdx, src/components/popover-container/popover-container.style.js
Surfaces `styled-system/padding` props on `PopoverContainer` to allow adjustments to the spacing of
its content
`PopoverContainer` does not support `padding` props
https://codesandbox.io/s/carbon-quickstart-forked-7bl6g
=> feat(popover-container): surface styled system padding props FE-3565

src/__experimental__/components/input/__snapshots__/input.spec.js.snap, src/__experimental__/components/input/input.style.js, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
Set the input margin value to avoid automatic margin setting by the browser.
When the date input is brought into focus in either the Date Input or Date Picker the date picker covers the bottom part of the focus outline border. This occurs in Safari only.
https://codesandbox.io/s/carbon-quickstart-forked-fmezl?file=/src/index.js
=> fix(day-picker): fix bottom of focus border is cut off by the date picker

src/components/settings-row/settings-row.component.js, src/components/settings-row/settings-row.spec.js, src/components/settings-row/settings-row.stories.mdx, src/components/settings-row/settings-row.style.js
Surfaces `styled-system/margin` props on `SettingsRow` component
`styled-system/margin` props not surfaced on `SettingsRow` component
`d.ts` file will be added as part of work to update definitions throughout carbon
https://codesandbox.io/s/carbon-quickstart-forked-k1755
=> feat(settings-row): add support for styled system margin props FE-3572

src/components/step-sequence/step-sequence.component.js, src/components/step-sequence/step-sequence.spec.js, src/components/step-sequence/step-sequence.stories.mdx, src/components/step-sequence/step-sequence.style.js
StepSequence has margin styled system props available to use.
No styled system props for StepSequence.
- [] <del>Screenshots are included in the PR if useful
=> feat(step-sequence): add styled system margin props to StepSequence - FE-3576

docs/testing-styleguide.md, package.json
New semantic release commits will be in the format
```
chore(release): 68.21.0
```
Commit format is 
```
chore(release): 68.21.0 [skip ci]
```
Existing branches will need to be re-created or use `npx chrmatic --patch-build=$head...$base`
Fixes FE-4029
Check next carbon release after merge.
=> build: run builds on all commits to master FE-4029

src/components/preview/__snapshots__/preview.spec.js.snap, src/components/preview/preview.component.js, src/components/preview/preview.d.ts, src/components/preview/preview.spec.js, src/components/preview/preview.stories.mdx, src/components/preview/preview.style.js
Added styled system margin props to Preview component.
No styled system margin props on Preview component
Locally in storybook by editing stories or in codesandbox.
=> feat(preview): add styled system margin props to Preview - FE-3567

src/components/portrait/portrait-gravatar.component.js, src/components/portrait/portrait-initials.component.js, src/components/portrait/portrait.component.js, src/components/portrait/portrait.spec.js, src/components/portrait/portrait.stories.mdx, src/components/portrait/portrait.style.js
Add styled-system margin to `portrait` component
Styled-system is not available to use on this component
N/A
https://codesandbox.io/s/adoring-lake-ke74p
=> feat(portrait): add styled-system margin - FE-3566

src/components/grid/__snapshots__/grid.spec.js.snap, src/components/grid/grid-container/grid-container.component.js, src/components/grid/grid-container/grid-container.style.js, src/components/grid/grid-container/index.d.ts, src/components/grid/grid-item/grid-item.component.js, src/components/grid/grid-item/grid-item.style.js, src/components/grid/grid.stories.mdx
Changed implementation of the Grid - use styled-system util.
Props added without usage of styled-system util.
- [x ] Commits follow our style guide
<del>- [ ] Screenshots are included in the PR if useful</del>
- [x ] All themes are supported if required
- [x ] Unit tests added or updated if required
=> feat(grid-container): use prop-types from styled-system

src/components/multi-step-wizard/multi-step-wizard.js, src/components/multi-step-wizard/multi-step-wizard.stories.mdx
deprecation warning added to console and MDX example
Add deprecation warning to `Multi Step Wizard` component
Component currently has no deprecation warning
<del> - [ ] All themes are supported if required </del>
N/A
- Visit Multi Step Wizard story on Storybook
- Story should have a deprecation warning at the top of the page (as per `Proposed behaviour` screenshot)
- Console warning should also be present (as per `Proposed behaviour` screenshot)
=> refactor(multi-step-wizard): add deprecation warning - FE-4011

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-head/flat-table-head.style.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.style.js
Set `text-align: 1em` of the wrappers.
There is an alignment gap between the "colapse" icon and the folder name if we configure the expand only on the first column.
Fixes: #3887
https://codesandbox.io/s/carbon-quickstart-forked-8qwsf?file=/src/index.js
=> fix(flat-table): fix an alignment gap between the colapse icon and the text

package-lock.json, package.json
Remove `sass-loader` and `node-sass` as they are no longer required in Carbon
`sass-loader` and `node-sass` dependencies exist.
=> chore(deps): remove sass dependencies

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.d.ts, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table-header/flat-table-header.d.ts, src/components/flat-table/flat-table-header/flat-table-header.spec.js, src/components/flat-table/flat-table-header/flat-table-header.style.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js, src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.d.ts, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.style.js
BREAKING CHANGE: FlatTable uses margin. FlatTableCell FlatTableHeader FlatTableRowHeader use padding
`@styled-system/space` margin only (remove padding - breaking change).
Filter styled system margin props.
Uses no filtered `propTypes.space`.
https://codesandbox.io/s/carbon-quickstart-forked-uc7mp
=> refactor(flat-table): update styled system implementation

cypress/features/regression/designSystem/flatTable.feature, cypress/features/regression/dialogFullScreen.feature, cypress/support/step-definitions/common-steps.js, src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js
fix #3875
Adds `useEffect` to ensure `expandable` `FlatTableRows` update when the value of the `expanded` prop
changes
`expandable` functionality cannot be controlled externally
`design-system-flat-table-expandable--controlled` added
https://codesandbox.io/s/nice-almeida-j22d6
=> fix(flat-table-row): add support for controlling expanded rows externally FE-4007

src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js
Updates prop types for `title`, `subtitle` and `description` to be type node
Adds `footer` prop of type node to support rendering content at the bottom of a given `TileSelect`
Prop types for `title`, `subtitle` and `description` are `string`
No `footer` prop available
The `footer` container has no spacing applied to it, this should be achieved by applying `padding`/`margin` to the component passed in
`design-system-tile-select--with-a-footer` added
https://codesandbox.io/s/carbon-quickstart-forked-bviry?file=/src/index.js
=> feat(tile-select): expand prop types for title, subtitle and description to node FE-4005

src/components/duelling-picklist/duelling-picklist.component.js, src/components/duelling-picklist/duelling-picklist.d.ts, src/components/duelling-picklist/duelling-picklist.spec.js, src/components/duelling-picklist/duelling-picklist.stories.mdx, src/components/duelling-picklist/duelling-picklist.style.js
Adds support for `styled-system/margin` interface to the root element of `DuellingPicklist`
`DuellingPicklist` does not support `styled-system/margin` interface
https://codesandbox.io/s/carbon-quickstart-forked-c9ku5?file=/src/index.js
=> feat(duelling-picklist): add support for styled-system margin interface FE-3543

src/components/card/card-footer/card-footer.component.js, src/components/card/card.component.js, src/components/card/card.spec.js, src/components/card/card.stories.mdx, src/components/card/card.style.js
This PR adds styled-system margin prop support to Card component
https://codesandbox.io/s/carbon-quickstart-forked-m74fx
=> feat(card): add styled-system margin support - FE-3534

src/components/action-popover/action-popover.component.js, src/components/action-popover/action-popover.d.ts, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.style.js
This PR adds styled-system margin support to `ActionPopover` component
https://codesandbox.io/s/carbon-quickstart-forked-i5sd0
=> feat(action-popover): add styled-system margin support - FE-3526

src/components/accordion/accordion.spec.js, src/components/help/help.component.js, src/components/help/help.d.ts, src/components/help/help.spec.js, src/components/help/help.stories.mdx, src/components/help/help.style.js, src/components/icon/icon.component.js, src/components/icon/icon.d.ts, src/components/icon/icon.spec.js, src/components/icon/icon.stories.mdx, src/components/icon/icon.style.js, src/components/portal/__snapshots__/portal.spec.js.snap, src/components/validations/validation-icon.component.js, src/components/validations/validation-icon.spec.js, src/components/validations/validation-icon.style.js
Adds support for the remaining `styled-system/margin` interface in `Icon`
Adds support for `styled-system/margin` interface in `ValidationIcon`
Adds support for `styled-system/margin` interface to `Help`
`Icon` only supports `ml` and `mr`.
`ValidationIcon` only supports `ml` and `mr`.
No support for `styled-system/margin` interface in `Help`
https://codesandbox.io/s/carbon-quickstart-forked-5o1sj?file=/src/index.js
=> feat(icon): add support for styled-system margin interface FE-3550

src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js
Call onChange when value is deleted or not matched.
The onChange event is not called when the textbox content is deleted.
Resolves:  #3854
https://codesandbox.io/s/carbon-quickstart-forked-eh7hk
=> fix(filterable-select): call onChange when value is deleted or not matched - FE-3985

src/__internal__/full-screen-heading/full-screen-heading.component.js, src/__internal__/full-screen-heading/full-screen-heading.style.js, src/components/alert/alert.component.js, src/components/confirm/confirm.component.js, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.spec.js, src/components/dialog-full-screen/dialog-full-screen.style.js, src/components/dialog/dialog.component.js
First element in DialogFullScreen should be focused by default (same as in Dialog component)
https://codesandbox.io/s/carbon-quickstart-forked-33phq
=> feat(dialog-full-screen): add auto focus functionality - FE-3968

src/components/accordion/accordion-group.component.js, src/components/accordion/accordion-group.d.ts, src/components/accordion/accordion.spec.js, src/components/accordion/accordion.stories.js, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.style.js
This PR adds styled-system margin prop support to AccordionGroup
https://codesandbox.io/s/carbon-quickstart-forked-0886w?file=/src/index.js
=> feat(accordion-group): add styled-system margin support - FE-3525

src/components/heading/heading.component.js, src/components/heading/heading.spec.js, src/components/heading/heading.stories.mdx, src/components/heading/heading.style.js
This PR adds styled-system margin prop support to Heading component
https://codesandbox.io/s/carbon-quickstart-forked-5cnk6?file=/src/index.js
=> feat(heading): add styled-system margin support - FE-3547

src/components/content/content.component.js, src/components/content/content.d.ts, src/components/content/content.spec.js, src/components/content/content.stories.mdx, src/components/content/content.style.js
Add styled-system margin props to `Content`
`Content` has no spacing props at all.
https://codesandbox.io/s/carbon-quickstart-forked-ez0b2
=> feat(content): add margin props

cypress/features/regression/designSystem/menu.feature, cypress/locators/menu/index.js, cypress/locators/menu/locators.js, cypress/support/helper.js, cypress/support/step-definitions/menu-steps.js, src/components/menu/__internal__/keyboard-navigation/index.js, src/components/menu/__internal__/keyboard-navigation/index.spec.js, src/components/menu/__internal__/spec-helper/index.js, src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.spec.js, src/components/menu/menu-divider/menu-divider.spec.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.d.ts, src/components/menu/menu-item/menu-item.spec.js, src/components/menu/menu-item/menu-item.style.js, src/components/menu/menu-segment-title/menu-segment-title.spec.js, src/components/menu/menu.component.js, src/components/menu/menu.spec.js, src/components/menu/menu.stories.mdx
Fixes: #3517
Update `Menu`/`Submenu` keyboard navigation to behave as described in this issue: https://github.com/Sage/carbon/issues/3517
Hovering over the submenu item no longer opens the submenu, you must click it instead, clicking anywhere outside of the submenu will close it.
Character navigation has been removed completely from the top level menu, and has been updated for submenus to search for multiple characters typed in quick succession. The user has 1.5 seconds from typing a character, to type another one or the search string will reset. This is to try and match the default HTML behaviour in a select list
Removed `keyboardOverride` prop from `MenuItem` - this option does not follow accessibility guidelines and the user would have had no idea which key to press to navigate to the …
=> refactor(menu): rewrite keyboard nav - FE-3695

src/__experimental__/components/search/search.component.js, src/__experimental__/components/search/search.d.ts, src/__experimental__/components/search/search.spec.js, src/__experimental__/components/search/search.stories.mdx, src/__experimental__/components/search/search.style.js
@styled-system/space margin only on root element 
In order for this to work the props must only be spread on the root element only rather than passed down to the sub components.
No styled system support
https://codesandbox.io/s/carbon-quickstart-forked-5w8x2
=> refactor(search): update styled system implementation - FE-3519

src/__experimental__/components/fieldset/__snapshots__/fieldset.spec.js.snap, src/__experimental__/components/fieldset/fieldset.component.js, src/__experimental__/components/fieldset/fieldset.d.ts, src/__experimental__/components/fieldset/fieldset.spec.js, src/__experimental__/components/fieldset/fieldset.stories.mdx, src/__experimental__/components/fieldset/fieldset.style.js
@styled-system/space margin only on root element 
In order for this to work the props must only be spread on the root element only rather than passed down to the sub components.
No styled-system support
https://codesandbox.io/s/carbon-quickstart-forked-u9h51
=> refactor(fieldset): update styled system implementation - FE-3511

src/__experimental__/components/search/search.component.js, src/__experimental__/components/search/search.d.ts, src/__experimental__/components/search/search.spec.js, src/__experimental__/components/textbox/textbox.component.js, src/components/select/filterable-select/filterable-select.component.js, src/components/select/multi-select/multi-select.component.js
Fixes a styling bug where the X icon appears a golden outline onClick
fixes #3857
Focus outline should only appear around 'X' icon when icon is navigated to via the keyboard.
Focus outline appears onClick.
<del> - [ ] Storybook added or updated if required </del>
N/A
https://codesandbox.io/s/carbon-quickstart-forked-dojtr?file=/src/index.js
=> fix(search): fix outline appearing onClick around the X icon - FE-3999

src/components/draggable/draggable-container.component.js, src/components/draggable/draggable-item.component.js, src/components/draggable/draggable-item.style.js, src/components/draggable/draggable.spec.js, src/components/draggable/draggable.stories.mdx
This PR adds styled-system props support to Draggable
https://codesandbox.io/s/carbon-quickstart-forked-6n58s?file=/src/index.js
=> feat(draggable): add styled-system props support - FE-3541

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__internal__/fieldset/fieldset.component.js, src/__internal__/fieldset/fieldset.d.ts, src/__internal__/fieldset/fieldset.spec.js, src/__internal__/fieldset/fieldset.style.js
@styled-system/space margin only on root element 
In order for this to work the props must only be spread on the root element only rather than passed down to the sub components.
Remove custom margin props
Custom margin props
Internal `Fieldset` is a part of `RadioButton`.
https://codesandbox.io/s/carbon-quickstart-forked-kkp18
=> refactor(fieldset): update styled system implementation - FE-3512

package-lock.json, package.json
Update `commitizen` to latest after they merged a security patch https://github.com/commitizen/cz-cli/pull/824. This will fix our current dependabot alert for `merge`
=> chore(deps): update commitizen

src/__experimental__/components/simple-color-picker/simple-color-picker.component.js, src/__experimental__/components/simple-color-picker/simple-color-picker.d.ts, src/__experimental__/components/simple-color-picker/simple-color-picker.spec.js, src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
- Add styled-system margin props to component
- Component currently does not have styled-system props available to use
https://codesandbox.io/s/carbon-quickstart-forked-wdsm2
=> feat(simple-color-picker): add styled system margin - FE-3520

cypress/features/regression/experimental/simpleColorPickerAction.feature, cypress/features/regression/test/advancedColorPickerNoIFrame.feature, cypress/support/step-definitions/simple-color-picker-steps.js, src/__internal__/focus-trap/focus-trap.component.js, src/__internal__/focus-trap/focus-trap.spec.js, src/components/advanced-color-picker/advanced-color-picker.spec.js, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.spec.js, src/components/dialog-full-screen/dialog-full-screen.stories.mdx, src/components/dialog-full-screen/dialog-full-screen.style.js, src/components/dialog/dialog.component.js, src/components/dialog/dialog.spec.js, src/components/dialog/dialog.stories.mdx, src/components/dialog/dialog.style.js, src/components/modal/__snapshots__/modal.spec.js.snap, src/components/modal/modal.component.js
- add help prop 
- wrap text
Fixes #3828
Fixes #3831
help prop doesn't exist
DialogFullScreen: https://5ecf782fe724630022d27d7d-oskymkvuxe.chromatic.com/?path=/story/dialog-full-screen--with-help
Dialog: https://5ecf782fe724630022d27d7d-oskymkvuxe.chromatic.com/?path=/story/dialog--with-help
=> feat(dialog, dialog-full-screen): add help and and fix text wrapping - [ FE-4025 | FE-4026 ] 

.github/workflows/chromatic-pr.yml, .github/workflows/chromatic-push.yml, .github/workflows/ci.yml, .github/workflows/cypress-pr.yml, .github/workflows/cypress-push.yml, .github/workflows/semantic-release.yml, .github/workflows/storybook.yml, .nvmrc, babel.config.js, check_version.js, docs/dev-environment-setup.md, package-lock.json, package.json
Change GitHub CI so it uses a compatible version of node `>=14.16.0`(defined in package.json#engines).
I increased the version range to include `14.16.0`, this is latest version available for the cypress docker image. `14.16.1` was rather arbitrary, it was the latest `lts` version at the time the engine field was updated.
I've restricted the range to keep it on the current LTS (`14.x`).
We don't force our consumers to stay on `14`, but we don't officially support `15`.
We no longer need to transpile from `12` to `14` so I removed it from the `babelrc.json`.
I've also removed the other text editor recommendations. Developers are still free to choose their editor, but we can only provide support for VS Code.
GitHub CI is using `12.x`
Blocking #3799
⚠️ Developers will no longer be able to …
=> build: upgrade to node 14 lts

src/__experimental__/components/date-range/__snapshots__/date-range.spec.js.snap, src/__experimental__/components/date/__snapshots__/date.spec.js.snap, src/__experimental__/components/date/date.component.js, src/__experimental__/components/date/date.spec.js, src/__experimental__/components/date/date.stories.mdx, src/__experimental__/components/date/date.style.js
This PR adds styled-system margin support to Date component
https://codesandbox.io/s/carbon-quickstart-forked-dnnin
=> feat(date): add styled-system margin support - FE-3508

src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.spec.js, src/components/menu/menu-item/menu-item.style.js, src/components/menu/menu.stories.mdx
Add a new `maxWidth` prop to `MenuItem`. If the title of the item exceeds the maximum width, it will automatically truncate.
This will also add a title attribute for hovering over the `MenuItem`.
It is not currently possible to add truncation to `MenuItem` titles in this way.
https://codesandbox.io/s/fervent-noyce-y162u
=> feat(menu-item): add max width prop for truncation

src/__experimental__/components/checkbox/checkbox.d.ts, src/__experimental__/components/form-field/form-field.d.ts, src/__experimental__/components/switch/switch.component.js, src/__experimental__/components/switch/switch.d.ts, src/__experimental__/components/textarea/textarea.d.ts, src/__experimental__/components/textbox/textbox.d.ts, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js, src/components/icon/icon.d.ts
PropTypes in various components are defined as strings, these props should have more specific types.
=> refactor: change propTypes to be more specific

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/checkbox/checkbox.component.js, src/__experimental__/components/radio-button/radio-button.d.ts, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__experimental__/components/switch/switch.component.js, src/__internal__/checkable-input/checkable-input.d.ts, src/components/flat-table/flat-table-checkbox/__snapshots__/flat-table-checkbox.spec.js.snap
This PR adds `name` propType to Checkbox and Switch components
Fixes #3693
https://codesandbox.io/s/carbon-quickstart-forked-94p3v?file=/src/index.tsx
=> fix(checkable-inputs): fix name prop forwarding - FE-3743

rfcs/text/internal-interfaces.md
Remove ambiguity in internal interfaces RFC. 
Some public interfaces have ended up in the `__internal__` folder with a public `index.js` file to export it. This has caused confusion if the interface is public or not. In this case the component should have been in the public folder.
Fixes FE-4106
=> docs: remove ambiguity in internal interfaces RFC - FE-4106

src/__experimental__/components/grouped-character/grouped-character.component.js, src/__experimental__/components/grouped-character/grouped-character.spec.js, src/__experimental__/components/grouped-character/grouped-character.stories.mdx
This PR adds styled-system margin support to GroupedCharacter component
https://codesandbox.io/s/carbon-quickstart-forked-hi6r3
=> feat(grouped-character): add styled-system margin support - FE-3514

cypress/plugins/index.js
Add `--simulate-outdated-no-au` flag to disable `chromium` based browser to be able automatically updated.
As `Cypress` team [recommended](https://github.com/cypress-io/cypress/issues/16693#issuecomment-848928505) we need to pass `--simulate-outdated-no-au` flag to disable `chromium` based browser to be able automatically updated.
=> test: disable chrome update

docs/usage-with-routing.stories.mdx, src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/tabs.component.js, src/components/tabs/tabs.d.ts, src/components/tabs/tabs.spec.js, src/components/tabs/tabs.stories.mdx
closes: #3520
Removes baked in support for manipulation of window location as implementation is extremely limited and implementing the a feature to override it will be difficult to maintain. Consumers wishing to have this functionality should utilise the `onTabChange` and `selectedTabId` props and implement their own `history` implementation.
BREAKING CHANGE: Internal support for updating window location has been removed from the `Tabs`
component, the `setLocation` prop has also been removed as it serves no purpose beyond serving as a
guard for this functionality. Consumers who wish to have this functionality should utilise the
`onTabChange` and `selectedTabId` props with whatever `history` implementation they want to.
Removes dark background from focused `TabTitle` when `isTabSelected` …
=> feat(tabs): remove internal support for history and url manipulation - FE-3484

src/components/duelling-picklist/duelling-picklist.component.js, src/components/duelling-picklist/duelling-picklist.context.js, src/components/duelling-picklist/duelling-picklist.spec.js, src/components/duelling-picklist/picklist-group/picklist-group.component.js, src/components/duelling-picklist/picklist-group/picklist-group.spec.js, src/components/duelling-picklist/picklist-group/picklist-group.style.js, src/components/duelling-picklist/picklist-item/picklist-item.component.js, src/components/duelling-picklist/picklist-item/picklist-item.spec.js, src/components/duelling-picklist/picklist/picklist.component.js
Fixes bug where it is possible to have less or more than two `Picklist`s.
Adds `FocusContext` to allow the correct `PicklistItem` or `PicklistGroup` button to be focused when
a given `Picklist` child is moved. If the item or group is not the last one it focuses the next in the given `Picklist`, if it is the last it focuses the first in the other `Picklist`.
Focus is moved to the element before the first `Picklist` when an item button is clicked or receives a keydown event
`design-system-duellingpicklist--grouped`
`design-system-duellingpicklist--default`
=> fix(duelling-picklist): add error if children do not have 2 picklist FE-4059 

src/__experimental__/components/search/search.spec.js, src/__experimental__/components/search/search.stories.mdx, src/__experimental__/components/search/search.style.js
Updates the `defaultValue` text so it isn't the same text used for `placeholder` to make it clearer
that there is what using each prop does.
The `InputIconToggle` is slightly out of alignment within the `Search` component, when it is focused
you can see it is slightly misaligned. Adding a transform to move it down vertically by 1% solves
the issue as it is trying to centre itself within the input but the input has a height of 35px
Stories that use `defaultValue` all have text `Search` which is similar to the `placeholder` text.
The `InputIconToggle` is slightly out of alignment within the `Search` component, when it is focused
you can see it is slightly misaligned.
`design-system-search--default-story` etc
=> docs(search): update stories with default values to not have same text used for placeholder FE-4069

src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/tab/tab.d.ts
fix #4048
There is a missing semi-colon meaning the styles for `TabTitle` are incorrectly applied when it is
selected
Styles are not applies correctly when a TabTitle is selected
=> fix(tabs): add missing colon to tab-title styles FE-4112

package-lock.json, package.json
Add `browserslist` as a temporary fix for https://github.com/Sage/carbon/security/dependabot/package-lock.json/browserslist/open 
We can remove it once the packages using browserslist have been upgraded to fix the vuln.
We have a vulnerable version of `browserslist` being used by multiple packages.
=> chore(deps): add browserslist as workaround

src/__experimental__/components/simple-color-picker/simple-color-picker.component.js, src/__experimental__/components/simple-color-picker/simple-color-picker.stories.mdx
fix #4062
Adds guard in `handleOnBlur` function to prevent calling `onBlur` prop if not defined
Calls onBlur when not defined
Check `SimpleColorPicker` stories
=> fix(simple-color-picker): add guard to prevent calling onBlur when undefined FE-4124

src/components/tile-select/tile-select-group.d.ts, src/components/tile-select/tile-select.d.ts
Fix incorrect type definitions for the onChange, onBlur and description props.
Add footer prop type definition.
=> fix(tile-select): incorrect ts type definitions (FE-4108)

cypress/README.md, cypress/docker-compose.yml
Only use `X11` when running `cypress open`.
Cypress tires to connect to X11 when running `cypress up`.
https://github.com/Sage/carbon/pull/4099
Please try the instructions in the `cypress/README.md`
=> chore(docker): remove X11 from cypress up - FE-4129

src/components/definition-list/definition-list.spec.js, src/components/definition-list/definition-list.stories.mdx, src/components/definition-list/dl.component.js, src/components/definition-list/dt.component.js
Fixes: #4013
Rewrite render logic in the definition list component to better handle conditional rendering. It now no longer wraps an unnecessary fragment around every `Dt` and `Dd` pair.
When conditionally rendered and wrapped in fragments, `Dt`s are duplicated in the DOM, and when only a single fragment is passed in as children the component errors.
See the sandboxes in the attached issue for the before test, and the rebuild ones in the codesandbox bot comment below for the fixed versions.
=> fix(definition-list): fix conditional rendering logic

src/components/note/note.component.js, src/components/note/note.style.js
fix #4137
Adds `getDecoratedValue` util to wrap `noteContent` and ensure decorator used to rneder link as
correct html element
Valid url strings are not rendered as correct html
https://codesandbox.io/s/editor-and-note-with-json-085j5
- add a link (eg www.foo.com), save it so it is stored in `localStorage`
- refresh and then click save again on editor, the note should render a link
- compare to sandbox in linked issue which will not render the link
=> fix(note): add decorator to content to ensure correct html applied

src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button.component.js, src/__experimental__/components/radio-button/radio-button.d.ts, src/__experimental__/components/radio-button/radio-button.spec.js, src/__internal__/checkable-input/checkable-input.component.js, src/__internal__/checkable-input/hidden-checkable-input.component.js
The component is wrapped in a forwardRef.
Type definition is updated to include refs.
RadioButton input cannot be directly accessed by Carbon developers.
https://codesandbox.io/s/carbon-quickstart-forked-z6lrn
=> fix(radio-button): allow ref forwarding to allow access to the underlying input - FE-4095

src/components/select/filterable-select/filterable-select.component.js, src/components/select/multi-select/multi-select.component.js, src/components/select/select-list/select-list.component.js, src/components/select/select-list/select-list.spec.js, src/components/select/simple-select/simple-select.component.js
Adds data role to `SelectList` `Loader` when `isLoading` prop is true.
`SimpleSelect` -> `simple-select-list-loader`
`MultiSelect` -> `multi-select-list-loader`
`FilterableSelect` -> `filterable-select-list-loader`
No selector surfaced on `Loader` rendered internally within the `SelectList`
=> fix(select-list): add data role to internal loader component

src/components/pod/pod.d.ts
`pod.d.ts` file has definition for `size`
`pod.d.ts` file has definition for `padding` prop but should be `size`
=> fix(pod): update incorrect type definition from padding to size

src/components/loader/loader.component.js
Destructure the props so they are not spread to all elements within component
The `Loader` component spreads all props to root and sub-elements meaning any `data-` selectors are also passed to every element etc.
Currently what happens in master:
After update:
https://codesandbox.io/s/carbon-quickstart-forked-el4yz inspect the console and confirm data- tags are only on root element
=> fix(loader): destructure props and only spread rest props on root element FE-4183

src/components/card/card.d.ts
Update `card.d.ts` to extend `styled-system` `MarginProps` interface
`styled-system` `MarginProps` interface missing from `card.d.ts`
=> fix(card): extend styled system margin props in ts interface

src/__experimental__/components/search/search.d.ts, src/__experimental__/components/simple-color-picker/simple-color-picker.d.ts, src/__experimental__/components/simple-color-picker/simple-color/simple-color.d.ts
Update type definitions for `onKeyDown` in `SimpleColorPicker` and `onMouseDown` in `SimpleColor` to not use `SyntheticEvent` type for callback parameter.
Update `onClick` and `onKeydown` in `Search` to not use `SyntheticEvent`
All callbacks use `SyntheticEvent` type for event parameter
=> fix(simple-color-picker, simple-color): update onkeydown and onmousedown to not use synthetic event

src/components/pod/pod.component.js
Remove the `title` attribute incorrectly passed to the styled-component through the rest spread.
=> chore(pod): remove title html attribute (FE-4172)

src/__internal__/popover/popover.component.js, src/__internal__/popover/popover.spec.js, src/components/accordion/accordion.component.js, src/components/accordion/accordion.spec.js, src/hooks/__internal__/useResizeObserver/index.d.ts, src/hooks/__internal__/useResizeObserver/index.js, src/hooks/__internal__/useResizeObserver/index.spec.js
This PR creates internal hook `useResizeObserver`
https://codesandbox.io/s/carbon-quickstart-forked-vwuyx?file=/src/index.js
=> refactor: create internal useresizeobserverhook - FE-4170

src/components/menu/menu-item/menu-item.style.js
Fixes: #4178
Apply hover background and text colour CSS to the menu item `a` or `button` only.
It is possible to hover over a `span` containing the menu item title, which will apply background and text colour CSS to the span. 
When this is within a menu item with truncated text, this causes the span to cover up part of the focus outline:
Sandbox to assist testing here: https://codesandbox.io/s/quizzical-lewin-yz35y?file=/src/index.js
The built version is in the codesandbox bot comment below.
=> fix(menu-item): stop hover css applying to span

src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-cell/flat-table-cell.spec.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.stories.mdx
pl prop is now available to use on a flat-table-cell component
fixes #4145
Allows `pl` prop to be used on a `flat-table-cell`.
`pl` value is overwritten by a hard-coded `padding-left: 4px` value.
N/A
Use codesandbox built on the PR.
=> fix(flat-table): fix styled-system pl support - FE-4160

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
pl and px values were being overwritten by a hard-coded 30px padding-left value from flat-table-row
fixes FE-4192
- Allow `pl` and `px` values to be used when `FlatTableRowHeader` is nested inside of a `FlatTableRow`.
- `pl` and `px` values are overwritten by a hard-coded `padding-left: 30px` value when `FlatTableRowHeader` is nested inside of a `FlatTableRow`.
N/A
https://codesandbox.io/s/youthful-germain-1n0rq
New example has also been created in storybook to demonstrate this too. It can be found:
Design System -> Flat Table -> Expandable -> With row headers with custom paddings
=> fix(flat-table-row-header): fix pl and px props not being applied - FE-4192

src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js
fix #4214
Now it is possible to override this behaviour if an `onClick` callback is set on the subrows
Currently all have `tabIndex` set to `undefined` when a `FlatTableRow` has either `isSubRow` or `firstColumnExpandable` set. 
https://codesandbox.io/s/loving-mendel-5e3gn?file=/src/index.js
`keyboard accessible subrows` added to flat-table-expandable stories
=> fix(flat-table-row): add support for setting tabindex on subrows with onclick handler passed FE-4202

src/components/note/note.spec.js, src/components/note/note.style.js
Fixes `createdDate` alignment when no `name` and `status` props passed
`createdDate` alignment when no `name` and `status` props passed is wrong
Example of issue:
fix:
https://codesandbox.io/s/carbon-quickstart-forked-oi132?file=/src/index.js
=> fix(note): ensure date aligns when no edited status

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-head/flat-table-head.style.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.style.js
fixes: #4190
There was an issue if there was not enough space for the table and scroll appears.
It causes that text inside of sticky header was scrolling when user used scroll
Testable in codesandbox
=> fix(flat-table): scrolling content in table header - FE-4193

src/__experimental__/components/numeral-date/numeral-date.component.js
`size` prop type does not pass an array to `PropTypes.oneOf`
Update `size` prop type to pass an array to `PropTypes.oneOf`
Should not see the below error in the console when viewing `NumeralDate` stories
```
Warning: Invalid arguments supplied to oneOf, expected an array, got 3 arguments. A common mistake is to write oneOf(x, y, z) instead of oneOf([x, y, z]).
```
=> fix(numeral-date): update size prop type to have correct oneOf syntax

src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap, src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap, src/components/button-toggle/button-toggle.style.js
This PR fixes incorrect hover styling on disabled ButtonToggle
Styling of the ButtonToggle should not change when hovered while in disabled state
https://codesandbox.io/s/carbon-quickstart-forked-77jel?file=/src/index.js
=> fix(button-toggle): fix hover styling on disabled state - FE-4214

src/components/typography/typography.component.js, src/components/typography/typography.d.ts, src/components/typography/typography.spec.js, src/components/typography/typography.stories.mdx
white-space is now able to be styled. Truncation is now also possible with the introduction of a
truncate prop.
fixes #4122
- Users can now style white-space using any valid CSS string
- Users can truncate text using the `truncate` prop
- white-space cannot be styled
- no way of truncating text
N/A
- Visit the Design System Folder
- Typography
- New examples have been created called:  `truncate`. 
Codesandbox - https://codesandbox.io/s/carbon-quickstart-forked-dhots?file=/src/index.js
=> feat(typography): add support for white-space styling and truncation - FE-4158

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap, src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap, src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap, src/__experimental__/components/radio-button/radio-button-group.component.js, src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap, src/__internal__/checkable-input/checkable-input.component.js, src/__internal__/checkable-input/checkable-input.spec.js
resolves the errors in axe relating to ARIA attributes must conform to valid values.
fixes FE-1700
No accessibility errors present for `radio-button` in Storybook.
Axe throws errors: 
- Ensures all ARIA attributes have valid values
- Ensures elements with an ARIA role that require child roles contain them
N/A
Check all `radio-button` stories for accessibility warnings in the Storybook `accessibility` tab.
=> fix(radio-button, checkable-input): fix invalid values in ARIA attributes - FE-1700

src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js
Reduces the `z-index` value when an `onClick` is passed from `2000` to `1001`. When it is at 2000 it
overlaps modals
clickable rows have a z-index of 2000 which overlaps carbon Modals
https://codesandbox.io/s/carbon-quickstart-forked-7kjq2?file=/src/index.js --> proposed change
https://codesandbox.io/s/charming-shadow-lcjp7?file=/src/index.js --> current behaviour v77.11.0
Test that focus outline is still correct for `story/design-system-flat-table--with-row-header` in safari
=> fix(flat-table-row): reduce z-index value when onclick passed to row

src/components/drawer/drawer.component.js, src/components/drawer/drawer.d.ts, src/components/drawer/index.d.ts, src/components/drawer/index.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.mdx, src/components/form/form.component.js, src/components/form/form.spec.js, src/components/form/form.style.js, src/components/sidebar/index.js, src/components/sidebar/sidebar.component.js, src/components/sidebar/sidebar.d.ts, src/components/tabs/tabs.component.js, src/components/tabs/tabs.spec.js
Fixed Form Footer inside of Sidebar
fixes: #4211
When Form with Form Footer in sticky mode is provided to Sidebar, the footer getting out of component
In this ticket I renamed SidebarContext that was in Drawer component because it was confusing. New name for Drawer context is DrawerSidebarContext.
I added new context SidebarContext to Sidebar component
Testable in codesandbox
=> fix(sidebar): Support for Form with stickyFooter FE-4205

src/components/flat-table/flat-table.stories.mdx
Better demonstrates the possibilities of using custom paddings in FlatTable
fixes FE-4187
N/A
- Build should pass
- No Cypress tests should be affected
- Chromatic snapshot should match the new version of this story
- No other stories should be affected by this change
=> docs(flat-table): improve custom cell padding example - FE-4187

src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.spec.js
fix #4227
Adds `useEffect` to set `hasFocus` to false if `disabled` prop is set
Focus outline remains when `disabled` prop is set on `TileSelect`
https://codesandbox.io/s/optimistic-mendeleev-f4i19?file=/src/index.js
=> fix(tile-select): prevent focus outline when tile select is disabled

cypress/features/regression/designSystem/filterableSelectEvents.feature, cypress/features/regression/designSystem/multiSelectEvents.feature
Add new Cypress tests for the onFilterChange action events in Filterable Select and Multi Select.
These tests do not currently exist.
Run Cypress tests `cypress/features/regression/designSystem/filterableSelectEvents.feature` and `cypress/features/regression/designSystem/multiSelectEvents.feature`. New scenarios added test the onFilterChange action event.
=> test(select): add new tests for filterable and multi select FE-4230

src/__experimental__/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap, src/__experimental__/components/simple-color-picker/simple-color-input/simple-color-input.style.js
Setting cursor to not-allowed brings this behaviour inline with our other components when disabled
fixes FE-4198
N/A
- Visit the `experimental-simple-color-picker--disabled` story for `simple-color-picker`
- Hover over the component and mouse pointer should be `not-allowed`
=> fix(simple-color-picker): set cursor to not-allowed when component is disabled - FE-4198

src/__experimental__/components/search/search.d.ts
Fixes: #4185
Correct the TypeScript type on the `Search` component `onClick` prop so that `event.target.value` is accessible.
The current type gives a ts error when you try to access `event.target.value`
https://codesandbox.io/s/peaceful-swanson-yyoe5?file=/src/index.tsx
=> fix(search): correct onClick prop ts type

.github/ISSUE_TEMPLATE/feature_request.yml
Fix the yaml indentation
The yaml is indented incorrectly, the template is not displayed.
https://github.com/Sage/carbon/pull/4251
Try to create a new issue after merging, you should see the option to create a feature request.
=> chore: update issue template

src/components/drawer/drawer.component.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table.component.js, src/components/tabs/tabs.component.js, src/components/tabs/tabs.spec.js
Adding default value to DrawerSidebarContext will allow us to use object destructuring
Default value is missing
I think we should just check all components that use DrawerSidebarContext and check if there are any changes. No changes should be visible. 
Components that uses DrawerSidebarContext:
- Drawer component
- Flat Table component
- Tabs
=> refactor(drawer): add default value to DrawerSidebarContext - FE-4224

cypress/features/regression/pod.feature, cypress/fixtures/commonComponents/pod.json, cypress/locators/pod/index.js, cypress/locators/pod/locators.js, cypress/support/step-definitions/pod-steps.js, src/components/pod/pod.component.js, src/components/pod/pod.d.ts, src/components/pod/pod.spec.js, src/components/pod/pod.stories.js, src/components/pod/pod.stories.mdx, src/components/pod/pod.style.js
Remove the pod collapse functionality, it could be re-created using the Accordion Component.
Remove the "description" prop, this is just a styled text that could be rendered in Pod children.
=> refactor(pod): remove collapse functionality (FE-1762)

src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-head/flat-table-head.component.js, src/components/flat-table/flat-table-header/flat-table-header.style.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table-row/flat-table-row.style.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.mdx
z-index has been increased to 1002 when hasStickyHead to prevent content being hidden on scrolling
horizontally
fixes #4226
N/A
https://codesandbox.io/s/winter-thunder-b1s6r
Story called `With stickyHead, rowSpan and colspan` has also been added to the `Flat-Table` MDX doc.
=> fix(flat-table): ensure correct z-index is applied to flat-table-header - FE-4225

src/components/link/link.component.js, src/components/menu/menu-full-screen/menu-full-screen.component.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu.component.js, src/components/pod/__snapshots__/pod.spec.js.snap
Adding aria-role to menu will fix accessibility violations that are visible in storybook story
=> fix(menu): add aria-role to fix accessibility violations - FE-3422

src/components/sidebar/index.d.ts, src/components/sidebar/sidebar.component.js, src/components/sidebar/sidebar.d.ts, src/components/sidebar/sidebar.spec.js
Sidebar component should be wrapped in a `forwardRef` to allow access to underlying html element.
=> feat(sidebar): implement ref forwarding

cypress/features/regression/designSystem/dateInput.feature, cypress/locators/date-input/index.js, cypress/locators/date-input/locators.js, cypress/support/step-definitions/date-input-steps.js, src/components/date/date-picker.component.js, src/components/date/date-picker.spec.js
Fixed useEffect
Unable to move between months using the DateInput's arrows
https://codesandbox.io/s/stupefied-pine-nsmpq
https://www.loom.com/share/fd66ea73983748cd86d11286379e2e46
Resolves #4307
https://codesandbox.io/s/carbon-quickstart-forked-1tciy
=> fix(date-picker): month could not be changed in datepicker - FE-4274

.storybook/utils/translation-keys-table.js, src/components/i18n-provider/i18n-provider.component.js, src/components/i18n-provider/i18n-provider.d.ts, src/components/text-editor/__internal__/toolbar/toolbar.component.js, src/components/text-editor/__internal__/toolbar/toolbar.spec.js, src/components/text-editor/text-editor.stories.mdx, src/locales/en-gb.js
fix #4121
Adds util to support generating translation key tables in storybook
Adds `textEditor` object to `en-gb.js` locale file with `tooltipMessages` and `ariaLabels`
properties. This will support implementation teams in overriding the default translations for the
`ToolbarButton`'s Tooltip and the `ariaLabel` using their own locale object and the `I18nProvider`
No util for generating translation key tables exists
No support for translation overriding in `TextEditor`
https://codesandbox.io/s/carbon-quickstart-forked-xgvtj?file=/src/index.js
=> docs(translation-keys-table): add util to support rendering translation keys in storybook FE-4159

src/__internal__/focus-trap/focus-trap.component.js, src/__internal__/focus-trap/focus-trap.spec.js
Fixes: #4255
Add `MutationObserver` to `FocusTrap` to reset it when something in it's child tree changes.
The `FocusTrap` does not reset if it's children changes.
Sandbox in issue rebuilt with this code in the codesandbox comment below
=> fix(focus-trap): add mutation observer

src/components/menu/menu.stories.mdx
Altering a `Menu` story to remove the false positive from the accessibility tests:
We currently have a false positive on the `design-system-menu--truncated-titles` story for an "incomplete" test:
=> docs(menu): alter story to remove aria false positive

src/components/select/select-list/select-list.component.js, src/components/select/select-list/update-list-scroll.js, src/components/select/select-list/update-list-scroll.spec.js
Container is not scrolled because the option ref is pointing to an incorrect ref.
Option ref list should be updated every time the option list is changed, so the proper ref is pointed when traversing options with keyboard.
When the option list is dynamically loaded, traversing it with keyboard does not scroll the container to show current option.
Fixes #4270
1. run npm start
2. open …
=> fix(select): option not scrolled using keyboard navigation when options are changed (FE-4244)

.storybook/welcome-page/loves-carbon/loves-carbon.style.js, src/components/help/help-test.stories.mdx, src/components/help/help.component.js, src/components/help/help.d.ts, src/components/help/help.spec.js, src/components/help/help.stories.mdx, src/components/icon/icon.component.js, src/components/icon/icon.d.ts, src/components/icon/icon.spec.js, src/components/icon/icon.stories.mdx, src/components/link/link.stories.mdx
The Help component accepts children of node type and no longer renders `aria-label` and `value` based on the string.
`aria-label` and `value` must be defined as separate props.
The Help component accepts children of string type and renders `aria-label` and `value` based on the string.
fix #4286
https://codesandbox.io/s/carbon-quickstart-forked-es8pl
=> refactor(help): change the children proptype from string to node - FE-4280

src/components/tile/tile.d.ts
Currently horizontal is spelt incorrectly in the ts file for tile. This is causing error for our ts
users using tile.
fixes FE-4313
`horizontal` is spelt correctly
`horizontal` is not spelt correctly
N/A
https://codesandbox.io/s/nervous-sea-d23km?file=/src/index.tsx
Codesandbox should not display any errors relating to the `orientation` prop value being incorrect.
=> fix(tile): address spelling mistake with horizontal in the options for orientation prop

src/components/menu/menu.stories.mdx, src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.d.ts, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js
fix #4219
Adds `flow-wrap` style property to container for `title`, `subtitle` and `adornment` to ensure they
wrap at smaller resolution or if any text is too long. Adds flex `Box` to wrap the the above content
and the action button so they render in correct layout.
Adds `prefixAdornment` prop to allow implementation teams to render a node in the top left corner of
`TileSelect` before other content.
Content does not wrap (see linked issue)
No support for prefix adornment
`design-system-tile-select--with-a-prefix-adornment` added.
Demo of wrapping:
https://codesandbox.io/s/eloquent-snyder-6d2gt?file=/src/index.js
=> fix(tile-select): ensure title, subtitle and adornment wrap at smaller screen resolution FE-4275

.github/workflows/chromatic-fork.yml, .github/workflows/cypress-push.yml, CONTRIBUTING.md
Allow carbon maintainers to start builds on forked PR's using GitHub actions.
Maintainers have to run the chromatic comparison locally.
We'll do the same for Cypress in another PR.
Merge then run run a build for a forked PR.
=> ci(github-actions): create forked pr workflow - FE-4298

package-lock.json, package.json
Unpin chromatic so it uses the latest version. There was an error in the dependency tree after removing the package, tests failed to run. Running `npm dedupe && npm prune && npm install` fixed the issue.
It's pinned to an old version which appears to be getting the incorrect git information.
https://github.com/Sage/carbon/runs/3526014600
N/A
=> chore(deps): upgrade chromatic

package-lock.json, package.json
Upgrade to `chromatic@5.9.2`.
GitHub actions is using a cached version `5.7.1` even when it is removed from `package-lock.json`.
https://github.com/Sage/carbon/pull/4365
https://github.com/Sage/carbon/pull/4366
N/A
=> chore(deps): upgrade chromatic to 5.9.2
