CHANGELOG.md
lib/components/detail/detail.scss
src/components/detail/detail.scss

This should have been included in the rc2 - since no one is using it yet, we want to re-release it with this change.

rc2 2nd try

---

.travis.yml
README.md
package.json

* Point at `carbon-factory` from npm
* Update reference to `xhr-mock` to use `git://`
* Add `.travis.yml` file with config for running travis builds
* Update build status image in README file.

Enable TravisCI

---

README.md

Add NPM, Codeship Badges

---

demo/i18n/en.js
lib/components/animated-menu-button/animated-menu-button.js
lib/components/button-toggle/button-toggle.js
lib/components/grouped-character/grouped-character.js
lib/components/menu-list/menu-list.js
package.json
src/components/animated-menu-button/animated-menu-button.js
src/components/button-toggle/button-toggle.js
src/components/grouped-character/grouped-character.js
src/components/menu-list/menu-list.js

Including lib and version bump for immediate release

Update import paths to relative ones

---

package.json

FYI you need at least npm v4 to publish releases.

bump 1.0.0-rc6

---

README.md

Uses http://shields.io/ image for consistency.

Update Codeship image

---

CHANGELOG.md
package.json

Upgrade bignumber to latest

---

CHANGELOG.md
src/components/animated-menu-button/animated-menu-button.js
src/components/button-toggle/button-toggle.js
src/components/button-toggle/definition.js
src/components/button/button.js
src/components/multi-action-button/multi-action-button.js
src/components/split-button/definition.js
src/components/split-button/split-button.js

To prepare for the future upgrade of [carbon-factory](https://github.com/Sage/carbon-factory), that will introduce stricter linting rules, this PR updates the `button` components to pre-emptively resolve the errors.
- AnimatedMenuButton
- Button
- ButtonToggle
- MultiActionButton
- SplitButton
No functional changes were made and no particularly significant refactors were required.

Button linting updates

---

CHANGELOG.md
src/components/content/__spec__.js
src/components/content/content.js

* `body` added to content.js
* sense check `Content` component on demo site

Adds data-element

---

docs/guides/services.md

Update service guide for carbon-react

---

CHANGELOG.md
src/components/profile/definition.js
src/components/profile/profile.js

Fix warnings in the component, and update the definition for the demo site.

Fix ESLint warnings for Profile component 

---

CHANGELOG.md
src/components/portrait/__spec__.js
src/components/portrait/definition.js
src/components/portrait/portrait.js

Add missing props, replace double quotes with single quotes.
Fix failing tests.
Update release notes

Fix ESLint warnings for Portrait component

---

CHANGELOG.md
src/components/message/definition.js
src/components/message/message.js

Replace multiline ternary operators with if statements, absolute imports before relative, replace string concatenation with templates, and add missing props.
Update definition with missing props.

Fix ESLint errors for Message component

---

CHANGELOG.md
src/utils/decorators/should-component-update/should-component-update.js
src/utils/decorators/tooltip-decorator/__spec__.js
src/utils/decorators/tooltip-decorator/tooltip-decorator.js

* NB Two tests that were removed were directly calling private functions and therefore don't fit with up to date best practice (they also failed which is why I noticed them)
* Fire up the demo site and check the Tooltip component

Tooltip and shouldComponentUpdate decorator linting

---

CHANGELOG.md
src/utils/css/css.js
src/utils/ether/ether.js

* sense check in the demo site

Linting CSS and Ether

---

src/utils/decorators/input-icon/input-icon.js
src/utils/decorators/input-label/__spec__.js
src/utils/decorators/input-label/input-label.js
src/utils/decorators/input-validation/__spec__.js
src/utils/decorators/input-validation/input-validation.js
src/utils/decorators/input/__spec__.js
src/utils/decorators/input/input.js

* A few changes in the specs correspond with the removal of `findDomNode` and changes to refs
* Sense check the input elements in the demo site

Linting decorators

---

CHANGELOG.md
src/utils/validations/date-range/date-range.js
src/utils/validations/email/email.js
src/utils/validations/exclusion/exclusion.js
src/utils/validations/inclusion/inclusion.js
src/utils/validations/length/length.js
src/utils/validations/numeral/numeral.js
src/utils/validations/presence/presence.js
src/utils/validations/regex/regex.js

* Given the changes, that show that only four of the eight changed validators have anything more than blank line removals, only those four will require testing - these will all be sense checked in a working application. (see proprietary ticket for more information).

Lints validations

---

CHANGELOG.md
src/utils/helpers/tags/__spec__.js
src/utils/helpers/tags/tags.js

https://github.com/Sage/carbon/pull/1310

revert data component prop override

---

package.json

Waiting on Revert of Data Tag work https://github.com/Sage/carbon/pull/1347

bump packge.json to v1.1.2

---

README.md

A few improvements to Submitting a Release section

---

CHANGELOG.md
src/utils/decorators/input-validation/__spec__.js
src/utils/decorators/input-validation/input-validation.js
src/utils/decorators/input/input.scss

Reverts Sage/carbon#1341
So we can target master

Revert "Add an 'info' prop in input to display info-styled icon and message"

---

CHANGELOG.md
gulpfile.js
src/components/rainbow/__spec__.js
src/components/rainbow/rainbow.js

Linting for the rainbow component

Rainbow Linting

---

CHANGELOG.md
src/components/pager/__spec__.js
src/components/pager/pager.js

* Negative numbers set to absolute value
* minus sign defaults to page 1
Opened instead of https://github.com/Sage/carbon/pull/1131

CARBON-701 Update how pager handles negative/invalid numbers

---

CHANGELOG.md
src/utils/helpers/i18n/__spec__.js
src/utils/helpers/i18n/i18n.js

Requirements have been defined for the I18n helper and to ensure consistency we need to revert the following: https://github.com/Sage/carbon/pull/1369

revert i18nhelper changes

---

CHANGELOG.md
package.json

bump version and update release notes

---

demo/stores/component/component.js

replace Object.assign with lodash function

---

CHANGELOG.md
check-version.js
package-lock.json
package.json
src/components/date-range/date-range.js

* to allow package locks when using npm 5
* Refactor date-range to satisfy compiler issue on upgrade.
Had to run `npm rebuild node-sass` after reinstall.
* Also needed to run `npm verify cache` before npm install in carbon root.

CARBON-888 add package-lock file

---

CHANGELOG.md
package.json
src/utils/decorators/input/input.scss

fixed background color on date validations

---

CHANGELOG.md
src/patterns/configurable-items/__definition__.js
src/patterns/configurable-items/__spec__.js
src/patterns/configurable-items/configurable-items.js

Backport the feature https://github.com/Sage/carbon/pull/1485 into version 1.4.6

Add the config items Pattern onReset prop to 1.4.6

---

CHANGELOG.md
package-lock.json
package.json
src/utils/decorators/input-validation/__spec__.js
src/utils/decorators/input-validation/input-validation.js

fixes change in v1.5 in https://github.com/Sage/carbon/pull/1452/commits/1f902687c507f7b9cc8fe8cb641c048f8d82b034
before:
after:

fixes floating error message

---

CHANGELOG.md
src/utils/service/__spec__.js
src/utils/service/service.js

As this class is setup to be inherited, we need to use prototypal inheritance to make extending it easier.

service class uses prototypal inheritance instead of class properties

---

CHANGELOG.md
package.json
src/components/dialog/dialog.scss

added additional specificity to dialog css

fixes css load order issue for dialog and form

---

CHANGELOG.md
package.json
src/components/dialog/dialog.scss

adds this change to 1.5.2 release

1351 to release

---

CHANGELOG.md
src/utils/service/__spec__.js
src/utils/service/service.js

Change service class to accept query params. Agreed approach to
deprecate existing implementation from method whilst maintaining
backwards compatibility.
https://github.com/Sage/carbon/issues/1499

_#1499 Service class accepts query params

---

src/components/form/form-summary/__spec__.js
src/components/form/form-summary/form-summary.js
src/components/form/form-summary/form-summary.scss
src/components/form/form.scss

cleaned up double class bug, and ensured that padding/margin remains consistent with/without cancel button and with/without additional form buttons.

ensures padding is consistent with cancel and additional form buttons

---

CHANGELOG.md
src/components/form/form-summary/__spec__.js
src/components/form/form-summary/form-summary.js
src/components/form/form-summary/form-summary.scss
src/components/form/form.scss

https://github.com/Sage/carbon/issues/1523
please [see issue](https://github.com/Sage/carbon/issues/1523)
Will need to be tested across different areas of the apps that use this before release

Fix Form Summary Button position bug #1523

---

CHANGELOG.md
docs/guides/services.md
src/utils/service/__spec__.js
src/utils/service/service.js

Description
Remove Service backwards compatibility for Carbon V2

remove service deprecation for v2

---

CONTRIBUTING.md

Move the `CONTRIBUTING.md` file to the project root.
Update the Jasmine reference to Jest.

Move CONTRIBUTING.md to the project root

---

README.md

Add testing section with links to carbon-factory

---

CHANGELOG.md
src/components/dialog-full-screen/__spec__.js
src/components/dialog-full-screen/full-screen-heading/full-screen-heading.js

Fix typo in fullscreenheading

---

CHANGELOG.md
package-lock.json
package.json
src/components/alert/__snapshots__/__spec__.js.snap
src/components/confirm/__snapshots__/__spec__.js.snap
src/components/confirm/__spec__.js
src/components/dialog-full-screen/__spec__.js
src/components/dialog/__snapshots__/__spec__.js.snap
src/components/dialog/__spec__.js
src/components/form/__spec__.js
src/components/modal/__snapshots__/__spec__.js.snap
src/components/modal/modal.js
src/components/sidebar/__snapshots__/__spec__.js.snap
src/components/sidebar/__spec__.js
src/utils/decorators/input-validation/__spec__.js

Removed the use of Portal from modals.
QA should check that modals still work as expected in applications.

removed portal from modals

---

CHANGELOG.md
demo/definitions.js
package.json
src/components/button-toggle-group/README.md
src/components/button-toggle-group/__definition__.js
src/components/button-toggle-group/__spec__.js
src/components/button-toggle-group/button-toggle-group.js
src/components/button-toggle-group/button-toggle-group.scss
src/components/button-toggle-group/package.json

This allows a group of ButtonToggles to behave as a single form component with label, field help, validation message, warning message, and info message support.

Adds a ButtonToggleGroup component.

---

CHANGELOG.md
src/components/menu/__definition__.js
src/components/menu/menu-item/menu-item.scss
src/components/menu/submenu-block/submenu-block.scss
src/components/portrait/portrait.js
src/components/portrait/portrait.scss
src/components/profile/profile.scss

PF-3520 - Update secondary menu styling as per new designs

---

CHANGELOG.md
src/utils/decorators/tooltip-decorator/tooltip-decorator.js

The Tooltip component accepts children. So the decorator should do the same.

Tooltip message prop

---

CHANGELOG.md
src/components/rainbow/rainbow.js

- Make sure the link works as expected and that the widget also displays what it is supposed to.

[AC-2007] - Rainbow component is unresponsive to mouse events

---

package-lock.json
package.json

Preparing for `v2.5.0` release.

Bump version to 2.5.0

---

.travis.yml
CHANGELOG.md
docs/tutorials/carbon-rails/hello-world.md
package-lock.json
package.json
src/components/portrait/__spec__.js
src/components/portrait/portrait.js
src/components/profile/__spec__.js
src/components/profile/profile.js
src/components/profile/profile.scss
src/components/rainbow/rainbow.js
src/utils/decorators/input-icon/__spec__.js
src/utils/decorators/input-icon/input-icon.js
src/utils/decorators/input-label/__spec__.js
src/utils/decorators/input-label/input-label.js
src/utils/decorators/input-validation/__spec__.js
src/utils/decorators/input-validation/input-validation.js
src/utils/decorators/input/__spec__.js
src/utils/decorators/input/input.js
src/utils/decorators/should-component-update/__spec__.js
src/utils/decorators/should-component-update/should-component-update.js
src/utils/decorators/tooltip-decorator/__spec__.js
src/utils/decorators/tooltip-decorator/tooltip-decorator.js
src/utils/flux/__spec__.js
src/utils/service/__spec__.js
src/utils/service/service.js

Merge `v2.5.0` from `master` to `release`.

v2.5.0 master to release

---

CHANGELOG.md
package-lock.json
src/components/profile/__spec__.js
src/components/profile/profile.js
src/components/profile/profile.scss

Undo the change that made `darkBackground={ true }` the default on the `Profile` component, and undo the CSS change to give the name and email a darker text colour.

CARBON-2010 Undo default darkBackground and darker text colour

---

CHANGELOG.md
package-lock.json
package.json

* Superagent has been updated to v3.8.2 for a security fix
* moment has been updated to v2.20.1 for a security fix

updated superagent and moment for security fixes

---

CHANGELOG.md
src/components/message/message.scss
src/components/toast/toast.scss

Fixes icon positioning in IE11 #1588

Fixes icon positioning in IE11 #1588

---

CHANGELOG.md
package-lock.json
package.json
src/components/portrait/__definition__.js
src/components/portrait/__spec__.js
src/components/portrait/portrait.js
src/components/portrait/portrait.scss

v2.6.1 patch - portrait colours

---

CHANGELOG.md
package-lock.json
package.json
src/components/menu/__definition__.js
src/components/menu/menu-item/menu-item.scss

Menu Items were displaying the wrong cursor when hovering them.

fixes cursor type on menu items

---

CHANGELOG.md
package-lock.json
package.json

Patch release on v2.5.x to fix security vulnerabilities in marked package.

Bump marked package

---

CHANGELOG.md
src/components/decimal/__spec__.js
src/components/decimal/decimal.js

*Cap precision at 20 and log warning if set higher
* replace double quotes in spec

Fix decimal precision in react upgrade

---

.npmignore
.travis.yml
README.md
package.json

Auto deploys to npm when a tag of `v#.#.#` is pushed.
Tested a tag of `v0.0.100` ✅ 
Tested a tag of `v0.0.100-rc1` ✅ 
Tested a normal tag ✅ 
Tested a branch ✅ 
Tested `release` branch ✅

added npm deploy

---

CHANGELOG.md
src/components/date/date.js
src/components/dialog/__definition__.js
src/components/dialog/dialog.scss
src/components/portal/__snapshots__/__spec__.js.snap
src/components/portal/__spec__.js
src/components/portal/portal.js

Datepicker Placement on Scroll Bug

Pf 3474 date picker scroll bug

---

CHANGELOG.md
src/components/dialog/__definition__.js
src/components/dialog/dialog.scss
src/components/dropdown/__spec__.js
src/components/dropdown/dropdown.js
src/components/dropdown/dropdown.scss
src/components/modal/modal.js

Carbon 969 dropdown portal

---

src/components/dropdown/__spec__.js
src/components/dropdown/dropdown.js

When loading the GAC Gateway pointing at local Master branch of Carbon.
Click on Contacts and Create and New Customer.
On the New Customer Screen open the dropdown for either Account Default or Country
Expected
The dropdown to be directly underneath the button
Observed
It appears off to the side of the page. See attachment.

bug fix and tests

---

package-lock.json
package.json

release v3_1_3

---

CHANGELOG.md
src/utils/decorators/input-validation/input-validation.js

Fixes the offset problem for error messages too

---

package.json

Bump version number to `3.2.4`.

Bump version number for 3.2.4 release

---

package-lock.json
package.json

Bump version number to v3.2.5

---

package-lock.json
package.json

Update `carbon-factory` to `4.2.1`, which includes the gzip images build fix.
Bump version number to `4.1.0`.

Prepare for v4.1.0

---

demo/views/pages/component/component-preview/component-preview.scss

Provides a more accurate representation of these components.

removes hacks in demo site for components

---

CHANGELOG.md
package-lock.json
package.json
webpack.config.js

This includes a change to support compilation on Windows environments, and required updating paths in the Webpack config.

upgraded carbon-factory to v4.2.2

---

.travis.yml
CHANGELOG.md

Add max workers to travis ci build

---

README.md
docs/guides/getting-started.md
docs/guides/setting-up-your-environment.md
gulpfile.js
package-lock.json
package.json

Remove the `gulp` package, `gulpfile.js`, and all references to gulp in the documentation.

Remove gulp

---

CHANGELOG.md
src/components/table/table-cell/table-cell.scss

Ensure that selected rows are all displayed in blue for primary and secondary tables.

Remove white background from selected table items

---

change_log/next/switch-component.yml
demo/definitions.js
src/components/checkbox/checkbox.js
src/components/switch/README.md
src/components/switch/__definition__.js
src/components/switch/__snapshots__/switch.spec.js.snap
src/components/switch/package.json
src/components/switch/switch.js
src/components/switch/switch.scss
src/components/switch/switch.spec.js

A new component which effectively restyles the Checkbox component.
Pull the branch down locally.
`$npm install`
`$npm start`
Navigate to localhost:8095
Go to the Switch component in the components list

Add Switch component

---

change_log/v4_5_1/add-data-role-to-icon.yml
package-lock.json
package.json
release_notes/v4_5_1.html.md
src/components/icon/__spec__.js
src/components/icon/icon.js
src/components/portal/__snapshots__/__spec__.js.snap

This is to ensure we have a consistent way of targetting the Icon components.

Add data-element to Icon component

---

.eslintrc
change_log/next/1865-step-sequence.yml
change_log/next/test-global-eslint.yml
demo/definitions.js
src/components/step-sequence/__definition__.js
src/components/step-sequence/__snapshots__/step-sequence.spec.js.snap
src/components/step-sequence/package.json
src/components/step-sequence/step-sequence-item/__definition__.js
src/components/step-sequence/step-sequence-item/__snapshots__/step-sequence-item.spec.js.snap
src/components/step-sequence/step-sequence-item/package.json
src/components/step-sequence/step-sequence-item/step-sequence-item.js
src/components/step-sequence/step-sequence-item/step-sequence-item.scss
src/components/step-sequence/step-sequence-item/step-sequence-item.spec.js
src/components/step-sequence/step-sequence-orientation.scss
src/components/step-sequence/step-sequence.js
src/components/step-sequence/step-sequence.scss
src/components/step-sequence/step-sequence.spec.js
src/components/step-sequence/style-config.scss
src/utils/helpers/options-helper/options-helper.js

This re-raises the original PR from https://github.com/Sage/carbon/pull/1867/ targeted against the release branch.

Add step sequence component #1865

---

change_log/v6_0_2/textarea-relative-paths.yml
package-lock.json
package.json
release_notes/v6_0_2.html.md
src/components/textarea/textarea.scss

Fixes an incorrect path Textarea was using to load Sass dependencies.

Fixes relative path in textarea

---

change_log/next/input-decorator-bridge.yml
src/__experimental__/components/input-decorator-bridge/__snapshots__/input-decorator-bridge.spec.js.snap
src/__experimental__/components/input-decorator-bridge/index.js
src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.component.js
src/__experimental__/components/input-decorator-bridge/input-decorator-bridge.spec.js

InputDecoratorBridge is a temporary component that we can use to gradually remove our reliance on the input decorators.

InputDecoratorBridge component

---

change_log/next/presence-arrays.yml
src/utils/validations/presence/__spec__.js
src/utils/validations/presence/presence.js

The presence validator now supports values that are arrays, as well as strings.

presence validator supports arrays

---

change_log/next/filterable.yml
package-lock.json
src/components/filterable/__snapshots__/filterable-item.spec.js.snap
src/components/filterable/__snapshots__/filterable.spec.js.snap
src/components/filterable/__snapshots__/with-filterable-item.spec.js.snap
src/components/filterable/filterable-item.component.js
src/components/filterable/filterable-item.spec.js
src/components/filterable/filterable.component.js
src/components/filterable/filterable.context.js
src/components/filterable/filterable.spec.js
src/components/filterable/index.js
src/components/filterable/with-filterable-item.hoc.js
src/components/filterable/with-filterable-item.spec.js

Filterable component has been added, this component allows you to make a list of components that will only render for a given filter value.

Filterable component

---

package.json

fix for an error when running "npm start" command on Windows environment

fix for "npm start" failing on windows

---

package-lock.json
src/components/pill/pill.scss

Fixes QA issues where hover for close icon was positioned inconsistently across browsers

Fe 1187 add delete state to pill component

---

demo/views/pages/sandbox/index.js

fixed sandbox

---

package-lock.json

This reverts some things that were upgraded but broke webpack-dev-server

reset package-lock to 6.1.0 and re-ran npm install

---

change_log/next/basic-input-type-declarations.yml
src/components/button/button.d.ts
src/components/decimal/decimal.d.ts
src/components/flash/flash.d.ts
src/components/input-definition.d.ts
src/components/link/link.d.ts
src/components/number/number.d.ts
src/components/textbox/textbox.d.ts
src/utils/helpers/options-helper/option-helper.d.ts
src/utils/validations/validator.d.ts

New TypeScript type declarations for the following components:
- Textbox
- Numeric
- Decimal
Generic interface added for Validators
InputProps interface added aligned with the content of `demo/utils/definition/input-definition/input-definition.js`

Type declarations for texbox, numeric and decimal components

---

change_log/v6_3_2/multi-select-pill-max-width.yml
release_notes/v6_3_2.html.md
src/__experimental__/components/select/__snapshots__/select.spec.js.snap
src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.style.scss

Sets a pill's max-width in multi select component to 170px.

sets max-width of pills in multi-select

---

.storybook/config.js
src/__experimental__/components/input/input-presentation.spec.js
src/__experimental__/components/input/input-presentation.style.js
src/__experimental__/components/select/select.stories.js
src/__experimental__/components/textbox/textbox.stories.js

Updates the props used for validation messages to not conflict with the props used for applying validations to components (eg. `info` vs `infoMessage`).
This PR does not require release notes as it is a bug fix for an unreleased component in master.

resolves border color for experimental inputs

---

change_log/next/mocdate-package.yml
package-lock.json
package.json
src/components/date/date.component.js
src/components/date/date.spec.js

Fixes bugs in unit tests for date component. Mock date to avoid generate different today day in the snapshot.

FE-1223 - fix for fail unit test

---

src/components/date/__snapshots__/date.spec.js.snap
src/components/date/day-picker-classic.style.js
src/style/themes/classic/classic-theme.config.js

removes text color overwrite in classic theme

FE-1223 - removes text color overwrite in classic theme

---

.vscode/launch.json

Enables the debugger in vscode to perform more accurately.

fixes vscode debugger

---

.storybook/__helpers__/components/app-layout/app-layout.js

Generic theme in storybook

---

cypress/integration/fieldset.feature
cypress/integration/filterComponent.feature
cypress/integration/flash.feature
cypress/locators/filter/index.js
cypress/locators/filter/locators.js
cypress/locators/flash/index.js
cypress/locators/flash/locators.js
cypress/locators/legend/index.js
cypress/locators/legend/locators.js
cypress/support/step-definitions/fieldset-steps.js
cypress/support/step-definitions/filter-component-steps.js
cypress/support/step-definitions/flash-steps.js

**Added to testing scope:**
- Fieldset,
- Filter,
- Flash

add Flash component tests

---

cypress.json
cypress/README.md
cypress/integration/confirm.feature

resolve @ignore tag for cypress

resolve @ignore tag for cypress

---

src/__experimental__/components/decimal/decimal.component.js

Adds data-component attribute to Experimental Decimal component for Cypress testing.

Adds Data Component Attribute to Decimal

---

src/__experimental__/components/decimal/decimal.component.js
src/__experimental__/components/decimal/decimal.spec.js

Updates Decimal Component - Prevents user from being to enter curly braces. Also updates specs for invalid character entry.

Fe 1514 no curlybraces in decimal

---

src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
src/__experimental__/components/date/date-picker.component.js
src/__experimental__/components/date/day-picker-classic.style.js
src/__experimental__/components/date/day-picker.style.js
src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
src/__experimental__/components/form-field/form-field.style.js

Fixed wrong styling in experimental datepickers

---

cypress/integration/alert.feature
cypress/integration/button.feature
cypress/integration/buttonToggleGroup.feature
cypress/integration/checkbox.feature
cypress/integration/confirm.feature
cypress/integration/decimal.feature
cypress/integration/dialog.feature
cypress/integration/dialogFullScreen.feature
cypress/integration/dropdown.feature
cypress/integration/flash.feature
cypress/locators/confirm/index.js
cypress/locators/confirm/locators.js
cypress/locators/content/index.js
cypress/locators/detail/index.js
cypress/locators/detail/locators.js
cypress/locators/dialog-full-screen/locators.js
cypress/locators/dropdown/index.js
cypress/locators/flash/index.js
cypress/locators/flash/locators.js
cypress/locators/index.js
cypress/locators/legend/index.js
cypress/locators/legend/locators.js
cypress/locators/locators.js
cypress/support/step-definitions/button-steps.js
cypress/support/step-definitions/button-toggle-group-steps.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/confirm-steps.js
cypress/support/step-definitions/deatil-steps.js
cypress/support/step-definitions/fieldset-steps.js
cypress/support/step-definitions/flash-steps.js

improve checkbox locators with getKnobsInput() method

improve checkbox locators with getKnobsInput() method

---

cypress/integration/i18nComponent.feature
cypress/locators/i18n/index.js
cypress/locators/i18n/locators.js
cypress/support/step-definitions/i18n-steps.js

add i18 compotent test

---

.travis.yml
webpack.config.js

This ensures the assets reference absolute URLs, which will resolve missing font/icon issues in CodePen examples.

fix assets prefix

---

src/components/table/table.stories.js

Fixes issue where page sizes were all the same so records exceeded the total records value

adds ternaries to set start and end index for pagination

---

src/components/table/draggable-table-cell/draggable-table-cell.component.js
src/components/table/table.component.js
src/components/table/table.stories.js
src/components/table/table.style.js

Surfaces the `sortOrder` and `sortColumn` props in Storybook

Sort props not surfaced in storybook

---

src/components/table/table.stories.js

Ensures that both columns are sortable in storybook

adds sortable prop to code column

---

src/components/table/table-modern.style.js
src/components/table/table-sizes.style.js
src/components/table/table.component.js
src/components/table/table.style.js

Adds rowTotal and rowHeight props to table wrapper to calculate its minimum height

Adds props to wrapper to calc min height

---

src/components/table/table.stories.js

Fixes defect that only sorted data per page and not the whole data set

Ensure all table data is sorted not just active page

---

src/components/table/__snapshots__/table.spec.js.snap
src/components/table/table-modern.style.js
src/components/table/table.component.js
src/components/table/table.spec.js

Table wrapper sizing was preventing shrink prop styling on table. Now passing the shrink prop to wrapper as well to allow it to toggle whether it calls the sizing function or not

fix wrapper sizing when shrink prop set

---

src/components/table/table-header/table-header.component.js
src/components/table/table-header/table-header.spec.js
src/components/table/table-header/table-header.style.js
src/components/table/table.component.js
src/components/table/table.spec.js
src/components/table/table.stories.js

Adds an optional width prop to the Header component to allow a developer to statically size the column

Add width prop to header component

---

src/components/table/__snapshots__/table.spec.js.snap
src/components/table/table-modern.style.js
src/components/table/table-sizes.style.js
src/components/table/table.component.js
src/components/table/table.spec.js
src/components/table/table.style.js

Fixes defect in storybook where table wrapper doesn't adjust it's height when the table resizes

removes inline style, passes prop to styled wrap

---

change_log/next/dependency-updates-for-v7-3-0.yml
package-lock.json
package.json

Updates the axios and highcharts dependencies and bumps version number

Updates axios and highcharts

---

src/components/table/table.stories.js

Fixes defect where pageSize caused incorrect currentPage value

Adjust current page between table stories

---

cypress/integration/table.feature
cypress/integration/tableAjax.feature
cypress/integration/tabs.feature
cypress/locators/table/index.js
cypress/locators/table/locators.js
cypress/locators/tabs/index.js
cypress/locators/tabs/locators.js
cypress/support/step-definitions/pager-steps.js
cypress/support/step-definitions/pod-steps.js
cypress/support/step-definitions/table-steps.js
cypress/support/step-definitions/tabs-steps.js

add table component scenario

---

change_log/v7_4_0/bump-carbon-factory-version.yml
package-lock.json
package.json
release_notes/v7_4_0.html.md

Mergeback for release of v7.4.0

Mergeback v7.4.0

---

cypress.env.json
cypress/features/build/build.feature
cypress/features/sanity/sanity.feature
cypress/locators/build/index.js
cypress/locators/index.js
cypress/locators/sanity/index.js
cypress/locators/sanity/locators.js
cypress/support/helper.js
cypress/support/step-definitions/build-steps.js
cypress/support/step-definitions/sanity-steps.js

**Added build and sanity tags and specs**

Added build and sanity tags and specs

---

src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
src/components/button-toggle-group/button-toggle-group.component.js
src/components/button-toggle/__snapshots__/button-toggle.spec.js.snap
src/components/button-toggle/button-toggle.component.js
src/components/inline-inputs/inline-inputs.js
src/components/mount-in-app/mount-in-app.js
src/components/row/__snapshots__/__spec__.js.snap
src/components/row/row.js
src/components/step-sequence/__snapshots__/step-sequence.spec.js.snap
src/components/step-sequence/step-sequence-item/__snapshots__/step-sequence-item.spec.js.snap
src/components/step-sequence/step-sequence-item/step-sequence-item.component.js
src/components/step-sequence/step-sequence.component.js

- Add missing `data-component=""` attr to the following components:
- button toggle group
- button toggle
- inlineInputs
- mount-in-app
- row
- step-sequence-item
- step-sequence

FE-1675 - [Add missing data-component attr]

---

src/components/pager/__snapshots__/pager.spec.js.snap
src/components/pager/pager-navigation.component.js
src/components/pager/pager-navigation.spec.js
src/components/pager/pager.component.js
src/components/pager/pager.stories.js
src/components/pager/pager.styles.js

Adds label to input, sets cursor for disabled buttons, removes `withTheme()` HOC from Pager and uses callback instead to identify theme

Fixes accessibility defects in Pager component

---

cypress/features/build/build.feature
cypress/features/sanity/sanity.feature

uncomment components after adding attributes

---

change_log/v7_4_1/update-dependencies-for-v7_4_1.yml
package-lock.json
package.json
release_notes/v7_4_1.html.md
src/components/flash/__spec__.js
src/style/themes/large/large.spec.js

Updates carbon-factory (v7.4.1) and carbon-state-management (v0.1.6).
Bumps version number for release of v7.4.1 and generates notes
Removes `focus` from test as it was skipping the rest of the specs in the file

update state-management, gen release notes

---

cypress/locators/index.js
cypress/support/helper.js
cypress/support/step-definitions/sanity-steps.js
cypress/support/step-definitions/textbox-steps.js

FE-1670 second phase of maintenance

---

cypress/features/sanity/sanity.feature
cypress/locators/index.js
cypress/support/helper.js
cypress/support/step-definitions/sanity-steps.js

reverting two methods for a click into accessibility tests and reRun tests for a sanity tests

revert for a sanity tests

---

change_log/next/FE-1288-apply-new-validation.yml
change_log/next/FE-1561-textarea-validation.yml
src/__experimental__/components/input/input-presentation.spec.js
src/__experimental__/components/input/input-presentation.style.js
src/__experimental__/components/textarea/__snapshots__/textarea.spec.js.snap
src/__experimental__/components/textarea/textarea-input.component.js
src/__experimental__/components/textarea/textarea.component.js
src/__experimental__/components/textarea/textarea.spec.js
src/__experimental__/components/textarea/textarea.stories.js
src/__experimental__/components/textarea/textarea.style.js
src/__experimental__/components/textbox/__snapshots__/textbox.spec.js.snap
src/components/button-toggle-group/__snapshots__/button-toggle-group.spec.js.snap
src/components/validations/__snapshots__/with-validation.spec.js.snap
src/components/validations/form-with-validations.hoc.js
src/components/validations/validation-icon.component.js
src/components/validations/validations.stories.js
src/components/validations/with-validation.hoc.js
src/components/validations/with-validation.spec.js
src/utils/helpers/options-helper/options-helper.js

Added the validation HOC to the Textarea component

FE-1561 textarea validation

---

src/__experimental__/components/select/__snapshots__/select.spec.js.snap
src/__experimental__/components/select/select.component.js
src/style/themes/base/base-theme.config.js

Fixes missing right border on select component.

FE-1795 right border

---

src/__experimental__/components/select/select.stories.js

Minor correction to follow naming conventions

FE-1801 changed story naming to follow conventions

---

src/__experimental__/components/select/select.component.js

Removes the console error when the select value is cleared.

FE-1810 select warning bug

---

change_log/v8_1_0/update-to-carbon-factory-v801.yml
package-lock.json
package.json
release_notes/v8_1_0.html.md

Merge back for v8.1.0 into release-candidate

Merge back for v8.1.0

---

src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.stories.js

Add default values for Select component story.

FE-1813 Select component - undefined values bug

---

src/__experimental__/components/form-field/form-field.component.js
src/__experimental__/components/label/label.spec.js
src/__experimental__/components/label/label.style.js

apply error colour to label component

FE-1807 apply error color to label

---

src/__experimental__/components/form-field/__snapshots__/form-field.spec.js.snap
src/__experimental__/components/form-field/form-field.style.js

- Fix for IE11
- Update snapshot

[BUG] FE-1805 - Experimental Form - IE11 - Labels are not inline

---

cypress/features/accessibility/accessibility.feature
cypress/locators/accessibility/index.js
cypress/locators/accessibility/locators.js
cypress/locators/index.js
cypress/locators/locators.js
cypress/support/helper.js
cypress/support/step-definitions/accessibility-steps.js
cypress/support/step-definitions/message-steps.js

adjust accessibility tests to docker

---

src/__experimental__/components/select/select.stories.js

Adds a default value to the `labelAlign` knob that is passed as prop to `FormField`

fixes warnings for labeAlign

---

src/__experimental__/components/select/select.stories.js

FE-1824 select - escape HTML

---

src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.stories.js

add aria-label for select component

FE-1823- add aria-label for select

---

src/__experimental__/components/select/__snapshots__/select.spec.js.snap
src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.spec.js
src/__experimental__/components/select/select.style.js
src/components/pill/pill.component.js

fix accessibility violation issues for Select component

FE-1826 multiselect accessibility violations

---

.gitignore

.vscode is a local store for visual studio code IDE config

added .vscode/ directory to .gitignore file

---

cypress/features/regression/button.feature
cypress/features/regression/buttonToggle.feature
cypress/features/regression/buttonToggleGroup.feature

fixed sizes for Docker in bdd specs:
- button
- buttonToggle
- buttonToggleGroup

fix sizes for Docker in bdd specs

---

change_log/next/FE-1777-select-validation-story.yml
src/__experimental__/components/select/documentation/index.js
src/__experimental__/components/select/documentation/info-validations.js
src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.stories.js
src/components/validations/with-validation.hoc.js

* Created a new Storybook story: **Experimental > Select > validations**.
* Removed non-functional props from all `<Select>` stories: `errorMessage`, `infoMessage`, `warningMessage`.

FE-1777 Validation story for Select component

---

cypress/README.md

Cypress/fe 1718 updating the readme.md file for cypress

Cypress/fe 1718 updating the readme.md file for cypress

---

cypress/features/regression/pages.feature
cypress/features/regression/textarea.feature
cypress/support/step-definitions/text-area-steps.js

unignored test cases after fixing FE-1761 for Pages component

unignored test cases after fixing FE-1761

---

cypress/features/regression/loader.feature
cypress/support/step-definitions/loader-steps.js

fixes step for loader, renamed feature file

fixes step for loader, renamed feature file

---

cypress/support/index.js
package-lock.json
package.json

update cypress cucumber and disable screenshots and reporting

---

src/components/pill/pill.stories.js

Fix filter of knobs for classic story

FE-1898 redundant knobs

---

.storybook/sageTheme.js
package.json

* Carbon logo needs to use a relative path
* Build step needs to include .assets folder

Ensure storybook compiles correctly for deployment

---

cypress/plugins/index.js

fix memory leak

---

Dockerfile-cypress

fix for importing for docker

---

change_log/next/add-isPassiveData-prop-to-table.yml
src/components/table/__spec__.js
src/components/table/table-cell/table-cell.scss
src/components/table/table-row/table-row.js
src/components/table/table.js

Adds prop that allows table data to be rendered passively with no hover styling applied to the rows

adds passive config prop to table context

---

src/__experimental__/components/checkable-input/checkable-input.spec.js
src/__experimental__/components/checkable-input/checkable-input.style.js
src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
src/components/help/help.style.js
src/components/icon/icon.component.js
src/components/icon/icon.style.js

Fixes the alignment of the label and icon in the checkable input components.
QA and UX can look at in main Icon branch

Fixes align of icon and label in checkable input

---

cypress/features/regression/configurableItems.feature
cypress/features/regression/dialog.feature
cypress/locators/decimal/locators.js
cypress/locators/form/index.js
cypress/locators/form/locators.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/form-steps.js
src/components/form/form.component.js

Fix failing cypress tests:
decimal.feature
decimalPrecision.feature
form.feature

Fix failing cypress tests

---

change_log/v8_1_1/add-isPassiveData-prop-to-table.yml
change_log/v8_1_1/tabs_new_prop.yml
package-lock.json
release_notes/v8_1_1.html.md
src/components/table/table-row/table-row.component.js
src/components/table/table.component.js
src/components/table/table.spec.js
src/components/tabs/__definition__.js
src/components/tabs/tabs.component.js
src/components/tabs/tabs.spec.js

Mergeback of changes from release of v8.1.1

changes from release of v8.1.1

---

change_log/next/date_allows_empty_value.yml
change_log/next/date_position_picker.yml
src/components/date/__definition__.js
src/components/date/__spec__.js
src/components/date/date.js

When the value is string.Empty, the visible value is also empty (and not the date of today)
The datePickerValue is set to today so the datePicker does not crash.
With the prop showPickerOnTop, the datePicker will appear above the input

Date component - The visible value is empty if the value is empty

---

change_log/next/FE-1918-fix-stickyfooter-in-dialog.yml
src/components/confirm/confirm.classic.style.js
src/components/confirm/confirm.stories.js
src/components/dialog/__snapshots__/dialog.spec.js.snap
src/components/dialog/dialog.style.js

Implements styled component for form footer to fix missing sticky footer in dialog

Fixes missing sticky footer in dialog

---

change_log/v8_1_3/update-to-latest-carbon-factory.yml
package-lock.json
package.json
release_notes/v8_1_3.html.md

Updates to latest carbon-factory v8.0.2 to fix critical security vulnerability in es-lint

Updates carbon-factory and bumps version with notes for release

---

change_log/v9_0_0/FE-1943-showeditpod-wranings.tml
src/components/show-edit-pod/show-edit-pod.js
src/components/show-edit-pod/show-edit-pod.stories.js

FE-1943 fixed console warnings.

---

change_log/next/position_date_picker.yml
src/components/date/__definition__.js
src/components/date/__spec__.js
src/components/date/date.js
src/utils/helpers/options-helper/options-helper.js

With the prop positionDatePicker, the user can choose where he wants to display the datePicker.

Date component - Position of date picker

---

change_log/v8_1_5/fix_path.yml
package-lock.json
package.json
release_notes/v8_1_5.html.md
src/components/date/__definition__.js
src/components/date/date.js

Fix file path and cut v8.1.5

---

cypress/features/regression/button.feature
cypress/features/regression/buttonToggle.feature
cypress/features/regression/buttonToggleChangeIconPart1.feature
cypress/features/regression/buttonToggleChangeIconPart2.feature

fix for the TeamCity for regression suite

fix for the TeamCity

---

change_log/next/FE-2033.yml
src/components/heading/__spec__.js
src/components/heading/heading.js
src/components/pages/pages.component.js
src/components/pages/pages.stories.js

Fixes for:
- switching between pages
- missing focus event on IE

FE-2033 - Animation Issue

---

change_log/v8_1_4/position_date_picker.yml
change_log/v8_1_5/fix_path.yml
release_notes/v8_1_4.html.md
release_notes/v8_1_5.html.md
src/__deprecated__/components/date/__definition__.js
src/__deprecated__/components/date/date.component.js
src/__deprecated__/components/date/date.spec.js
src/utils/helpers/options-helper/options-helper.js

Merges changes from `v8.1.4` and `v8.1.5` into master branch

Merge back for v8 releases

---

src/components/table/draggable-table-cell/draggable-table-cell.spec.js
src/components/table/draggable-table-cell/draggable-table-cell.style.js
src/components/table/table-row/__snapshots__/table-row.spec.js.snap
src/components/table/table-row/table-row.component.js
src/components/table/table-row/table-row.spec.js
src/components/table/table-row/table-row.style.js

Fix styling of draggable table cell icon cursor.
Fix setting of base theme by moving it from component to style

FE-1569 fix table classic

---

src/__experimental__/components/switch/switch.stories.js

Turn off escapeHTML for stories

FE-2051 char encoding

---

src/__experimental__/components/radio-button/radio-button.stories.js

- added edit possibility to the Radio Component

FE-2058 - [Radio Button] - lack of edit possibility 

---

src/__experimental__/components/switch/switch.stories.js

- removed not more necessary label field

2052-label

---

src/__experimental__/components/checkbox/checkbox-classic.style.js

FE-1728 validate icon size

---

src/__experimental__/components/checkbox/checkbox.stories.js

FE-2065-checkbox story

---

src/__experimental__/components/radio-button/radio-button.stories.js

Groups the knobs so there is more granular control over each component
Add a help label to non-validation stories

FE-2057 radio validation story refactor

---

src/__experimental__/components/switch/documentation/info-validations.js

fix validations information copy

FE-2071 switch validations text

---

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
src/__experimental__/components/checkbox/checkbox.stories.js
src/__experimental__/components/checkbox/checkbox.style.js

FE-2073 checkbox labels

---

src/__experimental__/components/switch/switch.stories.js

FE-2085 - Console Error

---

src/components/drag-and-drop/custom-drag-layer/custom-drag-layer.style.js
src/components/table/draggable-table-cell/draggable-table-cell.style.js
src/components/table/table-row/__snapshots__/table-row.spec.js.snap
src/components/table/table-row/table-row.style.js

FE-2083-mouse-cursor-issue

---

change_log/next/FE-2131-outline-for-validation.yml
src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
src/components/help/help.style.js

Fixed incorrect validation icon outline

FE-2131 Outline for validation icons

---

cypress/README.md
cypress/features/regression/experimental/textboxValidations.feature
cypress/features/regression/experimental/textboxValidationsClassic.feature
cypress/support/step-definitions/common-steps.js

Added tests for classic and default textbox validations stories
- checkout cypress/FE-2146-validation-textbox branch
- run npm run storybook
- run npm run test-cypress-build

Cypress/FE-2146 added classic/ default textbox validations component stories

---

change_log/next/FE-2151-radio-button-children-prop-warn.yml
src/__experimental__/components/radio-button/radio-button.component.js
src/__experimental__/components/radio-button/radio-button.spec.js

Added propType warning for forbidden children prop.

FE-2151 RadioButton should warn when using children prop instead of label

---

change_log/next/FE-2153-focus-icon-third-click.yml
src/__deprecated__/components/form/__snapshots__/form.spec.js.snap
src/__deprecated__/components/form/form-summary/form-summary.spec.js
src/__deprecated__/components/form/form-summary/form-summary.style.js
src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
src/__experimental__/components/checkbox/checkbox-svg.component.js
src/__experimental__/components/checkbox/checkbox.spec.js
src/__experimental__/components/checkbox/checkbox.style.js
src/__experimental__/components/form/__snapshots__/form.spec.js.snap
src/style/themes/base/base-theme.config.js

Removed border radius on validation pod
updated styling of checkbox tick/checkmark

Fe 2166 checkbox validation imp

---

change_log/next/fe-2228-add-tags-for-flash.yml
cypress/features/build/build.feature
src/components/flash/flash.component.js
src/components/flash/flash.spec.js
src/components/toast/toast.component.js

DLS Flash component currently only displays 'toast', refactored to support this being overriden and added a test

FE-2228 add tags to flash

---

cypress/features/regression/validations/checkboxValidations.feature
cypress/features/regression/validations/checkboxValidationsClassic.feature
cypress/features/regression/validations/dateInputValidations.feature
cypress/features/regression/validations/dateInputValidationsClassic.feature
cypress/features/regression/validations/radioButtonValidations..feature
cypress/features/regression/validations/radioButtonValidationsClassic.feature
cypress/features/regression/validations/selectValidationClassic.feature
cypress/features/regression/validations/selectValidations.feature
cypress/features/regression/validations/switchValidations.feature
cypress/features/regression/validations/switchValidationsClassic.feature
cypress/features/regression/validations/textareaValidations.feature
cypress/features/regression/validations/textareaValidationsClassic.feature
cypress/features/regression/validations/textboxValidations.feature
cypress/features/regression/validations/textboxValidationsClassic.feature
cypress/features/regression/validations/validationsBasic.feature
cypress/features/regression/validations/validationsBasicClassic.feature
cypress/locators/checkbox/index.js
cypress/locators/checkbox/locators.js
cypress/locators/radioButton/index.js
cypress/locators/radioButton/locators.js
cypress/support/step-definitions/checkbox-steps.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/radio-button-steps.js
cypress/support/step-definitions/validations-steps.js

Added tests for checkbox and radio button validations components

Cypress/FE-2160 Checkbox and RadioButton validations components

---

cypress/features/regression/experimental/select.feature
cypress/features/regression/experimental/selectClassic.feature
cypress/features/regression/experimental/textarea.feature
cypress/features/regression/experimental/textareaClassic.feature
cypress/locators/textarea/index.js
cypress/support/step-definitions/select-steps.js
cypress/support/step-definitions/text-area-steps.js

1. Select
- classic
2. Textarea
- default

Cypress/FE-2258 select / textarea

---

change_log/next/FE-2233-action-popover-lack-of-attributes.yml
src/components/action-popover/action-popover.component.js
src/components/action-popover/action-popover.spec.js
src/components/action-popover/action-popover.style.js

Added data attributes:
ActionPopover button - `data-component="action-popover-button"`
ActionPopover content - `data-component="action-popover"`
ActionPopover divider - `data-element="action-popover-divider"`

FE-2233 - ActionPopover - lack of data attributes

---

cypress/features/regression/experimental/form.feature
cypress/features/regression/experimental/formClassic.feature
cypress/locators/form/index.js
cypress/locators/form/locators.js
cypress/support/step-definitions/form-steps.js

added experimental form features

added Experimental Form features

---

change_log/next/FE-2132-configurable-items-wrong-cursor.yml
src/components/configurable-items/configurable-item-row/configurable-item-row.style.js

Fixed wrong cursor when dragging or hovering configurable items

FE-2132 - Configurable items wrong cursor

---

cypress/locators/create/index.js
cypress/locators/create/locators.js
cypress/locators/locators.js
cypress/support/step-definitions/create-steps.js
cypress/support/step-definitions/heading-steps.js
cypress/support/step-definitions/themes-steps.js

added fixes for Link component due to changes in FE-2159

updated tests for Link component

---

change_log/next/FE-2082-tables-wrong-pagination-behaviour.yml
src/components/pager/pager-navigation.component.js
src/components/pager/pager-navigation.spec.js

Fixed an issue with wrong table pagination behaviour where it was possible to navigate to further pages even though only one page is available.

FE-2082 - Table - wrong pagination behaviour

---

cypress/features/regression/link.feature
cypress/locators/link/index.js
cypress/locators/pod/locators.js
cypress/locators/show-edit-pod/locators.js
cypress/plugins/index.js
cypress/support/step-definitions/form-steps.js
cypress/support/step-definitions/link-steps.js
cypress/support/step-definitions/pod-steps.js
cypress/support/step-definitions/show-edit-pod-steps.js
docker-compose-cypress.yml

updated regression files after link merge

updated regression files after link merge

---

demo/utils/site-map-helper/generate-menu/generate-menu.js

Ensure storybook link is followed by making it a proper link

Ensure storybook link is followed

---

change_log/next/FE-2323-select-onBlur-fires-while-removing-option.yml
src/__experimental__/components/select/__snapshots__/select.spec.js.snap
src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.spec.js

Fixes unnecessary onBlur triggering while removing selected items in multi-select mode

FE-2323 - Fixed incorrect onBlur behaviour in Select component

---

change_log/next/FE-2367-pages-backlink-label-misalignment.yml
src/components/pages/page/page.style.js

Fixed Pages component backlink and header label misalignment on classic story.

FE-2367 - Fixed backlink and label misalignment

---

fixtures/src/components/controlled/date-range.js
src/__deprecated__/components/date/date.stories.js
src/__experimental__/components/date-range/date-range.component.js
src/__experimental__/components/date-range/date-range.spec.js
src/__experimental__/components/date-range/date-range.stories.js
src/__experimental__/components/date/date.component.js
src/__experimental__/components/date/date.spec.js
src/__experimental__/components/date/date.stories.js
src/__experimental__/components/textbox/textbox.component.js
src/components/validations/with-validation.hoc.js
src/utils/helpers/date/date.js

Fixes in this PR:
FE-2243 DateRange - onChange does not fire correctly
FE-2250 Validations no longer work on date range
FE-2235 Date Range does not work for uncontrolled
FE-2244 DateRange - onBlur does not fire correctly

Various bug fixes for the DateRange Component

---

change_log/next/select-left-children.yml
src/__experimental__/components/select/select.component.js
src/__experimental__/components/select/select.spec.js

feat: leftchildren property added to select

---

change_log/next/FE-2394-add-hidden-input-to-date.yml
src/__experimental__/components/date-range/date-range.spec.js
src/__experimental__/components/date/date.component.js
src/__experimental__/components/date/date.spec.js

```
New Features:
- Adds hidden input with raw value in experimental Date (Component: Date)
```

FE-2394 add hidden input to date

---

change_log/next/FE-2414-action-popover-prevent-propagation.yml
src/components/action-popover/action-popover.component.js
src/components/action-popover/action-popover.spec.js

Stopped further event propagation in ActionPopover

FE-2414 ActionPopover menu button event propagation

---

Dockerfile-cypress
package-lock.json
package.json

upgraded cypress version

---

change_log/next/upgrade-carbon-factory-to-v9-0-1.yml
package-lock.json
package.json

`carbon-factory` has been updated to `v9.0.1` to fix security warnings

Update to carbon factory v9.0.1

---

src/components/inline-inputs/inline-inputs.stories.js
src/components/validations/textbox-validations.stories.js

Updates to two stories that currently don't work due to the breaking API changes made in #2513
```
docs: update inline input story for decimal FE-2460
docs: update textbox validations story for decimal FE-2460
```

docs: update decimal stories FE-2460

---

change_log/v11_0_1/revert-carbon-factory.yml
package-lock.json
package.json
release_notes/v11_0_1.html.md

Hot fix as v11 has a broken `precompile` step and cannot deploy

Fix v11 after  broken deploy

---

change_log/next/FE-2477-wrong-cursor-type-link-component.yml
src/components/dismiss-button/__snapshots__/dismiss-button.spec.js.snap
src/components/link/__snapshots__/link.spec.js.snap
src/components/link/link.style.js

Fixed incorrect cursor on focused link component.

FE-2477 Incorrect cursor on focused link component

---

change_log/next/FE-2474-upgrade-to-carbon-factory-v11.yml
package-lock.json
package.json

Upgrades to `carbon-factory` `v11.0.0` to fix security warnings

FE-2474 upgrade to carbon factory v11

---

.travis.yml
change_log/next/npm-lint-script.yml
package.json

It allows running linter on `./src` and `./fixtures` directory

Update lint script

---

change_log/next/FE-2450-Add_src_prop_to_Profile_component.yml
src/components/profile/docgenInfo.json
src/components/profile/profile.component.js
src/components/profile/profile.config.js
src/components/profile/profile.spec.js
src/components/profile/profile.stories.js
src/components/profile/profile.style.js

adds support for src prop in Profile image

FE-2450 adds support for src prop in Profile

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

This PR adds a feature request template. When users create a new issue they can choose from this template or a blank one.

chore: feature request template FE-2023

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

Fixed capitalisation in the bug template.

chore: capitalisation FE-2023

---

.github/PULL_REQUEST_TEMPLATE.md

This PR updates the pull request template. It adds more items to the checklist and updates the headings to match the issue template.
Before this change the pull request template only asked for release notes.
<del>- [ ] Release notes (renogen)</del>
#2578 #2580 
You can preview this by looking at the markdown file in this PR.

chore: pull request template FE-2023

---

README.md
cypress/README.md

docs: add testing strategy 

---

cypress/features/regression/dialog.feature
cypress/features/regression/dialogClassic.feature
cypress/locators/dialog/index.js
cypress/support/index.js
cypress/support/step-definitions/dialog-steps.js

<del> - [ ] Release notes (Conventional Commits)  </del>
<del> - [ ] Storybook added or updated </del>
<del> - [ ] Theme support </del>
<del> - [ ] Typescript `d.ts` file added or updated </del>
run `./node_modules/.bin/cypress run --spec './cypress/features/regression/dialog*' --reporter spec --browser chrome`

test(dialog): add tests to dialog suite

---

cypress.env.json
cypress/features/regression/table.feature
cypress/features/regression/tableClassic.feature
cypress/features/regression/tableWithInputs.feature
cypress/features/regression/toast.feature
cypress/features/regression/toastClassic.feature
cypress/locators/pager/locators.js
cypress/locators/table/index.js
cypress/locators/table/locators.js
cypress/locators/toast/index.js
cypress/locators/toast/locators.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/table-steps.js
cypress/support/step-definitions/toast-steps.js

add cypress tests for default stories and refactor for classic stories related to table, toast and
table with inputs component
FE-2359
<del> - [ ] Release notes (Conventional Commits)  <del>
<del>  - [ ] Unit tests <del>  
<del>  - [ ] Storybook added or updated <del>  
<del>  - [ ] Theme support <del>  
<del>  - [ ] Typescript `d.ts` file added or updated <del>  
add table, toast and table with input tests
run: ./node_modules/.bin/cypress run --spec './cypress/features/regression/table*.feature', './cypress/features/regression/toats*.feature' --reporter spec

test(table, tablewithinputs, toast): add cypress tests for default

---

cypress.env.json
cypress/features/regression/create.feature
cypress/features/regression/createClassic.feature
cypress/features/regression/dialogFullScreen.feature
cypress/features/regression/dialogFullScreenWithStickyFooter.feature
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/create-steps.js
cypress/support/step-definitions/dialog-full-screen-steps.js

<del> - [ ] Release notes (Conventional Commits)  </del> 
<del> - [ ] Unit tests </del> 
<del> - [ ] Storybook added or updated </del> 
<del> - [ ] Theme support </del> 
<del> - [ ] Typescript `d.ts` file added or updated </del> 
add missing tests for Dialog fullscreen and for Create components
run `npm run test-cypress` and run separate feature files

test(create): add missing tests, add classic feature (FE-2348)

---

cypress/features/regression/pager.feature
cypress/features/regression/pagerClassic.feature
cypress/features/regression/pages.feature
cypress/features/regression/pill.feature
cypress/features/regression/pillClassic.feature
cypress/features/regression/table.feature
cypress/features/regression/tableClassic.feature
cypress/locators/pager/index.js
cypress/locators/pager/locators.js
cypress/locators/pill/locators.js
cypress/locators/table/index.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/pager-steps.js
cypress/support/step-definitions/pill-steps.js
cypress/support/step-definitions/table-steps.js

add missing tests for default stories, refactor for table component
FE-2354
<del> - [ ] Release notes (Conventional Commits)  <del>
<del>  - [ ] Unit tests <del>  
<del>  - [ ] Storybook added or updated <del>  
<del>  - [ ] Theme support <del>  
<del>  - [ ] Typescript `d.ts` file added or updated <del>  
Add missing tests for Pager, Pil and Pages stories. Small refactor for Table component
run: npm run test-cypress and choose proper feature file

test(pager, pages, pill, table): add missing test cases

---

cypress/features/build/build.feature
cypress/features/regression/test/search.feature
cypress/locators/index.js
cypress/locators/locators.js
cypress/locators/search/index.js
cypress/locators/search/locators.js
cypress/support/step-definitions/common-steps.js
cypress/support/step-definitions/search-steps.js
fixtures/src/components/controlled/search.js
fixtures/src/components/uncontrolled/search.js
fixtures/src/main.js
src/__experimental__/components/input/index.d.ts
src/__experimental__/components/input/input.d.ts
src/__experimental__/components/search/docgenInfo.json
src/__experimental__/components/search/documentation/index.js
src/__experimental__/components/search/documentation/info.js
src/__experimental__/components/search/index.js
src/__experimental__/components/search/search.component.js
src/__experimental__/components/search/search.d.ts
src/__experimental__/components/search/search.spec.js
src/__experimental__/components/search/search.stories.js
src/__experimental__/components/search/search.stories.mdx
src/__experimental__/components/search/search.style.js
src/style/themes/base/base-theme.config.js

Creates a new Search component.
There is no Search component.
Fixes FE-2332
Look at the `experimental/Search` stories and the fixture for search (No. 15).

feat(search): create search component - FE-2332

---

cypress/features/accessibility/accessibility.feature

<del> - [ ] Release notes (Conventional Commits)  </del> 
<del> - [ ] Unit tests  </del>
<del> - [ ] Cypress automation tests  </del>
<del> - [ ] Storybook added or updated  </del>
<del> - [ ] Theme support  </del>
<del> - [ ] Typescript `d.ts` file added or updated  </del>
remove spinner component as it isn't in list

test(accessibility): remove spinner component as it isn't in list

---

jest.conf.json

Update the jest config so it no longer extends `carbon-factory`
Currently requires `carbon-factory` to extend the config
Required to remove `carbon-factory` dependency
Tests will not run if config is incorrect

test: update jest config

---

tsconfig.json
tslint.json

The linting and config should work as previously when they were extending from `carbon-factory'
Currently the lint and configs extend from `carbon-factory`
Part of the process of removing `carbon-factory' dependency
The steps will run as part of the build

chore: update ts lint and config files

---

babel.config.js

The new config should allow the `lib` directory to be built without extending the config in `carbon-factory`
Currently the building of the `lib` relies on extending the config from `carbon-factory`
<del>- [ ] Unit tests <del>
<del>- [ ] Cypress automation tests <del>
<del>- [ ] Storybook added or updated <del>
<del>- [ ] Theme support <del>
<del>- [ ] Typescript `d.ts` file added or updated <del>
A step in removing `carbon-factory` dependency. The required babel dependencies will be added when `carbon-factory` is removed
The build will fail if it does not transpile the code

chore: update babel config

---

cypress/README.md
docker-compose-cypress.yml

update script for run application
run:
- `./script/docker/setup.sh`
- `./script/docker/start.sh`
- `./script/docker/cypress.sh --accessibility --build`

ci(docker-compose-cypress): update script for run application

---

.storybook/manager.js
.storybook/preview.js

Provide the ga-id in `manager.js`.
The GA-ID is not currently loaded and is throwing a warning in the console.
https://github.com/storybookjs/storybook/issues/9727
`npm start` there should be no warning from `react-ga`.

docs: update ga id

---

src/components/icon-button/icon-button.style.js
src/components/message/__snapshots__/message.spec.js.snap
src/components/message/message.style.js

- remove position 'absolute' from IconButton
- set default position to IconButton

refactor(icon-button, message): position update - FE-2606

---

cypress/features/accessibility/accessibility.feature

Add new components to accessibility suite
<del> - [ ] Release notes (Conventional Commits)  </del>
<del> - [ ] Storybook added or updated </del>
<del> - [ ] Theme support </del>
<del> - [ ] Typescript `d.ts` file added or updated </del>
run `npm run test-cypress-accessibility`

test: add missing tests for accessibility suite

---

cypress.env.json
cypress/features/accessibility/accessibility.feature
cypress/features/build/build.feature
cypress/features/regression/test/anchorNavigation.feature
cypress/locators/anchor-navigation/index.js
cypress/locators/anchor-navigation/locators.js
cypress/locators/index.js
cypress/support/helper.js
cypress/support/step-definitions/anchor-navigation-steps.js
cypress/support/step-definitions/common-steps.js
src/components/anchor-navigation/anchor-navigation-item.component.js
src/components/anchor-navigation/anchor-navigation-item.d.ts
src/components/anchor-navigation/anchor-navigation.component.js
src/components/anchor-navigation/anchor-navigation.d.ts
src/components/anchor-navigation/anchor-navigation.spec.js
src/components/anchor-navigation/anchor-navigation.stories.js
src/components/anchor-navigation/anchor-navigation.stories.mdx
src/components/anchor-navigation/anchor-navigation.style.js
src/components/anchor-navigation/anchor-section-divider.component.js
src/components/anchor-navigation/anchor-section-divider.d.ts
src/components/anchor-navigation/index.d.ts
src/components/anchor-navigation/index.js
src/style/themes/base/base-theme.config.js

This PR implements new AnchorNavigation component
Test/AnchorNavigation storybook stories
Also contains fixes for FE-2581 and FE-2582

feat: add new anchor navigation component - FE-2335

---

cypress/features/accessibility/accessibility.feature
cypress/features/build/build.feature
cypress/features/regression/test/popoverContainer.feature
cypress/locators/popover-container/index.js
cypress/locators/popover-container/locators.js
cypress/support/step-definitions/popover-container-steps.js
src/components/icon-button/icon-button.component.js
src/components/icon-button/icon-button.style.js
src/components/message/message.style.js
src/components/popover-container/index.js
src/components/popover-container/popover-container.component.js
src/components/popover-container/popover-container.d.ts
src/components/popover-container/popover-container.spec.js
src/components/popover-container/popover-container.stories.js
src/components/popover-container/popover-container.stories.mdx
src/components/popover-container/popover-container.style.js
src/style/themes/base/base-theme.config.js
src/utils/helpers/events/__spec__.js
src/utils/helpers/events/events.js

feat: add new Popover Container FE-2500

---

src/__experimental__/components/search/search.stories.mdx

Search story was moved to `test` directory but the path was not updated, this updates to new location
The story as `No Preview` currently

docs(search): update id path for search story docs

---

cypress/README.md

Updated couple of steps in readme

docs(readme): update steps in readme

---

CONTRIBUTING.md

This is an update to the COLLABORATION.md file to better describe our processes today. 
Currently the COLLABORATION.md file is inaccurate and incomplete.
We will continue to add to the guidelines with styleguides for:
- Test specs
- Documentation
- JavaScript
Plus a Code of Conduct will be added.
Documentation only, no testing required.

docs(collaboration): update collaboration

---

src/components/pod/pod.stories.mdx

Address pod mdx example
1. run: npm start
2. go to: http://localhost:9001/?path=/docs/design-system-pod--address-example

docs(pod): add address pod example (FE-2632)

---

cypress/features/regression/experimental/simpleColorPicker.feature
cypress/features/regression/heading.feature
cypress/features/themes/themes.feature
cypress/locators/grid/index.js
cypress/support/helper.js
cypress/support/step-definitions/heading-steps.js
cypress/support/step-definitions/simple-color-picker-steps.js
cypress/support/step-definitions/themes-steps.js

Fix grid.feature,  simpleColorPicker.feature, themes.feature cypress tests
During the nightly regression feature file grid,  simple color picker themes failed.
run: npm run test-cypress and chose proper feature file

test(grid, simplecolorpicker): fix cypress tests

---

cypress/features/accessibility/accessibility.feature

After adding `--knobs` story to button component we need to update tests for the `accessibility` suite.
After adding `--knobs` story to button component the `accessibility` suite was failing.
run:
- `npm run test-cypress` and choose `accessibility.feature`

test(accessibility): update for button knob accessility test

---

cypress/features/regression/test/batchSelection.feature
cypress/locators/flat-table/index.js
cypress/support/step-definitions/flat-table-steps.js

Tests should pass
TC from BatchSelection and FlatTableSortable components failed during nightly regression
run: npm run test-cypress and choose proper feature file

test(batchselection, flattablesortable): fix regression failed tests

---

CONTRIBUTING.md

Clarify that third-parties should seek approval before submitting a PR.

docs(contributing): update pr guide

---

.github/PULL_REQUEST_TEMPLATE.md

A new item on the checklist to confirm alignment between DLS documentation and Carbon.
Item does not currently exist in the checklist.
This reflects updates in our definition of done.
Create a new PR and see if the item appears in the checklist.

docs(pr-template): add dls check to pull request template

---

README.md
docs/getting-started.md

Adds a getting started guide to cover the installation and setup of a new project using Carbon.
Our old getting started guide was removed in v13.7.0 so we have not provided one for some versions.
None
This is documentation and requires a read-through only.

docs(getting-started): add getting started guide

---

src/components/popover-container/popover-container.style.js

fix(popover-container): fix displaying under other components

---

.github/workflows/cypress-parallel.yml
cypress/features/accessibility/accessibilityCommon.feature
cypress/features/accessibility/accessibilityCommonSecondPart.feature
cypress/features/regression/radioButtonMonthly.feature
cypress/features/regression/radioButtonWeekly.feature
cypress/features/regression/radioButtonYearly.feature

We need to enable actions with `action` commit
We have added a `cypress-parallel.yml` file, but actions are not started by default

ci: create cypress-parallel.yml

---

cypress/README.md

Add information how to re-run jobs in `Cypress` `README.md` file
When the test run will fail on GitHub Actions - there is no possibility to re-run jobs

docs: information about re-run

---

.github/workflows/cypress-parallel.yml

Add `docker` image as `container` to make separate and unique env parameters for every `job` for each `Actions` run
Cypress tests are frequently failing because of mismatch of browser version for different containers for the same run.

ci: add specific docker container image

---

src/__experimental__/components/decimal/decimal.spec.js
src/components/action-popover/action-popover.spec.js
src/components/advanced-color-picker/advanced-color-picker.spec.js
src/components/table/table-row/table-row.spec.js

@damianOfKyan found some unnecessary code in the ActionPopover tests. Removing it makes the tests simpler to understand.
We will now store the component under test in a variable.
The component under test is stored in a property in an object.
Ensure travis build is passing.

test(action-popover): simplify tests

---

package-lock.json
package.json

Since cypress is updated to v.4.6.0 we need to be updated
Currently we have 4.4.0 cypress version

test: cypress vesion update

---

.github/workflows/cypress-parallel.yml

- Remove `container` from `cypress-parallel.yml` file as we no more use `chrome` browser in `cypress` regression;
- Update `cypress-io/github-action@v1` -> `cypress-io/github-action@v1.24.2` fix for `warnings`.
We have a lot of warnings with like reporter [here](https://github.com/cypress-io/github-action/issues/141)

ci: bump cypress action version

---

applitools.config.js

Removed `safari` and `firefox` browsers
Currently we are running `applitools` checks on 3 browsers (`chrome` / `safari` / `firefox`)

ci: remove firefox and safari

---

.dockerignore
cypress/locators/index.js
package-lock.json
package.json

- update `applitools` dependency to `3.11.1`;
- update `cypress-cucumber-preprocessor` dependency to `2.4.0`;
- remove `.dockerignore` - no more needed;
- update comment (remove mention about docker).
- Not all testing dependency are up to date; 
- Clean up repo.

test: update testing dependencies

---

CONTRIBUTING.md
docs/dev-environment-setup.md

Documentation to help new developers with setting up their development environment.
No documentation currently exists for this.
<del>[ ] Screenshots are included in the PR </del>
<del>[ ] Carbon implementation and Design System documentation are congruent</del>
<del>[ ] All themes are supported </del>
[x] Commits follow our style guide
<del>[ ] Unit tests added or updated</del>
<del>[ ] Cypress automation tests added or updated</del>
<del>[ ] Storybook added or updated</del>
<del>[ ] Typescript `d.ts` file added or updated </del>
N/A
Read through to see if the document makes sense from the point of view of a new developer.
*I have followed these instructions to complete a fresh install on an iMac (iMac is running Catalina OS) that has not previously been used for any development work. …

docs(dev environment): add documentation for initial setup

---

.github/PULL_REQUEST_TEMPLATE.md

Adds improved instructions for sharing screenshots and code samples.
Isn't clear enough about preventing sharing of confidential information.
~- [ ] Screenshots are included in the PR~
~- [ ] All themes are supported~
~- [ ] Unit tests added or updated~
~- [ ] Cypress automation tests added or updated~
~- [ ] Storybook added or updated~
~- [ ] Typescript `d.ts` file added or updated~

docs: add more details to the pr template comments

---

docs/getting-started.md

Changes the link to the codesandbox from to a version that can be forked.
current version is the embedded one.
~- [ ] Screenshots are included in the PR~
~- [ ] All themes are supported~
~- [ ] Unit tests added or updated~
~- [ ] Cypress automation tests added or updated~
~- [ ] Storybook added or updated~
~- [ ] Typescript `d.ts` file added or updated~

docs: amend codesandbox template link

---

package-lock.json
package.json

- update `cypress` dependency to `4.8.0`;
- update `cypress-cucumber-preprocessor` dependency to `2.5.0`;
- update `applitools` dependency to `3.12.0`;
- Not all testing dependency are up to date;

test(package.json): update cypress and cucumber preprocessor

---

.storybook/main.js
docs/getting-started.stories.mdx
docs/validations.stories.mdx

Add a quick guide of how to approach validations using Carbon, Formik and yup

docs(validations): add carbon validations and formik guide

---

src/components/drawer/drawer.stories.mdx

docs(drawer): create `side view navigation` example - FE-2331

---

CONTRIBUTING.md

Add documentation for long lived branches.
N/A
N/A
N/A

docs: document long lived branches

---

.github/workflows/cypress-pr.yml

Enable debug logging so we can investigate our intermittent cypress failures.
Cypress has no output apart from reporter.
https://github.community/t/action-stuck-with-no-logs/121143
Ensure github checks run on this PR.

ci(cypress): enable debug logging

---

src/components/rainbow/rainbow.component.js

This PR adds deprecation warning to the Rainbow component
<del>- [ ] Screenshots are included in the PR</del>
<del>- [ ] Carbon implementation and Design System documentation are congruent</del>
<del>- [ ] All themes are supported</del>
<del>- [ ] Unit tests added or updated</del>
<del>- [ ] Cypress automation tests added or updated</del>

chore(rainbow): add deprecation warning - FE-2899

---

.github/workflows/cypress-pr.yml

This reverts commit 8b87ae466b4f016011250d3a72c373a7a0aa719f.
Verbose logging is enabled
<del>- [ ] Commits follow our style guide
Issue raised https://github.com/cypress-io/cypress/issues/7918
N/A

ci(cypress): disable debug logging

---

.github/workflows/cypress-pr.yml
.github/workflows/cypress-push.yml
cypress/features/regression/accessibility/accessibilityDesignSystem.feature
cypress/support/helper.js
cypress/support/step-definitions/common-steps.js
package-lock.json
package.json

To be all up to date we need to:
- update `accessibilityDesignSystem.feature` file and reduce unnecessary code;
- bump version of `cypress` from `4.9.0` to `4.10.0`;
- bump version of `cypress-cucumber-preprocessor` from `2.5.0` to `2.5.4`;
- update `cypress-github-actions` from `2.2.1` to `2.2.2` (updated `ciBuildId` to `jobID`);
- add `chrome` browser in `headless` mode to increase running speed for all regression suite.
To be up to date we need to update few dependency and make the code cleaner.

test(accessibility): update feature file TCs

---

cypress/features/regression/experimental/select.feature
cypress/features/regression/experimental/selectCustomFilter.feature
cypress/features/regression/experimental/selectMultiple.feature
cypress/fixtures/experimental/select.json
cypress/locators/select/index.js
cypress/support/step-definitions/select-steps.js

- `selectMultiple` (timing: was `01:37` -> `0:37`),
- `select` (timing: was `02:04` -> `1:18`),

test(select, selectmultiple): update a new approach

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Update the wording and order of the checklist so there is no need to use `<del>` tags.
Add detail on adding screenshots from codesandbox.
Users have to update the checklist on each PR.
N/A
N/A

chore: update issue template

---

cypress/support/step-definitions/duelling-picklist-steps.js
src/components/duelling-picklist/duelling-picklist.stories.js

docs(duelling-picklist): story updates

---

src/components/drawer/drawer.stories.mdx
src/components/flat-table/flat-table.stories.mdx

Update stories for `flat-table` and `drawer`
<del>- [ ] Screenshots are included in the PR if useful<del>
<del>- [ ] All themes are supported if required<del>
<del>- [ ] Unit tests added or updated if required<del>
<del>- [ ] Cypress automation tests added or updated if required<del>
<del>- [ ] Typescript `d.ts` file added or updated if required<del>

docs(flat-table, drawer): update story

---

src/components/pill/documentation/notes.md

Update notes for `pill`
<del>- [ ] Screenshots are included in the PR if useful<del>
<del>- [ ] All themes are supported if required<del>
<del>- [ ] Unit tests added or updated if required<del>
<del>- [ ] Cypress automation tests added or updated if required<del>
<del>- [ ] Typescript `d.ts` file added or updated if required<del>

docs(pill): update notes

---

src/__experimental__/components/date/date.stories.js
src/__experimental__/components/decimal/decimal.stories.js
src/__experimental__/components/fieldset/fieldset.stories.js
src/__experimental__/components/grouped-character/grouped-character.stories.js
src/__experimental__/components/number/number.stories.js
src/__experimental__/components/numeral-date/numeral-date.stories.js
src/__experimental__/components/simple-color-picker/simple-color-picker.stories.js
src/__experimental__/components/textbox/textbox.stories.js
src/components/batch-selection/batch-selection.component.js
src/components/button-toggle-group/button-toggle-group.stories.js
src/components/carousel/carousel.stories.js
src/components/dialog/dialog.stories.js
src/components/drawer/drawer.stories.mdx
src/components/flash/flash.stories.js
src/components/popover-container/popover-container.stories.mdx
src/components/sidebar/sidebar.stories.js

This PR fixes most of the easily fixable developer errors in development mode Storybook
Unfortunately some of `Each child in a list should have a unique "key" prop` errors were not possible to be fixed because they're caused by the `Info` addon, disabling `Info` on these stories solved this problem. These errors will be gone after we migrate stories to `mdx` files.

fix(storybook): fix various story related errors - FE-2963 / FE-2966

---

cypress/features/regression/experimental/simpleColorPicker.feature
cypress/features/regression/experimental/simpleColorPickerAction.feature
cypress/fixtures/experimental/simpleColorSelect.json
cypress/locators/simple-color-picker/index.js
cypress/support/step-definitions/simple-color-picker-steps.js

add test verifying name and legend
Add a new test cases for name and legend knobs
We don't have test cases for name and legend knob

test(simplecolorpicker): add a new test cases

---

.storybook/theme-selector/index.js

Add a warning in storybook to all classic stories warning about the removal of classic theme.
No warnings
Classic has been deprecated for a long time, but we want to make it more obvious for teams new to carbon.
See chromatic storybook preview.

docs(storybook): add classic removal warning

---

package-lock.json
package.json

- updated `cypress` to version 5.2.0
- updated `cucumber-preprocessor` to version 2.5.5
We need to update:
- `cypress` to version 5.2.0 because of huge performance fix _(Fixed a performance issue which led to CPU bottlenecking during Cypress runs.)_
- `cucumber-preprocessor` to version 2.5.5

test(cypress): update version to 5.2.0

---

cypress.env.json
cypress/features/regression/accessibility/accessibilityCommon.feature
cypress/features/regression/accessibility/accessibilityDesignSystem.feature

We need to `update` / `add` accessibility tests for `added` / `moved` components to be sure that those component are covered by.

test(accessibility): update for tests

---

.github/workflows/cypress-pr.yml
.github/workflows/cypress-push.yml

-  increased the timeout for `cypress CI` yaml files from `12 min` to `15 min`
We need to increase the timeout for `cypress CI` yaml files to avoid `canceling` of the builds.

ci(cypress): update the steps timeout

---

src/__experimental__/components/label/label.spec.js
src/__experimental__/components/label/label.style.js
src/components/form/form.stories.mdx

Update typo in prop name from `childofForm` to `childOfForm`
Prop has incorrect name

fix(label): remove margin from label when input in form

---

.github/workflows/cypress-pr.yml
.github/workflows/cypress-push.yml
.github/workflows/semantic-release.yml
.github/workflows/storybook.yml

Upgrade to latest versions of third-party actions.
Mix of versions
Build will fail due to invalid secrets.
Ensure there are no syntax errors.

ci(actions): update to latest versions

---

cypress/features/regression/test/flatTableNoiFrame.feature
cypress/support/step-definitions/flat-table-steps.js
src/components/drawer/__internal__/drawer.stories.mdx
src/components/flat-table/__snapshots__/flat-table.spec.js.snap
src/components/flat-table/flat-table-head/flat-table-head.d.ts
src/components/flat-table/flat-table.component.js
src/components/flat-table/flat-table.d.ts
src/components/flat-table/flat-table.spec.js
src/components/flat-table/flat-table.stories.mdx
src/components/flat-table/flat-table.style.js

fixes #3369
Adds `footer` and `hasStickyFooter` props to support rendering content in the `FlatTable` footer and
positioning it sticky if needed. The `Box` component is now composed within the `FlatTable` to
support setting its `height` as well.
There is no support for rendering any footer content or setting the height of the table
http://localhost:9001/?path=/docs/design-system-drawer--custom-sidebar
http://localhost:9001/?path=/docs/design-system-flat-table--basic

feat(flat-table): add support for rendering table footer FE-3268

---

docs/dev-environment-setup.md

Adds instructions on enabling GPG signing of git commits.
This is not in our current documentation.
~- [ ] Screenshots are included in the PR if useful~
~- [ ] All themes are supported if required~
~- [ ] Unit tests added or updated if required~
~- [ ] Storybook added or updated if required~
Read it and test the links.

docs(dev-environment-setup): add GPG signing instructions

---

docs/dev-environment-setup.md

Update major branch with master. This is just a 12 line change to dev-environment setup docs.
Branch is out of date with current master by 3 commit
All commits have been code-reviewed and QA'd.
Build must pass.

chore(major): update dev-environment with master

---

src/utils/ether/__spec__.js
src/utils/ether/ether.js

Improve the `validProps` documentation.
It's not clear what `validProps` is doing.
Part of FE-3306
Ensure CI passes.

refactor: improve validprops documentation

---

cypress/features/regression/accessibility/accessibilityExperimental.feature
src/__experimental__/components/checkbox/checkbox.stories.js
src/__experimental__/components/checkbox/checkbox.stories.mdx
src/__experimental__/components/radio-button/radio-button.stories.mdx
src/__experimental__/components/switch/switch.stories.js
src/__experimental__/components/switch/switch.stories.mdx

- update `docs` file `(mdx)`;
- update `story` naming for `default` in `Test` directory;
- update `validation` tests for `accessibility` suite.
We need to: 
- update `docs` file `(mdx)`;
- update `story` naming for `default` in `Test` directory;
- update `validation` tests for `accessibility` suite.

test: update validation tests for experimental

---

docs/javascript-styleguide.md

Add documentation about the `variant` prop.
There is no documentation about the `variant` prop.
Discussed with rest of team.
Review markdown.

docs(styleguide): add variant explanation

---

.github/workflows/cypress-pr.yml
.github/workflows/cypress-push.yml
cypress/plugins/index.js

- There is an open [issue](https://github.com/cypress-io/cypress/issues/6540) of `cypress` repo, but we have a `workaround ` with passing an `args` - `--disable-gpu` to the `chrome` browser before it starts. 
- Update the `chrome` version for `cypress` tests to `v87`.
Currently, we have a situation when the `cypress` tests build are failing because of `Error: connect ECCONNREFUSED 127.0.0.1:9001` 
Make sure that `cypress`/`unit tests`/`lint` builds passed on CI

test: add --disable-gpu args

---

src/components/menu/menu.stories.mdx

Correct example coded in menu stories

docs(menu): correct story examples for icon menuitems

---

src/components/button-toggle-group/button-toggle-group-validations.stories.mdx

Closes #3590 
Amend the button text to "First", "Second" and "Third" for these groups in `mdx` file
The text in the buttons in the group is "Small", "Medium" and "Large". This implies there is some size property difference, which there is not.

docs: update naming for buttons

---

package-lock.json
package.json

Upgrade Chromatic to latest to patch axios vulnerability
N/A

chore(deps): upgrade chromatic

---

cypress.env.json
cypress/features/regression/test/pager.feature
cypress/support/step-definitions/pager-steps.js
src/components/pager/__internal__/pager-navigation.component.js
src/components/pager/__internal__/pager-navigation.spec.js

Fixes #3453 
Check `Design System / Pager / loading-state` story

fix(pager): fix incorrect behaviour when page count is zero - FE-3388

---

cypress/features/regression/accessibility/accessibilityDesignSystem.feature

- enable tests marked as `ignored` in `accessibilityDesignSystem.feature` file
We have few accessibility tests marked as ignored. We need to check and enable those tests.

test: unignore accessibility tests

---

CONTRIBUTING.md

Update contributing.md file with our latest workflow.
Contributing file was out of date with our workflow.
<del> - [ ] All themes are supported if required </del>
<del> - [ ] Storybook added or updated if required </del>
<del> - [ ] Carbon implementation and Design System documentation are congruent </del>
N/A
N/A

docs(contributing): update contributing doc with latest workflow

---

cypress/features/regression/designSystem/flatTable.feature
cypress/locators/flat-table/index.js
cypress/locators/flat-table/locators.js
cypress/support/step-definitions/flat-table-steps.js
src/components/flat-table/__snapshots__/flat-table.spec.js.snap
src/components/flat-table/flat-table-cell/flat-table-cell.component.js
src/components/flat-table/flat-table-cell/flat-table-cell.style.js
src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js
src/components/flat-table/flat-table-checkbox/flat-table-checkbox.spec.js
src/components/flat-table/flat-table-expandable.stories.mdx
src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
src/components/flat-table/flat-table-row/flat-table-row.component.js
src/components/flat-table/flat-table-row/flat-table-row.spec.js
src/components/flat-table/flat-table-row/flat-table-row.style.js
src/components/flat-table/flat-table.spec.js
src/components/flat-table/flat-table.style.js
src/style/themes/base/base-theme.config.js

Add expandable rows option to `FlatTable` 
No expandable rows option using `FlatTable`
http://localhost:9001/?path=/story/design-system-flat-table-expandable--default-story
http://localhost:9001/?path=/story/design-system-flat-table-expandable--both-parent-and-chidren-selectable
http://localhost:9001/?path=/story/design-system-flat-table-expandable--children-only-selectable
http://localhost:9001/?path=/story/design-system-flat-table-expandable--expandable-by-first-column-only
http://localhost:9001/?path=/story/design-system-flat-table-expandable--initially-expanded
http://localhost:9001/?path=/story/design-system-flat-table-expandable--paginated
http://localhost:9001/?path=/story/design-system-flat-table-expandable--parent-only-selectable …

feat(flat-table): add expandable rows option

---

src/components/tabs/tab/tab.component.js
src/components/tabs/tab/tab.d.ts

The validation message props are no longer required
The validation message props are required

chore(tab):  validation messages no longer required prop

---

src/components/select/filterable-select/index.d.ts
src/components/select/multi-select/index.d.ts
src/components/select/option/index.d.ts
src/components/select/simple-select/index.d.ts

fixes incorrect type definitions in all Select Components

fix(select): incorrect typescript children types

---

src/components/text-editor/index.js

Fix import path of `TextEditor`
Import path still points at `__internal__`

fix(text-editor): update import path

---

cypress/features/regression/confirm.feature
cypress/features/regression/confirmActions.feature
cypress/fixtures/commonComponents/confirm.json
cypress/support/step-definitions/confirm-steps.js
src/components/confirm/confirm.component.js
src/components/confirm/confirm.d.ts
src/components/confirm/confirm.spec.js
src/components/confirm/confirm.stories.js
src/components/confirm/confirm.stories.mdx
src/components/dialog/dialog.component.js
src/components/dialog/dialog.spec.js
src/components/icon-button/icon-button.spec.js
src/components/icon-button/icon-button.style.js
src/components/modal/modal.component.js
src/components/modal/modal.spec.js

feat(confim): add new props

---

docs/validations.stories.mdx

Update link to codesanbox example in Validation docs
Link to codesandbox uses carbon v24

docs: update link to formik yup codesandbox using latest carbon FE-3691

---

.github/codeql/codeql-config.yml
.github/workflows/codeql-analysis.yml

Add CodeQL scanning workflow for PRs
No CodeQL scanning in Carbon

ci(workflows): add codeql workflow

---

package-lock.json
package.json

Upgrade `semantic-release` and `flux` to resolve npm vulnerabilities.
Moderate and low vulnerabilities in these packages.

chore(deps): upgrade vulnerable packages

---

src/__experimental__/components/date-range/date-range.spec.js
src/__experimental__/components/date/date-picker.component.js
src/__experimental__/components/date/date-picker.spec.js
src/__experimental__/components/date/date.spec.js
src/__experimental__/components/numeral-date/numeral-date.component.js
src/__experimental__/components/numeral-date/numeral-date.spec.js
src/__experimental__/components/textarea/textarea.component.js
src/__spec_helper__/I18next.js
src/components/action-popover/action-popover-item.component.js
src/components/batch-selection/batch-selection.component.js
src/components/batch-selection/batch-selection.spec.js
src/components/form/form-summary.component.js
src/components/form/form.spec.js
src/components/table-ajax/table-ajax.component.js
src/components/table-ajax/table-ajax.spec.js
src/components/table/table-cell/table-cell.spec.js
src/components/table/table-row/table-row.spec.js
src/components/table/table.component.js
src/components/table/table.spec.js
src/components/tile-select/tile-select.component.js
src/components/tile-select/tile-select.spec.js
src/utils/helpers/date/__spec__.js
src/utils/helpers/date/date.js

Merge FE-3697-implement-internationalisation-and-localisation into major/FE-3697-implement-internationalisation-and-localisation
-

refactor(table): replace i18n-js with i18next

---

src/components/dialog-full-screen/dialog-full-screen.stories.mdx
src/components/table/table-row/table-row.spec.js

close FE-3464
fixes  #3521
`Tile` and`ActionItemPopover` are used with correct props.
`Tile` component is used with the wrong `pixelWidth` type that caused errors in the console.
`ActionItemPopover` component is used without `onClick` prop that caused errors in the console.
This task is a little bit outdated. I couldn't find described issues with the `flat-table` component but I checked these errors in other places.
- required `value` prop on `Switch` component - right now, it is not required,
- ForwardRef `onAction` prop - couldn't address this problem,
- required `onClick` prop on `ActionPopoverItem` component - added where missing
- required `name` prop on `RequiredButtonGroup` component - couldn't address this problem, every `RequiredButtonGroup` component is used with the `name` prop …

docs: fix some console errors

---

src/components/icon-button/icon-button.component.js
src/components/icon-button/icon-button.spec.js
src/components/icon-button/icon-button.stories.mdx
src/components/icon-button/icon-button.style.js

add styled-system
there is no support for styled-system props
d.ts file be added in a different PR
https://codesandbox.io/s/carbon-quickstart-forked-zszrd?file=/src/index.js

feat(icon-button): add styled-system

---

docs/testing-styleguide.md

Add information into `docs/testing-styleguide.md` about proper enabling `chromatic` for `major/**` builds.
Currently we have no such information documented.
pass `CI`

docs: add info about chromatic for major branch

---

src/components/multi-action-button/__snapshots__/multi-action-button.spec.js.snap
src/components/multi-action-button/multi-action-button.component.js
src/components/multi-action-button/multi-action-button.spec.js
src/components/multi-action-button/multi-action-button.stories.mdx
src/components/multi-action-button/multi-action-button.style.js

Converts `MultiActionButton` to be functional component and removes extension of `SplitButton`
BREAKING CHANGE: Removed several `get` functions as part of the refactor which could have been
accessed in a consuming application
Adds support for `styled-system/margin` interface on `MultiActionButton`
Component is class based and `extends SplitButton`
`d.ts` file is added as part of the work to update all definition files in carbon
Check stories against master
https://codesandbox.io/s/carbon-quickstart-forked-gsxl4?file=/src/index.js

refactor(multi-action-button): convert to functional component FE-4018

---

src/components/select/select-list/select-list.component.js
src/components/select/select-list/select-list.spec.js

Select list is not resizing during window resize as shown in video in task description.
Fixes #3780
https://codesandbox.io/s/carbon-quickstart-forked-k0hxx?file=/src/index.js

fix(select): fix not resizing list during window resize - FE-3799

---

src/components/mount-in-app/mount-in-app.js

Add deprecation warning for component
No deprecation warning

chore(mount-in-app): add deprecation warning FE-4060

---

src/components/detail/detail.component.js
src/components/detail/detail.spec.js
src/components/detail/detail.stories.mdx
src/components/detail/detail.style.js

This PR adds support for styled-system margin props
https://codesandbox.io/s/carbon-quickstart-forked-4u720?file=/src/index.js

feat(detail): add styled-system margin support - FE-3539

---

.storybook/utils/styled-system-props.js
cypress/features/regression/accessibility/accessibilityDesignSystem.feature
src/__spec_helper__/test-utils.js
src/components/image/image.component.js
src/components/image/image.d.ts
src/components/image/image.spec.js
src/components/image/image.stories.mdx
src/components/image/index.d.ts
src/components/image/index.js
src/utils/helpers/options-helper/options-helper.d.ts

Creates a new `Image` component to support rendering either an `img` or a `div` with `background`
css properties. Adds test and storybook utils for using `styled-system/background`. 
**TypeScript definition file has been added based on the proposed approach adopted in the PR to update it in the whole library.**
Component and utils do not exist
`docs/design-system-image--default-story` etc
https://codesandbox.io/s/carbon-quickstart-forked-7zmwx?file=/src/index.js

feat(image): create new component to support rendering images

---

jest.conf.json
package-lock.json
package.json

Remove some unused dependencies

chore(deps): remove unused dependencies

---

src/components/pill/pill.spec.js
src/components/pill/pill.style.js

Add `white-space: nowrap` CSS property.
https://codesandbox.io/s/sharp-sunset-2vh1k?file=/src/index.js
Resolves #3982
https://codesandbox.io/s/carbon-quickstart-forked-wq5ye

fix(pill): fix text wrap if there are multiple words - FE-4076

---

.github/workflows/cypress-pr.yml

- `cypress/browsers:node14.16.0-chrome90-ff88`
- `cypress-io/github-action@v2.10.2`
The build is currently failing due to the `browser` issue. We need to update the docker container with newest `chrome` version.

ci: update actions and browser

---

.github/workflows/cypress-pr.yml

Updated container to `cypress/browsers:node14.16.0-chrome90-ff88`

ci: update browser container

---

cypress/features/regression/portrait.feature
cypress/fixtures/commonComponents/portrait.json
cypress/support/step-definitions/portrait-steps.js
src/components/portrait/portrait.component.js
src/components/portrait/portrait.spec.js
src/components/portrait/portrait.stories.js
src/components/portrait/portrait.stories.mdx

Trigger integration branch to push third-party fork PR to feature branch
This is the PR -> https://github.com/Sage/carbon/pull/3892

feat(portrait): adds prop to specify fallback icon

---

src/__experimental__/components/date/__snapshots__/date-picker.spec.js.snap
src/__experimental__/components/date/date-picker.component.js
src/__experimental__/components/date/date-picker.spec.js
src/__experimental__/components/date/date.component.js
src/__experimental__/components/date/date.spec.js

This PR fixes #4026
https://codesandbox.io/s/old-hooks-332fc

fix(date-range): fix incorrect date picker positioning - FE-4101

---

src/__experimental__/components/decimal/decimal.stories.mdx

This PR fixes inputs not working properly in all Decimal docs stories
Decimal > All stories

fix(decimal): fix not working inputs in stories -FE-4100

---

.gitignore
cypress/README.md
cypress/docker-compose.yml
package.json

Add documentation on running cypress in docker and using specific browsers for testing.
Not documented
FE-4129
Try it out on your machine 😃

docs: add cypress and docker documentation - FE-4129

---

src/__experimental__/components/checkbox/__snapshots__/checkbox-group.spec.js.snap
src/__experimental__/components/checkbox/__snapshots__/checkbox.spec.js.snap
src/__experimental__/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
src/__experimental__/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
src/__experimental__/components/radio-button/__snapshots__/radio-button.spec.js.snap
src/__experimental__/components/switch/__snapshots__/switch.spec.js.snap
src/__experimental__/components/switch/switch.component.js
src/__internal__/checkable-input/checkable-input.component.js
src/__internal__/checkable-input/checkable-input.d.ts
src/__internal__/checkable-input/checkable-input.spec.js
src/__internal__/checkable-input/checkable-input.style.js
src/__internal__/checkable-input/hidden-checkable-input.component.js

This PR converts `CheckableInput` to a function component
Check if all components using `CheckableInput` internally (Radio, Checkbox, Switch) still work properly.

refactor(checkable-input): convert to function component - FE-3637

---

src/components/flat-table/__snapshots__/flat-table.spec.js.snap
src/components/flat-table/flat-table-cell/flat-table-cell.component.js
src/components/flat-table/flat-table-cell/flat-table-cell.d.ts
src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
src/components/flat-table/flat-table-cell/flat-table-cell.style.js
src/components/flat-table/flat-table-header/flat-table-header.component.js
src/components/flat-table/flat-table-header/flat-table-header.d.ts
src/components/flat-table/flat-table-header/flat-table-header.spec.js
src/components/flat-table/flat-table-header/flat-table-header.style.js
src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js
src/components/flat-table/flat-table-row-header/flat-table-row-header.d.ts
src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js
src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
src/components/flat-table/flat-table-row/flat-table-row.component.js
src/components/flat-table/flat-table-row/flat-table-row.d.ts
src/components/flat-table/flat-table-row/flat-table-row.spec.js
src/components/flat-table/flat-table-row/flat-table-row.style.js
src/components/flat-table/flat-table.stories.js
src/components/flat-table/flat-table.stories.mdx
src/components/flat-table/flat-table.style.js
src/components/flat-table/index.d.ts
src/style/themes/base/base-theme.config.js

Add custom row background color prop
Add alternative header color prop
Add horizontal border size control
Add vertical border size control
1. npm start
2. open:
http://localhost:9001/?path=/story/design-system-flat-table--with-custom-row-background-color
http://localhost:9001/?path=/story/design-system-flat-table--with-custom-horizontal-border-size
http://localhost:9001/?path=/story/design-system-flat-table--with-custom-vertical-borders
http://localhost:9001/?path=/story/design-system-flat-table--with-alternative-header-background

feat(flat-table): flat table enhancements (FE-4065)

---

src/components/note/note.component.js
src/components/note/note.d.ts
src/components/note/note.spec.js
src/components/note/note.style.js

Removes `name` as a required prop
`name` is a required prop
https://codesandbox.io/s/carbon-quickstart-forked-trt1m?file=/src/index.js

fix(note): removes required constraint from name prop type FE-4208

---

package.json

Provided the proper url for the `homePage` as `https://carbon.sage.com`
Currently we have provided the url to the `readme.md` file on our repo

docs(package.json): update url for homepage

---

README.md

Document version strategy in README.
Version strategy not documented, questions and apprehensions over large version number.
FE-4254
Read the README.

docs: document version strategy FE-4254

---

SECURITY.md

Add security policy
Carbon currently has no documented security policy

docs(security-policy): add security policy

---

CONTRIBUTING.md

docs(contributing): add forked ci info

---

rfcs/text/design-tokens.md

This PR contains RFC for implementing design tokens in carbon.
---
This is a RFC and it is important to note that this PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/2163a70006e4e7853d6b4fe05703a2348a979f3e/rfcs/README.md).
Please use 👍 if you approve.

docs(design-tokens): rfc for implementing design tokens in carbon

---

.github/PULL_REQUEST_TEMPLATE.md

Add extra checks into our PR template to remind developers/QA to do certain tasks.

chore(pr template): add extra checks

---

.github/ISSUE_TEMPLATE/bug_report.yml

Add an input to capture JIRA ticket numbers.
Users have no way of tracking the progress of GitHub issues via JIRA.
N/A
Create an issue after this PR is merged.

chore(github): add JIRA ticket to bug template

---

src/__internal__/input/__snapshots__/input-presentation.spec.js.snap
src/__internal__/input/__snapshots__/input.spec.js.snap
src/__internal__/input/input-presentation.style.js
src/__internal__/input/input.style.js
src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap

Fixes #4319
https://codesandbox.io/s/gh-4319-oumk0

fix(textbox): fix incorrect styling when required and in error state - FE-4286

---

cypress/integration/common/anchorNavigation.feature

Make tests for `AnchorNav` not flaky 
tests for `AnchorNav` are flaky 
CI should pass

test: update tests for anchorNav

---

src/components/decimal/decimal-test.stories.mdx
src/components/decimal/decimal.component.js
src/components/decimal/decimal.spec.js

Refactor component to be a functional component.
Component is currently a class based component.
N/A
Codesandboxes for testing
- Manual Testing: https://codesandbox.io/s/decimal-manual-testing-9zf24
- Locale Testing: https://codesandbox.io/s/decimal-locale-testing-5wz6w

refactor(decimal): convert class to functional component - FE-3640

---

src/components/carousel/carousel.component.js
src/components/carousel/carousel.spec.js
src/components/carousel/carousel.style.js
src/components/carousel/slide/slide.style.js

Describes the Carousel with design tokens.
Updates the tests after changes.
The Carousel use the theme styled-component property.

feat(carousel): describe Carousel using design tokens (FE-4721)

---

docs/development-roadmap.stories.mdx

`MountInApp` and `ScrollableList` already have deprecation warnings on them so adding the here for consumer awareness.

docs(roadmap): add scrollable list and mount in app to deprecations

---

src/components/dialog/dialog.component.js
src/components/dialog/dialog.config.js
src/components/dialog/dialog.d.ts
src/components/dialog/dialog.spec.js
src/components/dialog/dialog.stories.mdx
src/components/dialog/dialog.style.js

Surfaces `contentPadding` prop which has an interface that partially supports the styled-system
padding `p`, `py` and `px` props
No support for adjusting padding of `Dialog` content.
https://codesandbox.io/s/modest-forest-fzd81?file=/src/index.js

feat(dialog): surface contentPadding prop to allow overriding default padding values dialog content FE-4758

---

src/components/flat-table/__snapshots__/flat-table.spec.js.snap
src/components/flat-table/flat-table-cell/flat-table-cell.spec.js
src/components/flat-table/flat-table-cell/flat-table-cell.style.js
src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.js
src/components/flat-table/flat-table-header/flat-table-header.spec.js
src/components/flat-table/flat-table-header/flat-table-header.style.js
src/components/flat-table/flat-table-row-header/flat-table-row-header.style.js
src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap
src/components/flat-table/flat-table-row/flat-table-row.spec.js
src/components/flat-table/flat-table-row/flat-table-row.style.js
src/components/flat-table/flat-table.spec.js
src/components/flat-table/flat-table.style.js
src/components/flat-table/sort/sort.style.js

Describes table component using design tokens.
Describes the color of the icons inside the table using a token: `--colorsActionMinor500`
Updates tests when the above changes are made.
Table use the theme styled-component property.
Currently for example chevron and drag icon have `--colorsYin065`.
Dark color table:
Light color table:
White color table: 
Base color table: 
The correct appearance can be checked in the component: Flat Table.
Use devtools to check if flat table use css variables.

feat(flat-table): describe table using design tokens, update tests - FE-4743

---

src/components/card/card.stories.mdx

Fixes #4946
Check for Axe violations in Card stories

fix(card): fix incorrect headers - FE-4964

---

src/__internal__/field-help/field-help.spec.js
src/__internal__/field-help/field-help.style.js
src/__internal__/fieldset/fieldset.spec.js
src/__internal__/fieldset/fieldset.style.js

Describes Fieldset and FieldHelp components using design tokens. Removes all possible 'theme' in css files.

feat(fieldset, field-help): describe fieldset and field-help using design tokens, update tests

---

cypress/support/step-definitions/text-area-steps.js
src/__internal__/character-count/character-count.spec.js
src/__internal__/character-count/character-count.style.js
src/__internal__/checkable-input/checkable-input.spec.js
src/__internal__/checkable-input/checkable-input.style.js
src/__internal__/input-icon-toggle/input-icon-toggle.style.js
src/__internal__/input/__snapshots__/input-presentation.spec.js.snap
src/__internal__/input/input-presentation.style.js
src/components/radio-button/__snapshots__/radio-button-group.spec.js.snap
src/components/radio-button/__snapshots__/radio-button-mapper.spec.js.snap
src/components/radio-button/__snapshots__/radio-button.spec.js.snap
src/components/textarea/textarea.spec.js
src/components/textbox/textbox.spec.js
src/hooks/__internal__/useCharacterCount/index.spec.js

Describes components using design tokens. Removes all possible 'theme' in css files.

feat(input-presentation, input-icon-toggle, checkable-input, character-count): describe components using design tokens, update tests

---

.github/CODEOWNERS

Update owners to assign QAs ownership of `*.test.js` files
Devs have ownership of `*.test.js` files

chore(code-owners): update file to assign ownership of test.js files to carbon qa

---

docs/development-roadmap.stories.mdx

Updated roadmap to reflect our current priorities.
Roadmap is outdated.
N/A
N/A

docs: update roadmap

---

src/components/loader/loader.test.js

update flaky test for `loader.test.js` file
one test is marked as flaky
`loader.test.js` file should pass

test(loader): test fix

---

package-lock.json

Running `npm install` on master changes the package-lock file. Committing the updated version here.
Running `npm install` on master changes the package-lock file.

chore(deps): update package-lock file

---

package-lock.json

Resolve some of our npm vulnerabilities with `npm audit fix`

chore(deps): run npm audit fix to update some packages

---

.github/workflows/cypress.yml
src/components/split-button/split-button.test.js

Revert a commit with update `docker` image which is using `Debian 10.10` v
Update the `action` version
No commit info in cypress dashboard
Check:

ci: revert for docker image

---

src/components/multi-action-button/multi-action-button.test.js

remove duplicated tests
duplicated tests

test: remove duplicates

---

src/components/heading/index.d.ts
tsconfig.json

fix(heading): fix typings - FE-5214

---

.github/ISSUE_TEMPLATE/bug_report.yml

This PR corrects the hint/help text for the 'Expected behaviour' field in the 'Bug' Issue template.
The 'Expected behaviour' help text on the 'Bug' Issue template uses the word 'current', which I assume was copied from the 'Current behaviour' template field.
-->

chore(github): corrects wording on 'Expected behaviour' help text

---

src/components/box/box.test.js

Refactor for Box component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.
Currently we are using the regular cypress approach with BDD.

test(box): refactor for cypress tests

---

rfcs/text/remove-support-for-uncontrolled-inputs.md

Proposal to remove uncontrolled support for our Carbon input components.
---
This PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/master/rfcs/README.md).
Please use 👍  if you approve.

docs: rfc to remove support for uncontrolled inputs - FE-4341

---

.github/workflows/chromatic-push.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml
.github/workflows/semantic-commit-lint.yml
.github/workflows/semantic-release.yml
.github/workflows/storybook.yml
docs/dev-environment-setup.md
package.json
scripts/check_node_version.js

Reverts #5364
There are some issues when running npm install with v8 of npm that need further investigating so reverting this back

revert(node, npm): revert relaxing of node and npm versions

---

src/components/fieldset/fieldset.stories.mdx

Checkbox was used in the default story but wasn't important in the .mdx file. Storybook doesn't
throw any errors but appears to simply render the unknown component as a div, which resulted in the
checkbox props being passed as HTML attributes and therefore warnings about unknown or
incorrectly-used attributes.
There should be no console errors/warnings on the Storybook page for Fieldset. Also the default story using the Checkbox component should include a checkbox in the rendered output.
No checkbox visible in the rendered output, several console errors when run in development mode.
No need to run any component tests, as no code has changed except in the storybook .mdx file. Just check that the console errors/warnings have gone and the stories all display correctly.
The following …

docs(fieldset): add missing checkbox import

---

.github/workflows/cypress.yml
package-lock.json
package.json

- update the cypress version to the latest `10.9.0`
- update the docker image with `node 16.17.0` and latest `chrome v106`
- Now we were using cypress in version `10.8.0`
- We are running on CI using not the newest `node` and `chrome` versions

test(cypress): udpate the dependency

---

.storybook/isChromatic.d.ts
src/components/dialog/dialog.component.tsx
src/components/dialog/dialog.config.ts
src/components/dialog/dialog.stories.mdx
src/components/dialog/dialog.stories.tsx
src/components/dialog/dialog.style.ts
src/components/dialog/index.ts

closes #5516 
- Add missing `DialogSizes` type from the interface for the `Dialog` component
- Amend typing of `DialogSizes` so consumers can see their types as literal unions, not type alias names
- Convert story setup to CSF stories with MDX docs approach to allow for story type checking
- `DialogSizes` type is missing from `Dialog` interface
- The type of `size` prop of `Dialog` shows as `DialogSizes` and not `extra-small | small | ...`   
- Cannot type check stories
- Using the provided codesandboxes, verify the following error has been resolved: ``Module '"carbon-react/lib/components/dialog"' has no exported member 'DialogSizes'.``
- In storybook:
- Verify in `Dialog` prop table that the `size` prop has its possible values documented (i.e. `extra-small`, `small`, etc.) 
- Verify all …

fix(dialog): add DialogSizes type to component interface (FE-5390)

---

cypress/e2e/themes/themes.feature
src/components/multi-action-button/multi-action-button.stories.mdx
src/components/multi-action-button/multi-action-button.stories.tsx
src/components/multi-action-button/multi-action-button.style.ts

Refactor stories to be tsx
Stories are still currently js after ts refactor has been completed.
N/A
Check stories are still how they should be

refactor(multi-action-button): refactor stories to be tsx

---

src/components/sidebar/sidebar-test.stories.tsx
src/components/sidebar/sidebar.component.tsx
src/components/sidebar/sidebar.spec.tsx
src/components/sidebar/sidebar.stories.mdx
src/components/sidebar/sidebar.stories.tsx
src/components/sidebar/sidebar.style.ts
src/style/utils/width.ts

Adds `width` prop to support overriding preset widths defined via the `size` prop
No support for setting custom width
https://codesandbox.io/s/reverent-tree-3nzukd?file=/src/index.js

feat(sidebar): add support for setting custom width

---

cypress/locators/hr/index.js
cypress/locators/hr/locators.js
src/components/hr/hr.test.js

Add Cypress tests for the `Hr` component to use new cypress-component-react framework for testing.
Add `hr.test.js`. 
Add locators as well.
No tests for `Hr` component

test(hr): add cypress tests

---

cypress/locators/form/index.js
cypress/locators/form/locators.js
src/components/form/form.test.js

Refactor for form component to use new cypress-component-react framework for testing.
I have added test.js and deleted steps.js and feature file.
Currently we are using the regular cypress approach with BDD.

test(form): add cypress tests

---

package-lock.json

Revert "fix(loader-utils): bumps version to remove critical security vulnerab…"

---

cypress/support/component.js
package-lock.json
package.json
src/components/accordion/accordion.test.js
src/components/action-popover/action-popover-test.stories.tsx

- update dependencies
- remove cy.task from `component` accessibility part
- we've been using older `cypress-axe` version
- cy.task was called for both `e2e` and `component` types

ci: update dependecies

---

package-lock.json
package.json
src/__internal__/focus-trap/focus-trap-utils.ts
src/__internal__/focus-trap/focus-trap.component.tsx
src/__internal__/focus-trap/focus-trap.spec.tsx

fixes #5544
https://codesandbox.io/s/carbon-quickstart-forked-q2dckr?file=/src/index.js

fix(dialog): fix incorrect focus trap behaviour with ag-grid - FE-5497

---

.storybook/preview.js
cypress.config.js
cypress/docker-compose.yml
cypress/support/e2e.js
package-lock.json
package.json
src/components/advanced-color-picker/advanced-color-picker.test.js
src/components/flat-table/flat-table.test.js
src/components/heading/heading.test.js
src/components/help/help.test.js
src/components/icon/icon.test.js

- update dependencies
- update `docker-compose.yml` file
- an old version of cypress

test: update cypress dependencies

---

cypress/locators/vertical-menu/index.js
cypress/locators/vertical-menu/locators.js
cypress/support/accessibility/a11y-utils.js
src/components/vertical-menu/index.ts
src/components/vertical-menu/vertical-menu-full-screen.component.tsx
src/components/vertical-menu/vertical-menu-full-screen.context.ts
src/components/vertical-menu/vertical-menu-full-screen.spec.tsx
src/components/vertical-menu/vertical-menu-item.component.tsx
src/components/vertical-menu/vertical-menu-item.spec.tsx
src/components/vertical-menu/vertical-menu-test.stories.tsx
src/components/vertical-menu/vertical-menu-trigger.component.tsx
src/components/vertical-menu/vertical-menu-trigger.spec.tsx
src/components/vertical-menu/vertical-menu.component.tsx
src/components/vertical-menu/vertical-menu.spec.tsx
src/components/vertical-menu/vertical-menu.stories.mdx
src/components/vertical-menu/vertical-menu.stories.tsx
src/components/vertical-menu/vertical-menu.style.ts
src/components/vertical-menu/vertical-menu.test.js
src/locales/en-gb.ts
src/locales/locale.ts
src/locales/pl-pl.ts

This PR introduces a new VerticalMenu component
Closes Sage/design-system#12
Check FE-5619 ticket for acceptance criteria + answered questions that I had for the UX team.
Create test stories and add Cypress tests.

feat: add new VerticalMenu component - FE-5619

---

src/components/icon/icon-test.stories.tsx

enable visual test for all icons
the `all`/`visual` story is disabled for `Icon` component
Check if the new change will be in `Chromatic` - the new snapshot with `all` icons

docs(icon): enable visual test for all icons

---

src/components/link/link.stories.mdx

fix #5816
Imports the `Link` component into `link.stories.mdx` to ensure the components props are properly displayed.
Currently, no props are displayed on storybook.

docs(link): import Link component into stories file

---

cypress/support/accessibility/a11y-utils.js
src/components/box/box-test.stories.tsx
src/components/box/box.stories.mdx
src/components/box/box.stories.tsx
src/components/box/box.test.js
src/components/carbon-provider/carbon-provider.stories.mdx
src/components/carbon-provider/carbon-provider.stories.tsx
src/components/carbon-provider/carbon-provider.test.js

- Add `accessibility` Cypress tests for the `Box` component to use the new cypress-component-react framework for testing.
- Move component stories to the `box.stories.tsx`
- Refactor for `box.stories.mdx` file
- Move testing component to the `box-test.stories.tsx`
- Add `accessibility` Cypress tests for the `Carbon Provider` component to use the new cypress-component-react framework for testing.
- Move component stories to the `carbon-provider.stories.tsx`
- Refactor for `carbon-provider.stories.mdx` file
Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that:

Cypress accessibility box carbon provider

---

src/components/advanced-color-picker/advanced-color-picker.component.tsx

Exports the component from the `.component.tsx` file to ensure component is properly imported into the `.stories.mdx` file to display props.
Currently, no props are displayed on storybook.

docs(advanced-color-picker): add export to component file to ensure props are properly displayed

---

cypress/components/button-bar/button-bar.test.tsx
cypress/components/textbox/textbox.test.js
cypress/support/commands.ts
package-lock.json
package.json

- add a new level of testing for checking `designTokens` applied to css properties
- we are no checking the `designTokens` used by designers.

test(): add design tokens implementation

---

cypress/components/batch-selection/batch-selection.cy.tsx
cypress/components/password/password.cy.js
src/components/batch-selection/batch-selection-test.stories.tsx

Rename the `batch-selection.cy.js` into `batch-selection.cy.tsx` file in `./cypress/components/batch-selection/` folder
Refactor tests to Typescript
Move any remaining stories in `batch-selection.cy.tsx` file to `batch-selection-test.stories.tsx` in `'./src/components/batch-selection/'` folder.
tests are in js not ts

test(batch-selection): refactor to TS

---

cypress/components/loader-bar/loader-bar.cy.tsx
src/components/loader-bar/loader-bar-test.stories.tsx

- Rename the `loader-bar.cy.js` to `loader-bar.cy.tsx` file in `./cypress/components/heading/` folder.
Currently Badge component is in JS not in TS.

test(loader-bar): refactor to typescript

---

cypress/components/card/card.cy.tsx
src/components/card/card-test.stories.tsx
src/components/card/card.stories.tsx

- Rename the `card.cy.js` to `card.cy.tsx` file in `./cypress/components/card/` folder.
Currently Detail component is in JS not in TS.

test(card): refactor tests to ts

---

cypress/components/decimal/decimal.cy.tsx

- Rename the `decimal.cy.js` to `decimal.cy.tsx` file in `./cypress/components/decimal/` folder.
Currently Decimal component is in JS not in TS.

test(decimal): refactor tests to ts

---

cypress/components/loader/loader.cy.tsx
src/components/loader/loader-test.stories.tsx

- Rename the `loader.cy.js` to `loader.cy.tsx` file in `./cypress/components/loader/` folder.
Currently Loader component is in JS not in TS.

test(loader): typescript refactor

---

cypress/components/preview/preview.cy.tsx
src/components/preview/preview-test.stories.tsx

- Rename the `preview.cy.js` to `preview.cy.tsx` file in `./cypress/components/preview/` folder.
Preview tests are in js not ts.

test(preview): typescript refactor

---

cypress/components/hr/hr.cy.tsx

- Rename the `hr.cy.js` to `hr.cy.tsx` file in `./cypress/components/hr/` folder.
Hr tests are in js not ts.

test(hr): typescript refactor

---

.github/workflows/chromatic-push.yml
.github/workflows/chromatic.yml
.github/workflows/codeql-analysis.yml
.github/workflows/semantic-commit-lint.yml
.github/workflows/semantic-release.yml
.github/workflows/storybook.yml

Update github actions/** to newest versions
we are still using the old one github actions/**

ci: update actions versions

---

.github/workflows/chromatic-push.yml

Revert for update for `chromaui/action@v1`
`chromaui/action@v6` is not available

ci: revert for chromatic action

---

cypress/components/progress-tracker/progress-tracker.cy.tsx
cypress/components/search/search.cy.tsx
src/components/progress-tracker/progress-tracker-test.stories.tsx

- Rename the `progress-tracker.cy.js` file to `progress-tracker.cy.tsx` file in `./cypress/components/progress-tracker/` folder.
- Formatting for `search` test file
Progress Tracker tests are in js not ts.

test(progress-tracker): refactor to TS

---

src/components/password/password.stories.mdx

fix #6092
PR will import `TranslationKeysTable` into `password.stories.mdx` to ensure consumers can see the relevant translation keys available to override the translations for the component.
Currently, `TranslationKeysTable` is not imported into `password.stories.mdx`
-[x] Related docs have been updated if required

docs(password): import translation keys table

---

src/components/decimal/decimal-test.stories.tsx
src/components/grouped-character/grouped-character-test.stories.tsx
src/components/number/number-test.stories.tsx
src/components/numeral-date/numeral-date-test.stories.tsx
src/components/search/search-test.stories.tsx

Update the `action` to report proper values instead of `"[Object]"`
Now values are reported for `onChange`/`onBlur` like `"[Object]"`

docs: update action reports

---

cypress/components/menu/menu.cy.tsx
src/components/menu/menu-test.stories.tsx

- Rename the `menu.cy.js` to `menu.cy.tsx` file in `./cypress/components/menu/` folder.
Currently Menu component is in JS not in TS.

test(menu): typescript refactor

---

.github/workflows/forked-ci.yml
.github/workflows/playwright.yml
.github/workflows/pr.yml

- add `playwright.yml` to be able to run the tests
- no `playwright.yml`

ci(playwright): add ci configuration

---

.storybook/welcome-page/get-started/get-started.component.js
.storybook/welcome-page/header/header.component.js
README.md

Dead links on `README.md` and `header.component.js` have been replaced with the correct link.
Currently, there are dead links on our `README.md` and `header.component.js` which is our main landing page.

docs: fix dead links on README and main page

---

docs/codebase-overview.md
docs/dev-environment-setup.md

- Update `/docs/dev-environment-setup.md`

docs: update dev environment setup docs

---

src/components/carbon-provider/carbon-provider.stories.mdx

FE-6237
Fixed typo in docs where import path was incorrect. 
Incorrect directory in the import path. 

docs(carbon-provider): typo fix

---

cypress/components/flat-table/flat-table.cy.tsx
cypress/components/grouped-character/grouped-character.cy.tsx
cypress/components/menu/menu.cy.tsx
cypress/components/multi-action-button/multi-action-button.cy.tsx
cypress/components/number/number.cy.tsx
cypress/components/pager/pager.cy.tsx
cypress/components/password/password.cy.tsx
cypress/components/switch/switch.cy.tsx
cypress/components/tooltip/tooltip.cy.tsx
cypress/components/vertical-menu/vertical-menu.cy.tsx
playwright/components/step-sequence/index.ts
src/components/action-popover/action-popover.pw.tsx
src/components/action-popover/action-popover.stories.tsx
src/components/button-bar/button-bar.spec.tsx
src/components/button-minor/button-minor.pw.tsx
src/components/button-toggle/button-toggle.spec.tsx
src/components/flat-table/flat-table-test.stories.tsx
src/components/loader/loader.pw.tsx
src/components/menu/menu.spec.tsx
src/components/progress-tracker/progress-tracker.spec.tsx
src/components/text-editor/text-editor.spec.tsx
src/components/tooltip/tooltip.stories.mdx
src/components/tooltip/tooltip.stories.tsx
src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx

Various spelling mistakes have been addressed.
Some spelling mistakes present.
N/A
- Cypress and Playwright tests should pass.
- Unit tests should still pass and achieve 100% coverage.

chore: address various spelling mistakes and some code formatting 

---

.github/workflows/chromatic-push.yml
.github/workflows/chromatic.yml
.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/cypress.yml
.github/workflows/playwright.yml
.github/workflows/semantic-commit-lint.yml
.github/workflows/semantic-release.yml
.github/workflows/storybook.yml
.gitignore
.husky/post-checkout
playwright-ct.config.ts
src/components/action-popover/action-popover.pw.tsx
src/components/action-popover/components.test-pw.tsx
src/global.d.ts

- Add support for [sharding](https://playwright.dev/docs/test-sharding) in Playwright's CI workflow - allowing portions of the test suite (or "_shards_") to be run in parallel. This reduces the total average runtime by ~70%:
- Tweak an `ActionPopover` playwright test, which generates file artifacts, so Playwright can clean these up afterwards  
- GitHub Actions runs all Playwright tests as part of the same job:
- Verify HTML report of test results can be downloaded (go to Playwright workflow run, then download HTML report from generated artifacts).
- Verify HTML report has correctly merged the results from all shards.
- ~~Verify HTML report is correctly merged when there is a failing test.~~ **Workflow successfully merges [when there is a failing …

chore(playwright): shard test suite in github actions workflow

---

.codesandbox/ci.json

Remove the config for codesandbox app as csb pricing plan has changed
Updating of docs and PR/ issue template to be done when we have a new sandbox template
Config exists

ci: remove codesandbox config

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

Open `bug_report.yml` and `feature_request.yml` files in branch. Check github doesn't flag any syntax errors.

chore(github): fix yaml errors in templates

---

src/components/button/__snapshots__/button.spec.tsx.snap
src/components/button/button-test.stories.tsx
src/components/button/button-types.style.ts
src/components/button/button.component.tsx
src/components/button/button.config.ts
src/components/button/button.pw.tsx
src/components/button/button.spec.tsx
src/components/button/button.stories.mdx
src/components/button/button.stories.tsx
src/components/button/button.style.ts
src/components/button/components.test-pw.tsx
src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap
src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap

Adds new `buttonType` options for `gradient-white` and `gradient-grey` buttons
NB: I've avoided adding much unit test past what's required for coverage as I prefer chromatic to capture the visual stuff here
No support for gradient buttons

feat(button): add new `gradient-white` and `gradient-grey` buttonTypes

---

.github/workflows/chromatic-push.yml
.github/workflows/chromatic.yml

Enable [TurboSnap for Chromatic](https://www.chromatic.com/docs/turbosnap/) 
Setup Docs: https://www.chromatic.com/docs/setup-turbosnap/#configure

ci: enable chromatic turbosnap

---

plugins/generate-proptypes/inject-prop-types.mjs

Carbon components are released with `propTypes` definitions, automatically generated from the Typescript types, which are in some cases very large (eg Box has over 3500 lines of proptypes in the npm package). These can be useful in development for teams not using typescript, but are not needed in production (and proptypes warnings are turned off by React in production builds anyway). To reduce the size of consumers' builds, this change wraps the generated proptype definitions in a conditional check on `process.env.NODE_ENV`, so that they will still be there in development but will be stripped out of production builds by the bundler.
BREAKING CHANGE: Carbon components will no longer expose `propTypes` in production builds - any functionality that relies on reading the `propTypes` of a …

build: remove proptypes from production bundles

---

src/components/checkbox/checkbox.mdx

Update import path for optional and required checkbox stories
Import path for optional and required checkbox stories is incorrect

chore(checkbox): update imports for required and optional stories

---

src/components/select/filterable-select/components.test-pw.tsx
src/components/select/filterable-select/filterable-select-test.stories.tsx
src/components/select/filterable-select/filterable-select.pw.tsx
src/components/select/filterable-select/filterable-select.stories.tsx
src/components/select/multi-select/components.test-pw.tsx
src/components/select/multi-select/multi-select-test.stories.tsx
src/components/select/multi-select/multi-select.pw.tsx
src/components/select/multi-select/multi-select.stories.tsx
src/components/select/select-list/select-list.component.tsx
src/components/select/select-list/select-list.spec.tsx
src/components/select/simple-select/components.test-pw.tsx
src/components/select/simple-select/simple-select-test.stories.tsx
src/components/select/simple-select/simple-select.pw.tsx
src/components/select/simple-select/simple-select.stories.tsx

fix #6600
When values for options in the `Select` component are set to objects, `select-list` is not able to compare object values and does not highlight the selected option as it does not find it in the children values. Added a shallow equality check to be able to compare property values instead of object references. 
'Object as value' story for `Select` components does not highlight the preselected value.

fix(select): objects as value fix

---

package-lock.json

- update npm version to resolve security dependency with tar
- there is a security vulnerability with tar that needs to be resolved
NA

build(npm): update npm version to resolve tar security vulnerability

---

.storybook/manager.ts
.storybook/version-picker/index.js

Revert "chore(storybook): reorder the addon registration to resolve showing the version picker"

---

README.md

chore: remove cypress badge from README

---

.github/workflows/codeql-analysis.yml

chore(ci): update version of used CodeQL GitHub Actions

---

.storybook/manager.ts
.storybook/version-picker/index.js

chore(version picker): change order of addon registration and add logging

---

.storybook/manager.ts
.storybook/version-picker/index.js

Revert "chore(version picker): change order of addon registration and add logging"

---

package-lock.json

chore: upgrade transitive dependency ejs

---

src/components/select/filterable-select/filterable-select.stories.tsx
src/components/select/multi-select/multi-select.stories.tsx
src/components/select/simple-select/simple-select.stories.tsx

Select lists are not hidden when opened in stories. 
Select lists are hidden when opened in stories.

docs(select): increase container height for stories

---

src/components/date-range/date-range.mdx
src/components/date/date.mdx

Update import path in docs
Import paths are incorrect

chore(date, date-range): update docs for locale imports

---

package-lock.json

chore: update transitive dependencies

---

.storybook/manager.ts

chore(storybook): disable version picker addon

---

src/components/menu/menu-item/menu-item.style.ts
src/components/menu/menu.stories.tsx

Update styling to ensure vertical alignment is uniform when icon and onClick props passed
Alignment is incorrect when icon and onClick passed

fix(menu-item): ensure correct alignment when onClick and icon props are set

---

src/components/flat-table/flat-table-row/flat-table-row.style.ts
src/components/flat-table/flat-table-test.stories.tsx
src/components/flat-table/flat-table-themes.mdx
src/components/flat-table/flat-table-themes.stories.tsx
src/components/flat-table/flat-table.component.tsx
src/components/flat-table/flat-table.mdx
src/components/flat-table/flat-table.pw.tsx
src/components/flat-table/flat-table.spec.tsx
src/components/flat-table/flat-table.stories.tsx
src/components/flat-table/flat-table.style.ts

- Add `hasOuterVerticalBorders` prop  - toggles visibility of table's outer left and right borders
- Add `bottomBorderRadius` prop - for customising the table's bottom border radius. Accepts the following tokens:
- "borderRadius000"
- "borderRadius010"
- "borderRadius025"
- "borderRadius050"
- "borderRadius100"
- "borderRadius200"
- "borderRadius400"
After these additions a minimal design can now be achieved:
Currently, there is no support for horizontal-only borders between cells, and the bottom border radius of the table cannot be customised.
- Validate the functionality of the new “Minimal Design” story. Ensure it meets expectations and behaves as intended.
- Review the new `hasOuterVerticalBorders` and `bottomBorderRadius` props added to `FlatTable`. Assess if they function correctly …

add flat-table enhancements

---

src/components/dialog/dialog.component.tsx
src/components/form/form.component.tsx

When tabbing through a form in FireFox browser, the form as a whole should not be focusable and the focus should jump to the first focusable element within the form
https://github.com/user-attachments/assets/d049545e-6fd0-49b8-a251-a2ac35548736
When tabbing through a form in FireFox browser, the form as a whole is focusable and highlighted in blue.
https://github.com/user-attachments/assets/19ccac39-a69c-4ac5-951c-b9b5421ff591

fix(form): tabbing in FireFox - focus incorrect

---

src/__internal__/focus-trap/focus-trap.test.tsx
src/__internal__/sticky-footer/sticky-footer.test.tsx
src/components/alert/alert.test.tsx
src/components/breadcrumbs/crumb/crumb.test.tsx
src/components/button-bar/button-bar.test.tsx
src/components/button-toggle/button-toggle-group/button-toggle-group.test.tsx
src/components/file-input/__internal__/file-upload-status/file-upload-status.test.tsx
src/components/file-input/file-input.test.tsx
src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.test.tsx
src/components/global-header/global-header.test.tsx
src/components/hr/hr.test.tsx
src/components/loader-spinner/loader-spinner.test.tsx
src/components/menu/menu-full-screen/menu-full-screen.test.tsx
src/components/radio-button/radio-button-group/radio-button-group.test.tsx
src/components/step-flow/step-flow.test.tsx
src/components/time/time.test.tsx
src/hooks/__internal__/useClickAwayListener/useClickAwayListener.test.tsx
src/hooks/__internal__/useFloating/useFloating.test.tsx
src/hooks/__internal__/useFormSpacing/useFormSpacing.test.tsx
src/hooks/__internal__/useLocale/useLocale.test.tsx
src/hooks/__internal__/useModalAria/useModalAria.test.tsx

Tidy up earlier tests converted to RTL
Earlier converted RTL tests may not be aligned with our current standards
N/A
N/A

test: tidy up new RTL tests - FE-6549

---

src/components/tile/flex-tile-cell/flex-tile-cell.stories.tsx
src/components/tile/flex-tile-cell/flex-tile-cell.test.tsx
src/components/tile/tile.mdx

fix #7031
Add margin, spacing, grid, layout and position props to FlexTileCell prop table. 
Missing margin, spacing, grid, layout and position props in FlexTileCell prop table.

docs(flex-tile-cell): add missing props to FlexTileCell prop table

---

jest.config.ts
package-lock.json
package.json
src/components/card/card-test.stories.tsx

This reverts commit 1c03d3d6178f1dd3f7c98207e66266fe56e8e117.

Revert "chore: upgrade react-dnd to v16"

---

playwright/support/helper.ts
src/components/date/date.pw.tsx

Adds a new helper function `toBeFocusedDelayed` and utilises the current `containsClass` helper to address frequently flaking tests 
Tests in date are flaking

test(date): address flakiness

---

src/components/tabs/__internal__/tabs-header/tabs-header.component.tsx
src/components/tabs/tabs-test.stories.tsx

fixes: #7142
Added `type="button"` to the `Tabs` navigation left and right buttons to prevent accidental form submission when the component is used inside a `Form`.
https://github.com/user-attachments/assets/779950f5-a7cd-49c1-8be8-0fab35cd3cb0
When the left and right navigation buttons are used on the `Tabs` component and the component is inside a `Form`, the `Form` is being submitted.
https://github.com/user-attachments/assets/3a4045ad-abb3-48bd-acd6-fb6242d7b2c4

fix(tabs): click on navigation button in Tabs submit the form

---

src/components/accordion/accordion-test.stories.tsx
src/components/accordion/accordion.mdx
src/components/accordion/accordion.stories.tsx

Update the documentation for `Accordion` to improve readability and usefulness
The documentation for `Accordion` contains ineffective examples and unclear instructions.
Run Storybook and view the documentation for `Accordion`

docs(accordion): refresh the documentation for the Accordion component

---

src/components/tile/flex-tile-divider/flex-tile-divider.component.tsx
src/components/tile/flex-tile-divider/flex-tile-divider.test.tsx

fix #7173
Adds `aria-hidden` to the hr element rendered
Assistive technologies are recognising the hr element, causing issues

fix(flex-tile-divider): add aria-hidden attribute to hr element

---

src/components/checkbox/checkbox.mdx
src/components/checkbox/validations.stories.tsx

chore: rm warning story from new boolean validation

---

.storybook/welcome-page/header/header.style.js
.storybook/welcome-page/selling-points/selling-points.style.js
README.md
docs/installation.mdx

- Docs: Update `styled-components` version referenced in installation page
- Docs: Fix syntax error in CSS used for the Welcome Page—which occurred after upgrading `styled-components` to v5
- Chore: Update copyright in project README
- Incorrect CSS styling used by the Welcome Page, for example the font size:

docs(installation): update version of styled-components

---

src/components/note/note.pw.tsx
src/components/note/note.stories.tsx
src/components/note/note.style.ts
src/components/text-editor/text-editor.pw.tsx
src/components/text-editor/text-editor.stories.tsx
src/components/text-editor/text-editor.style.ts

Links within `TextEditor` and `Note` match Carbon's Link component styles:
Links within `TextEditor` and `Note` have default styling:

fix(text-editor, note): ensure links have correct styles

---

playwright/support/helper.ts

Log incomplete tests to the console, which will appear in both pipeline runs and when ran locally.
Playwright currently does not flag accessibility findings that are marked as `incomplete` by `axe-core`, which has the potential to be allowing a number of false negatives through the check process.
This is a much simpler approach than would be preferred however it does expedite the process of finding potential issues without requiring changes to the pipeline or other CI processes.
Run the following test:
```
src/components/button/button.pw.tsx > should pass accessibility tests for SecondaryButtonWhite example
``` 
Note that it passes. Open `src/components/button/components.test-pw.tsx` and set the `backgroundColor` of the wrapping `Box` to `white` in the `SecondaryButtonWhite` component: …

test(playwright): output incomplete accessiblity findings to console

---

src/components/action-popover/action-popover-interaction.stories.tsx

Add play functions to ActionPopover
ActionPopover has no play functions

docs(action-popover): add interaction functions to action-popover stories

---

package-lock.json
package.json
src/components/decimal/decimal.test.tsx
src/components/text-editor/__internal__/plugins/Toolbar/buttons/buttons.test.tsx

Includes `dependabot` commit to bump form-data
Bumps `eslint-plugin-testing-library` to latest and addresses two linting errors
Vulnerability wrt to form-data exists
Peer dependancy conflict due to older version of `eslint-plugin-testing-library`

Dependency admin

---

package.json

mergeback revert commit removing exports from package.json
component imports are broken

fix: revert updates to package.json exports

---

src/__internal__/form-field/form-field.style.ts
src/components/textbox/textbox-test.stories.tsx

Adds `position: relative` to the form field wrapper
Currently, there is no `position: relative` on the form field wrapper
See the `"Form Field Relative Position"` story which shows the fix working in a specific scenario, remove the line of styling from `form-field.style.ts` on line `6` to intentionally break the fix

feat: add relative position to form field wrapper
