Sage/carbon

.github/workflows/chromatic-fork.yml, package-lock.json, package.json
We always want to use the latest chromatic package, regardless of what is in package-lock.
Third-party PR's could downgrade the CI package.
#4365
#4366
#4367
N/A
=> ci: always use latest chromatic verson

.github/workflows/chromatic-fork.yml
This introduces a new `check` which prevents the `chromatic` build from running if the third-party pr has a `"` char in the PR label.
If there is a `"` in the branch name and a carbon maintainer started the workflow it could execute arbitrary code. 
#4365
#4366
#4367
#4368
N/A
=> ci(github-actions): prevent escape chars

.github/workflows/chromatic-fork.yml
Fix typo in workflow.
The branch name is not being passed correctly.
#4365
#4366
#4367
#4368
#4369
N/A
=> ci(github-actions): use branch name from check output

cypress/features/regression/accessibility/accessibilityDesignSystem.feature, src/components/button-bar/button-bar-test.stories.mdx, src/components/button-bar/button-bar.component.js, src/components/button-bar/button-bar.config.js, src/components/button-bar/button-bar.d.ts, src/components/button-bar/button-bar.spec.js, src/components/button-bar/button-bar.stories.mdx, src/components/button-bar/button-bar.style.js, src/components/button-bar/index.d.ts, src/components/button-bar/index.js, src/components/button/button.spec.js, src/components/button/button.style.js
**Use case**
The design system offers a Button Bar that is currently not available in Carbon.
It must be seen as a new variation and does not correspond to Button Toggle.
**Acceptance Criteria**
There should be a way to add a Button Bar to a product using Carbon.
It should match the Design specified here: https://brand.sage.com/d/NdbrveWvNheA/components#/basics/buttons/variations
Ensure only Button or IconButton children for this component.
We refer to Buttons v 0.1.0. This version should be implemented.
Storybook MDX updated with a compatibility table showing which version of the Design System is implemented
There is no such component, buttons would need to be added separately and be styled by the user.
Screenshot:
=> feat(button-bar): create button-bar component - FE-4259

.github/workflows/forked-ci.yml
Only run Cypress after check has finished
=> ci(forked): only run cypress after check

src/components/pager/pager.component.js, src/components/pager/pager.spec.js
Update show select value when page size prop is changed
Show select value is not updated when page size prop is changed
https://codesandbox.io/s/beautiful-oskar-yxjes?file=/src/index.js
Resolves #4344
https://codesandbox.io/s/carbon-quickstart-forked-fkwhb
=> fix(pager): update show select value when page size prop is changed

src/__internal__/input/input-presentation.style.js, src/components/form/form.stories.mdx, src/components/form/form.style.js, src/components/inline-inputs/inline-inputs.component.js, src/components/inline-inputs/inline-inputs.d.ts, src/components/inline-inputs/inline-inputs.spec.js, src/components/inline-inputs/inline-inputs.style.js, src/components/table/__snapshots__/table.spec.js.snap, src/components/table/table-row/__snapshots__/table-row.spec.js.snap
Inline inputs should have the ability to set label and content width the same way as other form elements 
Inline inputs could not be aligned with other form elements when their labels are in-line
Resolves #4300 
1. run npm start
2. open http://localhost:9001/?path=/story/design-system-form--default-with-sticky-footer
3. open http://localhost:9001/?path=/story/design-system-inline-inputs--default-story
=>  feat(inline-inputs): add labelWidth and inputWidth props (FE-4279)

src/components/decimal/decimal.component.js, src/components/decimal/decimal.spec.js, src/components/decimal/decimal.stories.mdx, src/components/switch/switch.stories.mdx
Get locale from i18n provider if not passed in props.
Locale is provided only in props.
https://codesandbox.io/s/carbon-quickstart-forked-lsrqo?file=/src/index.js
=> refactor(decimal): get locale from i18n provider if not passed in props - FE-4318

.github/workflows/cypress-pr.yml, .github/workflows/cypress.yml, .github/workflows/forked-ci.yml
Remove duplicated Cypress workflow and have it in one place: `cypress.yml`. 
For non-forked branches, this will be triggered from `cypress-pr.yml` which is run on `pull_request`.
For forked branches, this will be triggered manually via the `forked-ci.yml` workflow. Note this workflow will still run both Cypress and Chromatic on the relevant PR branch.
Duplicate Cypress workflows and different ones for forked and non-forked branches.
=> ci(cypress): set up single manually triggered workflow

.github/workflows/forked-ci.yml
Correct line setting the PR number in the forked CI process
It is currently setting it incorrectly, this workflow does not have access to `github.event.pull_request.number`
=> ci(forked-ci): fix number input

cypress/support/step-definitions/anchor-navigation-steps.js
add an `alias` -> `as("anchorNavigation")`
```javascript
Then("{string} anchor navigation section is visible", (anchorName) => {
anchorNavigationStickyMainPage(anchorName).as("anchorNavigation");
cy.get("@anchorNavigation").should("be.visible");
});
```
Tests for `AnchorNavigation` component are not stable.
=> test: add an alias to make test stable

src/components/form/__internal__/form-summary.component.js, src/components/form/__internal__/form-summary.style.js, src/components/form/form.spec.js, src/components/form/form.stories.mdx, src/components/i18n-provider/i18n-provider.d.ts, src/locales/en-gb.js
BREAKING CHANGE: `errors.messages.formSummary` key returns an array of strings instead of a string
https://codesandbox.io/s/carbon-quickstart-forked-9xjd9
=> refactor(form-summary): change the design of the validation message - FE-4262

src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.spec.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu-item/menu-item.d.ts, src/components/menu/menu-item/menu-item.spec.js
Fixes: #4303
Add `onSubmenuOpen` and `onSubmenuClose` to `MenuItem`. These are callbacks triggered when the submenu is opened or closed.
No prop to trigger custom actions when submenus open/close.
https://codesandbox.io/s/carbon-quickstart-forked-qhweu?file=/src/index.js
=> feat(menu-item): add callback for submenu toggle

src/components/navigation-bar/navigation-bar.component.js, src/components/navigation-bar/navigation-bar.d.ts, src/components/navigation-bar/navigation-bar.spec.js, src/components/navigation-bar/navigation-bar.stories.mdx, src/components/navigation-bar/navigation-bar.style.js
Allow Navigation Bar to use sticky options and specify position.
https://user-images.githubusercontent.com/77274590/132504285-b9497eac-018a-4441-9c8e-c22a3eb70753.mov
No sticky options and specify position.
https://codesandbox.io/s/carbon-quickstart-forked-t47jo?file=/src/index.js
`npm run start`
http://localhost:9001/?path=/story/design-system-navigation-bar--sticky
=> feat(navigation-bar): add sticky position - FE-4268

src/components/tile-select/__internal__/accordion/accordion.component.js, src/components/tile-select/__internal__/accordion/accordion.d.ts, src/components/tile-select/__internal__/accordion/accordion.spec.js, src/components/tile-select/__internal__/accordion/accordion.style.js, src/components/tile-select/__internal__/accordion/index.js, src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.d.ts, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.stories.mdx, src/components/tile-select/tile-select.style.js
Adds support for rendering an `Accordion` as the footer of `TileSelect`. Pass a desired layout to the `accordionContent` prop and a use the `accordionControl` render prop to supply the control for the expanded state of the accordion, this is achieved by toggling the `accordionExpanded` prop.
No support for rendering an accordion footer
`docs/design-system-tile-select--with-accordion-footer`
https://codesandbox.io/s/carbon-quickstart-forked-rm5j9?file=/src/index.js
=> feat(tile-select): add support for rendering accordion footer FE-4283

src/components/split-button/split-button-test.stories.mdx, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js
Rewrite SplitButton class component to functional
BREAKING CHANGE: SplitButton is now a functional component and cannot be extended
~~- [ ] Related issues linked in commit messages if required~~
=> refactor(split-button): rewrite class component to functional

.github/workflows/forked-ci.yml
Use the number input by the user to pass to the Chromatic workflow.
The incorrect number is being passed, the pull request number will be undefined.
=> ci(forked): use input number instead of pr

src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/menu-divider/menu-divider.component.js, src/components/menu/menu-item/menu-item.component.js, src/components/menu/menu.component.js
Remove incorrect menubar ARIA role in the Menu component and unused menuitem role in MenuItem Component.
Move `data-component="menu-item"` attribute to the menu item 'li' wrapper as it is overwritten by the Link component attribute.
Axe test failing in Navbar component, caused by incorrect use of menubar role in Menu Component
=> fix(menu): incorrect menu aria role (FE-4327)

.github/workflows/chromatic-push.yml
Re-introduce running the chromatic workflow on push to master, major or tags
Chromatic is not running on push to any of these branches
=> ci(chromatic): run workflow on push

src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.d.ts, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.d.ts, src/components/select/multi-select/multi-select.spec.js, src/components/select/multi-select/multi-select.stories.mdx, src/components/select/select-list/select-list-container.style.js, src/components/select/select-list/select-list.component.js, src/components/select/select-list/select-list.spec.js, src/components/select/simple-select/simple-select-test.stories.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.d.ts, src/components/select/simple-select/simple-select.spec.js, src/components/select/simple-select/simple-select.stories.mdx
- Add `listPlacement` prop passed to Popover component `placement` prop.
- Add `flipEnabled` prop to enforce list placement if the set placement doesn't fit.
- Change the list opening animation from accordion to fading.
No way to set the select options list position.
https://codesandbox.io/s/carbon-quickstart-forked-ngpvp
=> feat(simple-select): add prop to specify the open direction of a select list - FE-4316

src/components/pager/pager.d.ts
When consuming the latest version of Carbon in our application, we found the type for pageSizeSelectionOptions was causing errors in our linter.
The type is: `Record<string, unknown>` when this should be `Record<string, unknown>[]`
=> fix(pager): resolve typing for pageSizeSelectionOptions to be an array of objects

src/components/icon/icon.component.js, src/components/icon/icon.d.ts
Add missing `sage_coin` to `type` defintion in `icon.d.ts`
Tidies up the prop table documentation
`sage_coin` missing in `type` definition in `icon.d.ts`
=> fix(icon): add missing sage_coin to type definition

cypress/features/regression/dialog.feature, cypress/locators/dialog/index.js, cypress/locators/dialog/locators.js, cypress/support/step-definitions/dialog-steps.js, src/components/dialog-full-screen/content.style.js, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog/dialog.spec.js, src/components/dialog/dialog.stories.mdx, src/components/dialog/dialog.style.js, src/components/form/form.component.js, src/components/form/form.d.ts, src/components/form/form.spec.js, src/components/form/form.stories.mdx, src/components/form/form.style.js
BREAKING CHANGE: Sticky footers on Form will no longer disappear on
scrolling to the bottom of the form.
The new height prop on Form can be used to set the size of a Form
with a sticky footer, particularly within a Dialog
Rewrite the sticky footer to not use `position: fixed`, it is now positioned underneath the form content on the page, so the scroll box for the content is above it. This means keyboard focus can no longer be lost underneath the sticky footer.
This means it will no longer animate away and turn into a normal footer when you scroll to the bottom of the form. 
Also add. new `height` prop to `Form` which is needed to correctly set the height of a `Form` within a `Dialog`.
Currently the sticky footer just uses CSS position sticky to appear "above" the bottom of the form. This …
=> refactor(form): rewrite sticky footer and add height prop

src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/__internal__/tabs-header/tabs-header.spec.js, src/components/tabs/__internal__/tabs-header/tabs-header.style.js
Fixes: #4254
Remove extra grey border on warning/info tabs. For position left, and for normal size and large size (I haven't added screenshots for the large size):
An extra grey border is visible on warning/info tabs, for position left: 
Look at both tabs positioned left validations stories: 
https://carbon.sage.com/?path=/docs/tabs--with-validations-positioned-left
https://carbon.sage.com/?path=/docs/tabs--with-validations-sized-large-positioned-left
Chromatic will capture the visual changes as well for these.
=> fix(tabs): remove extra grey border on warning and info

cypress/features/regression/dateInput.feature, cypress/fixtures/commonComponents/dateInput.json, cypress/support/helper.js, cypress/support/step-definitions/date-input-steps.js
Fix the `Change Date Input component minDate` and `Change Date Input component maxDate` tests in Cypress. 
These now set a min/max date in the future to test against, rather than always testing against today's date, which can fail depending on the date/day.
Currently these tests are testing against today's date, so if the 1st of the month falls on a Monday, or the last day of the month falls on a Sunday these will fail.
http://localhost:9001/?path=/story/date-input-test--default-story
=> test(cypress): fix date input min and max date tests FE-4438

src/components/tabs/tabs.component.js, src/components/tabs/tabs.spec.js
Fixes: #4501
Fix to allow validations to display correctly when `renderHiddentTabs={false}`.
When `renderHiddentTabs={false}`, validations do not display on the tab header.
See codesandbox from the Github issue below
=> fix(tabs): enable validations when renderHiddenTabs set

src/components/select/filterable-select/filterable-select.component.js, src/components/select/filterable-select/filterable-select.spec.js, src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js, src/components/select/simple-select/simple-select.component.js, src/components/select/simple-select/simple-select.d.ts, src/components/select/simple-select/simple-select.spec.js, src/components/select/utils/is-expected-option.js, src/components/select/utils/is-expected-option.spec.js
fix #4482
Select components no longer set the selectedValue to `defaultValue` on re-renders: this was causing issues
as in some demos no `value` or `defaultValue` is passed so when the theme changes and the component
re-renders the new `selectedValue` is `undefined`. Also updates the `isExpectedOption` function to
handle for empty strings and objects.
Behaviour in master:
Behaviour in PR:
Behaviour is testable by following the steps included in the linked issue for all Select components
All stories should have brush test to ensure no functionality has broken following change
Open selects, pick `red` then click the button …
=> fix(multi-select): prevent re-renders from setting selectedValue to undefined FE-4396

.storybook/theme-selector/index.js, .storybook/theme-selector/register.js, docs/testing-styleguide.md, package-lock.json, package.json, src/components/button-toggle-group/button-toggle-group.stories.mdx, src/components/button/button-test.stories.mdx, src/components/date/date.stories.mdx, src/components/popover-container/popover-container.stories.mdx, src/components/search/search.stories.mdx, src/components/vertical-divider/vertical-divider.stories.mdx
Chromatic will snapshot all the themes by duplicating the story onto the same canvas.
Chromatic only snapshots the sage theme.
FE-4444
Please review all the changes in Chromatic. There should be no differences but the content will be duplicated 4 times, one for each theme.
=> ci(chromatic): screenshot all themes - FE-4444

rfcs/text/refactoring-date-component.md
RFC detailing a proposal for a new implementation for the `Date` component
Existing implementation has considerable technical debt and issues and pending features
POC (*very* rough implementation):
https://codesandbox.io/s/poc-of-rfc-proposal-ctdfw?file=/src/index.js
=> docs(date): rfc proposing new date component

docs/development-roadmap.stories.mdx
Add `Row` and `Column` to deprecation list in the development roadmap.
Remove `shouldComponentUpdate` decorator from list as it's already gone.
=> docs(dev-roadmap): add row and column to deprecation list FE-4398

package-lock.json, package.json
New version of packege includes a new types of tokens with yang. New version: 1.80.0
The latest version of the package is: ^1.73.0
=> chore(deps): update design tokens package to the last version

src/components/search/search.component.js, src/components/search/search.spec.js
Fixes a bug when tabbing focus is lost to the search button when searchButton is true but search has
no value.
fixes #4480
N/A
Please use the codesandbox built from the linked issue
=> fix(search): correct tabbing order when searchButton true and no search value - FE-4390

src/components/progress-tracker/index.d.ts, src/components/progress-tracker/index.js, src/components/progress-tracker/progress-tracker-test.stories.js, src/components/progress-tracker/progress-tracker.component.js, src/components/progress-tracker/progress-tracker.config.js, src/components/progress-tracker/progress-tracker.d.ts, src/components/progress-tracker/progress-tracker.spec.js, src/components/progress-tracker/progress-tracker.stories.mdx, src/components/progress-tracker/progress-tracker.style.js, src/style/themes/base/base-theme.config.js
Creates the `ProgressTracker` component. It currently supports two colour `variant`s ("default" and
"traffic"), either "horizontal" or "vertical" `orientation`, various `size`s ("small", "medium",
"large"), a current `progress`,  supports rendering custom strings through the `currentProgressLabel` and `maxProgressLabel` props or the option to render default percentages by setting `showDefaultLabels` (the `labelPosition` can also be set depending on the orientation). The component also supports changing the `direction` the bar travels when in vertical orientation. 
New component
`progress-bar` stories have been added
=> feat(progress-tracker): create new component  FE-4367

src/__internal__/focus-trap/focus-trap.component.js, src/__internal__/focus-trap/focus-trap.spec.js, src/components/modal/__internal__/modal-manager.js, src/components/modal/__internal__/modal-manager.spec.js, src/components/modal/modal.component.js
fix #4502
Add `triggerRefocusFlag` to trigger the refocusing of an element in the trap. Also adds a listener to support
maintaining a record of last focused element which will be focused when the flag is set.
When there are at least two `Modal`s stacked and one closes the `ModalManager` will trigger a
callback to set a flag which is passed to the `FocusTrap` via `ModalContext` and triggers
refocussing of an element within the top most `Modal`
Stacked Modals will result in focus not being trapped when the top most modal closes
=> feat(focus-trap): add flag to trigger refocus of either last focused element first element FE-4422

src/components/pages/index.d.ts, src/components/pages/index.js, src/components/pages/pages-test.stories.mdx, src/components/pages/pages.stories.mdx
Fixes: #4562
- Export `Page` from `Pages` index file (js and ts).
- Fix console errors in `Pages` stories by adding some content on the third page in each one.
`Page` is not exported from the `Pages` index file.
Every `Pages` story on Storybook has this console error: 
https://codesandbox.io/s/bitter-meadow-4bxzx?file=/src/index.js
=> fix(page): export page correctly from pages interface

.github/workflows/semantic-release.yml, .github/workflows/storybook.yml, .storybook/manager.js, .storybook/version-picker/constants.js, .storybook/version-picker/fetch-data.js, .storybook/version-picker/index.js, __mocks__/fs.js, jest.conf.json, package-lock.json, package.json, scripts/generate_metadata/generate_metadata.mjs, scripts/generate_metadata/generate_metadata.spec.js, scripts/generate_metadata/index.mjs, src/__spec_helper__/index.js
Add versioned docs for the Carbon Storybook. As of this PR every new version of Carbon going forward will have archived docs available at `https://carbon.sage.com/v/X.X.X/index.html`.
The process for generating these is this: 
- When a commit generating a new version of Carbon is pushed to master, the `storybook.yml` workflow will push the new version to `carbon.sage.com` as usual.
- The semantic-release workflow will:
- Release the new version to npm as usual.
- Run the new `generate_metadata` script to generate a metadata json file with the archived versions and the corresponding urls for their storybooks.
- Push the archived storybook to the s3 bucket.
- Push the `metadata.json` to the s3 bucket, overwriting the existing one (after the first run).
This PR then introduces a custom addon …
=> docs(storybook): add version switcher

cypress/integration/common/simpleSelect.feature, src/components/select/select-list/select-list.component.js, src/components/select/select-list/select-list.spec.js, src/components/select/simple-select/simple-select-test.stories.js
Wrapped text should render at the correct height in the SelectList. Adding listRef.current to the
height calculation enables this to happen as expected.
fixes #4489
- Text in the SelectList should wrap correctly and apply the correct height the select option.
- Select option height is not being calculated correctly.
N/A
Use the codesandbox build from the Source `Issue #4489`
=> fix(select): render wrapped text correctly in SelectList - FE-4044

cypress/integration/common/flatTable.feature, src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.stories.mdx, src/components/flat-table/flat-table.style.js
Fixes: #4259 
Make `FlatTable` focusable by keyboard by giving the table wrapper div a `tabindex`. Give it the usual focus outline when it is focused and a `role` of `region`.
Note this focus border will **only** show when focus is given via keyboard, not via mouse. This allows keyboard users to scroll the table using the arrow keys, without impacting the existing mouse scroll functionality.
Also add an `overflowX` prop to `FlatTable`. This allows the user to create a horizontally scrolled table without another wrapping div. It can be scrolled horizontally using the keyboard now as well. Add a new story for this.
- Keyboard users cannot focus or scroll a `FlatTable`, either vertically or horizontally.
- Horizontal scrolling can only be set up by wrapping the table in an extra div with …
=> fix(flat-table): make scrollable content accessible via keyboard

cypress/support/step-definitions/tabs-steps.js, src/components/tabs/__internal__/tab-title/index.d.ts, src/components/tabs/__internal__/tab-title/tab-title.component.js, src/components/tabs/__internal__/tab-title/tab-title.d.ts, src/components/tabs/__internal__/tab-title/tab-title.spec.js, src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/__internal__/tabs-header/index.d.ts, src/components/tabs/__internal__/tabs-header/tab-header.d.ts, src/components/tabs/__internal__/tabs-header/tabs-header.style.js, src/components/tabs/tabs.component.js, src/components/tabs/tabs.stories.mdx
fix #4517
fix #4524
The `headerWidth` story has multiple `Tab` components with the same `tabId` which causes axe warnings to be generated
`TabHeader` now renders a `div` container and `TabTitle` renders either a `button` or `a` element. This fixes accessibility issues raised against the old implementation relating to focusable children  not being read out by screen readers: `tabIndex` for `ValidationIcon` is now null and `customLayout` story has been updated to remove `ActionPopover`.
Renders `ul` and `li` elements, has multiple accessibility errors on stories
No `d.ts` files for `TabTitle` and `TabHeader`
Test all Tabs stories for accessibility errors and to confirm no regressions after refactor away from `ul` `li`
You can …
=> docs(tabs): update headerWidth story to use unique id for each tab child  FE-4440

.github/workflows/semantic-release.yml, .storybook/manager.js
- Disable the Storybook version switcher in development mode (it doesn't work anyway).
- Hide the test stories and set the view mode to docs on the versioned Storybook docs.
- The version switcher tries to fetch the metadata in dev mode and fails due to CORS errors (and rightfully so). This give us some console errors.
- The versioned docs contain the test stories and default to canvas view.
=> docs: disable version switcher in dev mode

.codesandbox/ci.json
- Add our TypeScript codesandbox template to the codesandbox ci config so it's built in every PR, like the carbon-quickstart one is
- Only a JavaScript codesandbox is built automatically in our PRs
=> ci(codesandbox): add typescript template for pr generation

src/components/date-range/date-range.stories.mdx
Date Range requires start and end labels so that it complies with the WCAG rule that input elements
must have labels.
fixes #4570
N/A
To test this, please visit the `Date Range -> Allow Empty Value` example. Visit the `Canvas` tab and check for accessibility issues. None should be present for this example.
=> docs(date range): add start and end labels to allow empty value example - FE-4478

src/components/search/search.component.js, src/components/search/search.d.ts
Incorrect tabindex behaviour on Search component caused the blue outline issue in DuellingPicklist. This PR fixes this issue.
Check DuellingPicklist stories and confirm that the blue outline no longer occurs
=> fix(search): fix incorrect tabindex behaviour - FE-4412

src/components/link/link.component.js, src/components/link/link.stories.mdx, src/locales/en-gb.js, src/locales/pl-pl.js
Fixes #4581 
After opening the sandbox, focus the browser and press tab to display Skip Link and check that the text is equal to "Different text"
https://codesandbox.io/s/confident-shockley-hzmjr?file=/src/index.js
=> feat(link): make skip link possible to be translated

src/components/tile-select/tile-select.component.js, src/components/tile-select/tile-select.spec.js
Opacity of 0.3 is now applied to the prefixAdornment when disabled is true for TileSelect component
fixes #4606
Opacity of 0.3 applied to the prefixAdornment when disabled is true on TileSelect Component.
Opacity is not applied to the prefixAdornment when disabled is true on TileSelect Component.
[Codesandbox link](https://codesandbox.io/s/vigorous-bash-v54eq?file=/src/index.js)
=> fix(tile select): apply opacity to prefixAdornment when component is disabled - FE-4489

.github/workflows/cypress.yml, cypress/README.md, package.json
refactor for `cypress.yml` file to use `with` 
the [link](https://github.com/Sage/carbon/runs/4456795514?check_suite_focus=true) to report of passing tests
Cypress doesn't allow us to use `custom command`
=> ci(cypress): use cypress-io gh action for component tests

src/components/card/__snapshots__/card.spec.js.snap, src/components/link/link.spec.js, src/components/link/link.stories.mdx, src/components/link/link.style.js, src/components/pod/__snapshots__/pod.spec.js.snap
Describes the link using design tokens. Removes all possible 'theme' in css files (left theme where using elevation property - lack of tokens for elevations). 
The Link use the theme styled-component property.
=> feat(link): describe link component using design tokens

src/components/message/message.spec.js, src/components/message/message.style.js, src/components/message/type-icon/__snapshots__/type-icon.spec.js.snap, src/components/message/type-icon/type-icon.style.js
Describes the message using design tokens. Removes all possible 'theme' in css files 
The Message use the theme styled-component property.
=> feat(message): describe Message component using design tokens

cypress/fixtures/commonComponents/flatTable.json, cypress/integration/common/flatTable.feature, cypress/locators/flat-table/index.js, cypress/support/step-definitions/flat-table-steps.js, src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table-cell/flat-table-cell.spec.js, src/components/flat-table/flat-table-cell/flat-table-cell.style.js, src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table-row/__snapshots__/flat-table-row.spec.js.snap, src/components/flat-table/flat-table-test.stories.mdx
Increase specificity of padding props so that the pl prop is correctly applied to a flat table cell
when it is a sub row.
fixes #4348
pl prop should apply the desired padding-left to a flat table cell when it is nested in a sub row.
pl prop is not being applied to a flat table cell when it is nested in a sub row.
Please use the codesandboxes provided [here](https://github.com/Sage/carbon/pull/4617#issuecomment-984547871)
=> fix(flat-table-cell): ensure that pl prop is correctly applied to a sub row - FE-4306

src/components/date/date.stories.mdx
Currently `with custom date format` does not have a code example due to invalid JSX.
N/A
Make sure that `Date Input -> with custom date format` example has a `show code` option and clicking this expands to show the code that makes this example.
=> docs(date): ensure with custom date format example has a code example - FE-4697

src/components/checkbox/checkbox-group.spec.js, src/components/checkbox/checkbox.style.js
Fixes #4641
Remove margin applied by the Form component to Checkboxes in a CheckboxGroup
Incorrect margin of Checkboxes inside a CheckboxGroup when in Form
=> fix(checkbox-group): remove incorrect margin in form (FE-4634)

src/components/pages/page/page.component.js, src/components/pages/page/page.spec.js, src/components/pages/pages.style.js
AppWrapper is due to be deprecated but before this can happen, we must remove it from the Page
component. AppWrapper has been removed in favour of Box in the Page component.
fixes FE-4574
Replace `AppWrapper` with `Box` component.
Page component uses `AppWrapper` but `AppWrapper` is due to be deprecated.
There should be no differences in appearance or functionality between Pages on `master` and Pages on this PR. 
A codesandbox can be prepared if a test case arises.
=> refactor(page): remove AppWrapper from component - FE-4574

src/components/split-button/__snapshots__/split-button.spec.js.snap, src/components/split-button/split-button-test.stories.mdx, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js
Ensures that a type of button is specified on the split button toggle. This is to make sure that
when split button is used inside of a HTML form, the split toggle button does not automatically
submit the form when clicked.
fixes #4651
- `Split Button Toggle` has a type of `button`.
- `Split Button Toggle` does not a type specified so when `Split Button` is used in a Form, the toggle button acts as a submit button by default.
N/A
- Codesandbox built using the example in Github issue can be found [here](https://github.com/Sage/carbon/pull/4678#issuecomment-1005928848).
=> fix(split-button): apply type of button to split button toggle - FE-4969

src/components/date-range/date-range-test.stories.mdx, src/components/date-range/date-range.component.js, src/components/date-range/date-range.spec.js
closes #4615
When `DateRange` allows for empty values and both stored dates are empty, updating one of the dates via `onChange` should only update that date and not its sibling.
When `allowEmptyValue` is set to true for the start/end date props and `value = ["",""]`, updating one of the date values via `onChange` also causes the other value to update to the current date.
A test which verifies that current behaviour occurs actually exists in the codebase, so this has been removed and updated with a new test that verifies if the proposed behaviour occurs.
The following CodeSandbox is an example of the broken behaviour:
https://codesandbox.io/s/thirsty-gagarin-wc56o?file=/src/index.js
=> fix(date-range): prevent both fields becoming populated when one value passed (FE-4506)

src/components/batch-selection/__snapshots__/batch-selection.spec.js.snap, src/components/carousel/carousel.spec.js, src/components/icon/icon.spec.js, src/components/icon/icon.style.js, src/components/pod/__snapshots__/pod.spec.js.snap, src/components/portal/__snapshots__/portal.spec.js.snap, src/components/search/search.spec.js, src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap
Describes the icon using design tokens. Removes all possible 'theme' in css files (left theme where calling styledColor function).
Icon styles use design tokens
=> refactor(icon): use design tokens to describe icon component

cypress/integration/common/tooltip.feature, src/components/textbox/textbox.spec.js, src/components/tooltip/tooltip-pointer.style.js, src/components/tooltip/tooltip.component.js, src/components/tooltip/tooltip.spec.js, src/components/tooltip/tooltip.style.js
Describes the tooltip with design tokens. 
Leaves a theme for z-index (layer order tokens will be created in the next step) and custom colors.
Changes the tooltip background color according to the design.
Adds missing props in tooltip.style.js and tooltip-pointer.style files.
Updates the tests after the above changes.
The Tooltip use the theme styled-component property.
The current background-color for `tooltip` is black color. 
The propTypes in the css files are missing used props.
The correct appearance can be checked in the component: `tooltip`.
For theme: mint and aegean there should be no differences.
Use devtools to check if tooltips use css variables.
=> feat(tooltip): describe tooltip using design tokens

src/components/tabs/__internal__/tab-title/tab-title.style.js, src/components/tabs/tabs.component.js, src/components/tabs/tabs.spec.js
fix #4640, fix #4611
Removes `onFocus` handler to prevent `onTabChange` callback being triggered twice `onClick` and to
ensure that tabs become active on up click rather than down click
Calls `onTabChange` twice when tabs are clicked
Tabs are active on mouse down
=> fix(tabs, tab-title): remove onFocus to stop firing callback twice and tabs activate onmouseup FE-4509

src/__internal__/input-icon-toggle/input-icon-toggle.spec.js, src/__internal__/input-icon-toggle/input-icon-toggle.style.js, src/__internal__/input/__snapshots__/input-presentation.spec.js.snap, src/__internal__/input/__snapshots__/input.spec.js.snap, src/__internal__/input/input-presentation.spec.js, src/__internal__/input/input-presentation.style.js, src/__internal__/input/input-sizes.style.js, src/__internal__/input/input.spec.js, src/__internal__/input/input.style.js, src/components/grouped-character/grouped-character.test.js, src/components/select/multi-select/multi-select.spec.js, src/components/simple-color-picker/__snapshots__/simple-color-picker.spec.js.snap
Introduces design tokens into internal `Input` and `InputPresentation` components, that are consumed in `Textbox` component.
`Textbox` component itself doesn't include any theme properties that could be replaced with tokens.
Following elements are affected by this change:
- Search
- Date Range
- Date Input
- Inline Inputs
- Numeral Date
- Pager
- Multi select
- Select
- Textarea
PR includes test updates for code related with changes.
Currently `Input` and `InputPresentation` are described by styled-components theme feature.
All styles in all themes should match. There should be no changes in mint or aegean theme.
Code sandbox: https://codesandbox.io/s/carbon-quickstart-forked-jkw4x
=> feat(textbox): describe Textbox component using design tokens - fe-4373

cypress/integration/common/pill.feature, src/components/pill/pill.spec.js, src/components/pill/pill.style.config.js, src/components/pill/pill.style.js, src/style/design-tokens/carbon-scoped-tokens-provider/__snapshots__/carbon-scoped-tokens-provider.component.spec.js.snap, src/style/themes/aegean/__snapshots__/aegean-theme.spec.js.snap, src/style/themes/base/base-theme.config.js, src/style/themes/mint/__snapshots__/mint-theme.spec.js.snap, src/style/themes/none/__snapshots__/none.spec.js.snap
Describes the pill component using design tokens.
Changes the backgroundColor for the ` positive`  color - token colorsSemanticPositive500  used. 
_(Both the Pill and Messages components use the same colorsSemanticPositive500 token. In the `mint` and `aegean` theme the colors are changed and are identical to those in sage(experimental). The color change for positive is required because of the contrast between background and text - accessibility contrast tests.  The changes made also change the color for the `message` component for the `success` state - same for all theme. )_
Changes the backgroundColor for the ` neutral`  color - token colorsSemanticNeutral500 used.
Changes the backgroundColor for the ` warning`  color - token colorsSemanticCaution400 used.
Adds missing props in the …
=> feat(pill): describe pill component using design tokens - FE-4454

.codesandbox/ci.json, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md, docs/development-roadmap.stories.mdx, docs/getting-started.stories.mdx
closes #4679
Update storybook to have:
- Updated quickstart code snippet
- Section detailing the deprecation of `AppWrapper`
- Links to a new starting template - which uses `Box` instead of `AppWrapper`. [View template here](https://codesandbox.io/s/carbon-quickstart-j5pb2?file=/src/index.js).
Also update all files (such as CI files, github PR templates, etc) to have a reference to the new starting template. 
Storybook quickstart guide is out of date - `AppWrapper` is to be deprecated and not recommended for future use and old imports need to be removed.
Sanity check that links are working, descriptions and examples used are sufficient and clear.
=> docs: update storybook quickstart and create new codesandbox template (FE-4718)

cypress/support/step-definitions/select-steps.js, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/select/list-action-button/list-action-button.style.js, src/components/select/option-group-header/__snapshots__/option-group-header.spec.js.snap, src/components/select/option-group-header/option-group-header.style.js, src/components/select/option-row/__snapshots__/option-row.spec.js.snap, src/components/select/option-row/option-row.spec.js, src/components/select/option-row/option-row.style.js, src/components/select/option/__snapshots__/option.spec.js.snap, src/components/select/option/option.spec.js, src/components/select/option/option.style.js, src/components/select/select-list/select-list.spec.js, src/components/select/select-list/select-list.style.js, src/components/select/select.style.js, src/components/select/simple-select/simple-select.spec.js
Describes the select using design tokens. Removes all possible 'theme' in css files
The select use the theme styled-component property.
=> feat(select): describe select component using design tokens

cypress/support/step-definitions/action-popover-steps.js, cypress/support/step-definitions/flat-table-steps.js, src/components/action-popover/action-popover.spec.js, src/components/action-popover/action-popover.style.js
Describes a action popover element using the tokens of the design.
Changes the left and right padding of menu items to - `--spacing150` (12px).
Removes white background from MenuButton when menu is open. 
Changes the color of the ButtonIcon to:  
- default color: `--colorsActionMinor500`
- hover color: `--colorsActionMinor600`
Changes the outline border thickness for focus - 3px.
Changes the color of the custom menu button on hover: 
- background: `--colorsActionMajorTransparent`
- color: `--colorsActionMajor600`
Updates tests when the above changes are made.
Action popover component use the theme styled-component property.
Current the left and right padding of menu items: 24px.
MenuButton has white background when menu is open.
Current outline border thickness for focus - 2px.
Current …
=> feat(action popover): describe action popover using design tokens, update tests - FE-4725

src/components/confirm/confirm.component.js, src/components/confirm/confirm.spec.js
=> fix(confirm): fix incorrect button margin - FE-4750

README.md
Update copyright year now that it's 2022.
=> docs(readme): change copyright year to 2022

src/components/loader/loader.component.js, src/components/loader/loader.d.ts, src/components/loader/loader.stories.mdx
When a Loader component is nested in a button, axe throws an error to say that there is no
discernible text. Loader should have a role of progressbar and an aria-label to solve this issue.
fixes #4644
- Loader should have a role of `progressbar`
- aria-label prop has been made available for Loader to use
- When a Loader is nested inside of a Button component there are now no logged accessibility issues
- Loader has no role
- aria-label is not available for Loader to use 
- When a Loader is nested inside of a Button component there is an accessibility issued logged by axe
N/A
Visit `Loader -> inside buttons` example in storybook. There should not be accessibility errors on this example.
=> fix(loader): give loader the correct role and aria-label prop - FE-4635

package.json
Sets `TZ=UTC` in test and test-update scripts
Tests fail in other timezones
=> test(test, test-update scripts): set timezone flag to UTC when running jest

src/components/dialog-full-screen/dialog-full-screen.style.js, src/components/dialog/dialog.style.js
Describes the Dialog and DialogFullScreen with design tokens.
The Dialog and DialogFullScreen use the theme styled-component property.
=> feat(dialog): describe dialog and dialog full screen with design tokens

src/components/navigation-bar/navigation-bar.spec.tsx, src/components/navigation-bar/navigation-bar.style.ts, src/components/portal/__snapshots__/portal.spec.js.snap, src/style/themes/base/base-theme.config.js, src/style/themes/base/index.d.ts
fix #4690
Sets the z-index of NavigationBar to stack it just below Modals and displays over main UI components
Has no z-index so does not stack over main UI components
=> fix(navigation-bar): add z-index so NavigationBar stacks just below Modals

src/__internal__/checkable-input/checkable-input.component.js, src/__internal__/checkable-input/checkable-input.spec.js, src/__internal__/form-field/form-field.component.js, src/__internal__/form-field/form-field.d.ts, src/__internal__/input-icon-toggle/input-icon-toggle.component.js, src/__internal__/input-icon-toggle/input-icon-toggle.d.ts, src/__internal__/input-icon-toggle/input-icon-toggle.spec.js, src/__internal__/label/label.component.js, src/__internal__/label/label.d.ts, src/__internal__/label/label.spec.js, src/__internal__/tooltip-provider/index.js, src/components/help/help.component.js, src/components/help/help.d.ts, src/components/textarea/textarea.component.js, src/components/textarea/textarea.spec.js, src/components/textbox/textbox.component.js, src/components/textbox/textbox.spec.js, src/hooks/__internal__/useInputAccessibility/index.spec.js, src/hooks/__internal__/useInputAccessibility/useInputAccessibility.js
fix #4725
aria-describedby should point to icons instead of their tooltips, as these icons already have aria-label attribute
aria-describedby in the input points to tooltips which are not yet displayed
=> fix(accessibility): fix incorrect aria-describedby on input  (FE-4713)

src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.stories.mdx, src/components/dialog/dialog.component.js, src/components/dialog/dialog.stories.mdx, src/components/sidebar/sidebar.component.js, src/components/sidebar/sidebar.stories.mdx, src/components/toast/toast.component.js, src/components/toast/toast.stories.mdx, src/locales/en-gb.js, src/locales/locale.d.ts, src/locales/pl-pl.js
This PR fixes incorrect aria-labels in Toast, Sidebar, Dialog and DialogFullScreen and makes them translatable
Fixes #4142 
Check if aria-label on components listed above is correct, also check if changing the locale to polish changes these values as well
=> feat: dismissible buttons labels - FE-4154

cypress/support/step-definitions/search-steps.js, src/components/search/search.spec.js, src/components/search/search.style.js
Describes the Search component using design tokens. Removes all possible 'theme' in css files
=> feat(search): describe search component using design tokens

.storybook/version-picker/index.js
Correctly sort versions in Storybook version picker by semantic version: 
The versions are currently sorted in chronological order of when each version was realised. So when we patch versions, they will be displayed in the incorrect order like this:
=> fix(docs): sort versions by semver in picker

cypress/fixtures/commonComponents/toast.json, cypress/integration/common/toast.feature, cypress/support/step-definitions/toast-steps.js, src/components/toast/toast-test.stories.mdx, src/components/toast/toast.style.js
Fixes: #4730 
Change `Toast` position to fixed, so it stays at the top of the viewport when it is scrolled down.
Add a Cypress test which scrolls the page down to test `Toast` is still visible.
`Toast` currently has a position absolute set, which means it can be scrolled off the top of the page.
See issue PR below and use the http://localhost:9001/?path=/story/toast-test--default-story story with the `scrollablePage` control set to true to test.
=> fix(toast): make toast position fixed to top of viewport

src/components/decimal/decimal.component.js, src/components/decimal/decimal.spec.js
During the functional refactor of Decimal, a bug was introduced that caused a console error to
incorrectly fire when a precision prop was not specified.
fixes #4826
Bug was caused because a custom prop type validation does not work on default function parameters. 
`Const Decimal = ({precision = 2}) => {}` ❌  
`Const Decimal = ({precision}) => {}
Decimal.defaultProps = {precision: 2}` ✅ 
You can see the new behaviour by looking at the `decimal-precision` by `codesandbox[bot]`.
=> fix(decimal): fix precision console error firing when no precision prop specified (FE-4941)

src/components/icon-button/icon-button.spec.js, src/components/icon-button/icon-button.stories.mdx, src/components/icon-button/icon-button.style.js
A bug was introduced in v101.2.0 where the background color of a disabled icon-button was made to
be grey. The correct colour should be transparent.
This patches #4790 to 101.2.x.
- Check `Confirm -> disableCancel` story to make sure that the `X` has the correct styling.
- New story for `icon-button` has been created called `disabled` so that Chromatic can catch any visual changes in future.
=> fix(icon-button): fix background color when component is disabled

rfcs/text/enzyme-to-rtl.md
This PR contains an RFC detailing why and how I think we should convert our unit tests from using Enzyme to React Testing Library.
Our unit tests currently use Enzyme as a testing utility for React components. This does not support React 17+ and it doesn't look like it will anytime soon.
---
This PR does not follow the typical PR process. Details of the RFC process can be found [here](https://github.com/Sage/carbon/blob/master/rfcs/README.md).
Please use 👍  if you approve.
=> docs(unit-tests): rfc for converting tests to rtl

src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap, src/components/date/__internal__/date-picker/day-picker.style.js, src/components/date/__internal__/navbar/__snapshots__/navbar.spec.js.snap, src/components/date/__internal__/navbar/button.style.js, src/components/date/__internal__/navbar/navbar.style.js, src/components/date/__internal__/weekday/__snapshots__/weekday.spec.js.snap, src/components/date/__internal__/weekday/weekday.style.js
- Rewrite of `DateInput`'s styling to use design tokens, and fit the latest design changes.
- Update snapshot tests to check the new styles
- `DateInput` uses the styled-component's `theme` property.
- Check in Storybook that the appearance is consistent with the new designs.
- Use devtools to check if the tokens are loading properly.
=> feat(date): describe using design tokens (FE-4735)

src/components/form/__internal__/form-summary.style.js, src/components/form/form.spec.js, src/components/form/form.style.js, src/components/portal/__snapshots__/portal.spec.js.snap, src/style/themes/base/base-theme.config.js
Describes Form component using design tokens. Removes all possible 'theme' in css files.
Removes the redundant form's object from base-theme.config.js.
=> feat(form): describe form using design tokens, update tests

.github/PULL_REQUEST_TEMPLATE.md
Remove the 123 from our PR template comment, whenever this gets left in and the PR is merged, `@semantic-release/github` thinks the PR is linked to [this issue](https://github.com/Sage/carbon/pull/123) and comments on it 😅 
=> ci(pr-template): remove 123 from template comment

cypress/fixtures/commonComponents/stepSequence.json, cypress/integration/common/stepSequenceItem.feature, cypress/support/step-definitions/step-sequence-steps.js, src/components/step-sequence/step-sequence-item/step-sequence-item.component.js, src/components/step-sequence/step-sequence-item/step-sequence-item.d.ts, src/components/step-sequence/step-sequence-item/step-sequence-item.spec.js, src/components/step-sequence/step-sequence-test.stories.mdx, src/components/step-sequence/step-sequence.stories.mdx
There is now a new flag called `hideIndicator` for the `StepSequenceItem` which, when set to true, hides the sequence indicator on non-completed steps. The gap on either side of the `StepSequenceItem` is now the same distance if there is the desire for no `indicator` to be shown. Example: 
If there is no indicator supplied, then there is a bigger gap on the left side of the `StepSequenceItem` text than on the right. 
- [ ✓ ] Commits follow our style guide
- [ ✓ ] Screenshots are included in the PR if useful
- [ ✓ ] All themes are supported if required
- [ ✓ ] Unit tests added or updated if required
- [ ✓ ] Cypress automation tests added or updated if required
- [ ✓ ] Storybook added or updated if required
- [ ✓ ] Typescript `d.ts` file added or updated if required
This can be tested by …
=> feat(step-sequence-item): support hiding indicator

src/components/navigation-bar/navigation-bar.component.tsx, src/components/navigation-bar/navigation-bar.spec.tsx, src/components/navigation-bar/navigation-bar.stories.mdx, src/components/navigation-bar/navigation-bar.style.ts
fix #4691
Surfaces `position`, `offset` and `orientation` props to support setting the `NavigationBar` to be
either `sticky` or `fixed` positioned.
Adds deprecation warning for `stickyPosition` and `stickyOffset` props in favour of using `position`, `offset` and `orientation` props
No support for setting position to `fixed`, `stickyOffset` and `stickyPosition` props have no deprecation warning
`navigation-bar--fixed` and `navigation-bar--sticky` stories should be tested
https://codesandbox.io/s/admiring-wilbur-uiwu52?file=/src/index.js
**--- No point in testing linked issue sandbox as interface has changed ---**
=> feat(navigation-bar): add position, offset and orientation props to enable fixed or sticky positions FE-4711

src/__internal__/sticky-footer/sticky-footer.spec.js, src/__internal__/sticky-footer/sticky-footer.style.js, src/components/carousel/slide/slide.style.js, src/components/select/select-list/select-list.style.js
Replaces deprecated tokens from the design-tokens package: `colorsComponentsNavigation`
Up
Sticky-footer, slide and select-list use the `colorsComponentsNavigation` tokens
Details of token substitution in the task FE-5002 - comments.
=> refactor(sticky-footer, slide, select-list): replace colorsComponentsNavigation tokens - FE-5002

src/components/grid/__snapshots__/grid.spec.js.snap, src/components/grid/grid-container/grid-container.component.js, src/components/grid/grid-container/grid-container.d.ts, src/components/grid/grid-container/grid-container.style.js, src/components/grid/grid-item/grid-item.component.js, src/components/grid/grid-item/grid-item.d.ts, src/components/grid/grid-item/grid-item.style.js, src/components/grid/grid.spec.js
Add styled-system grid props to GridContainer and GridItem
There is no possibility to customize the grid layout using the Carbon Grid component
=> feat(grid): add styled-system props (FE-4912)

cypress/support/step-definitions/tooltip-steps.js, src/__internal__/tooltip-provider/index.js, src/components/help/help.component.js, src/components/help/help.spec.js, src/components/help/help.stories.mdx, src/components/icon/icon.component.js, src/components/icon/icon.spec.js, src/components/numeral-date/numeral-date.stories.mdx, src/components/portal/__snapshots__/portal.spec.js.snap, src/components/radio-button/radio-button.stories.mdx, src/components/switch/switch-test.stories.mdx, src/components/switch/switch.stories.mdx, src/components/tooltip/tooltip.component.js
Resolve ARIA issues so the component is read correctly in voice readers:
- allow to pass aria-hidden attribute to the Icon HTML
- remove tooltip role from Help and Icon, that role should be set only on the tooltip itself
- add button role to Help
- add aria-describedby attribute to Help so it could reference the tooltip
fixes #4676
fixes #4634
fixes #4734
=> fix(help): icon tooltip voice reader issue (FE-979)

src/components/box/box.component.js, src/components/box/box.config.js, src/components/box/box.spec.js, src/components/content/content.spec.js, src/components/content/content.style.js, src/components/dismissible-box/dismissible-box.component.js, src/components/dismissible-box/dismissible-box.spec.js, src/components/dismissible-box/dismissible-box.style.js, src/components/portal/__snapshots__/portal.spec.js.snap, src/components/show-edit-pod/show-edit-pod.spec.js, src/components/show-edit-pod/show-edit-pod.style.js, src/components/tile/__snapshots__/tile.spec.js.snap, src/style/themes/base/base-theme.config.js, src/style/themes/base/index.d.ts
Describes PopoverContainer and Draggable components using design tokens. Removes all possible 'theme' in css files.
Removes redundant base-theme property.
=> feat(dismissible-box, box, content): describe components using design tokens, update tests

src/components/sidebar/__internal__/sidebar-header/sidebar-header.spec.js, src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.js
Describes sidebar-header component using design tokens.
Changes background color: `--colorsUtilityMajor025`
Updates tests when the above changes are made.
Sidebar header component use theme styled-component property.
Currently the background color is `rgb(255, 255, 255)`
The correct appearance can be checked in the component: `Sidebar`
Use devtools to check if component use css variables.
=> feat(sidebar-header): describe sidebar-header using design tokens, update tests - FE-5021

src/components/select/multi-select/multi-select.component.js, src/components/select/multi-select/multi-select.spec.js
fix #4727
Removes `useEffect` and make `onChange` calls within `setSelectedValue`
`onChange` is called on first render
=> fix(multi-select): prevent component calling onChange on first render when uncontrolled FE-4884

.storybook/preview.js, cypress/integration/common/simpleSelect.feature, src/components/select/simple-select/simple-select-test.stories.js, src/components/select/simple-select/simple-select.stories.mdx
- Change the maximum depth for action objects to 6, as it's broken for anything less than 5. 6 allows us to see the option selected on the onChange action for Select.
- Remove actions completely from Select docs, we only need them in the test stories. 
- Update implementation of actions in the test stories
- Change Cypress to run the actions tests over the test stories
As per #4878, whenever you try to open Select (via keyboard or mouse) in Storybook, it crashes the page.
You can test the new actions implementation here: http://localhost:9001/?path=/story/select-test--default
=> docs(select): stop stories from crashing when opening select

src/hooks/__internal__/useInputAccessibility/useInputAccessibility.js
check for empty string when creating the validation icon id
when the validation string is empty, aria-describedby is filled with non existent id
fixes #4839
=> fix(textbox): prevent axe issue when the validation string is empty (FE-4982)

cypress/locators/flat-table/index.js, cypress/locators/flat-table/locators.js, cypress/support/step-definitions/flat-table-steps.js, src/components/flat-table/__snapshots__/flat-table.spec.js.snap, src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.d.ts, src/components/flat-table/flat-table.spec.js, src/components/flat-table/flat-table.style.js
Fixes: #4822
Fixes: #4821
Note we will not be adding the `overflowY` prop for issue #4821 
Add a `width` prop to `FlatTable`.
Add a wrapper around the table element in `FlatTable` to handle the horizontal scrolling so it does not horizontally scroll the table footer. This means only the table content (including headings) can be scrolled horizontally, and not a `Pager` when it is in the footer. The `Pager` should be 100% of the width of the table. It is down to the user to use the responsive props on `Pager` to ensure that it fits within the table width.
The `width` and `overflowX` props cannot just be added to the `StyledFlatTable` as they don't work as expected on a `table` element.
When using the `width` and `overflowX` props on `FlatTable` with a `Pager` in the footer, scrolling …
=> feat(flat-table): add width prop

src/__spec_helper__/test-utils.js, src/components/button-bar/button-bar.spec.js, src/components/button/button.component.js, src/components/button/button.spec.js, src/components/multi-action-button/multi-action-button.component.js, src/components/multi-action-button/multi-action-button.spec.js, src/components/pill/pill.spec.js, src/components/simple-color-picker/color-sample-box/color-sample-box.spec.js, src/components/simple-color-picker/simple-color-picker.spec.js, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js, src/components/text-editor/text-editor.spec.js
Updates `expectError` util to support other console functions such as `warn` and renames the
function to `expectConsoleOutput`.
Adds deprecation warnings to `Button`, `SplitButton` and `MultiActionButton` when `as` prop used
Util only supports `console.error` and no deprecation warnings exist
Run unit tests for  `Button`, `SplitButton` and `MultiActionButton`, there should be no console output and all test should pass.
https://codesandbox.io/s/bold-dust-vr0lx1 -- check that console outputs deprecation warnings for the components
=> test(test-utils): refactor expectError to catch console warn and rename to expectConsoleOutput FE-5023

src/__internal__/popover/popover.component.js, src/__internal__/popover/popover.spec.js, src/components/modal/modal.component.js, src/components/select/__internal__/select-text/select-text.component.js, src/components/select/__internal__/select-text/select-text.spec.js, src/components/select/select-textbox/select-textbox.component.js, src/components/select/simple-select/simple-select.spec.js
Fixes: #4880
**First fix:** 
Fix the openOnFocus behaviour in SimpleSelect component by removing the unnecessary props passed down to `SelectText` from `SelectTextbox`. 
`SelectText` renders a span which is not focusable, therefore it doesn't need the focus or blur props that were currently being passed down. These were causing the `handleTextboxFocus` function in `SimpleSelect` to be called twice when clicking on the select input which was causing the broken behaviour as seen in Storybook.
**Second fix:**
Fixes the openOnFocus behaviour in every Select, FilterableSelect and MultiSelect when in a Dialog. This was caused by the portal generated by the Popover in the select list being in a different stacking context to the Dialog, so the scroll blocking background of the popover was always …
=> fix(select): fix openOnFocus behaviour when clicked

src/components/button/button.component.js, src/components/button/button.spec.js, src/components/multi-action-button/multi-action-button.component.js, src/components/multi-action-button/multi-action-button.spec.js, src/components/split-button/split-button.component.js, src/components/split-button/split-button.spec.js, src/components/tile/tile.component.js, src/components/tile/tile.d.ts, src/components/tile/tile.spec.js, src/components/tile/tile.stories.mdx, src/components/toast/toast.component.js, src/components/toast/toast.spec.js
Adds deprecation warning for `as` prop in Toast and Tile components
Updates warning for `Button`, `MultiActionButton` and `SplitButton` components to make it clearer which ones are triggering them
No warning for `Toast` and `Tile`
`Button`, `MultiActionButton` and `SplitButton` components have generic warning
Use sandbox based on linked one below
https://codesandbox.io/s/carbon-quickstart-forked-lvotbt -- don't test this one test the one codesandbox builds using this
=> feat(tile): surface variant prop and add deprecation warning for as prop FE-5029

.storybook/theme-selector/index.js, src/components/alert/alert.stories.mdx, src/components/confirm/confirm.stories.mdx, src/components/dialog-full-screen/dialog-full-screen.stories.mdx, src/components/dialog/dialog.stories.mdx, src/components/sidebar/sidebar.stories.mdx
- Modal based components in storybook are closed by default, unless it's taking a chromatic screenshot.
- Fixed the theme selector so you can use it if we have set `chromaticTheme`. Note that the `all` theme does not work at the moment. I've removed this broken code and will re-introduce it at a later date. It's also not possible to link to a theme.
When you visit the a modal based stories the component is open by default. Readers must close them to see the documentation.
FE-5107
=> docs: close modals by default - FE-5107

.storybook/withThemeProvider.js
Specify the three variants of `Sage UI` font to wait for when loading storybook.
Storybook waits until all fonts are loaded before rendering storybooks, but the specific variants of `Sage UI` font haven't been specified.
=> chore: amend withThemeProvider to load three SageUI variants

.storybook/withThemeProvider.js, docs/getting-started.stories.mdx, package-lock.json, package.json
Remove webfontloader, it's unsupported and isn't solving our loading issue on chromatic.
We recommend and use webfontloader to check if the font has finished loading.
N/A
N/A
Ensure there are no chromatic differences.
=> docs(chromatic): remove webfontloader

src/components/split-button/index.d.ts
fix #5049
Exports the prop type definition from the index file as well as the functional component
`MultiActionButton` is not correctly extending the `SplitButton` prop type as they are not exported from the index file
Export the built TS sandbox and test it locally that the component now supports `children` without throwing TS errors
I will help QA test this in a local TS project as the error isn't showing up in a codesanbox
https://codesandbox.io/s/determined-marco-9zqno9?file=/src/index.tsx
=> fix(split-button): ensure prop type definition is exported from index.d.ts file

src/components/button-bar/button-bar.test.js
Add tests for `button-bar` component to use new cypress-component-react framework for testing.
No tests at all
=> test(button-bar): add cypress tests

src/components/card/__snapshots__/card.spec.js.snap, src/components/link/link.spec.tsx, src/components/link/link.style.ts, src/components/pod/__snapshots__/pod.spec.js.snap
fixes https://github.com/Sage/carbon/issues/5088
- Navigate to `Link` stories and select `with icon`
- hover over the link and the colour of the icon should match that of the link
=> fix(link): apply correct hover colour to icon - FE-5143

src/components/date/__internal__/date-formats/date-formats.spec.js, src/components/date/__internal__/date-formats/index.js, src/components/date/__internal__/utils.js, src/components/date/__internal__/utils.spec.js, src/components/date/date.component.js, src/components/date/date.spec.js, src/components/date/date.stories.mdx
fix #4966
fix #5072
fix #5119
Ensures that the correct formats are used for input and output strings. Fixes the output string and
valid inputs for Chinese (CN) locales for example by using the [Intl](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl) util API to handle the format displayed
on blur of the text input
Ensures that the the callback passed to the `onBlur` prop is called when the text input is blurred.
Ensure that the rawValue matches formattedValue when a year string is only 2 digits long
Two issue have sandbox repros that can be tested
QA should also test DateRange against current master to ensure the blur behaviour remains consistent
https://codesandbox.io/s/carbon-quickstart-forked-vwnj65?file=/src/index.js
=> fix(date): ensure correct output format and input formats are used for given locale FE-5035

.github/workflows/cypress.yml
Update cypress docker image with `node14` to the latest version to use `chrome` with `v.100`
Currently we are using an old image with `chrome v.91`
All CI tests should be marked as pass - :heavy_check_mark:
=> ci(cypress-image): update to latest

.github/workflows/cypress.yml, package-lock.json, package.json
Removed `**/` for `**/package.json` and for `**/package-lock.json` to avoid failing on `ubuntu` CI machine
Updated version of `cypress` to `9.6.0`
Currently we are using as a `path` for `**/package.json` and for `**/package-lock.json`
Check if all jobs are passing check [this](https://github.com/Sage/carbon/actions/runs/2293970085) also in term we are not able to run directly from this `yml` just from `master`.
=> ci: change for proper path for cache

README.md
Add a status badge to the readme that will check the status of the latest Cypress run on master.
No status badge.
=> docs(readme): add cypress status badge

src/components/form/form.spec.js, src/components/form/form.stories.mdx, src/components/form/form.style.js
Margin should be applied to the div that wraps the textarea component and not just the form field of
textarea
fixes #5074
N/A
You can see the new behaviour by looking at the version in the comment by `codesandbox[bot]` or you can use https://codesandbox.io/s/serverless-violet-gsk4et
=> fix(form): apply margin correctly to textarea component in a form - FE-5146

src/components/progress-tracker/progress-tracker.component.js, src/components/progress-tracker/progress-tracker.config.js, src/components/progress-tracker/progress-tracker.d.ts, src/components/progress-tracker/progress-tracker.spec.js, src/components/progress-tracker/progress-tracker.stories.mdx, src/components/progress-tracker/progress-tracker.style.js
This can be used to set the width/height of the bar, for horizontal/vertical
orientations.
Fixes: #5106
Add `length` prop to `ProgressTracker`. 
This can be any valid CSS string and will set the width of horizontal bars, and height of vertical ones.
Also change the inner bar calculation to get the actual length of the outer bar from the DOM via a ref, and calculate a percentage of that, rather than a hardcoded `256px`.
There is currently no way for a user to change the length of the `ProgressTracker` component via props.
=> feat(progress-tracker): add length prop

src/components/date/__internal__/utils.js, src/components/date/__internal__/utils.spec.js, src/components/date/date.component.js, src/components/date/date.spec.js
fix #5120
Prevents `onChange` from being called when input is blurred and the value has not updated
When the initial value is different from the given locale's format it will call onChange when the input is blurred
Compare the the story in linked issue with local version
=> fix(date): prevent calling onChange when input is blurred and value has not changed FE-5161

src/components/portrait/portrait-initials.component.js, src/components/portrait/portrait.spec.js, src/components/portrait/portrait.style.js
The background of portrait should fill consistently when the component is zoomed to a value greater
than 100%
fixes #4939
N/A
You can test in Storybook by using the stories for `Portrait`. Zoom in on the browser and background should correctly fill. You can also use this [codesandbox](https://codesandbox.io/s/vigilant-dust-j8pm1x?file=/src/index.js) and when zooming in, the background should fill the component consistently. 
Might also be good to regression test in Storybook to make sure that nothing else with Portrait has been effected by this change.
=> fix(portrait): ensure background fills consistently when zoom is greater than 100% - FE-5102

cypress/integration/common/textarea.feature, cypress/support/step-definitions/text-area-steps.js, src/components/textarea/textarea-test.stories.js, src/components/textarea/textarea.style.js
- Modify inner `InputPresentation` container to use design token for controlling its vertical padding.
- Add label to `Textarea` test story to fix accessibility violation 
- The vertical padding is not correct and doesn't use design tokens.
(For devs) Both `InputPresentation` and `Input` have css rules for their `min-height`. `Textarea` programmatically controls its height with its internal logic (using `MIN_HEIGHT` constant in `textarea.style.js` on line 10). Since `InputPresentation` controls its own min-height using design tokens, the logic in `Textarea` becomes partially redundant, however we cannot currently modify the `MIN_HEIGHT` constant to use the design token value since we can importing its value as a css custom property and not a js variable. This does not cause an issue but …
=> feat(textarea): modify padding to use design tokens

src/__internal__/popover/popover.component.js, src/__internal__/popover/popover.spec.js, src/components/select/select.style.js
fix #5135
Ensures that the `Popover` the `SelectList` is rendered in appends to `document.body` if no parent
with `role="dialog"` is found
Updates select style to remove quotes around `cursor: "text"`
The `Popover` the `SelectList` is rendered tries to append to `document.body` with `role="dialog"` if `isInModal` context  flag is true
Select style has quotes around `cursor: "text"`
See linked issue
=> fix(select): ensure select list appends to body if no element with role dialog exists FE-5163

src/components/link/link.component.tsx, src/components/link/link.spec.tsx, src/components/link/link.stories.mdx, src/components/menu/__internal__/spec-helper/index.js, src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.spec.js, src/components/menu/menu.component.js, src/components/menu/menu.spec.js, src/components/menu/scrollable-block/scrollable-block.component.js
Fixes for Menu behaviour with screenreaders:
- add role="list" to main menu and submenu ul's, so that Voiceover on Safari announces as a list (see https://www.tempertemper.net/blog/accessibility-issues-when-removing-list-markers)
- change menu items which open submenus from <a> tags with no href (which semantically are just spans) to <button>s
- remove role="link" from Link component when it renders as a button due to onClick prop
- fix Scrollable Block for screen readers so that in a scrollable submenu the correct number of menu items is announced
- update documentation to onChange story on Link component to explain why using this pattern is not accessible and suggest alternatives
- change link text in that story to make clear it's actually a button not a link
- Voiceover on Safari does …
=> fix(menu): change HTML to be more semantic and fix for screenreaders - FE-5009

src/components/tooltip/tooltip.component.tsx
Ensure private props (`target`, `isPartOfInput` and `inputSize`) are not displayed in the prop table of `Tooltip`
Some private props are displayed in the prop table of `Tooltip` after TS refactor
=> chore(tooltip): hide target, isPartOfInput and inputSize props from prop table

src/components/date-range/date-range.spec.js, src/components/date/__internal__/date-picker/date-picker.component.js, src/components/date/__internal__/date-picker/date-picker.d.ts, src/components/date/__internal__/date-picker/date-picker.spec.js, src/components/date/date.component.js, src/components/date/date.spec.js
fix #5181
Ensures that months are a capitalised for all locales and that day strings are all 3 characters long
in `DatePicker`. Introduces small optimisation by adding `useMemo` to arrays of days and months so
they only regenerate values when locale changes.
German days updated:
Spanish months updated:
Incorrect formatting for month and days 
No memoization added
German days current:
Spanish months current:
https://codesandbox.io/s/carbon-quickstart-forked-vwnj65?file=/src/index.js
=> fix(date): ensure months and days are capitalised and formatted correctly for all locales FE-5197

src/components/date-range/date-range.d.ts, src/components/date-range/index.d.ts, src/components/date/date.d.ts, src/components/date/index.d.ts
fix #5185
Sets the type for `startDateProps` and `endDateProps` are `Partial` implementations of the
`DateInputProps` interface. Also exports the `DateRangeChangeEvent` interface
exports `DateChangeEvent` from `Date` component
- Export the sandbox locally 
- run `npm i`
- confirm no type warnings in `startDateProps` and `endDateProps` for `value` and `onChange`
- compare to master where there will be warnings
https://codesandbox.io/s/carbon-quickstart-typescript-forked-vhtwgu
=> chore(date): add DateChangeEvent interface and export from index file FE-5195

src/components/button-toggle-group/button-toggle-group.component.js, src/components/button-toggle-group/button-toggle-group.spec.js, src/components/flat-table/flat-table-body/flat-table-body.spec.js, src/components/flat-table/flat-table-cell/flat-table-cell.spec.js, src/components/flat-table/flat-table-head/flat-table-head.spec.js, src/components/flat-table/flat-table-header/flat-table-header.spec.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.js, src/components/form/form.spec.js, src/components/pages/pages.spec.js, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/multi-select/multi-select.stories.mdx, src/components/select/option-row/__snapshots__/option-row.spec.js.snap, src/components/select/option-row/option-row.spec.js, src/components/select/select-list/select-list.spec.js, src/components/select/simple-select/simple-select.stories.mdx, src/components/select/utils/with-filter.spec.js, src/components/show-edit-pod/show-edit-pod.spec.js
To fix some of the error messages that appear when running the unit test suite.
We have a lot of error and warning messages when running our unit test suite.
N/A
Unit tests should still pass as they did prior to this PR being raised.
=> fix(button-toggle-group): ensure that id prop is passed to FormField

src/components/date/__internal__/date-picker/date-picker.component.js, src/components/date/__internal__/date-picker/date-picker.spec.js, src/components/date/date.spec.js
fix #5193
Ensure that the `onDayClick` is called with an event that contains the input `name` and `id` when picker is used to update value
Event target has no `name` or `id` when picker is used to update value
=> fix(date): ensure that event contains input name and id when picker is used to change date FE-5206 

src/components/flat-table/flat-table-cell/flat-table-cell.component.js, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.js, src/components/flat-table/flat-table-header/flat-table-header.component.js, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.js, src/components/flat-table/flat-table-row/flat-table-row.component.js, src/components/flat-table/flat-table-row/flat-table-row.spec.js, src/components/flat-table/flat-table.stories.mdx
fix #5208
Updates functionality to use `child.type.displayName` instead of `child.type`. This will allow
wrapping of the `FlatTableRowHeader` component as the wrapper component can set its `displayName` to
`FlatTableRowHeader.displayName` to ensure the required columns are sticky.
Adds `displayName` property to children of `FlatTableRow`.
Wrapping the `FlatTableRowHeader` prevents sticky column functioning correctly
Children of `FlatTableRow` have no `displayName` property
Use sandbox below, the one included in the linked issue will not work as there is no way to dynamically set the displayName on the wrapper. I have also added a story to demo how to implement this `flat-table--wrapping-row-headers`
You can see the new …
=> chore(flat-table-header): add displayName to component FE-5208

src/components/inline-inputs/inline-inputs.component.tsx, src/components/inline-inputs/inline-inputs.spec.tsx, src/components/inline-inputs/inline-inputs.stories.mdx, src/components/inline-inputs/inline-inputs.style.ts
currently it is not possible to add a breakpoint where the label will be displayed above the
component if displayed on a small screen. this change will make this component behave the same way
as the `Form Field` components.
fixes #5099
This can be tested against the codesandbox from the issue. https://codesandbox.io/s/flamboyant-breeze-yq5pde?file=/src/index.js
Resize the window and you should be able to see the label move from above to inline.
=> feat(inline-inputs): add adaptiveLabelBreakpoint prop to component - FE-5187

.github/CODEOWNERS
Updates `CODEOWNERS` to include all spec files as we now have some that are `ts` and `tsx` that aren't being assigned to the correct owner group
The `ts` and `tsx` spec files aren't being assigned to the correct `carbon-qa` owners
=> chore(code-owners): ensure ts spec files are owned by carbon-qa

.github/workflows/semantic-commit-lint.yml
Semantic App has gone down https://github.com/zeke/semantic-pull-requests/issues/183
Adds `semantic-commit-lint.yml` to workflows to ensure that commit messages are semantically valid according
to conventional commits spec https://www.conventionalcommits.org/en/v1.0.0/
No linting of commit messages currently setup
=> ci: add workflow to lint commit messages of pull requests

.storybook/main.js, package.json
Update how assets are found by storybook. Use storybook configuration instead of the deprecated CLI option.
Storybook currently serves static assets using the `-s` CLI option, which is now deprecated: https://storybook.js.org/docs/react/configure/images-and-assets#%EF%B8%8F-deprecated-serving-static-files-via-storybook-cli
Our documentation around storybook use does not reference this CLI option so does not require updating.
=> chore: refactor asset loading for storybook

package.json
Ensure `npm prepublishOnly` does not run `npm ci` 
`npm prepublishOnly` runs `npm ci`
=> ci: remove npm ci from prepublishOnly script

src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/menu-full-screen/menu-full-screen.spec.js
When onClick is passed to a top-level MenuItem of a MenuFullScreen, ensure it is passed down to the
underlying component
fix #5313
an onClick handler passed to a top-level MenuItem (with submenu prop) inside a MenuFullScreen should be called when the corresponding menu item is clicked
the onClick handler is not called in this situation (broken since version 106.6.4)
https://codesandbox.io/s/menu-items-v54s7l
=> fix(menu-full-screen): pass onClick to menu item

package-lock.json, package.json
Updates `commitizen` dev-dependency to resolve the critical vulnerabilities
https://github.com/commitizen/cz-cli/releases/tag/v4.2.5
The remaining vulnerabilities relate to `storybook`'s use of `glob-parent` and aren't resolved in the latest version so I chose to leave them for now
There are  critical vulnerabilities relating to the version of `commitizen` we are using
=> chore: update commitizen dependency to resolve critical vulnerabilities

src/components/button/__snapshots__/button.spec.tsx.snap, src/components/button/button-types.style.ts, src/components/loader/loader.stories.mdx, src/components/loader/loader.test.js, src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap
Loader will now mimic the colours of icon when nested inside of a button.
fixes #5226
Any button other than primary renders like this with `Loader`
N/A
Link to [codesandbox for testing](https://codesandbox.io/s/sweet-platform-4okwd3?file=/src/FilesT.js)
=> fix(loader): ensure correct colours are applied to loader when in a button - FE-5215

src/components/definition-list/definition-list.test.js
Refactor Cypress tests for Definition List component to use new cypress-component-react framework for testing.
Add definition-list.test.js.
Current process is the regular Cypress approach with BDD.
=> test(definition-list): refactor for cypress tests

cypress/e2e/common/menu.feature, cypress/locators/global-header/index.js, cypress/locators/global-header/locators.js, cypress/locators/navigation-bar/index.js, cypress/support/step-definitions/menu-steps.js, cypress/support/step-definitions/navigation-bar-steps.js, cypress/webpack.config.js, src/components/global-header/global-header-test.stories.tsx, src/components/global-header/global-header.component.tsx, src/components/global-header/global-header.spec.tsx, src/components/global-header/global-header.stories.mdx, src/components/global-header/global-header.test.js, src/components/global-header/index.ts, src/components/menu/menu-test.stories.js, src/components/menu/menu.d.ts, src/components/menu/menu.stories.mdx, src/components/navigation-bar/navigation-bar.spec.tsx, src/components/navigation-bar/navigation-bar.stories.mdx, src/components/navigation-bar/navigation-bar.style.ts, src/components/portal/__snapshots__/portal.spec.js.snap, src/global.d.ts, src/style/themes/base/base-theme.config.ts
Addresses #5045
Add a new `GlobalHeader` component to match the component of the same name in Design System. This should also fix the linked issue where it is not possible to have two navigation bars side by side vertically.
Amend old stories in `Menu` and `NavigationBar` which show how to create a navigation bar with the Sage logo
If two `NavigationBar`s are used side by side vertically both have the same z-index, so when a submenu is opened from the top bar, its content is shown beneath the bottom bar, which consequently means it's not possible hover over the contents. 
To fix the referenced issue, a separate component has been created instead of surfacing a `z-index` prop in `NavigationBar`. This is so Carbon is aligned with Design System (where Global Header and Navigation Bar are …
=> feat: introduce new GlobalHeader component (FE-5148)

src/components/modal/modal.component.tsx
The propTypes import and declaration object for Modal were left in the component after the refactor
to TS.
fixes #5376
Remove propType import and object from `modal` component
`modal` component still has the propTypes import and declaration. This is causing an error when carbon is built.
N/A
- Export the follow [codesandbox](https://codesandbox.io/s/carbon-quickstart-typescript-forked-3zjh85)
- Open it locally in VSCode
- run `npm install`
- run `npm run build`
- There should be no errors relating to Modal having two propType declarations
=> fix(modal): remove propTypes from component - FE-5309

src/components/definition-list/definition-list.style.ts
During the introduction of design tokens, text-decoration of none was added to links when they are
used in a definition-list. Links are underlined by default in the browser and we should honour this.
fixes #5240
N/A
This change can be seen in the story `Tile -> with Definition List Default`. Link Text should be underlined.
=> fix(definition-list): ensure links are styled correctly - FE-5293

cypress/locators/pod/index.js, cypress/locators/pod/locators.js, src/components/content/content.spec.js, src/components/content/content.style.js, src/components/content/content.test.js, src/components/pod/pod.component.js, src/components/pod/pod.spec.js, src/components/pod/pod.stories.mdx, src/components/pod/pod.style.js, src/components/pod/pod.test.js, src/components/show-edit-pod/show-edit-pod.spec.js, src/components/show-edit-pod/show-edit-pod.style.js, src/components/show-edit-pod/show-edit-pod.test.js, src/components/tile/__snapshots__/tile.spec.js.snap
fixes #5301
- Update `color` css for text within a `Pod` in a soft delete state to improve colour contrast with `Pod` background
- Update `background-color` for tertiary variant `Pod` to improve colour contrast when used with secondary or tertiary buttons
- Refactored markup in `address example` and `soft delete state` stories for `Pod` 
- Fix `Pod` styling so no border is rendered when in soft delete state
- Update `Content` component so when `title` prop is passed and `variant='primary'` - it uses body css rule for `color`
- Having a secondary or tertiary `Button` within a tertiary variant `Pod` causes a colour contrast warning in AXE
- Any text within a `Pod` in a soft delete state causes a colour contrast warning in AXE
`Pod` does not exist within Design System. Check visual changes …
=> style(pod): modify colours to fix poor colour contrast ratios (FE-5246)

src/components/definition-list/dd.component.tsx, src/components/definition-list/definition-list.stories.mdx, src/components/definition-list/dl.component.tsx, src/components/definition-list/dt.component.tsx, src/components/dialog/dialog.stories.mdx, src/components/preview/preview.stories.mdx, src/components/profile/profile.stories.mdx, src/components/step-sequence/step-sequence.stories.mdx
Adds responsive examples for: 
- Dialog
- Profile
- Step Sequence
- Definition List
Also improve upon an existing story in `Preview`
No responsive examples for dialog, step sequence, profile and definition list
The with children example of preview could be better.
- [] Related issues linked in commit messages if required
N/A
Visit the new stories in Storybook and make sure they work as expected.
New stories are:
`dialog -> responsive`
`definition list -> responsive`
`profile -> responsive`
`step sequence -> responsive`
and also ensure sure that `Preview -> with children` example works as expected.
=> docs(dialog): add responsive examples

src/components/action-popover/action-popover.style.ts, src/components/action-popover/action-popover.test.js, src/components/select/filterable-select/filterable-select.test.js, src/components/select/list-action-button/__snapshots__/list-action-button.spec.js.snap, src/components/select/list-action-button/list-action-button.style.js, src/components/select/multi-select/multi-select.test.js, src/components/select/option-row/__snapshots__/option-row.spec.js.snap, src/components/select/option-row/option-row.spec.js, src/components/select/option-row/option-row.style.js, src/components/select/option/__snapshots__/option.spec.js.snap, src/components/select/option/option.spec.js, src/components/select/option/option.style.js, src/components/select/simple-select/simple-select.test.js
- Change dropdown menu item hover colour and action popover menu item hover to use a light gray as opposed to dark. new colour token = 'colorsUtilityMajor100'
- Removed styling overrides for dropdown menu sticky footer button to align with figma implementation. 
old colour tokenused  = 'colorsUtilityMajor200'
=> fix hover dropdown and action popover hover colours so they align with figma implementation

src/components/menu/__internal__/submenu/submenu.component.js, src/components/menu/__internal__/submenu/submenu.spec.js
This fix ensures that when a menuitem with a href has a key press of enter, that the broswer navigates to the href and closes the submenu
fixes #4792
MenuItem should close after `enter` key is pressed.
MenuItem currently stays open when `enter` key is pressed.
N/A
Open storybook and navigate to the menu stories. Default story will do. 
Navigate to a menuitem with a href and press enter. 
Menu should close and browser should navigate to the specified href destination.
=> fix(menu): ensure submenu closes when enter key is pressed - FE-4919

scripts/check_carbon_version/check_carbon_version.js, scripts/check_carbon_version/check_carbon_version.spec.js, scripts/check_rfcs/check_rfcs.js, scripts/check_rfcs/check_rfcs.spec.js
Updates guard to prevent the scripts making api calls when run as part of CI pipeline
Guard only prevents the scripts making api calls when run as part of BITRISE pipeline
=> ci(check_rfcs, check_carbon_version): prevent api calls when run as part of CI pipeline

src/components/toast/toast-test.stories.mdx, src/components/toast/toast.component.js, src/components/toast/toast.d.ts, src/components/toast/toast.spec.js, src/components/toast/toast.stories.mdx, src/components/toast/toast.style.js, src/components/toast/toast.test.js
Toast component has the alternative style variant, which is always full width and rendered in the bottom of the screen.
Toast with that variant should animate from the bottom.
Alternative style can choose any content, icon/pill/text etc, default just text.
Alternative style can be dismissible or delay to animate out.
~~- [ ] Related issues linked in commit messages if required~~
=> feat(toast): add notice variant (FE-4402)

cypress/locators/radiobutton/index.js, cypress/locators/radiobutton/locators.js, cypress/support/component-helper/constants.js, src/components/radio-button/radiobutton.test.js
=> test: radiobutton

src/components/loader-bar/loader-bar.component.tsx
DisplayName and named export was missed when loader bar was refactored
N/A
Props table should appear in Storybook Docs
=> docs(loader-bar): ensure prop table displays in docs - FE-5405

cypress/support/accessibility/a11y-utils.js, cypress/support/component.js, src/components/accordion/accordion.stories.tsx, src/components/accordion/accordion.test.js
POC of the possible refactor for the `accessibility` Cypress tests for the `Accordion` component to use new cypress-component-react framework for testing.
Introduced new `custom` command for `a11y` check.
Current process is based on building the `json` story for the all list of `component` -> `story`.
=> test(accordion): refactor for accessibility tests

src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/multi-action-button/multi-action-button.component.tsx, src/components/multi-action-button/multi-action-button.style.ts
Fixes a styling bug that would appear when a href is passed to a children button
fixes #5483
N/A
- Use [pensive-jerry-yl0tz4](https://codesandbox.io/s/pensive-jerry-yl0tz4) to test this PR
=> fix(multi-action-button): fix styling bug when a href is passed to a button - FE-5375

package-lock.json, package.json
Moves `@badeball/cypress-cucumber-preprocessor` and `@bahmutov/cypress-esbuild-preprocessor` to `devDependencies` as there are some security vulnerabilities in some of its downstream dependencies that we want to exclude from our bundle
They are dependencies rather than devDependencies 
=> fix: move cypress preprocessor dependencies to devDependencies

src/components/tabs/tab/tab.component.js, src/components/tabs/tab/tab.d.ts
Adds `private` and `ignore` annotations to the `isTabSelected` prop as it is an internal prop that cannot be used by passing a value to it.
`isTabSelected` prop is exposed in the `Tab` prop table
=> chore(tab): make isTabSelected prop private and ignore in prop table docs

src/components/carbon-provider/carbon-provider.component.tsx, src/components/carbon-provider/top-modal-context.spec.tsx, src/components/carbon-provider/top-modal-context.tsx, src/components/dialog-full-screen/dialog-full-screen.component.js, src/components/dialog-full-screen/dialog-full-screen.spec.js, src/components/dialog-full-screen/dialog-full-screen.test.js, src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.spec.tsx, src/components/modal/__internal__/modal-manager.spec.ts, src/components/modal/__internal__/modal-manager.ts, src/components/sidebar/sidebar.component.tsx, src/components/sidebar/sidebar.spec.tsx
Currently we add aria-modal=true to the container div of each modal component (dialog, dialog-full-screen, sidebar). This ensures screenreaders do not announce content outside the modal. However when opening one modal from another, VoiceOver on Safari refuses to read the content on the new modal while the old one still has aria-modal=true. The workaround is to ensure aria-modal=true only appears on whatever the current top modal is. This requires keeping track of the current top modal in a context which has been added to CarbonProvider, as well as keeping a global list of "top modal setters" in the window object to ensure that multiple Carbon Providers in the same application (potentially even from different versions of Carbon) still update each other's context correctly.
fix #5303 …
=> fix(dialog, sidebar): ensure aria-modal is only added to top modal

src/components/tabs/tabs.test.js
- Change the `hover` way for `Tabs` component for cypress tests. 
- `Tabs` component test for `hover` is flaky.
No functionality or visuals to test - ensure all cypress tests are passing, the tests are testing the behaviour they describe and no `flaky` tests marked on the Dashboard.
=> test(tabs): update flaky test

.eslintrc
Adds eslint plugin `no-restricted-imports` and configures to prevent `prop-types` being imported in `ts/x` files
No linting exists to prevent `prop-types` from being imported in `ts/x` files
Add `import PropTypes from "prop-types"` to a `ts/x` file and run the linter
=> chore: add lint rule to prevent prop-type imports in typescript files

cypress/locators/note/index.js, cypress/locators/note/locators.js, src/components/note/note.test.js
Add Cypress tests for the `Note` component to use new cypress-component-react framework for testing.
Add `note.test.js`. 
Add locators as well.
No tests for `Note` component
=> test(note): add cypress tests

src/components/step-sequence/__snapshots__/step-sequence.spec.tsx.snap, src/components/step-sequence/step-sequence-item/step-sequence-item.component.tsx, src/components/step-sequence/step-sequence-item/step-sequence-item.spec.tsx, src/components/step-sequence/step-sequence-item/step-sequence-item.style.ts, src/components/step-sequence/step-sequence.component.tsx, src/components/step-sequence/step-sequence.spec.tsx, src/components/step-sequence/step-sequence.stories.mdx, src/components/step-sequence/step-sequence.stories.tsx, src/components/step-sequence/step-sequence.style.ts, src/components/step-sequence/step-sequence.test.js
Refactor stories, moved to tsx file
Removes the hardcoded padding styling and surfaces the padding interface with a default value of 0
Ensures height flexes to container when in `vertical` `orientation`
Update styling for `incomplete` steps to include dashed line
Hardcoded padding styling
Height does not flex to container when in `vertical` `orientation`
Styling for `incomplete` steps to has solid line
https://codesandbox.io/s/sad-field-nu72jj?file=/src/index.js
=> refactor(step-sequence): move demo stories to tsx file FE-5501 

src/components/icon-button/icon-button.test.js
- Add Cypress tests for the `Icon-Button` component to use new cypress-component-react framework for testing.
- Add `icon-button.test.js`. 
No tests for `Icon-Button` component
=> test(icon-button): add cypress tests

src/components/date/__internal__/date-picker/__snapshots__/date-picker.spec.js.snap, src/components/date/__internal__/date-picker/day-picker.style.js
Current date active styling:
Current date disabled styling:
Fixes: #5332 
The styling was incorrect for the current date and appeared like it was selectable even if disabled.
An updated codesandbox link can be found here: https://codesandbox.io/s/nervous-lucy-z5rssd?file=/src/index.js
It describes both test cases (disabled and active 'current date')
=> fix(date-picker): correct css disabled states

src/components/date-range/date-range.spec.js, src/components/date-range/date-range.stories.mdx, src/components/date/date.component.js, src/components/date/date.style.js, src/components/textarea/textarea.component.tsx, src/components/textbox/textbox.component.tsx, src/components/textbox/textbox.style.ts
fix #5431
The text for the validation message and label will now wrap to a new line if they exceed the input width of the individual `Date` inputs within `DateRange`
Label and validation text does not wrap
See updated story and linked sandbox
https://codesandbox.io/s/strange-carson-v72mlk
=> fix(date-range): update styles so validation and label text wrap if they exceed input width

cypress/locators/pager/index.js, cypress/locators/pager/locators.js, src/components/pager/pager.spec.js, src/components/pager/pager.style.js, src/components/pager/pager.test.js
Ensure the "current page" input field of Pager always has margin-bottom 0, even when inside a form.
Note - this is a fix for the change already merged from [this PR](https://github.com/Sage/carbon/pull/5660), which doesn't always work due to CSS rules having the same specificity. This PR increases the specificity of the `margin-bottom: 0` in Pager and adds a Cypress test to ensure the correct CSS is applies in the browser.
fix #5650 (properly this time!)
=> fix(pager): fix bottom margin of number input when inside a form

cypress/support/accessibility/a11y-utils.js, src/components/action-popover/action-popover-test.stories.tsx, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.stories.tsx, src/components/action-popover/action-popover.test.js
- Add `accessibility` Cypress tests for the `Action-Popover` component to use the new cypress-component-react framework for testing.
- Refactor `action-popover.stories.mdx` and `action-popover.stories.test.mdx` to corresponding `*.tsx`files.
=> test(action-popover): refactor for accessibility

src/components/card/card.component.tsx, src/components/card/card.stories.mdx, src/components/card/card.stories.tsx, src/components/card/card.style.ts, src/components/card/card.test.js
Add height prop and change the card display to flex, to allow content to match the card size
Component height could not be customised
~~- [ ] Related issues linked in commit messages if required~~
~~- [ ] Related docs have been updated if required~~
You can see the new behaviour by looking at the version in the comment by …
=> feat(card): add height prop (FE-5560)

src/__internal__/form-field/form-field.component.tsx, src/components/tabs/tab/tab.component.js, src/components/tabs/tab/tab.d.ts, src/components/tabs/tabs.component.js, src/components/tabs/tabs.d.ts, src/components/tabs/tabs.spec.js, src/components/tabs/tabs.stories.mdx, src/components/tabs/tabs.test.js
fix #5591
fix #5618
Ensures that any validation failures reported to parent Tab components are removed when the
associated child unmounts.
Adds `showValidationsSummary` prop to `Tabs` to support the option of rendering a summary of any
validation string failures in the `ValidationIcon` `Tooltip`.
Validation failures are not removed when an input within a `Tab` unmounts
No support for rendering a summary of all validation string failures in the `ValidationIcon` `Tooltip`
Use linked sandbox below for testing validation summary (linked issue has different implementation) and sandbox included in #5591 …
=> fix(tab): ensure that validation failures are no longer reported when children unmount FE-5527

src/components/box/box.component.tsx, src/components/typography/typography.component.tsx
Add a deprecation warning to the console explaining immediate plans to remove undocumented props being allowed on Box and Typography components.
Can see the deprecation comment when you navigate to the Typography or Box stories and check your Browser's console.
=> docs(typography,box): add deprecation message regarding removal of undocumented props

src/components/pager/__internal__/pager-navigation.component.js, src/components/pager/__internal__/pager-navigation.spec.js, src/components/pager/pager.component.js, src/components/pager/pager.spec.js, src/components/pager/pager.style.js
Neither the numeric input for page number nor the page size select had a label that was programatically associated to the input and contained descriptive text. This is now fixed.
fix #5284 and #5632
In the Pager component, both the numeric input showing the current page number, and the select for the page size (if present due to the `showPageSizeSelection` prop), should have a meaningful label which is correctly associated in HTML with the corresponding input.
This has the following benefits:
- screenreader users will get an indication of what the input is for when browsing the page (eg asking for a list of inputs, or navigating via the tab key)
- mouse users will be able to click on the label and have the input automatically focused
Both the select and the numeric input fail to associate …
=> fix(pager): correctly associate labels to input fields

.storybook/utils/partial-action.js, src/__internal__/utils/storybook/partial-action.ts, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.stories.tsx, src/components/alert/alert.stories.tsx, src/components/button-toggle-group/button-toggle-group-test.stories.tsx, src/components/button-toggle-group/button-toggle-group.stories.mdx, src/components/button-toggle/button-toggle.stories.mdx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog/dialog.stories.tsx, src/components/dismissible-box/dismissible-box.stories.mdx, src/components/draggable/draggable.stories.mdx, src/components/drawer/drawer.stories.mdx, src/components/pager/pager.stories.mdx, src/components/popover-container/popover-container.stories.mdx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/multi-select/multi-select.stories.mdx, src/components/sidebar/sidebar.stories.tsx, src/components/tile/tile.stories.mdx, src/components/toast/toast-test.stories.tsx, src/components/toast/toast.stories.tsx
Internal utils should not be used in code examples to not confuse Carbon users
internal utils like `partialAction` or storybook `action` are used in code examples
~~- [ ] Related issues linked in commit messages if required~~
=> docs: storybook remove util references (FE-5315)

cypress/locators/vertical-divider/index.js, cypress/locators/vertical-divider/locators.js, cypress/support/accessibility/a11y-utils.js, src/components/vertical-divider/vertical-divider-test.stories.tsx, src/components/vertical-divider/vertical-divider.component.tsx, src/components/vertical-divider/vertical-divider.test.js
- Add `react` and `accessibility` Cypress tests for the `Vertical Divider` component to use the new cypress-component-react framework for testing.
- Refactor `vertical-divider-test.stories.tsx`
=> test(vertical-divider): add cypress tests

src/components/date/__internal__/utils.spec.js
This PR fixes an internal issue where our unit tests are failing after the year has changed. This was caused by the fact, that we had hardcoded year `2022` in mocked Date.
If the CI build has passed, there is no need for further QA
=> test: remove hardcoded year from utils unit tests - FE-5594

cypress/support/accessibility/a11y-utils.js, src/components/button-bar/button-bar-test.stories.tsx, src/components/button-bar/button-bar.config.ts, src/components/button-bar/button-bar.test.js
- Add `accessibility` Cypress tests for the `Button-Bar` component to use the new cypress-component-react framework for testing.
- Refactor `button-test.stories.js` to the corresponding `*.tsx`files.
=> test(button-bar): add accessibility tests

scripts/check_rfcs/check_rfcs.spec.js
Overrides the `process.env.NODE_ENV` (so it is not `test` ) in test asserting `Octokit` API is not called.
The `process.env.NODE_ENV` is `test` meaning the guard does not catch
=> test(check_rfcs): ensure NODE_ENV is set correctly for test checking that API call is not made

cypress/support/accessibility/a11y-utils.js, src/components/badge/badge.test.js
- Add `accessibility` Cypress tests for the `Badge` component to use the new cypress-component-react framework for testing.
=> test(badge): add accessibility tests

src/components/action-popover/action-popover.stories.mdx
Adds `ActionPopoverMenuButton` import to `ActionPopover` story
`ActionPopoverMenuButton` not imported in `ActionPopover` story
Check story now loads in stroybook
=> chore(action-popover): add missing import to fix broken story

cypress/support/accessibility/a11y-utils.js, src/components/advanced-color-picker/advanced-color-picker.test.js
- Add `accessibility` Cypress tests for the `Advanced-Color-Picker` component to use the new cypress-component-react framework for testing.
- Refactor `advanced-color-picker.stories.mdx` and `advanced-color-picker.stories.test.mdx` to corresponding `*.tsx`files.
=> test(advanced-color-picked): refactor for accessibility test

src/components/tile-select/tile-select-group.component.js, src/components/tile-select/tile-select.spec.js, src/components/tile-select/tile-select.test.js
fix #5699
After the proposed changes when no `Description` prop is passed or the passed string is empty, the DOM element which displays the `TileSelectGroup` description no longer appears.
Currently when no `Description` prop is passed or the passed string is empty, the DOM element which displays the `TileSelectGroup` description still appears.
[This CodeSandbox ](https://codesandbox.io/s/priceless-mestorf-25fpzr?file=/src/index.js)is an example of the broken behaviour.
=> fix(tile-select-group): implement conditional rendering for the Description prop

cypress/support/accessibility/a11y-utils.js, src/components/detail/detail.test.js
- Add `accessibility` Cypress tests for the `Detail` component to use the new cypress-component-react framework for testing.
- [] Run `npx cypress open --component` to check if there is newly added test.file
- [] Check if the `detail.test.js` file passed
- [] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `action-popover` tests are not running twice.
=> test(detail): add accessibility tests

src/components/inline-inputs/inline-inputs.component.tsx, src/components/inline-inputs/inline-inputs.spec.tsx, src/components/inline-inputs/inline-inputs.stories.mdx
Add required prop
Component has no required prop
closes #4625
=> feat(inline-inputs): add required prop (FE-5584)

cypress/support/accessibility/a11y-utils.js, src/components/loader/loader-test.stories.tsx, src/components/loader/loader.test.js
- Add `accessibility` Cypress tests for the `Loader` component to use the new cypress-component-react framework for testing.
=> test(loader): refactor for accessibility test

src/components/note/note.component.tsx, src/components/note/note.spec.tsx, src/components/note/note.style.ts
Add margin to Note tile and Note content to avoid these elements be overlapped by the inlineControl button.
When inlineControl is defined, it is rendered over the Note title or content.
fixes #5734
=> fix(note): fix text overlapping inlineControl button (FE-5611)

cypress/support/accessibility/a11y-utils.js, src/components/help/help.test.js
- Add `accessibility` Cypress tests for the `Help` component to use the new cypress-component-react framework for testing.
=> test(help): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/toast/toast-test.stories.tsx, src/components/toast/toast.test.js
- Add `accessibility` Cypress tests for the `Toast` component to use the new cypress-component-react framework for testing.
- Refactor `toast-test.stories.js` to the corresponding `*.tsx`files.
=> test(toast): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.test.js
- Add `accessibility` Cypress tests for the `Dialog-Full-Screen` component to use the new cypress-component-react framework for testing.
- Refactor `dialog-full-screen.stories.mdx` and `dialog-full-screen.stories.test.mdx` to corresponding `*.tsx`files.
=> test(dialog-full-screen): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/sidebar/sidebar-test.stories.tsx, src/components/sidebar/sidebar.test.js
- Add `accessibility` Cypress tests for the `Sidebar` component to use the new cypress-component-react framework for testing.
- Refactor `sidebar-test.stories.js` to the corresponding `*.tsx`files.
=> test(sidebar): refactor accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/message/message.test.js
- Add `accessibility` Cypress tests for the `Message` component to use the new cypress-component-react framework for testing.
=> test(message): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/date/date.test.js
- Add `accessibility` Cypress tests for the `Date Input` component to use the new cypress-component-react framework for testing.
=> test(date): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/card/card-test.stories.tsx, src/components/card/card.test.js
- Add `accessibility` Cypress tests for the `Card` component to use the new cypress-component-react framework for testing.
- Refactor `card.stories.mdx` and `card.stories.test.mdx` to corresponding `*.tsx`files.
=> test(card): add accessibility tests

src/components/button-bar/button-bar-test.stories.tsx, src/components/button-bar/button-bar.component.tsx, src/components/button-bar/button-bar.spec.tsx, src/components/button-bar/button-bar.test.js, src/components/button/button.component.tsx, src/components/icon-button/icon-button.component.tsx
fix #5669
This change will remove the use of an Invariant and replace element.type with a context based approach for passing props from `ButtonBar` to its children `IconButton` and `Button`. This will mean consumers can use wrapper components within `ButtonBar` without receiving an Invariant Violation, and all props and `ref`s will be passed and preserved correctly. 
Currently, an Invariant is used to ensure children of `ButtonBar` are `Button` or `IconButton` elements, therefore wrapped components which return these elements cannot be used. Consequently, consumers cannot attach added logic to these components with the use of a wrapper, or have to use other complex approaches to avoid the Invariant violation and achieve functionality the or logic they desire.
[This …
=> fix(button-bar, button, icon-button): remove invariant and implement context to pass props

cypress/support/accessibility/a11y-utils.js, src/components/step-sequence/step-sequence-test.stories.tsx, src/components/step-sequence/step-sequence.test.js
- Add `accessibility` Cypress tests for the `step-sequence` component to use the new cypress-component-react framework for testing.
- Refactor `step-sequence-test.stories.js` to the corresponding `*.tsx`files.
=> test(step-sequence): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/button-toggle/button-toggle-test.stories.tsx, src/components/button-toggle/button-toggle.test.js
- Add `accessibility` Cypress tests for the `Button-Toggle` component to use the new cypress-component-react framework for testing.
- Refactor `button-toggle.stories.test.mdx` to corresponding `*.tsx`files.
- [] Run `npx cypress open --component` to check if there is newly added test.file
- [] Check if the `button-toggletest.js` file passed
- [] Run `npx cypress run --component` to check none of the other *.test.js files have regressed
- [] Run `npx cypress run --e2e` to check none of the feature files have regressed
- [] Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that `button-toggle` tests are not running twice.
=> test(button-toggle): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/profile/profile-test.stories.tsx, src/components/profile/profile.test.js
- Add `accessibility` Cypress tests for the `Profile` component to use the new cypress-component-react framework for testing.
=> test(profile): add accessibility tests

src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.test.js
- Remove typos with spreaded props in consumer-facing stories
- Amend cypress accessibility tests so the content within an open dialog is validated
- Storybook docs for `DialogFullscreen` currently do not load due to the page hanging indefinitely. This is because an argument to the component's consumer-facing stories has been incorrectly spread.
- Open `DialogFullscreen`'s docs page locally and check it loads: https://carbon.sage.com/?path=/docs/dialog-full-screen--default
- Check the amendments to cypress accessibility tests are satisfactory.
=> docs(dialog-full-screen): fix storybook docs from hanging on load

cypress/support/accessibility/a11y-utils.js, src/components/date-range/date-range.test.js
- Add `accessibility` Cypress tests for the `Date Range` component to use the new cypress-component-react framework for testing.
=> test(date-range): add accessibility tests

src/components/tabs/__internal__/tab-title/tab-title.component.js, src/components/tabs/__internal__/tab-title/tab-title.d.ts, src/components/tabs/__internal__/tab-title/tab-title.spec.js, src/components/tabs/tab/tab.component.js, src/components/tabs/tab/tab.d.ts, src/components/tabs/tabs.component.js, src/components/tabs/tabs.spec.js, src/components/tabs/tabs.stories.mdx
- `Tab`: Add new `titleProps` prop - which accepts an object of props to pass to the tab's corresponding `TabTitle`.
- `TabTitle`: Accepts new `data-role` prop to be used for testing and analytics purposes
- Consumers cannot set a `data-role` property for a `Tab`'s corresponding `TabTitle`, which has been raised as a feature request to allow consumers to query a tab's title using testing/analytics tools.
- Verify tab title has `data-role` property set when specified
- Double check typescript and docs definitions 
The following CodeSandbox is an example of the broken behaviour: [Go to codesandbox](https://codesandbox.io/s/tab-data-role-6v5wvp?file=/src/App.js)
=> feat(tab): introduce titleProps for passing props to corresponding title

src/__internal__/popover/popover.component.tsx, src/__internal__/popover/popover.spec.tsx
Prevent all Popover based components like Select, ActionPopover, SplitButton, MultiActionButton and other from crashing the app when rendered in Sidebar
Fixes #5753 
Replicate the steps shown in the video in #5753 issue and see if the error still persisrs.
Ignore the "Warning: Failed prop type: The prop `reference.current` is marked as required in `Popover`, but its value is `undefined`." error as it is not possible to fix in this ticket, this has to be fixed globally and there is an existing ticket for that
https://codesandbox.io/s/peaceful-haze-4jdmin
=> fix(popover): prevent from crashing when rendered in sidebar - FE-5621

src/components/step-sequence/step-sequence-test.stories.tsx
Fix typo in test stories file meaning storybook does not recognise the test story to include when building docs.
Currently get this console error when loading storybook in the browser:
``ReferenceError: StepSequenceStory is not defined``
=> docs(step-sequence): fix error with test story not being recognised by storybook

src/__internal__/form-field/form-field.component.tsx, src/__internal__/label/label.component.tsx, src/__spec_helper__/test-utils.ts, src/components/button-bar/button-bar.spec.tsx, src/components/button/button.spec.tsx, src/components/button/button.style.ts, src/components/dialog/dialog.spec.tsx, src/components/global-header/global-header.component.tsx, src/components/help/help.spec.tsx, src/components/link/link.component.tsx, src/components/menu/menu-item/menu-item.d.ts, src/components/split-button/split-button.spec.tsx, src/components/switch/switch.spec.tsx, src/style/design-tokens/carbon-scoped-tokens-provider/carbon-scoped-tokens-provider.component.ts, src/style/utils/color.ts
Updates import paths to be relative in `Label`, `Button` `ButtonBar` `Link`, `MenuItem`, `Dialog` `SplitButton`, `Switch`, `Help` and so on
Some import paths are not relative
=> chore: update import paths to be relative

cypress/support/accessibility/a11y-utils.js, src/components/button-minor/button-minor-test.stories.tsx, src/components/button-minor/button-minor.component.tsx, src/components/button-minor/button-minor.spec.tsx, src/components/button-minor/button-minor.stories.mdx, src/components/button-minor/button-minor.stories.tsx, src/components/button-minor/button-minor.style.ts, src/components/button-minor/button-minor.test.js, src/components/button-minor/index.ts, src/components/button/button-types.style.ts, src/components/button/button.component.tsx, src/components/button/button.spec.tsx, src/components/button/button.stories.mdx, src/components/button/button.style.ts
The Button Minor is a new component. The boolean prop isMinor is added to render a Button Minor variant. Storybook stories has been updated to reflect the differences between Minor and Major varinats.
=> Add new component to Carbon: Button Minor

src/components/batch-selection/batch-selection-test.stories.tsx, src/components/batch-selection/batch-selection.spec.tsx, src/components/batch-selection/batch-selection.stories.tsx, src/components/button-bar/button-bar-test.stories.tsx, src/components/button-bar/button-bar.spec.tsx, src/components/button-bar/button-bar.stories.mdx, src/components/card/card.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.component.tsx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog/dialog.component.tsx, src/components/dismissible-box/dismissible-box.component.tsx, src/components/flat-table/flat-table-expandable.stories.mdx, src/components/flat-table/flat-table.stories.mdx, src/components/flat-table/flat-table.test.js, src/components/icon-button/icon-button.component.tsx, src/components/icon-button/icon-button.spec.tsx, src/components/icon-button/icon-button.stories.mdx, src/components/icon-button/icon-button.test.js, src/components/link-preview/link-preview.component.tsx, src/components/menu/menu-full-screen/menu-full-screen.component.js, src/components/message/message.component.tsx, src/components/pill/pill.component.tsx, src/components/pod/pod.component.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.spec.tsx, src/components/sidebar/sidebar.component.tsx, src/components/toast/toast.component.tsx, src/components/vertical-menu/vertical-menu-full-screen.component.tsx
fix #5791
A deprecation warning has been added for the use of `onAction` within the `IconButton` component, and `onClick` has been added to replace its functionality, and will ensure keyboard behaviour is handled by default. All instances of `onAction` have been replaced by `onClick` internally also. As `onAction` will soon be removed and `onClick` has been added, an invariant has been added to ensure both cannot be used at the same time, as this would result in potentially incorrect behaviour.
Currently, when `IconButton` is focused, it stops propagation on any key that is not enter or space due to `onAction` event being primarily used within `IconButton`.
You can see the new behaviour by looking at the version in the …
=> fix(icon-button): use onClick instead of onAction to ensure keyboard behaviour is handled by default

cypress/support/accessibility/a11y-utils.js, src/components/progress-tracker/progress-tracker.test.js
- Add `accessibility` Cypress tests for the `Progress-Tracker` component to use the new cypress-component-react framework for testing.
=> test(progress-tracker): add accessibility tests

src/components/box/box.component.tsx, src/components/box/box.spec.tsx, src/components/box/box.test.js
fix #5572
Ensures that the any `Box` container that has `sticky` or `fixed` positioning has a z-index set to prevent it being overlaid by other elements that are relatively positioned
Any `Box` container that has `sticky` or `fixed` positioning has no z-index set
See sandbox in linked issue below
=> fix(box): ensure z-index is set when sticky or fixed positioned

cypress/e2e/accessibility/a11y-eleventh-part.test.js, cypress/e2e/accessibility/a11y-ninth-part.test.js, cypress/e2e/accessibility/a11y-tenth-part.test.js, cypress/e2e/accessibility/a11y-twelfth-part.test.js, cypress/locators/progress-tracker/index.js, cypress/support/accessibility/a11y-utils.js, src/components/draggable/draggable.test.js, src/components/progress-tracker/progress-tracker.test.js
- Add `accessibility` Cypress tests for the `Draggable` component to use the new cypress-component-react framework for testing.
- Remove unused `accessibility` files
- Add a missing test for `progress-tracker`
=> test(draggable): add accessibility tests

src/components/date/__internal__/date-picker/date-picker.component.js, src/components/date/__internal__/date-picker/date-picker.spec.js
fix #5786
Ensures that the abbreviated day translations in the picker component are only two characters long when locale is `de` (German)
The abbreviated day translations in the picker component are three characters long when locale is `de` (German)
=> fix(date): update abbreviated day translations in picker component for German locale FE-5660

cypress/support/accessibility/a11y-utils.js, src/components/definition-list/definition-list.test.js
- Add `accessibility` Cypress tests for the `Definition List` component to use the new cypress-component-react framework for testing.
=> test(definition-list): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/pod/pod-test.stories.tsx, src/components/pod/pod.test.js
- Add `accessibility` Cypress tests for the `Pod` component to use the new cypress-component-react framework for testing.
- Move testing component to the `pod-test.stories.tsx`
=> test(pod): refactor for accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/decimal/decimal-test.stories.tsx, src/components/decimal/decimal.test.js
- Add `accessibility` Cypress tests for the `Decimal` component to use the new cypress-component-react framework for testing.
- Refactor `decimal.stories.test.mdx` to corresponding `*.tsx`files.
=> test(decimal): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/pill/pill.test.js
- Add `accessibility` Cypress tests for the `Pill` component to use the new cypress-component-react framework for testing.
=> test(pill): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/checkbox/checkbox-test.stories.tsx, src/components/checkbox/checkbox.test.js
- Add `accessibility` Cypress tests for the `Checkbox` component to use the new cypress-component-react framework for testing.
- Refactor `checkbox.stories.test.mdx` to corresponding `*.tsx`files.
=> test(checkbox): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/textarea/textarea-test.stories.tsx, src/components/textarea/textarea.test.js, src/components/textbox/textbox-test.stories.tsx, src/components/textbox/textbox.stories.mdx, src/components/textbox/textbox.stories.tsx, src/components/textbox/textbox.test.js
- Add `accessibility` Cypress tests for the `Textbox` component to use the new cypress-component-react framework for testing.
- Move component stories to the `textbox.stories.tsx`
- Refactor for `textbox.stories.mdx` file
- Move testing component to the `textbox-test.stories.tsx`
- Add `accessibility` Cypress tests for the `Textarea` component to use the new cypress-component-react framework for testing.
- Move component stories to the `textarea-test.stories.tsx`
Run `npm run build-storybook` -> `npx sb extract` -> `npx http-server storybook-static -p 9001` and run `npx cypress run --e2e` and check that:
=> Cypress accessibility textarea textbox

src/components/heading/heading.component.tsx, src/components/heading/heading.spec.tsx, src/components/heading/heading.stories.mdx, src/components/heading/heading.test.js, src/components/heading/index.ts, src/components/settings-row/settings-row.component.js, src/components/settings-row/settings-row.d.ts, src/components/settings-row/settings-row.spec.js, src/components/settings-row/settings-row.stories.mdx, src/components/settings-row/settings-row.style.js, src/components/settings-row/settings-row.test.js
fix #5723
This change will surface the `headingType` prop on the `SettingsRow` and `Heading` components to provide consumers with the means to explicitly define which `<h>` tag they would like to be rendered when the `title` prop is passed in `SettingsRow` and in the `Heading` component itself. This will ensure a proper order of importance is established within the entire page when the components are used or re-used. Each `string` from `h1-h5` will each represent one of the six HTML Section Heading elements, ensuring a proper web page hierarchy can be created, to improve readability and accessibility. 
Currently, when the `title` prop is passed within the `SettingsRow` component, or the `Heading` component is used, a `<h1>` tag is rendered by default. If the components were used multiple …
=> feat(settings-row, heading): surface headingType prop on components

cypress/support/accessibility/a11y-utils.js, src/components/search/index.ts, src/components/search/search-test.stories.tsx, src/components/search/search.stories.mdx, src/components/search/search.stories.tsx, src/components/search/search.test.js
- Add `accessibility` Cypress tests for the `Search` component to use the new cypress-component-react framework for testing.
- Move component stories to the `search.stories.tsx`
- Refactor for `search.stories.mdx` file
- Move testing component to the `search-test.stories.tsx`
- Create the `search.stories.tsx`
=> test(search): refactor accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/switch/switch-test.stories.tsx, src/components/switch/switch.test.js
- Add `accessibility` Cypress tests for the `Switch` component to use the new cypress-component-react framework for testing.
- Move testing component to the `switch-test.stories.tsx`
=> test(switch): refactor accessibility tests

package-lock.json, package.json
- Update `browserslist` from version `4.16.6` to latest `4.21.5`
- Update data `browserslist` uses
Currently our build script is failing due to the data `browserslist` uses to verify browser support being out of date:
```shell
Error: 'cross-env babel --config-file /tmp/1d0c304b/babel.config.js --extensions ".js,.ts,.tsx" /tmp/1d0c304b/src --out-dir /tmp/1d0c304b/esm --ignore "**/*.test.js","**/*.test.ts","**/*.test.tsx","**/*.spec.js","**/*.spec.ts","**/*.spec.tsx","**/*.stories.js","**/*.stories.tsx","**/*.d.ts"' failed with 
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
```
- Verify the `precompile` npm script runs without the above error message. …
=> chore: update browserslist

cypress/support/helper.js, src/components/accordion/accordion.test.js, src/components/flat-table/flat-table.test.js
Currently the cypress tests for Accordion and FlatTable fail when run locally, although they pass on Github CI. This is because recent versions of Chrome (since v109) appear to calculate CSS transform matrices more accurately for rotations - the Github CI is currently running on v107, so to get this to pass we've had to test against specific CSS values that are not quite zero. This not only causes failure when using updated versions of Chrome, it's a very fragile way to test in general. To avoid this we should refactor to use a test utility specifically designed to compute the rotation angle from such a CSS matrix string, while accounting for rounding errors.
Cypress test should pass when run against all recent browser versions
Cypress tests fail when run locally on Chrome v110 (but pass …
=> test(accordion, flat-table): add helper for testing rotation angle

src/components/decimal/decimal-test.stories.tsx
Unexpected error while loading decimal-test-story is appearing in the console whilst using Storybook in localhost. This is due to a nonexistent story being definied as the includeStories parameter.
fixes #FE-5695
No error message relating to `decimal-test.stories` appears in the console when using localhost.
N/A
All tests should pass as usual and no error should appear in the console when using Storybook on localhost.
=> docs(decimal): fix naming error with test story - FE-5695

cypress/support/accessibility/a11y-utils.js, src/components/icon/icon-test.stories.tsx, src/components/icon/icon.test.js
- Add `accessibility` Cypress tests for the `Icon` component to use the new cypress-component-react framework for testing.
- Move testing component to the `icon-test.stories.tsx`
=> test(icon): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/fieldset/fieldset-test.stories.tsx, src/components/fieldset/fieldset.test.js
- Add `accessibility` Cypress tests for the `Fieldset` component to use the new cypress-component-react framework for testing.
- Move component stories to the `fieldset.stories.tsx`
=> test(fieldset): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/pager/pager-test.stories.tsx, src/components/pager/pager.test.js
- Add `accessibility` Cypress tests for the `Pager` component to use the new cypress-component-react framework for testing.
=> test(pager): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/form/form-test.stories.tsx, src/components/form/form.test.js
- Add `accessibility` Cypress tests for the `Form` component to use the new cypress-component-react framework for testing.
- Move testing component to the `form-test.stories.tsx`
- change the behaviour or disabling stories
=> test(form): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/drawer/drawer-test.stories.tsx, src/components/drawer/drawer.test.js
- Add `accessibility` Cypress tests for the `Drawer` component to use the new cypress-component-react framework for testing.
- Move component stories to the `drawer.stories.tsx`
=> test(drawer): add accessibility tests

src/components/dialog/dialog-test.stories.tsx
No errors should appear in console related to dialog stories.
N/A
- Open Storybook in LocalHost. 
- Open the console and make sure no error is there for dialog's test story.
- Check everything still work as it should too and all tests pass.
=> docs(dialog): fix error with includeStories parameter - FE-5704

cypress/support/accessibility/a11y-utils.js, src/components/duelling-picklist/duelling-picklist-test.stories.tsx, src/components/duelling-picklist/duelling-picklist.test.js
- Add `accessibility` Cypress tests for the `Duelling-Picklist` component to use the new cypress-component-react framework for testing.
- Move component stories to the `duelling-picklist-test.stories.tsx`
=> test(duelling-picklist): add accessibility tests

src/components/flat-table/flat-table.test.js
Add a test to cover icon node and a child for Flat Table as this was left out during the refactor work due to a lint error.
No test covering icon node and a child due to lint error when original refactor work was done.
N/A
Test should pass and QA should be happy with the code quality.
=> test(flat-table): add test for icon node and a child - FE-5613

src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/multi-action-button/multi-action-button.stories.mdx, src/components/multi-action-button/multi-action-button.stories.tsx, src/components/multi-action-button/multi-action-button.style.ts, src/components/split-button/split-button-children.style.ts, src/components/split-button/split-button.spec.tsx, src/components/split-button/split-button.stories.mdx
Fixes #5720
Fixes #5874 
Styles of Buttons used inside the MultiActionButton or SplitButton are currently overriden by the parent component meaning that none of the following props work correctly on the Buttons: buttonType, disabled, destructive.
Either check the following sandboxes or check the new stories added to the SplitButton and MultiActionButton stories which covers scenarios where the used Buttons have different `buttonType` or are `disabled` or `destructive`
https://codesandbox.io/s/epic-blackwell-uk5u8q
https://codesandbox.io/s/spring-thunder-qntwkz
=> fix: resolve an issue with styles being overriden in child buttons in SplitButton/MultiActionButton - FE-5678/FE-5700

src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/multi-action-button/multi-action-button.component.tsx, src/components/multi-action-button/multi-action-button.spec.tsx, src/components/multi-action-button/multi-action-button.test.js, src/components/split-button/split-button.component.tsx, src/components/split-button/split-button.spec.tsx, src/components/split-button/split-button.test.js
The additional buttons are now shown on click of the toggle button, rather than just on hover. This means that Voice Control users can activate the button by just saying its name (or the appropriate number if going through "show numbers"). Also tidy up by removing aria-haspopup on the surrouding div, this was already on the toggle button itself and from ARIA 1.2 is no longer valid on generic elements like a div.
fix #5615
There should be a click action on the main button of MultiActionButton, and the toggle button of SplitButton, that opens the child buttons. This enables Voice Control users to open the additional buttons without further instructions needed (see video on the original issue).
The div wrapper of both components should not have aria-haspopup=true, as it is only the (toggle) …
=> fix(multi-action-button, split-button): open menu on click

src/components/badge/badge-test.stories.tsx, src/components/badge/badge.component.tsx, src/components/badge/badge.spec.tsx, src/components/badge/badge.stories.mdx, src/components/badge/badge.style.ts, src/components/badge/badge.test.js
This change allows Badge to be display only by not passing an `onClick` prop to the component. In this variant, the badge will render as a `span` element instead of a `button`.
fixes #5706
Have a display only variant of `Badge` that is not interactive but looks the same as `Badge` currently does.
`Badge` component cannot be display only. Component is always interactive, even without an `onClick` function a hover style is applied implying that the component is able to be interacted with. 
N/A
A new example has been created called `display only`. This can be seen in Storybook. 
A codesanbox can be created if needs be too.
=> feat(badge): allow component to be display only - FE-5687

cypress/support/accessibility/a11y-utils.js, src/components/global-header/global-header-test.stories.tsx, src/components/global-header/global-header.test.js
- Add `accessibility` Cypress tests for the `Global-Header` component to use the new cypress-component-react framework for testing.
- Move component stories to the `global-header-test.stories.tsx`
=> test(global-header): add accessibility tests

cypress/locators/menu/index.js, src/__internal__/focus-trap/focus-trap-utils.ts, src/__internal__/focus-trap/focus-trap.component.tsx, src/__internal__/focus-trap/focus-trap.spec.tsx, src/components/dialog-full-screen/dialog-full-screen.test.js, src/components/dialog/dialog-test.stories.tsx, src/components/dialog/dialog.test.js, src/components/menu/menu.test.js, src/components/sidebar/sidebar.test.js, src/components/vertical-menu/vertical-menu.test.js
Fixes 2 separate issues within the FocusTrap internal component (which is used by Dialog and related components to trap focus inside when tabbing):
1) Carbon should as far as possible not interfere with the behaviour of any 3rd-party libraries which the consumer is using that, by not calling `preventDefault` on the keyboard event (see first paragraph of "current behaviour" for details). This has been achieved by relying on focusable "tab guard" elements before and after the focus trap which "redirect" the focus as needed when focused, and otherwise relying on browser default behaviour (as modified by any other libraries in use) except when this would result in incorrect behaviour in Carbon (which happens in only one situation - when the consumer is using a custom `focusableSelectors` …
=> Focus trap fixes

cypress/support/accessibility/a11y-utils.js, src/components/grid/grid-test.stories.tsx, src/components/grid/grid.test.js
- Add `accessibility` Cypress tests for the `Grid` component to use the new cypress-component-react framework for testing.
- Move component stories to the `grid-test.stories.tsx`
=> test(grid): add accessibility tests

src/components/date/date.component.js, src/components/date/date.spec.js, src/components/date/date.stories.mdx, src/components/date/date.style.js, src/components/date/date.test.js
allow the use of labelWidth, inputWidth and MaxWidth props
labelWidth, inputWidth and MaxWidth props are ignored, width of the component is non-changeable
~~- [ ] Related docs have been updated if required~~
fixes #5787
=> fix(date): enable width customization (FE-5659)

cypress/support/accessibility/a11y-utils.js, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.test.js
- Add `accessibility` Cypress tests for the `Popover-Container` component to use the new cypress-component-react framework for testing.
- Move component stories to the `popover-container-test.stories.tsx`
=> test(popover-container): add accessibility tests

package.json
Add the `scripts/check_rfcs/index.js` file as it is causing the installation to fail as the file is not ending up in the published package since https://github.com/Sage/carbon/commit/d850a25883b7eff9a03ad6ce47755af2e202b63d
The installation fails with the missing index of the check_rfc file. This can be worked around by `npm install --ignore-scripts` flag. CodeSanbox cannot be use as it ignores the postinstall scripts by default, e.g. this still works but will fail on a local install by default: https://codesandbox.io/s/angry-andras-opoejq?file=/package.json
Install the latest version and see the error. Install the proposal version to see that it works fine.
=> fix(check_rfcs): ship the index file in the published package

jest.config.json, src/__internal__/character-count/character-count.component.tsx, src/__internal__/character-count/character-count.spec.tsx, src/components/date/date.d.ts, src/components/date/date.stories.mdx, src/components/form/form.spec.tsx, src/components/number/number.test.js, src/components/textarea/textarea-test.stories.tsx, src/components/textarea/textarea.component.tsx, src/components/textarea/textarea.spec.tsx, src/components/textarea/textarea.stories.mdx, src/components/textarea/textarea.stories.tsx, src/components/textarea/textarea.test.js, src/components/textbox/textbox-test.stories.tsx, src/components/textbox/textbox.component.tsx, src/components/textbox/textbox.spec.tsx, src/components/textbox/textbox.stories.mdx, src/components/textbox/textbox.stories.tsx, src/components/textbox/textbox.style.ts, src/components/textbox/textbox.test.js, src/hooks/__internal__/useCharacterCount/useCharacterCount.spec.tsx, src/hooks/__internal__/useCharacterCount/useCharacterCount.tsx, src/locales/en-gb.ts, src/locales/locale.ts, src/locales/pl-pl.spec.tsx, src/locales/pl-pl.ts
fix #5717
This PR will introduce a mandatory hint string before the input, which explicitly states that the input contains a character counter/limit. Also, this hint has been given a unique Id and is referenced within the Input with an `aria-describedby` attribute. This ensures users using AT will also be able to benefit from the additional information the hint provides.
Also, the wording of the actual counter below the input has now been changed from numerical to a sentence, mirroring the [GOV.UK character count component](https://design-system.service.gov.uk/components/character-count/), this sentence description will be more descriptive for users reading the string visually, but also sounds much clearer on the `aria-live` region which reads this count on change.
Currently there is no …
=> fix(textarea, textbox): accessibility enhancements on character counter

cypress/support/accessibility/a11y-utils.js, src/components/navigation-bar/navigation-bar.test.js
- Add `accessibility` Cypress tests for the `Navigation-bar` component to use the new cypress-component-react framework for testing.
=> test(navigation-bar): add accessibility tests

src/components/show-edit-pod/show-edit-pod.component.js, src/components/show-edit-pod/show-edit-pod.spec.js, src/components/show-edit-pod/show-edit-pod.stories.mdx
=> Sage/DSY-2333(FE-5717): ShowEditPod Storybook Update

cypress/locators/breadcrumbs/index.js, cypress/locators/breadcrumbs/locators.js, src/components/breadcrumbs/breadcrumbs-test.stories.tsx, src/components/breadcrumbs/breadcrumbs.component.tsx, src/components/breadcrumbs/breadcrumbs.spec.tsx, src/components/breadcrumbs/breadcrumbs.stories.mdx, src/components/breadcrumbs/breadcrumbs.stories.tsx, src/components/breadcrumbs/breadcrumbs.style.ts, src/components/breadcrumbs/breadcrumbs.test.js, src/components/breadcrumbs/crumb/crumb.component.tsx, src/components/breadcrumbs/crumb/crumb.spec.tsx, src/components/breadcrumbs/crumb/crumb.style.ts, src/components/breadcrumbs/crumb/index.ts, src/components/breadcrumbs/index.ts, src/locales/en-gb.ts, src/locales/locale.ts, src/locales/pl-pl.ts
=> Sage/DSY-1757 Breadcrumbs Component (FE-5562)

cypress/support/accessibility/a11y-utils.js, src/components/inline-inputs/inline-inputs.test.js
- Add `accessibility` Cypress tests for the `Inline-inputs` component to use the new cypress-component-react framework for testing.
=> test(inline-inputs): add accessibility tests

cypress/locators/advanced-color-picker/index.js, cypress/locators/advanced-color-picker/locators.js, src/components/advanced-color-picker/advanced-color-picker.component.tsx, src/components/advanced-color-picker/advanced-color-picker.spec.tsx, src/components/advanced-color-picker/advanced-color-picker.stories.mdx, src/components/advanced-color-picker/advanced-color-picker.stories.tsx, src/components/advanced-color-picker/advanced-color-picker.style.ts, src/components/advanced-color-picker/advanced-color-picker.test.js, src/components/definition-list/dl.component.tsx, src/locales/en-gb.ts, src/locales/locale.ts, src/locales/pl-pl.ts, src/style/utils/visually-hidden.ts
This pull request will add a visually hidden description list which will describe the currently selected colour, as well as an `aria-describedby` attribute to the button which opens the component, to create an association between the two. However, this is just a part-solution to improve accessibility in the short-term, as an accessible re-design of how this component is opened is due to take place in the foreseeable future, which will integrate with the changes made in this PR.
Currently, there is no indication of the button's purpose due to a lack of any proper labelling. Also, the current chosen colour is only returned to the user visually, so users unable to see colour will not know which colour is currently selected.
You …
=>  fix(advanced-color-picker): add visually hidden description list to describe selected color

src/components/alert/alert.stories.mdx, src/components/alert/alert.stories.tsx
N/A
In the Alert docs, you should be able to view the code that the story is composed from.
=> docs(alert): fix not showing code example - FE-5739

cypress/support/accessibility/a11y-utils.js, src/components/radio-button/radio-button-test.stories.tsx, src/components/radio-button/radiobutton.test.js
- Add `accessibility` Cypress tests for the `Radio-Button` component to use the new cypress-component-react framework for testing.
- Move component stories to the `radio-button-test.stories.tsx`
=> test(radio-button): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/tile-select/tile-select-test.stories.tsx, src/components/tile-select/tile-select.test.js, src/components/tile/tile-test.stories.tsx, src/components/tile/tile.test.js
- Add `accessibility` Cypress tests for the `Tile` and `Tile Select` components to use the new cypress-component-react framework for testing.
- Move the testing component to the `tile-test.stories.tsx` and `tile-select-test.stories.tsx`
=> test(tile): add accesibility tests

src/components/switch/__internal__/__snapshots__/switch-slider.spec.tsx.snap, src/components/switch/__internal__/switch-slider.style.ts, src/components/switch/switch.spec.tsx, src/components/switch/switch.style.ts, src/components/switch/switch.test.js
if border-box css is applied globally, it effects the styling of the swtich component. This fix address this bug by applying box-sixing: border-box to the switch-slider span element.
fixes FE-5738
N/A
Switch component should look and behave exactly as it did before this change. 
- Codesandbox that was created for the ticket - https://codesandbox.io/s/lucid-faraday-unr1n1?file=/src/App.js
- Codesandbox that uses the same code but built from this PR - https://codesandbox.io/s/carbon-quickstart-forked-dow72s
=> fix(switch): fix styling defect caused by box-sizing border-box css - FE-5738

cypress/support/accessibility/a11y-utils.js, src/components/hr/hr.test.js
- Add `accessibility` Cypress tests for the `Hr` component to use the new cypress-component-react framework for testing.
=> test(hr): add accessibility tests

cypress/support/accessibility/a11y-utils.js, src/components/simple-color-picker/simple-color-picker.test.js
- Add `accessibility` Cypress tests for the `Simple-color-picker` components to use the new cypress-component-react framework for testing.
=> test(simple-color-picker): add accessibility tests

package.json
Update package.json file to add the cross-env function to set the environment variable in the start script
Currently the start script on Windows unless the environment variable has already been set
=> chore: update node start script to include cross-env to fix windows setups

.github/workflows/cypress.yml, cypress/components/typography/typography.test.js, cypress/e2e/accessibility/a11y-fifth-part.test.ts, cypress/e2e/accessibility/a11y-fourth-part.test.ts, cypress/e2e/accessibility/a11y-sixth-part.test.ts, cypress/support/accessibility/a11y-utils.ts, src/components/typography/typography-test.stories.tsx
- Add `accessibility` Cypress tests for the `Typography` component to use the new cypress-component-react framework for testing.
=> test(typography): add cypress tests

cypress/components/icon-button/icon-button.test.js, src/components/icon-button/icon-button-test.stories.tsx
- Add `accessibility` Cypress tests for the `icon-button` component to use the new cypress-component-react framework for testing.
=> test(icon-button): add accessibility tests

cypress/components/tabs/tabs.test.js, cypress/support/accessibility/a11y-utils.ts, src/components/tabs/tabs-test.stories.tsx
- Add `accessibility` Cypress tests for the `Tabs` component to use the new cypress-component-react framework for testing.
=> test(tabs): add accessibility tests

src/style/utils/visually-hidden.ts
Adds `white-space: nowrap` CSS property to the visually hidden class.
Currently, there is no mechanism to prevent text content wrapping within the visually hidden class, which in some cases can result in incorrect screen reader announcements.
=> feat: add white-space: nowrap CSS property to visually hidden class

cypress/components/split-button/split-button.test.js, cypress/support/accessibility/a11y-utils.ts, src/components/split-button/split-button-test.stories.tsx
Add accessibility Cypress tests for the Split Button component to use the new cypress-component-react framework for testing.
Old approach with separate test files and run jobs for accessibility tests.
=> test(split button): refactor cypress accessibility tests

cypress/components/tabs/tabs.test.js, src/components/tabs/tabs-test.stories.tsx
- Update cypress test which verifies when a `Tab` child with a validation failure is removed, the `Tab` no longer show a validation icon.  
- Currently, test passes given though a validation prop has not been set on the `Tab` child in the test case.
Open Cypress via `npx cypress open --component` and run the `Tabs` tests and verify for these three tests are passing correctly:
"should no longer report any error validation failures of children no longer mounted"
"should no longer report any warning validation failures of children no longer mounted",
"should no longer report any info validation failures of children no longer mounted",
=> test(tabs): fix cypress test returning false positive result

cypress/components/button-minor/button-minor.test.js, src/components/button-minor/button-minor.spec.tsx, src/components/button-minor/button-minor.style.ts
fix #5946
This PR will add position: absolute CSS property to `Icon` when component is icon only. This prevents the rendered `Icon` from moving position on hover due to a reduction in padding added during `ButtonMinor`s composition, which causes the `Icon` and Portal used to to provide a tooltip message to stack on top of one another
Currently, the `Icon` rendered within the component and Portal used to to provide a tooltip message stack on top of one another, this is due to the rendred `Icon` having relative positioning, which is needed for other variants of the button and a reduction in padding implemented during the components composition.
You can see the new behaviour by looking at the version in the comment by …
=>  feat(minor-button): add position: absolute property to icon when component is icon only

cypress/components/flat-table/flat-table.test.js, cypress/support/accessibility/a11y-utils.ts, src/components/icon-button/icon-button-test.stories.tsx
- Add `accessibility` Cypress tests for the `flat-table` component to use the new cypress-component-react framework for testing.
=> test(flat table): add accessibility tests

cypress/components/select/filterable-select/filterable-select.test.js, cypress/components/select/multi-select/multi-select.test.js, cypress/components/select/simple-select/simple-select.test.js, cypress/support/accessibility/a11y-utils.ts, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/simple-select/simple-select-test.stories.tsx
- Add `accessibility` Cypress tests for the `Select` component to use the new cypress-component-react framework for testing.
=> test(select): add accessibility tests

cypress/components/password/password.cy.js, src/components/button-minor/button-minor.component.tsx, src/components/button-minor/button-minor.style.ts, src/components/button-minor/index.ts, src/components/password/index.ts, src/components/password/password.component.tsx, src/components/password/password.spec.tsx, src/components/password/password.stories.mdx, src/components/password/password.stories.tsx, src/components/password/password.style.ts, src/locales/en-gb.ts, src/locales/locale.ts, src/locales/pl-pl.ts
fix #5614
This pull request aims to add a brand-new component into Carbon named `Password`, the component will render `Textbox` but provide further capacity for obscured text control. The component will also render `ButtonMinor` as a means to change the input type, as well as built-in approaches and attributes to ensure the component is accessible and secure. 
The `Password` component will surface the HTML input type attribute on `Textbox` but limit the types to be either `text` or `password`, with the latter being the default. The component will also render the `ButtonMinor` carbon component to change type back and forth, allowing users to view and obscure their password when needed. The `ButtonMinor` will utilise a label of either `Show` and `Hide` and icons `View` and `Hide` depending …
=> feat(password): add new component

cypress/components/accordion/accordion.cy.tsx
- Rename the `accordion.cy.js` to `accordion.cy.tsx` file in `./cypress/components/accordion/` folder.
Tests are in js not ts
=> test(accordion): typescript refactor

cypress/components/dialog-full-screen/dialog-full-screen.cy.js, cypress/components/dialog/dialog.cy.js, cypress/components/menu/menu.cy.js, cypress/components/sidebar/sidebar.cy.js, cypress/components/vertical-menu/vertical-menu.cy.js, cypress/support/commands.ts, cypress/support/helper.ts, src/__internal__/focus-trap/focus-trap.component.tsx, src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx, src/components/dialog/dialog-test.stories.tsx, src/components/sidebar/sidebar-test.stories.tsx, src/components/vertical-menu/vertical-menu-test.stories.tsx, src/style/global-style.ts
The addition of invisible "tab guard" divs at the top and bottom of each focus trap causes the browser to scroll these into view when tabbing into them - causing the user to see the background of the page jump to the bottom when tabbing from the bottom element in the trap to the top one, and vice versa. This is now fixed by giving these divs a CSS `position: fixed` property, which keeps them permanently in the viewport so stops the browser scrolling anything.
fix #5986
When tabbing through a dialog or other modal component, the background should stay in the same place at all times, and not scroll/jump unexpectedly.
When tabbing across the "edge" of a modal component (forward tabbing from the last focusable element to focus the first one, or back tabbing from the first to focus the last), …
=> fix(focus-trap): prevent scroll to bottom when tabbing through

cypress/components/button-bar/button-bar.cy.tsx
Apply new approach for `type` for `ButtonBar` component
Applied most types as `string` instead of proper type
=> test(button-bar): apply new approach of types

cypress/components/alert/alert.cy.tsx
Rename the `alert.cy.js` into `alert.cy.tsx` file in `./cypress/components/alert/` folder
Refactor tests to Typescript
Move any remaining stories in `alert.test.tsx` file to `alert-test.stories.tsx` in './src/components/alert/' folder.
tests are in js not ts
=> test(alert): typescript refactor

cypress/components/button-toggle/button-toggle.cy.tsx, src/components/button-toggle/button-toggle-test.stories.tsx
- Rename the `button-toggle.cy.js` into `button-toggle.cy.tsx` file in `./cypress/components/button-toggle/` folder
- Refactor tests to Typescript
tests are in js not ts
=> test(button-toggle): refactor to TS

cypress/components/badge/badge.cy.tsx, cypress/components/heading/heading.cy.tsx, src/components/heading/heading-test.stories.tsx
- Rename the `heading.cy.js` to `heading.cy.tsx` file in `./cypress/components/heading/` folder.
- Added eslint comment for 'badge.cy.tsx'
Currently Badge component is in JS not in TS.
=> test(heading): typescript refactor

cypress/components/message/message.cy.tsx, src/components/message/message-test.stories.tsx
- Rename the `message.cy.js` to `message.cy.tsx` file in `./cypress/components/message/` folder.
Currently Message component is in JS not in TS.
=> test(message): typescript refactor

cypress/components/link/link.cy.tsx, src/components/link/link-test.stories.tsx
- Rename the `link.cy.js` to `link.cy.tsx` file in `./cypress/components/link/` folder.
Currently Link component is in JS not in TS.
=> test(link): typescript refactor

cypress/components/checkbox/checkbox.cy.tsx, src/components/checkbox/checkbox-test.stories.tsx
- Rename the `checkbox.cy.js` to `checkbox.cy.tsx` file in `./cypress/components/checkbox/` folder.
Checkbox tests are in js not ts.
=> test(checkbox): typescript refactor

cypress/components/action-popover/action-popover.cy.js, cypress/locators/action-popover/index.js, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover.spec.tsx, src/components/action-popover/action-popover.style.ts
There should be no console warnings about incorrect DOM nesting - <button> elements should not be children of other <button> elements.
When rendering an ActionPopover component with a submenu, the submenu items are buttons that are nested inside the parent menu item in the DOM - this parent menu item is also an HTML button:
This results in a warning in the console - which can be seen when running the unit tests for this component.
[Note that this isn't an accessibility failing - Axe does not complain - due to the `role="menuitem"` on both buttons and `role="menu"` on the submenu container.]
Ensure that the console warning can not be seen on https://carbon.sage.com/?path=/docs/action-popover--action-popover-component-submenu or when running the action-popover unit tests.
Perform regression …
=> fix - action popover nested buttons

cypress/components/confirm/confirm.cy.tsx, src/components/confirm/confirm-test.stories.tsx
- Rename the `confirm.cy.js` to `confirm.cy.tsx` file in `./cypress/components/confirm/` folder.
Currently Confirm component is in JS not in TS.
=> test(confirm): typescript refactor

docs/colors.stories.mdx
Fixes broken link to the external Design Tokens page,
Was pointing to https://sage.jaha.pro/
Now points to https://zeroheight.com/2ccf2b601/p/217e24-design-tokens/b/46fb17
Slack discussion [here](https://sageone.slack.com/archives/C0D6DD3N2/p1685615050409499).
=> docs: fix broken Design Tokens link

cypress/components/number/number.cy.tsx, cypress/components/textarea/textarea.cy.tsx, cypress/components/textbox/textbox.cy.tsx, src/components/number/number-test.stories.tsx
- Rename the `number.cy.js` to `number.cy.tsx` file in `./cypress/components/number/` folder.
Number tests are in js not ts.
=> test(number): refactor tests to TS

src/components/multi-action-button/multi-action-button.component.tsx
The iconType and iconPosition props on MultiActionButton have no effect as they are passed to the Button but deliberately overridden by hardcoded values. These are now removed from the props interface to avoid confusion for consumers.
fix #6059
`iconType` and `iconPosition` should not be accepted by the TypeScript compiler as valid props for `MultiActionButton`, nor should they be documented on Storybook.
The `iconType` and `iconPosition` props are listed in the props on storybook, and are accepted by Typescript, even though they do nothing.
The fact that these props do not do anything appears to be deliberate, and it has been like this way since 2020 - this was the PR where this was introduced: https://github.com/Sage/carbon/pull/2669
No QA should be required on the component as the …
=> fix(multi-action-button): remove unused props from interface

cypress/components/drawer/drawer.cy.tsx, src/components/drawer/drawer-test.stories.tsx
- Rename the `drawer.cy.js` to `drawer.cy.tsx` file in `./cypress/components/drawer/` folder.
Drawer tests are in js not ts.
=> test(drawer): typescript refactor

cypress/components/menu/menu.cy.js, src/components/menu/__internal__/submenu/submenu.component.tsx
The onSubmenuOpen prop, if provided, should only be called once each time the submenu opens - even if subsequent events are triggered while it is open, that would open it if it weren't already open.
onSubmenuOpen is called multiple times in some situations:
- when pressing the Enter or Space key to open a submenu with the keyboard, the function is called twice
- when moving the mouse over the item, the function is called multiple times (typically 3 to 4), even though the submenu only opens once
https://codesandbox.io/s/trusting-water-yiyzf3?file=/src/App.tsx
=> fix(menu): ensure onSubmenuOpen is only called once when the submenu opens

cypress/components/pager/pager.cy.tsx, src/components/pager/pager-test.stories.tsx
- Rename the `pager.cy.js` to `pager.cy.tsx` file in `./cypress/components/pager/` folder.
Pager tests are in js not ts.
=> test(pager): refactor tests to ts

cypress/components/pill/pill.cy.tsx, src/components/pill/pill-test.stories.tsx
- Rename the `pill.cy.js` to `pill.cy.tsx` file in the `./cypress/components/pill/` folder.
Pill tests are in js not ts.
=> test(pill): refactor tests to TS

cypress/components/settings-row/settings-row.cy.tsx, src/components/settings-row/settings-row-test.stories.tsx
- Rename the `settings-row.cy.js` to `settings-row.cy.tsx` file in `./cypress/components/settings-row/` folder.
Currently settings-row component is in JS not in TS.
=> test(settings-row): refactor ts

cypress/components/duelling-picklist/duelling-picklist.cy.tsx, src/components/duelling-picklist/duelling-picklist-test.stories.tsx
- Rename the `duelling-picklist.cy.js` to `duelling-picklist.cy.tsx` file in `./cypress/components/duelling-picklist/` folder.
Duelling-picklist tests are in js not ts.
=> test(duelling-picklist): typescript refactor

cypress/components/breadcrumbs/breadcrumbs.cy.js, src/components/breadcrumbs/breadcrumbs.component.tsx, src/components/breadcrumbs/breadcrumbs.spec.tsx, src/components/breadcrumbs/breadcrumbs.stories.mdx, src/components/breadcrumbs/breadcrumbs.style.ts, src/components/breadcrumbs/crumb/crumb.component.tsx, src/components/breadcrumbs/crumb/crumb.spec.tsx
fix #6105
fix #6096
Removes `href` as required props and ensures all props defined in interface are passed down to
rendered element
Adds `margin` and `padding` props to component to allow custom values to be passed. Overrides the
user agent styling on the `ol` element as well.
User agent styling is adding unwanted padding and margin to `ol` element. No ability to pass custom margin or padding values.
`CrumbProps` interface extends `LinkProps`, overrides `href` to make it required and does not pass `rest` to rendered element so some props do not work such as `onClick`
=> fix(crumb): ensure all props in interface are passed down and remove href as required prop FE-6006 

cypress/components/fieldset/fieldset.cy.tsx, src/components/fieldset/fieldset-test.stories.tsx
- Rename the `fieldset.cy.js` to `fieldset.cy.tsx` file in `./cypress/components/fieldset/` folder.
Currently fieldset component is in JS not in TS.
=> test(fieldset): refactor ts

cypress/components/message/message.cy.tsx, cypress/locators/message/index.js, cypress/locators/message/locators.js, src/components/message/message-test.stories.tsx, src/components/message/message.component.tsx, src/components/message/message.spec.tsx, src/components/message/message.stories.mdx, src/components/message/message.stories.tsx, src/components/message/message.style.ts
fixes #5924
Add a ref so that the `Message` component can be focused.
Component is not currently focusedable.
Inconsistent screenreader behaviour will not be addressed in this ticket. This work is to provide a mechanism for consumers to focus the `Message` component.
- `with focus` example: Message component should be focused when first opened and **not** display an outline. 
- `with focus` example: Screenreader should read out the message in the component.
- Should not have effected the functionality of the component.
- Should be no new accessibility warnings.
=> feat(message): enable component to be programmatically focused - FE-5727

cypress/components/numeral-date/numeral-date.cy.tsx, src/components/numeral-date/numeral-date-test.stories.tsx
- Rename the `numeral-date.cy.js` to the `numeral-date.cy.tsx` file in `./cypress/components/numeral-date/` folder.
Numeral Date tests are in js not ts.
=> test(numeral-date): refactor to TS

cypress/components/profile/profile.cy.tsx, src/components/profile/profile-test.stories.tsx
- Rename the `profile.cy.js` to `profile.cy.tsx` file in `./cypress/components/profile/` folder.
Currently profile component is in JS not in TS.
=> test(profile): typescript refactor

cypress/components/note/note.cy.tsx, src/components/note/note-test.stories.tsx
- Rename the `note.cy.js` to the `note.cy.tsx` file in `./cypress/components/note/` folder.
Currently Note component is in JS not in TS.
=> test(note): typescript refactor

cypress/components/search/search.cy.js, src/components/search/search.component.tsx, src/components/search/search.spec.tsx, src/components/search/search.stories.mdx, src/components/search/search.stories.tsx
New prop `searchButtonAriaLabel` has been created so that consumers can add their own aria-label to the Search component when rendered with a button.
fixes #6007
Add `searchAriaLabelButton` prop to component so that consumers can specify their own custom aria-label for the Search component's button when rendered. 
Currently no mechanism to specify a custom aria-label for Search's button.
N/A
- Inspect the search button and ensure that a default aria-label appears correctly.
- Inspect the search button and ensure that a user-defined aria-label appears correctly.
=> feat(search): add searchButtonAriaLabel prop to component - FE-5880

cypress/components/fieldset/fieldset.cy.tsx, cypress/components/loader-bar/loader-bar.cy.tsx, cypress/components/message/message.cy.tsx, cypress/components/note/note.cy.tsx, cypress/components/numeral-date/numeral-date.cy.tsx, cypress/components/typography/typography.cy.tsx, package.json
- Rename the `typography.cy.js` to the `typography.cy.tsx` file in `./cypress/components/typography/` folder.
- Apply `prettier` to run over `cypress` folder too to avoid such conflits  
Typography tests are in js not ts.
=> test(typography): refactor to TS

cypress/components/grid/grid.cy.tsx
- Rename the `grid.cy.js` to `grid.cy.tsx` file in `./cypress/components/grid/` folder.
Grid tests are in js not ts.
=> test(grid): typescript refactor

cypress/components/toast/toast.cy.tsx
- Rename the `toast.cy.js` to `toast.cy.tsx` file in `./cypress/components/toast/` folder.
Toast tests are in js not ts.
=> test(toast): typescript refactor

cypress/components/inline-inputs/inline-inputs.cy.tsx, src/components/inline-inputs/inline-inputs-test.stories.tsx
- Rename the `inline-inputs.cy.js` to the `inline-inputs.cy.tsx` file in `./cypress/components/inline-inputs/` folder.
- Create `inline-inputs-test.stories.tsx` file
Inline Inputs tests are in js not ts.
=> test(inline-inputs): refactor to TS

.storybook/preview.js, .storybook/withThemeProvider.js
Warning relating to `showName is deprecated as name will stop having dual purposes in the future. Please specify a title in globalTypes instead.` should not be present in console.
These warnings are acceptable:
Open up Storybook locally and visit the console in dev tools. There should be no warning relating to `showName is deprecated`.
=> chore(storybook): ensure toolbars have titles - FE-6030

cypress/components/icon-button/icon-button.cy.tsx, src/components/icon-button/icon-button-test.stories.tsx
- Rename the `icon-button.cy.js` to `icon-button.cy.tsx` file in `./cypress/components/icon-button/` folder.
Icon-button tests are in js not ts.
=> test(icon-button): typescript refactor

cypress/components/search/search.cy.tsx, src/components/search/search-test.stories.tsx
- Rename the `search.cy.js` to the `search.cy.tsx` file in `./cypress/components/search/` folder.
- Add eslint rule to cover `cypress` folder as well
Search tests are in js not ts.
=> test(search): refactor ts

cypress/components/pod/pod.cy.tsx, src/components/pod/pod-test.stories.tsx
- Rename the `pod.cy.js` to `pod.cy.tsx` file in `./cypress/components/pod/` folder.
Currently `Pod` component is in JS not in TS.
=> test(pod): ts refactor

cypress/components/breadcrumbs/breadcrumbs.cy.tsx
- Rename the `breadcrumbs.cy.js` to `breadcrumbs.cy.tsx` file in `./cypress/components/breadcrumbs/` folder.
Breadcrumbs tests are in js not ts.
=> test(breadcrumbs): refactor to TS

cypress/components/popover-container/popover-container.cy.tsx, src/components/popover-container/popover-container-test.stories.tsx
- Rename the `popover-container.cy.js` to `popover-container.cy.tsx` file in `./cypress/components/popover-container/` folder.
`Popover-container` tests are in js not ts.
=> test(popover-container): typescript refactor

cypress/components/decimal/decimal.cy.tsx, src/components/decimal/decimal.component.tsx, src/components/decimal/decimal.spec.tsx
A bug was present whereby if `allowEmptyValue` was false and precision value was less than 2, the value of Decimal would not be formatted correctly. This has been rectified by making sure that an empty value is formatted  with precision and locale taken in to consideration.
fixes #6012
When `allowEmptyValue` is false, the value displayed should follow the precision and locale set by the consumer. 
When `allowEmptyValue` is false, the value displayed does not follow the precision and locale set by the consumer if precision value is less than 2. 
N/A
- There should be not regressions with functionality.
- CSB link to test functionality. CSB is built from the one provided on the original issue: https://codesandbox.io/s/pensive-edison-lhqw2t
=> fix(decimal): ensure empty value is formatted correctly - FE-5892

cypress/components/radio-button/radio-button.cy.tsx, src/components/radio-button/radio-button-test.stories.tsx, src/components/radio-button/radio-button.stories.tsx
- Rename the `radio-button.cy.js` file to `radio-button.cy.tsx` file in `./cypress/components/radio-button/` folder.
- Formatting for `radio-button` test file
Radio Button tests are in js not ts.
=> test(radio-button): refactor ts

cypress/components/simple-color-picker/simple-color-picker.cy.tsx, src/components/simple-color-picker/simple-color-picker-test.stories.tsx
- Rename the `simple-color-picker.cy.js` file to `simple-color-picker.cy.tsx` file in `./cypress/components/simple-color-picker/` folder.
Simple color picker tests are in js not ts.
=> test(simple-color-picker): refactor tests to ts

src/components/flat-table/flat-table.component.js, src/components/flat-table/flat-table.spec.js
fix #6152
Ensure the default browser behaviour is prevented when using up and down arrow keys to navigate clickable/ expandable rows
Using up and down arrow keys to navigate clickable/ expandable rows scrolls the window
This can be tested in storybook using any FlatTable story that has clickable rows or the expandable ones
=> fix(flat-table): ensure window does not scroll when using up and down  arrow keys to navigate rows

cypress/components/dialog/dialog.cy.tsx, src/components/dialog/dialog-test.stories.tsx
- Rename the `dialog.cy.js` file to `dialog.cy.tsx` file in `./cypress/components/dialog/` folder.
Dialog tests are in js not ts.
=> test(dialog): typescript refactor

cypress/components/sidebar/sidebar.cy.tsx, src/components/sidebar/sidebar-test.stories.tsx
- Rename the `sidebar.cy.js` file to `sidebar.cy.tsx` file in `./cypress/components/sidebar/` folder.
- Formatting for `sidebar` test file
Sidebar tests are in js not ts.
=> test(sidebar): refactor ts

cypress/components/accordion/accordion.cy.tsx, cypress/components/button-minor/button-minor.cy.tsx, src/components/button-minor/button-minor-test.stories.tsx
- Rename the `button-minor.cy.js` to `button-minor.cy.tsx` file in `./cypress/components/button-minor/` folder.
bBtton-minor tests are in js.
=> test(button-minor): refactor to ts

cypress/components/select/filterable-select/filterable-select.cy.tsx, cypress/components/select/multi-select/multi-select.cy.tsx, cypress/components/select/simple-select/simple-select.cy.tsx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/simple-select/simple-select-test.stories.tsx
- Rename the `multi-select.cy.js`, `filterable-select.cy.js`, `simple-select.cy.js` to `multi-select.cy.tsx`, `filterable-select.cy.tsx`, `simple-select.cy.tsx` file in `./cypress/components/select/` folder.
`Select` tests are in js not ts.
=> test(select): typescript refactor

.storybook/main.js
- Explicitly opt-out of telemetry in main storybook config
- Carbon is currently opted-in for Storybook to collect data about how its used in Carbon. For more details, [see this full list of information Storybook collects](https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out). 
=> chore: disable storybook telemetry

cypress/components/tooltip/tooltip.cy.tsx, src/components/tooltip/tooltip-test.stories.tsx, src/components/tooltip/tooltip.stories.tsx
- Rename the `tooltip.cy.js` to `tooltip.cy.tsx` file in `./cypress/components/tooltip/` folder.
Currently Tooltip component is in JS not in TS.
=> test(tooltip): typescript refactor

cypress/components/tile/tile.cy.tsx, src/components/tile/tile-test.stories.tsx
- Rename the `tile.cy.js` to `tile.cy.tsx` file in `./cypress/components/tile/` folder.
`Tile` tests are in js not ts.
=> test(tile): typescript refactor

cypress/components/box/box.cy.tsx, src/components/box/box-test.stories.tsx
- Rename the `box.cy.js` to `box.cy.tsx` file in `./cypress/components/box/` folder
`Box` tests are in js not ts.
=> test(box): refactor cypress tests to typescript

cypress/components/password/password.cy.tsx, src/components/password/password-test.stories.tsx, src/components/password/password.stories.tsx
- Rename the `password.cy.js` to the `password.cy.tsx` file in the `./cypress/components/password/` folder.
`Password ` tests are in js not ts.
=> test(password): refactor to ts

cypress/components/date/date.cy.tsx, cypress/support/component-helper/cypress-mount.tsx, src/components/date/date-test.stories.tsx
- Rename the `date.cy.js` to the `date.cy.tsx` file in the `./cypress/components/date/` folder.
`Date Input` tests are in js not ts.
=> test(date): refactor to ts

cypress/components/date-range/date-range.cy.tsx, src/components/date-range/date-range-test.stories.tsx
- Rename the `date-range.cy.js` to the `date-range.cy.tsx` file in the `./cypress/components/date-range/` folder.
`Date Range` tests are in js not ts.
=> test(date-range): refactor to ts

cypress/components/menu/menu.cy.tsx, src/__internal__/utils/helpers/events/events.ts, src/components/menu/__internal__/submenu/submenu.component.tsx, src/components/menu/__internal__/submenu/submenu.spec.tsx
A bug is present that means when the `enter` key is pressed on the Search component, the whole submenu closes. This fix ensures that the submenu does not close when enter is pressed when an event is fired from the input or the `X` icon inside Search.
fixes #6146
Submenu should only close if the `enter` key event comes outside of the Search input or `X` icon.
Submenu closes when the `enter` key is pressed inside of the Search component.
N/A
Codesandbox to test with: https://codesandbox.io/s/submenu-with-search-c4xdvw
- Navigate to Search component
- Type a value in the Search component
- Press `Enter`
- Submenu should stay open
=> fix(menu): ensure menu remains open when enter is pressed on search - FE-6035

src/__internal__/fieldset/fieldset.component.tsx, src/components/checkbox/checkbox.component.tsx, src/components/checkbox/checkbox.style.ts, src/components/radio-button/radio-button-group.component.tsx, src/components/radio-button/radio-button-group.spec.tsx, src/components/radio-button/radio-button-group.style.ts, src/components/radio-button/radio-button.component.tsx, src/components/radio-button/radio-button.stories.mdx, src/components/radio-button/radio-button.stories.tsx, src/components/textbox/textbox.style.ts
New style validations are not supported in `Radio Button` and `Radio Button Group`.
Validation styles for `large` size will be completed in another ticket due to the way in which `size` is specified in this component.
- New validations should match the designs created by DS.
- Old validations should continue to work as normal.
- No other regressions with functionality or styles.
=> feat(radio-button): add support for new validation - FE-5753

cypress/components/definition-list/definition-list.cy.tsx, src/components/definition-list/definition-list-test.stories.tsx
- Rename the `definition-list.cy.js` to the `definition-list.cy.tsx` file in the `./cypress/components/definition-list/` folder.
- Added definition-list-test.stories.tsx
`definition-list` tests are in js not ts.
=> test(definition-list): typescript refactor

cypress/components/select/filterable-select/filterable-select.cy.tsx, cypress/components/select/multi-select/multi-select.cy.tsx, cypress/components/select/simple-select/simple-select.cy.tsx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/option-group-header/option-group-header.component.tsx, src/components/select/option-group-header/option-group-header.spec.tsx, src/components/select/option-row/option-row.component.tsx, src/components/select/option-row/option-row.spec.tsx, src/components/select/option/option.component.tsx, src/components/select/option/option.spec.tsx, src/components/select/select-list/select-list.component.tsx, src/components/select/select-list/select-list.spec.tsx, src/components/select/simple-select/simple-select-test.stories.tsx
fix #6126, fix #5810
A condition has been added to `SelectList` which checks if the `id` prop is present on any children, if it is the GUID is not applied. This provides consumers with flexibility to pass specific IDs to `OptionGroupHeader`, `OptionRow`, and `Option` component children. Also all interfaces in `Option`, `OptionRow` and `OptionGroupHeader` now extend `TagProps`, giving consumers access to the `data-role` and `data-element` attributes for testing purposes
Currently, a GUID is applied to every potential child of the `SelectList` component `(OptionGroupHeader, OptionRow, Option)`. Even when consumers pass the `id` prop, the id attribute is still overwritten with a GUID.
You can see the new behaviour by looking at …
=> feat(option-group-header, option-row, option): allow custom IDs and surface data selectors

cypress/components/action-popover/action-popover.cy.tsx, cypress/locators/action-popover/index.js, cypress/locators/action-popover/locators.js, src/components/action-popover/action-popover-context.ts, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx, src/components/action-popover/action-popover-test.stories.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.spec.tsx, src/components/action-popover/action-popover.stories.mdx, src/components/action-popover/action-popover.stories.tsx, src/components/action-popover/action-popover.style.ts
fix #5801
Nine new design variations have been implemented for the component, each one varies based on specific props and attributes passed to individual children and siblings.
**Please see new designs below:**
**Number 1: All children and siblings have no icons or submenus.**
**Number 2: All children and siblings have no icons, but only some have submenus.**
**Number 3: All children and siblings have no icons, but all have submenus.**
**Number 4: All children and siblings have no submenus, but only some have icons.**
**Number 5: All children and siblings have no submenus, but all have icons.**
**Number 6: All children and siblings have submenus and icons.**
**Number 7: All children and siblings have icons, but only some have submenus.**
**Number 8: All children and siblings have …
=> feat(action-popover): align component with design system 

cypress/components/multi-action-button/multi-action-button.cy.tsx, cypress/components/split-button/split-button.cy.tsx, src/components/button/button.component.tsx, src/components/multi-action-button/multi-action-button-test.stories.tsx, src/components/multi-action-button/multi-action-button.component.tsx, src/components/split-button/__internal__/split-button.context.ts, src/components/split-button/split-button-test.stories.tsx, src/components/split-button/split-button.component.tsx, src/hooks/__internal__/useChildButtons/index.ts, src/hooks/__internal__/useChildButtons/useChildButtons.tsx, src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.spec.tsx, src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.ts
SplitButton and MultiActionButton used to clone their children and pass particular props, including refs - assuming each child was a Button component. This meant that the components failed to work properly when using custom child components that wrap one or more Carbon Buttons (at least unless forwardRef was used). This has now been replaced by a context-based approach using DOM selectors to achieve the same functionality no matter how the children are composed.
fix #4784
All functionality in SplitButton and MultiActionButton should work when consumers wrap Carbon Button in a custom child component
There are warnings in the console when using such a wrapper, and keyboard navigation fails to work
Ensure that the original issue is fixed, and perform regression testing on the SplitButton and …
=> fix(split-button, multi-action-button): remove children iteration

cypress/components/checkbox/checkbox.cy.tsx, src/components/checkbox/checkbox-group.component.tsx, src/components/checkbox/checkbox-group.spec.tsx, src/components/checkbox/checkbox-group.style.ts, src/components/checkbox/checkbox-test.stories.tsx, src/components/checkbox/checkbox-validations.stories.mdx, src/components/checkbox/checkbox-validations.stories.tsx, src/components/checkbox/checkbox.component.tsx, src/components/checkbox/checkbox.stories.mdx
New style validations are not supported in Checkbox
Styling for `size="large"` larger validation will be done in a separate piece of work
Testing instructions to follow
=> feat(checkbox): add support for new validation - FE-5754

tsconfig-build.json, tsconfig.json
The `build:types` script ran as part of the release process is broken as it outputs the `.d.ts` files inside `src` directories in the output folders. On investigation, this has happened because of the addition of `.ts` files inside the new `playwright` folder which are not excluded from the ts build and which cause tsc to default the `rootDir` compiler option to the root directory, rather than the `src` folder as it needs to be. To fix this, `rootDir` has been explicitly set to `./src/` in the build config, as well as the playwright ts files being excluded (without that tsc throws errors about trying to build files outside of `rootDir`). To avoid breaking the local `type-check` script which still needs to typecheck the playwright ts files, the new config has only been added inside the …
=> fix: set rootDir to src in tsconfig

.github/workflows/playwright.yml, playwright/support/helper.ts, src/components/badge/badge.pw.tsx, src/components/breadcrumbs/breadcrumbs.pw.tsx
- add reporting statuses back to github
- add helper for events 
- no reporting statuses back to github
- no helper for events
=> Playwright events

.github/workflows/cypress.yml, .github/workflows/playwright.yml
Update SHA so correct commit status is reported back
Reporting is using current HEAD SHA from master instead of PR
=> build(playwright, cypress): update workflows to ensure commit status is reported FE-6174

.github/CODEOWNERS
Carbon dev own unit (spec) test files
Carbon QA own unit (spec) test files
=> chore: remove qa as owners of unit test files

cypress/components/flat-table/flat-table.cy.tsx, src/components/flat-table/__internal__/build-position-map.ts, src/components/flat-table/__internal__/index.ts, src/components/flat-table/__internal__/use-calculate-sticky-cells.ts, src/components/flat-table/flat-table-cell/flat-table-cell.component.tsx, src/components/flat-table/flat-table-cell/flat-table-cell.style.ts, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.component.tsx, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.spec.tsx, src/components/flat-table/flat-table-checkbox/flat-table-checkbox.style.ts, src/components/flat-table/flat-table-head/flat-table-head.component.tsx, src/components/flat-table/flat-table-header/flat-table-header.component.tsx, src/components/flat-table/flat-table-header/flat-table-header.spec.tsx, src/components/flat-table/flat-table-header/flat-table-header.style.ts, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.tsx, src/components/flat-table/flat-table-row-header/flat-table-row-header.spec.tsx, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.ts, src/components/flat-table/flat-table-row/__internal__/flat-table-row-context.tsx, src/components/flat-table/flat-table-row/__internal__/flat-table-row-draggable.component.tsx, src/components/flat-table/flat-table-row/__internal__/sub-row-provider.tsx, src/components/flat-table/flat-table-row/flat-table-row.component.tsx, src/components/flat-table/flat-table-row/flat-table-row.spec.tsx, src/components/flat-table/flat-table-row/flat-table-row.style.ts, src/components/flat-table/flat-table-test.stories.tsx, src/components/flat-table/flat-table.component.tsx, src/components/flat-table/flat-table.spec.tsx, src/components/flat-table/flat-table.stories.tsx
fix #6219
- some tests were refactored to RTL as they now need to be async to allow the update to occur before the assertion
Adds data tags to FlatTableCheckbox
Refactors `FlatTable` and sub-components to allow consumers greater flexibility with respect to
wrapping the components by removing code that relied on iterating over children and cloning.
Refactors `FlatTableRow` so that it is no longer required that an array is passed to the `subRows`
prop. Adds `FlatTableRowContext` and `SubRowProvider` as well as adding `data-sticky-align` attribute to `FlatTableRowHeader` and `id` attribute to all row children to support `expandable` and `sticky` column functionality.
Components rely heavily on children iteration and using cloning to pass props down to achieve desired functionality.
The …
=> feat(flat-table, flat-table-row): components can now be wrapped, subRows no longer need to be arrays FE-6050

cypress/components/typography/typography.cy.tsx, src/components/typography/typography.component.tsx, src/components/typography/typography.spec.tsx, src/components/typography/typography.stories.mdx, src/components/typography/typography.stories.tsx, src/components/typography/typography.style.ts
Add a new prop to the Typography component that will allow consumers to visually hide text for the purpose of screen readers.
This is a new feature so currently there is no support for this
Adding the prop `screenReaderOnly` will enable the visually hidden behaviour
The following CodeSandbox shows the new prop in operation:
https://codesandbox.io/s/carbon-quickstart-forked-7xhg4n
=> feat(typography): add a prop to support text that is for screen readers only

.github/workflows/codeql-analysis.yml
related reading:
https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
Update to v2 of CodeQL action
workflow uses v1
=> ci(code-ql): update code-ql workflow to use latest version of action

src/components/link/link.component.tsx, src/components/link/link.spec.tsx, src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.spec.tsx
`Elements must only use allowed ARIA attributes` error was occurring in an example of Menu with icon only menu items. This was due to the aria-label being specified on the anchor element and also the underlying span element of the icon itself.
fixes #6175
fixes #4986
Address "Elements must only use allowed ARIA attributes" warning on `with icon` Menu story.
`with icon` Menu story has an accessibility error of "Elements must only use allowed ARIA attributes".
N/A
- `with icon` Story should have no accessibility errors. 
- Should be no regression of features or screenreader behaviour in `menu-item`, `link` and `icon`.
=> fix(menu-item): address aria role accessibility error with icon only menu items - FE-6055

cypress/components/flat-table/flat-table.cy.tsx, src/components/flat-table/__internal__/index.ts, src/components/flat-table/__internal__/use-table-cell.ts, src/components/flat-table/flat-table-cell/flat-table-cell.component.tsx, src/components/flat-table/flat-table-header/flat-table-header.component.tsx, src/components/flat-table/flat-table-header/flat-table-header.spec.tsx, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.tsx, src/components/flat-table/flat-table-row/__internal__/flat-table-row-context.tsx, src/components/flat-table/flat-table-row/flat-table-row.component.tsx, src/components/flat-table/flat-table-row/flat-table-row.spec.tsx, src/components/flat-table/flat-table-test.stories.tsx, src/components/flat-table/flat-table.component.tsx, src/components/flat-table/flat-table.spec.tsx
Updates component to handle loading states and pagination to ensure tab stop is put on correct row.
Ensure tab index is placed on correct cell when first column is expandable and is in selected or highlighted row
Tab index is not updated on first/ highlighted/ selected row when there is a loading state and pagination is used
When first column is expandable and part of the a highlighted/ selected row the tab index is set incorrectly
https://codesandbox.io/s/rough-paper-nmdxzk?file=/src/App.js
(may be easier to run locally so you can trigger the loading state by refreshing page etc)
Ensure first row/ cell is focused when tabbing or …
=> fix(flat-table): ensure tabindex is set on clickable elements when table has pager and loading state FE-6194

src/components/link-preview/link-preview.stories.mdx
fixes #6313
Ensure prop table renders for component
No prop table currently renders
N/A
Prop table should be rendered for `Link-Preview` component
=> docs(link-preview): ensure props table renders 

cypress/components/toast/toast.cy.tsx, src/components/message/message-test.stories.tsx, src/components/message/message.component.tsx, src/components/message/message.pw.tsx, src/components/message/message.spec.tsx, src/components/message/message.stories.mdx, src/components/message/message.stories.tsx, src/components/message/message.style.ts, src/components/message/type-icon/__snapshots__/type-icon.spec.tsx.snap, src/components/message/type-icon/type-icon.component.tsx, src/components/message/type-icon/type-icon.spec.tsx, src/components/message/type-icon/type-icon.style.ts, src/components/toast/toast.component.tsx, src/components/toast/toast.config.ts, src/components/toast/toast.spec.tsx, src/components/toast/toast.stories.mdx, src/components/toast/toast.stories.tsx, src/components/toast/toast.style.ts
Toast: 
- Update Toast with new variants and colours.
- Introduced a new `notification` variant.
- Introduced a new `align` prop that will supersede the current `isCenter` prop.
- Deprecation warning applied to the `isCenter` prop.
Message:
- Update Message with new variants and colours.
- Update success variant icon to `tick_circle`.
- No `notification` variant.
- No `align` prop.
- `isCenter` prop is still recommended for positioning the component.
- Message no doesn't align with the DS.
N/A
- Deprecation warning should only appear in the console once.
- Test the new stories created for `align` prop example.
- Test that the new `notification` toast example matches the designs provided in the ticket.
- No other styling regressions to any other variants of `Toast`.
- `isCenter` prop …
=> feat(toast, message): update component to align with Design System - FE-5775

src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.pw.tsx, src/components/dialog/dialog.spec.tsx, src/components/dialog/dialog.stories.mdx, src/components/dialog/dialog.stories.tsx, src/components/dialog/index.ts
addresses #6250
- Allow ability for consumers to forward a ref handle to `Dialog`, which exposes the component's root DOM node `focus()` method:
```tsx
import Dialog from "carbon-react/lib/components/dialog";
import type { DialogHandle } from "carbon-react/lib/components/dialog";
const MyComponent = () => {
const dialogHandle = useRef<DialogHandle>(null);
return (
<Dialog ref={dialogHandle}>
<Button onClick={() => dialogHandle.current?.focus()}>
Refocus on dialog
</Button>
</Dialog>
);
};
``` 
- Update `Dialog` tests to address DOM elements, particularly those used by React Portals, that were not cleaned-up after tests
Currently, there is no way to programmatically refocus on the `Dialog`'s root DOM node. This functionality is required for cases where the content inside the `Dialog` is …
=> feat(dialog): expose focus method of root dom node via a ref handle (FE-6176)

src/components/accordion/accordion-test.stories.tsx, src/components/accordion/accordion.stories.tsx, src/components/sidebar/sidebar-test.stories.tsx, src/components/sidebar/sidebar.stories.tsx
N/A
Content should not be obscured by the new focus styling in any `Sidebar` examples.
Content should not be obscured by the new focus styling in any `Accordion` examples.
=> docs(sidebar): ensure content is not obscured due to new focus styling

.github/workflows/playwright.yml, cypress/components/flat-table/flat-table.cy.tsx
- Increase timeout for Playwright workflow from 20mins to 30mins.
- Skip flaking `FlatTable` cypress test, note to investigate in a separate ticket
- Currently, some PRs have failing Playwright tests, due to workflow timing out.
[Playwright seems to recommend 60 minutes for GitHub Actions workflows](https://playwright.dev/docs/ci-intro). However, it would be ideal to first ensure tests are written to not encourage flakiness, as well as explore parallelisation options.
=> chore(playwright): increase timeout for github actions workflow

src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/multi-action-button/multi-action-button.stories.mdx, src/components/multi-action-button/multi-action-button.stories.tsx, src/components/multi-action-button/multi-action-button.style.ts
fix #6214
Removes styling that targets icons in child buttons and applies 8px of left position. This ensures that the spacing between button text and icon matches DS.
Incorrect spacing when child buttons have icons
=> fix(multi-action-button): update styling to ensure corrext spacing when child buttons have icons

cypress/components/menu/menu.cy.tsx, src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap, src/components/link/__snapshots__/link.spec.tsx.snap, src/components/link/link-test.stories.tsx, src/components/link/link.component.tsx, src/components/link/link.style.ts, src/components/menu/menu-item/menu-item.style.ts
fix #6320
Refactor new focus styling for `Link` to avoid `focus-within` as it creates issues when running tests in JSDOM.
Ensures `text-decoration` is `none` when new focus styling applied
Fixes test story `icon` dropdown
New focus styling uses `focus-within`
`text-decoration` is `underline` when new focus styling applied
Test story `icon` dropdown is broken
=> fix(link): refactor styles to remove focus-within due to issues with JSDOM FE-6217

src/components/dialog/dialog.stories.mdx
- Fix typos in docs 
- Reword explanation regarding refocusing dialogs, to avoid ambiguity.
- Explanation of refocusing dialogs is misleading
- [] Related issues linked in commit messages if required
- [] Screenshots are included in the PR if useful
- [] All themes are supported if required
- [] Unit tests added or updated if required
=> docs(dialog): update explanation on refocusing

src/components/batch-selection/batch-selection.pw.tsx, src/components/button/button.pw.tsx, src/components/dialog/dialog.pw.tsx
Fix flaky Batch-Selection, Button & Dialog Playwright tests
Tests regularly fail during CI checks
N/A
=> test(playwright): more flaky tests

playwright/support/helper.ts, src/components/dialog/dialog.pw.tsx, src/components/drawer/__snapshots__/drawer.spec.tsx.snap, src/components/drawer/drawer.component.tsx, src/components/drawer/drawer.pw.tsx
Adds a util to ensure animations are complete before asserting the state of UI in playwright tests
We assert that there are no accessibility failures on Dialog and Drawer but we trigger actions as part of these tests and they run animations. This means that the tests are occasionally asserting whilst the animation is still running and failing incorrectly
=> Fix animation issues pw

cypress/components/global-header/global-header.cy.tsx, cypress/components/menu/menu.cy.tsx, src/components/global-header/global-header-test.stories.tsx, src/components/global-header/global-header.spec.tsx, src/components/navigation-bar/components.test-pw.tsx, src/components/navigation-bar/fixed-navigation-bar-context.spec.tsx, src/components/navigation-bar/fixed-navigation-bar.context.tsx, src/components/navigation-bar/navigation-bar-test.stories.tsx, src/components/navigation-bar/navigation-bar.component.tsx, src/components/navigation-bar/navigation-bar.pw.tsx, src/components/navigation-bar/navigation-bar.spec.tsx
NavigationBar and GlobalHeader, when rendered, should not throw ResizeObserver errors.
Fix https://github.com/Sage/carbon/issues/6259
An error is thrown: "ResizeObserver loop completed with undelivered notifications" (precise wording varies between browsers but it always mentions ResizeObserver).
The error is only seen in the console on Safari - so please check all our stories for GlobalHeader and NavigationBar in the Safari browser: they should throw an ResizeObserver-related error in the console when run on master, but not on this branch.
For testing other browsers, uses this sandbox https://codesandbox.io/s/tender-stallman-mz9tz7?file=/src/App.tsx which catches the error and logs it to the console. (This is similar to what happens in Sage MFE environments, where there is a window …
=> fix: remove resize observer error

src/components/button-bar/button-bar.pw.tsx, src/components/button/__snapshots__/button.spec.tsx.snap, src/components/button/button.spec.tsx, src/components/button/button.style.ts, src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap
Correct the icon sizes when used inside a button to 20px width and height.
Icons inside button are currently using "space" as 16px width and height.
n/a
View Button story and view button with an icon, inspect to view size render.
=> fix(button): correct the width and height of icons inside buttons

cypress/components/date/date.cy.tsx, cypress/components/select/filterable-select/filterable-select.cy.tsx, cypress/components/select/multi-select/multi-select.cy.tsx, cypress/components/select/simple-select/simple-select.cy.tsx, cypress/components/textarea/textarea.cy.tsx, cypress/components/textbox/textbox.cy.tsx, src/__internal__/input-icon-toggle/input-icon-toggle.component.tsx, src/__internal__/input-icon-toggle/input-icon-toggle.spec.tsx, src/__internal__/input-icon-toggle/input-icon-toggle.style.ts
When the `inputIcon` prop is passed and `disabled` or `readOnly` are true, the input icon is properly rendered with the expected styling and cursor behaviour.
When the `inputIcon` prop is passed and `disabled` or `readOnly` are true the input icon is not rendered in the DOM.
=> fix(textarea, textbox): display icon when component is disabled or readOnly

cypress/components/popover-container/popover-container.cy.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.spec.tsx, src/components/popover-container/popover-container.stories.tsx
This fix ensures that the PopoverContainer component close when the escape key is pressed. The only exception to this is if Select is currently focused/open as we want Select to still function as it's default behaviour when escape key is pressed.
fixes #6195
- Component should be closed when Esc key is pressed.
- Component does not close when Esc key is pressed. 
If the `PopoverContainer` contains a `Select` component, then the popover should not close when `Select` is focused/ `SelectList` is open as we want to preserve the default functionality of `Select` in this particular case.
- Esc key closes the `PopoverContainer`. 
- In the `complex` example, then the correct behaviour is that the `PopoverContainer` should not close when `Select` is focused and the `SelectList` is open as we want …
=> fix(popover-container): ensure that component is closed when Esc key is pressed - FE-6072

src/components/switch/switch.component.tsx, src/components/switch/switch.spec.tsx
A bug is present whereby when the new validation style is used and no hint text or validation message is passed to the component, the label appears to be misaligned
fixes #6303
N/A
There should be no other styling regressions to Switch in the new or old style validations.
=> fix(switch): fix alignment issue with component when no new validation is applied

package-lock.json, package.json
wait-on package is no longer required in the codebase as the script that use it has since been removed.
Remove `wait-on` package.
`wait-on` package exists in Carbon.
N/A
N/A
=> chore(dependencies): remove wait-on package - FE-6272

src/components/dialog-full-screen/components.test-pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx
fixes #4942
- Address invalid DOM nesting warning in the `with complex` example of `DialogFullScreen`
- Replace any `div` element with our `Box` component
- Address a few styling issues with the `Button Tertiary +` button and the text inside of `Example One Products`, `Example Two Products` and `Example Three Products`.
invalid DOM nesting warning in the `with complex` example of `DialogFullScreen`
N/A
- No visual or functional regressions in the `DialogFullScreen` Examples.
- No console errors regarding invalid DOM nesting.
=> docs(dialog-full-screen): address invalid DOM nesting in stories - FE-5025

cypress/components/select/filterable-select/filterable-select.cy.tsx, cypress/components/select/multi-select/multi-select.cy.tsx, cypress/components/select/simple-select/simple-select.cy.tsx, src/__internal__/checkable-input/hidden-checkable-input.component.tsx, src/__internal__/focus-trap/focus-trap-utils.ts, src/__internal__/focus-trap/focus-trap.component.tsx, src/__internal__/focus-trap/focus-trap.spec.tsx, src/__internal__/input/input.component.tsx, src/components/dialog-full-screen/components.test-pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog/components.test-pw.tsx, src/components/dialog/dialog.pw.tsx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/filterable-select/filterable-select.component.tsx, src/components/select/filterable-select/filterable-select.spec.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/multi-select/multi-select.component.tsx, src/components/select/multi-select/multi-select.spec.tsx, src/components/select/simple-select/simple-select-test.stories.tsx, src/components/select/simple-select/simple-select.component.tsx, src/components/select/simple-select/simple-select.spec.tsx
fix #6384
Ensures that when a Carbon input has the `autoFocus` prop set on it and rendered as a child of a focus trapped parent (`Dialog`, `DialogFullScreen`, `Sidebar`, `Confirm` and so on) is focused first when rendered. Also ensures that any elements with tabIndex of -1 are ignored by the tab guards, rendered as part of the FocusTrap, when selecting which element to focus next.
Children with `autoFocus` are not focused when a focus trapped parent is rendered
Elements with tabIndex -1 are not ignored by the tab guards in the FocusTrap
https://codesandbox.io/s/charming-water-jvt46y?file=/src/App.js
=> fix: ensure any auto-focused element is focused first when a child of a focus trapped component

playwright/support/helper.ts, src/components/alert/alert.pw.tsx, src/components/anchor-navigation/anchor-navigation.pw.tsx, src/components/checkbox/checkbox.pw.tsx, src/components/confirm/confirm.pw.tsx, src/components/decimal/decimal.pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog/dialog.pw.tsx, src/components/drawer/drawer.pw.tsx, src/components/duelling-picklist/duelling-picklist.pw.tsx, src/components/form/form.pw.tsx, src/components/help/help.pw.tsx, src/components/icon/icon.pw.tsx, src/components/portrait/portrait.pw.tsx, src/components/tile/tile.pw.tsx
Adds a animation wait to the check accessibility util
Refactors some other flaky tests
Ignores the `color-contrast` rule for `DialogFullscreen`, to be investigated separately
Several flaky playwright tests that intermittently fail the build
=> chore: address flaky playwright tests

src/components/checkbox/checkbox.stories.mdx
- Add `CheckboxGroup` import to `Checkbox`'s quick start section
- `CheckboxGroup` import in `Checkbox`'s quick start section is missing
=> docs(checkbox): add missing import for checkbox group

src/components/message/message-content/message-content.style.ts, src/components/toast/toast.component.tsx, src/components/toast/toast.spec.tsx, src/components/toast/toast.stories.mdx, src/components/toast/toast.style.ts
It was decided in 2019 that `Toast` should share the same functionality and styling as `Message`. This was the correct decision at the time but with the new Design System and the changes coming to these components, it will be easier to maintain these as two separate components.
- Split `Toast` and `Message` so that `Toast` no longer relies on `Message` for styling, icons and colours.
- Tidying up the naming used in the `Toast` style file.
`Toast` relies on `Message` for styling, icons and colours.
N/A
There should be no functional or styling regressions with Toast.
=> refactor(toast): Decouple Toast component from Message component - FE-6228

src/components/date/date.component.tsx, src/components/select/select-textbox/select-textbox.component.tsx, src/components/textbox/textbox.component.tsx, src/components/textbox/textbox.pw.tsx, src/components/textbox/textbox.spec.tsx
fix #6471
Ensures that `click` and `mousedown` event handlers are not triggered when `disabled` or `readOnly` `Textbox` based components or the input `Icon` is clicked.
Textbox based components set to readOnly or disabled can still trigger and action when clicked
=> fix(textbox): ensure no action is triggered when disabled or readOnly input or input icon is clicked FE-6293

cypress/components/numeral-date/numeral-date.cy.tsx, cypress/locators/numeralDate/index.js, src/components/numeral-date/numeral-date.component.tsx, src/components/numeral-date/numeral-date.spec.tsx, src/components/numeral-date/numeral-date.stories.mdx, src/components/numeral-date/numeral-date.stories.tsx, src/components/numeral-date/numeral-date.style.ts, src/locales/en-gb.ts, src/locales/locale.ts, src/locales/pl-pl.ts
- Component has 3 separate fields with distinct labels for 'Day', 'Month' and 'Year'. 
- Fields have a gap between them. 
- Supports YYYY/MM/DD date format. 
- New validation side border reaches the message. 
- `labelHelp` tooltip does not appear with new validation hint text. 
- Component does not support YYYY/MM/DD date format. 
- Fields do not have distinct labels.
- Fields don't have a gap between them. 
- New validation side border does not reach the message. 
- `labelHelp` tooltip still shows with new validation hint text. 
=> feat(numeral-date): add date format and update to align with DS

playwright/index.tsx, src/components/numeral-date/numeral-date.component.tsx, src/components/numeral-date/numeral-date.pw.tsx, src/components/numeral-date/numeral-date.spec.tsx, src/components/numeral-date/numeral-date.stories.tsx, src/locales/__internal__/pl-pl.ts, src/locales/en-gb.ts, src/locales/locale.ts
fix #6438
Built in internal validations will now use `month` and `year` values if provided to validate if `day` input value is within valid range. Adds optional dynamic message that includes the month and days in it when a value is invalid.
Built-in validations do not dynamically account for month or year values
See internal validation stories for `NumeralDate`
=> fix(numeral-date): ensure internal validation uses given month and year values where possible

cypress/components/popover-container/popover-container.cy.tsx, src/__internal__/popover/popover.component.tsx, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.spec.tsx, src/components/popover-container/popover-container.stories.mdx, src/components/popover-container/popover-container.stories.tsx, src/components/popover-container/popover-container.style.ts
Introduces the `disableAnimation` prop to the component so that the transitions can be disabled.
fixes #6002
- Add `disableAnimation` prop
- Disable animation if the user specifies that they want reduced motion
- Skip flaky Cypress test that uses `getBoundingClientRect()` to assert whether the button is covered or not.
- No way to disable animation
- Component does not cater for users who prefer no motion.
Comment out of the flaky Cypress test that uses `getBoundingClientRect()` to assert whether the button is covered or not is covered by a Chromatic snapshot. This means we'll be able to see in future if this feature happens to regress. It will also be converted to PW.
- No functional regressions with component.
- If reduce motion is set, there should be no animations. 
- If …
=> feat(popover-container): add prop to disable animation - FE-5881

src/components/popover-container/popover-container.spec.tsx
Fixes issue in test whereby the `disableAnimation` prop is passed directly to the styled-component and not the component itself.
`disableAnimation` prop is passed directly to the styled-component 
N/A
N/A
=> test(popover-container): pass disableAnimation prop to component and instead of styled-component - (FE-6336)

src/components/link/link.pw.tsx, src/components/link/link.style.ts
fix #6434
`link` focus underline only wraps the component's children and is not affected by the width of the parent container. 
When `link` is focused the focus underline extends to the width of the parent container.
=> fix(link): focus underline fix

package-lock.json
- Upgrade `vite` to version 4.5.2
- `vite` is on version 4.5.1
=> chore: upgrade vite

src/components/select/filterable-select/components.test-pw.tsx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/filterable-select/filterable-select.component.tsx, src/components/select/filterable-select/filterable-select.pw.tsx, src/components/select/multi-select/components.test-pw.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/multi-select/multi-select.pw.tsx, src/components/select/option-row/option-row.component.tsx, src/components/select/option-row/option-row.spec.tsx, src/components/select/option-row/option-row.style.ts, src/components/select/option/option.component.tsx, src/components/select/option/option.spec.tsx, src/components/select/option/option.style.ts, src/components/select/select-list/select-list.component.tsx, src/components/select/select-list/select-list.spec.tsx, src/components/select/simple-select/simple-select-test.stories.tsx
Add `disabled` prop to `Option` and `OptionRow` in `Select` component. A disabled option will:
- Have disabled styles
- Have an `aria-disabled` attribute
- The user cannot click or keyboard navigate to this option
- The option will still appear in a filtered select but cannot be selected
`Option` and `OptionRow` in `Select` component do not have the option to be disabled. 
=> feat(option, option-row): add disabled prop

src/components/select/filterable-select/filterable-select.component.tsx, src/components/select/filterable-select/filterable-select.spec.tsx, src/components/select/filterable-select/filterable-select.stories.mdx, src/components/select/filterable-select/filterable-select.stories.tsx
Adds a new boolean prop to the FilterableSelect component, `disableDefaultFiltering`.
- By default `disableDefaultFiltering` is `false`, and filtering and highlighting of options is handled by the component itself. 
- If `disableDefaultFiltering` is set to `true`, the component does not automatically filter or highlight options as the user enters a text filter.
This allows use-cases like server-side filtering of options, or rich formatting of options.  Our use-case is an address search dropdown.
The new implementation uses a `FilterableSelectList` by default, and a `SelectList` if `disableDefaultFiltering` is `true`.  It is still appropriate to use a `FilterableSelect` in this case, because we still want access to the filter which is typed into the textbox.
Screenshot of the storybook …
=> feat(filterable-select): add disableDefaultFiltering prop

src/components/inline-inputs/inline-inputs.component.tsx, src/components/inline-inputs/inline-inputs.pw.tsx, src/components/inline-inputs/inline-inputs.spec.tsx, src/components/inline-inputs/inline-inputs.stories.mdx, src/components/inline-inputs/inline-inputs.stories.tsx
Add a labelAlign prop that will take "left" or "right" params. 
Should replicate the behaviour of the inline label labelAlign for the Textarea component.
fix #6498
No such prop exists.
=> feat(inline-inputs): add labelAlign prop

src/components/flat-table/flat-table-row/flat-table-row.component.tsx, src/components/flat-table/flat-table-row/flat-table-row.spec.tsx, src/components/flat-table/flat-table-row/flat-table-row.style.ts, src/components/flat-table/flat-table-test.stories.tsx
This fix uses the offset height of the flat-table-row element to correctly apply the correct height when the row is focused. This is fix is only for the newer focus styling and the old style will continue to work as it did previously.
fixes #6496
https://github.com/Sage/carbon/assets/56251247/8140b568-257d-4301-83d7-3d4eff7cc86e
https://github.com/Sage/carbon/assets/56251247/7a0e677e-b6ac-4f99-8ba2-943ba308528a
This piece of work is purely to address the static styling of Flat Table Row in Safari. A further piece of work to address any dynamic styles will be addressed in FE-6334.
- Navigate to the new `Flat Table Size Focus` test story in Safari and ensure that the focus border is the correct size for the new focus styling. 
- There should be no other functional or styling regressions …
=> fix(flat-table): ensure that focus size is correctly applied in Safari - FE-6315

src/components/preview/__internal__/preview-placeholder.style.ts, src/components/preview/preview.pw.tsx, src/components/preview/preview.spec.tsx
Applies a border radius to the component to ensure it is updated to have rounded corners.
fixes #6174
N/A
- Component should have the expected border-radius values.
- Turning the `Rounded corners` flag to `off` in Storybook should display the component with squared corners.
- No other styling or functional regression to this component.
=> feat(preview): add rounded corners styling to component - FE-6056

src/components/accordion/accordion-test.stories.tsx, src/components/accordion/accordion.component.tsx, src/components/accordion/accordion.pw.tsx, src/components/accordion/accordion.spec.tsx, src/components/accordion/accordion.stories.mdx, src/components/accordion/accordion.stories.tsx, src/components/accordion/accordion.style.ts
- Introduced `variant` prop with "standard" and "subtle" options, default accordion is now standard variant. 
- "chevron_down_thick" added to `iconType` options.
- Update standard accordion styles to align with DS. 
- `scheme` and `buttonHeading` have been deprecated. 
Subtle variant:
- `iconAlign` is set to "left" by default
- `iconType` is set to "chevron_down_thick" by default
- `borders` is set to "none"
- `subTitle` will not be rendered
- Does not support validation
- Accordion component does not have "subtle" variant. 
- Default styles do not align with DS. 
=> feat(accordion): add subtle variant and update default styles

playwright/support/helper.ts, src/__internal__/fieldset/fieldset.component.tsx, src/__internal__/fieldset/fieldset.spec.tsx, src/__internal__/fieldset/fieldset.style.ts, src/__internal__/label/label.component.tsx, src/components/box/box.component.tsx, src/components/button-toggle/button-toggle-group/button-toggle-group.component.tsx, src/components/button-toggle/button-toggle.style.ts, src/components/time/__internal__/time-toggle/index.ts, src/components/time/__internal__/time-toggle/time-toggle.component.tsx, src/components/time/__internal__/time-toggle/time-toggle.style.ts, src/components/time/components.test-pw.tsx, src/components/time/index.ts, src/components/time/time.component.tsx, src/components/time/time.pw.tsx, src/components/time/time.spec.tsx, src/components/time/time.stories.mdx, src/components/time/time.stories.tsx, src/components/time/time.style.ts, src/components/typography/typography.component.tsx, src/components/typography/typography.style.ts, src/locales/__internal__/pl-pl.ts, src/locales/en-gb.ts, src/locales/locale.ts
- Adds new `Time` component.
- Updates `Label` (internal) to accept `className` and `aria-label` props.
- Adds (private)`className` prop to `ButtonToggleGroup`. Temporarily extends it so disabled styling can be applied via opacity, ticket raised to address bug in actual component.
- Adds `legendMargin`, `width`, `isOptional`, `isDisabled`, `name` and `id` props to `Fieldset` (internal).
Default:
With toggle:
With hint text:
Validation:
- No `Time` component exists
- Fieldset does not support required/ optional/ disabled styling or application of `width`/ `name`/ `id`
Stories added for new component
=> feat(time): add new component

docs/extending-styles-using-styled-components.stories.mdx, docs/extending-styles-using-styled-system.stories.mdx, src/components/box/box.component.tsx, src/components/image/image.component.tsx, src/components/image/image.pw.tsx, src/components/image/image.spec.tsx, src/components/image/image.stories.mdx, src/components/image/image.stories.tsx, src/components/image/image.style.ts
- Add `position` prop to `Image` component.
- Add new document outlining how to extend the styling of Carbon's components. 
- No `position` prop on the `Image` component.
- No document outlining how to extend the styling of Carbon's components. 
N/A
- There should be no regression with the `Image` component.
- Passing `position` prop to `Image` component should apply the correct position to CSS of component.
- New document should render in Storybook and explain how to correctly extend the styling.
=>  feat(image): add position prop to component - FE-6226 

src/components/numeral-date/numeral-date.component.tsx
Ensures that we aren't using the current month to validate the day value when the month input is blank, it should use the static validation in that case.
Uses current month to dynamically validate the day value when there is no value in month input
=> fix(numeral-date): ensure it uses static validation when no month value passed

playwright/components/step-flow/index.ts, playwright/components/step-flow/locators.ts, src/components/step-flow/components.test-pw.tsx, src/components/step-flow/index.ts, src/components/step-flow/step-flow-test.stories.tsx, src/components/step-flow/step-flow.component.tsx, src/components/step-flow/step-flow.pw.tsx, src/components/step-flow/step-flow.spec.tsx, src/components/step-flow/step-flow.stories.mdx, src/components/step-flow/step-flow.stories.tsx, src/components/step-flow/step-flow.style.ts, src/components/typography/index.ts, src/components/typography/typography.component.tsx, src/locales/__internal__/pl-pl.ts, src/locales/en-gb.ts, src/locales/locale.ts
This PR will add the `StepFlow` component which aims to help users advance through a user journey, and keep track of their progress. This is done initially with a very simple default configuration, with just the current title, current step and the total steps in the journey. This can also be contextualised further with an optional `category` prop.
However, a progress indicator can also be rendered via the `showProgressIndicator` prop, providing an added decorative indicator of progress, with indicators holding three individual states: completed, in progress, not completed ; each with their own background colours.
A close icon can also be rendered, with its own `onDismiss` prop, allowing consumers to pass functions to be called onClick such as closing a modal.
The component is also …
=> feat(step-flow): add new component

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md, docs/installation.stories.mdx, docs/usage.stories.mdx
- Replace all references to Codesandbox with link to [stackblitz starter template](https://stackblitz.com/fork/github/Parsium/carbon-starter)
- The Formik demo has not been updated yet as part of this PR: <http://localhost:9001/?path=/docs/documentation-validations--string-validation#formik-overview>
- Currently the code for the starter template used by Stackblitz is hosted externally: [Link to external repo](https://github.com/Parsium/carbon-starter). This ideally should be included in the Carbon repo in the future (see FE-6361).
- Check the edited files for any grammatical errors
=> docs: replace codesandbox references with stackblitz

src/components/select/option-group-header/__snapshots__/option-group-header.spec.tsx.snap, src/components/select/option-group-header/option-group-header.component.tsx, src/components/select/option-group-header/option-group-header.spec.tsx, src/components/select/option-row/option-row.component.tsx, src/components/select/option/__snapshots__/option.spec.tsx.snap, src/components/select/option/option.component.tsx, src/components/select/option/option.spec.tsx, src/components/select/select-list/select-list.component.tsx, src/components/select/simple-select/components.test-pw.tsx, src/components/select/simple-select/simple-select.pw.tsx, src/components/select/simple-select/simple-select.stories.mdx, src/components/select/simple-select/simple-select.stories.tsx
Currently Select assigns a random guid as ID to each of its option children if no ids are provided explicitly, and regenerates this list of ids whenever the number of children changes. This results in unexpected behaviour when a new option is dynamically added to the start of the list on selection, as then the ids are regenerated and a critical axe error results from the aria-activedescendant property no longer referencing a valid child ID. To fix this, guids are now generated in Option itself (rather than SelectList as before) when the prop is not provided, and it is up to consumer to set keys on the list of option children to ensure individual child components maintain their identity correctly across renders even as children are added or removed.
fix #6378
Option ids, even when …
=> fix(select): maintain option ids according to key when children count changes

cypress/components/text-editor/text-editor.cy.tsx, src/components/portal/__snapshots__/portal.spec.tsx.snap, src/components/portal/portal.style.ts, src/components/portal/portal.tsx, src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.spec.tsx, src/components/text-editor/__internal__/toolbar/toolbar-button/toolbar-button.style.ts, src/components/text-editor/__internal__/toolbar/toolbar.component.tsx, src/components/text-editor/__internal__/toolbar/toolbar.spec.tsx, src/components/text-editor/__internal__/toolbar/toolbar.style.ts, src/components/text-editor/text-editor-test.stories.tsx, src/components/text-editor/text-editor.spec.tsx, src/components/text-editor/text-editor.stories.mdx, src/components/text-editor/text-editor.stories.tsx, src/components/text-editor/text-editor.style.ts, src/components/tooltip/__snapshots__/tooltip.spec.tsx.snap
addresses #6530 
addresses #6529
For `TextEditor`:
- Remove styling that fixes dimensions of custom toolbar elements added via `toolbarElements` prop:
- Make toolbar of `TextEditor` a flex container and remove fixed dimensions on it - so content reflows when there isn't enough space:
https://github.com/Sage/carbon/assets/18368713/c9efa8cd-ad6f-4357-853a-07581db8e47f
- Amend styling of toolbar buttons - notably the background colour when active and gap between them:
- Update documentation to include missing `characterCount` translation keys.
For `TextEditor`:
- Custom toolbar elements added via `toolbarElements` prop have their height and width fixed:
- Missing documentation on supported `characterCount` translation keys.
- Styling of toolbar buttons doesn't match the Design System - …
=> feat(text-editor): make container of toolbarElements a flex container for responsiveness (FE-6337 and FE-6340)

src/components/date/__internal__/date-picker/date-picker.component.tsx, src/components/date/components.test-pw.tsx, src/components/date/date.component.tsx, src/components/date/date.pw.tsx, src/components/date/date.spec.tsx
When datepicker is open the `esc` key should only close the datepicker and not the dialog, when it's contained in a dialog
fix #6505
Currently there's a bug that when `esc` is pressed it is closing the dialog as well as the datepicker
https://codesandbox.io/p/sandbox/esc-closes-dialog-when-datepicker-open-st56mm
=> fix(date): prevent dialog from closing if esc is pressed and date picker is open

cypress/components/button-toggle/button-toggle.cy.tsx, src/__internal__/checkable-input/checkable-input.component.tsx, src/components/button-toggle/button-toggle-group/button-toggle-group.component.tsx, src/components/button-toggle/button-toggle-group/button-toggle-group.spec.tsx, src/components/checkbox/checkbox.component.tsx, src/components/checkbox/checkbox.stories.tsx, src/components/fieldset/components.test-pw.tsx, src/components/fieldset/fieldset.stories.tsx, src/components/form/form-test.stories.tsx, src/components/radio-button/radio-button.component.tsx, src/components/switch/switch-test.stories.tsx, src/components/switch/switch.component.tsx, src/components/switch/switch.pw.tsx
BREAKING CHANGE: The `labelAlign` prop has been removed from `Checkbox`, `RadioButton` and `Switch`
Remove `labelAlign` prop from checkable input components: `Checkbox`, `RadioButton` and `Switch`.  
The `labelAlign` has no effect on checkable inputs: `Checkbox`, `RadioButton` and `Switch`. 
=> fix: remove unused labelAlign prop from checkable input

src/__internal__/input/__snapshots__/input-presentation.spec.tsx.snap, src/__internal__/input/__snapshots__/input.spec.tsx.snap, src/__internal__/input/input-presentation.component.tsx, src/__internal__/input/input-presentation.style.ts, src/__internal__/input/input.component.tsx, src/__internal__/input/input.style.ts, src/components/box/box.component.tsx, src/components/textarea/textarea-test.stories.tsx, src/components/textarea/textarea.component.tsx, src/components/textarea/textarea.pw.tsx, src/components/textarea/textarea.spec.tsx, src/components/textarea/textarea.stories.mdx, src/components/textarea/textarea.stories.tsx
Allow a custom border radius to be specified on Textarea component
No option to apply a custom border radius to Textarea component
N/A
- New story has been created called `with borderRadius`. This story should render has expected.
- `Controls` for `borderRadius` have been added to the `test` example of Textarea.
- There should be no visual regressions with Textarea.
=> feat(textarea): add new borderRadius prop - FE-6363

src/components/portal/portal.stories.mdx, src/components/portrait/portrait.stories.mdx, src/components/preview/preview.stories.mdx, src/components/progress-tracker/progress-tracker.stories.mdx, src/components/search/search.stories.mdx
Create new document that informs our consumers of Portal's existence 
No documentation for Portal.
N/A
- Ensure document renders in Storybook correctly.
=> docs(portal): add new documentation for component - FE-6322

src/components/loader/loader-square.spec.tsx, src/components/loader/loader-square.style.ts, src/components/loader/loader-test.stories.tsx, src/components/loader/loader.component.tsx, src/components/loader/loader.stories.mdx, src/components/loader/loader.stories.tsx
adds a `color` prop, with the option for a `gradient` type . This new variant will give each loader a different color (green, blue, purple) to achieve a gradient appearance.
Currently, there is no way to achieve a gradient appearance on the `Loader` component, as each loader has the same set colour.
=> feat(loader): add gradient color to component

src/components/button-toggle/__snapshots__/button-toggle.spec.tsx.snap, src/components/button-toggle/button-toggle-icon.component.tsx, src/components/button-toggle/button-toggle.style.ts, src/components/button/__snapshots__/button.spec.tsx.snap, src/components/button/button.component.tsx, src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap, src/components/flat-table/flat-table-cell/flat-table-cell.component.tsx, src/components/flat-table/flat-table-cell/flat-table-cell.style.ts, src/components/flat-table/flat-table-row-header/flat-table-row-header.component.tsx, src/components/flat-table/flat-table-row-header/flat-table-row-header.style.ts, src/components/icon/icon-test.stories.tsx, src/components/icon/icon.component.tsx, src/components/icon/icon.pw.tsx, src/components/icon/icon.spec.tsx, src/components/icon/icon.stories.mdx, src/components/icon/icon.stories.tsx, src/components/icon/icon.style.ts, src/components/link/link.component.tsx, src/components/link/link.spec.tsx, src/components/link/link.style.ts, src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/menu-item/menu-item.style.ts, src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap, src/components/split-button/split-button.component.tsx, src/components/split-button/split-button.spec.tsx
fix #5812
fix #6353 
- If the `bgSize` value is smaller than the `fontSize` value, the background size will be adjusted to be equal to the icon size. Otherwise, the `fontSize` value has no effect on the background size. 
- "extra-small" option for `bgSize` prop has been deprecated, components internally using this size have been updated. 
When using `bgSize` and `fontSize` props together on an `Icon`, if `fontSize` is not small its value will always override the `bgSize` value.
=> fix(icon): bgSize and fontSize bug fix

src/components/form/form.spec.tsx, src/components/form/form.style.ts
Removes the 4px margin bottom from FormField rendered as part of Textarea when in Form
There is 4px margin bottom added to FormField rendered as part of Textarea when in Form
=> fix(form): remove 4px margin bottom from Textarea FormField

src/components/tabs/__internal__/tabs-header/tabs-header.spec.tsx, src/components/tabs/__internal__/tabs-header/tabs-header.style.ts
Remove negative margin to resolve issue where horizontal is appearing unnecessarily
fix #6511
A horizontal scrollbar appears unnecessarily on the Tabs component
https://stackblitz.com/edit/horizontal-scrollbar-appears-tabs?file=src%2FApp.tsx
=> fix(tabs): remove negative margin to resolve scrollbar appearing

.github/workflows/playwright-audit.yml, .github/workflows/playwright.yml, playwright-ct.config.ts
- Add new `playwright-audit.yml` workflow - allowing contributors with write permissions to run specific test(s) N times in a CI environment.
- Update Playwright container image in `playwright.yml` to match Playwright version in package lock file.
- Unable to run specific Playwright tests in CI, which would be useful when auditing tests for flakiness, particularly since test results can vary depending on the runtime environment.   
To experiment with the workflow, please contact me externally to access a privately-owned test repo.
=> chore(playwright): create CI workflow for running specific tests multiple times

src/__internal__/focus-trap/focus-trap.spec.tsx, src/__internal__/sticky-footer/sticky-footer.spec.tsx, src/__spec_helper__/index.ts, src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.component.tsx, src/components/flat-table/flat-table-body-draggable/flat-table-body-draggable.spec.tsx, src/components/flat-table/flat-table.spec.tsx, src/components/global-header/global-header.spec.tsx, src/components/navigation-bar/fixed-navigation-bar-context.spec.tsx, src/components/tile/flex-tile-cell/flex-tile-cell.spec.tsx, src/components/tile/flex-tile-container/flex-tile-container.spec.tsx, src/components/tile/tile-content/tile-content.spec.tsx, src/components/tooltip/__snapshots__/tooltip.spec.tsx.snap, src/components/tooltip/tooltip.spec.tsx, src/hooks/__internal__/useClickAwayListener/useClickAwayListener.spec.tsx, src/hooks/__internal__/useFloating/useFloating.spec.tsx, src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.spec.tsx, src/hooks/__internal__/useModalAria/useModalAria.spec.tsx
- Configure RTL to [override the attribute looked up by the *ByTestId queries](https://testing-library.com/docs/queries/bytestid#overriding-data-testid), given Carbon already uses `data-role` extensively as a test identifier.
- RTL's *ByTestId queries search for elements with a matching `data-testid` attribute.
=> test: configure RTL *ByTestId queries to use data-role tags (FE-5549)

playwright/support/helper.ts, src/components/dialog-full-screen/components.test-pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog/components.test-pw.tsx, src/components/dialog/dialog.pw.tsx
Add an automation test to cover `focusableSelectors` prop.
Currently no automation test for `focusableSelectors` prop.
Test has had to be commented out for now as there is a known issue with Playwright and our Modal-based components testing internal focus behaviours. 
N/A
=> test(dialog, dialog-full-screen): add test for focusableSelectors - FE-5533

playwright/components/action-popover/index.ts, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.pw.tsx, src/components/action-popover/action-popover.spec.tsx, src/components/action-popover/action-popover.style.ts, src/components/button/button.component.tsx, src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/multi-action-button/multi-action-button.component.tsx, src/components/multi-action-button/multi-action-button.pw.tsx, src/components/multi-action-button/multi-action-button.style.ts, src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap, src/components/split-button/split-button-children.style.ts, src/components/split-button/split-button.component.tsx, src/hooks/__internal__/useChildButtons/useChildButtons.tsx
- ActionPopover, SplitButton and MultiActionButton should not use the `menu` and `menuitem` roles, but simply present buttons in a semantic HTML list
- the consumer should be able to override the `aria-label` attribute for the main button on ActionPopover should
- no `aria-label` should be placed on menu items that open a submenu, so that screenreaders read the text of the item rather than a vague word like "actions"
- ActionPopover, SplitButton and MultiActionButton use ARIA menu roles, which are not semantically appropriate for a simple list of actions/buttons
- It is not possible to override the `aria-label` of "actions" on the main button for ActionPopover, which may lead to a poor experience for users (potentially many duplicate labels on a page, none of them meaningful for what the …
=> feat: accessibility improvements to ActionPopover, SplitButton and MultiActionButton

CHANGELOG.md, tsconfig-build.json
- Exclude any TypeScript files in `docs/` directory when building types for production code.
- Include notes in changelog about unpublished versions.
- Manually trigger build process via `npm run precompile`
- Check if build artifacts are successfully generated with TypeScript declaration files
- Sanity check that fix will trigger a new patch version
=> chore: exclude docs/ directory in TS build config

src/components/dialog-full-screen/dialog-full-screen-test.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.component.tsx, src/components/dialog-full-screen/dialog-full-screen.spec.tsx, src/components/dialog/dialog-test.stories.tsx, src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.spec.tsx
enable consumers to pass a node as the subtitle prop
fix #5844
Allow the consumers to pass a node as the subtitle prop
Currently the type of the subtitle prop can only be  `string`
=> feat(dialog): allow subtitle prop to accept a node

src/components/step-flow/step-flow.mdx, src/components/textarea/textarea.mdx
Ensures proper page structure is used above the translation keys table to properly inform users about the keys, locales, `i18nProvider` etc.
Currently, there is a lack of heading above the translation keys table on the storybok page for `StepFlow` and `Textarea`, meaning some consumers may struggle to locate the keys, or understand what they are for.
=> docs(step-flow, textarea): ensure proper page structure when translation keys table is used

src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap, src/components/link/link.spec.tsx, src/components/link/link.style.ts, src/components/menu/__internal__/submenu/submenu.spec.tsx, src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/component.test-pw.tsx, src/components/menu/menu-full-screen/menu-full-screen.component.tsx, src/components/menu/menu-full-screen/menu-full-screen.spec.tsx, src/components/menu/menu-full-screen/menu-full-screen.style.ts, src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu.pw.tsx, src/components/menu/menu.style.ts, src/components/profile/profile.spec.tsx, src/components/search/index.ts, src/components/search/search-button.style.ts, src/components/search/search.component.tsx, src/components/search/search.mdx, src/components/search/search.pw.tsx, src/components/search/search.spec.tsx, src/components/search/search.stories.tsx, src/components/search/search.style.ts, src/locales/__internal__/es-es.ts, src/locales/en-gb.ts, src/locales/locale.ts
fix #6581
fix #6597
BREAKING CHANGE: The `threshold` prop has been removed as it no longer does anything in the
redesigned component
BREAKING CHANGE: The `inputRef` is no more
Implements new designs for `Search` component. The button is now rendered at all times when the
`searchButton` is set; expands the type of this prop to also accept string values which will support
more granular control over the text rendered in the button. Support for overriding the button text
via the locale provider has also been added. Updates have also been made to `Link` and `Menu` style
files to ensure the styling is correct when `Search` is rendered in a `Menu`. Styling targeting the
search input in menus has also been removed. These changes have also addressed the issue with
padding of `MenuItem` components …
=> feat(search): search button is rendered at all times when `searchButton` prop is set FE-6078

src/components/drawer/drawer.stories.tsx, src/components/flat-table/components.test-pw.tsx, src/components/flat-table/flat-table.mdx, src/components/flat-table/flat-table.stories.tsx, src/components/flat-table/sort/sort.component.tsx, src/components/flat-table/sort/sort.spec.tsx, src/components/flat-table/sort/sort.stories.tsx, src/locales/__internal__/es-es.ts, src/locales/en-gb.ts, src/locales/locale.ts
adds the `accessibleName` prop as well as translation support for a new visually hidden span which provides the component with an accessible name
The current accessible name uses string interpolation with the sort type and children props, which may result in English-only announcements for users of another language. The accessible name is also contained in a span with the `hidden` attribute applied to it, making it in theory inaccessible to screen readers
=> fix(sort): add a prop and translation support to provide an accessible name

playwright/components/tileSelect/index.ts, playwright/components/tileSelect/locators.ts, src/components/fieldset/__snapshots__/fieldset.spec.tsx.snap, src/components/fieldset/fieldset.component.tsx, src/components/fieldset/fieldset.pw.tsx, src/components/fieldset/fieldset.spec.tsx, src/components/fieldset/fieldset.style.ts, src/components/tile-select/tile-select-group/tile-select-group.component.tsx, src/components/tile-select/tile-select.component.tsx, src/components/tile-select/tile-select.pw.tsx, src/components/tile-select/tile-select.style.ts
BREAKING CHANGE: The `inline` prop has been removed from the `Fieldset` component.
- Legend element is no longer nested in two div containers and is now a direct child of the fieldset element.
- `inline` prop has been removed. 
- Legend element in the `Fieldset` component is nested in two divs, which is invalid HTML.
=> fix(fieldset): invalid fieldset HTML fix

.storybook/manager.ts
- fix the issue with the version selector not appearing by reordering the addon registration assignment
- the version selector is no longer showing on production
NA
=> chore(storybook): reorder the addon registration to resolve showing the version picker

src/components/menu/__internal__/submenu/submenu.component.tsx, src/components/menu/__internal__/submenu/submenu.spec.tsx, src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/component.test-pw.tsx, src/components/menu/menu-test.stories.tsx, src/components/menu/menu.pw.tsx
The last child in the segment title should not have rounded corners.
fixes #6488
border-radius is applied to all last children of the segment title. 
I have opted to do the styling test in Playwright alone instead of doubling up with unit and automation. The reason for this is we already have a humongous amount of unit tests for `Menu` and it's associated components. Doing the tests in Playwright is also much simpler and easier to maintain. With a component as complex as `Menu`, I felt this way benefited future development work but I am happy to add unit tests if we feel strongly that they should be included. 
- No visual regressions in the other menu examples
- New test story `MenuWithTwoSegments` should have the correct styling applied to the last menu items in the submenus.
=> fix(submenu): ensure last child in segment title has correct styling - FE-6308

.eslintignore, .eslintrc, contributing/testing-guide.md, playwright-ct.config.ts, playwright/README.md, src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap, src/components/dialog-full-screen/components.test-pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/file-input/file-input.pw.tsx, src/components/icon/icon.component.tsx, src/components/menu/component.test-pw.tsx, src/components/menu/menu.pw.tsx, src/components/message/type-icon/__snapshots__/type-icon.spec.tsx.snap, src/components/multi-action-button/__snapshots__/multi-action-button.spec.tsx.snap, src/components/portal/__snapshots__/portal.spec.tsx.snap, src/components/select/list-action-button/__snapshots__/list-action-button.spec.tsx.snap, src/components/select/option-group-header/__snapshots__/option-group-header.spec.tsx.snap, src/components/sidebar/components.test-pw.tsx, src/components/sidebar/sidebar.pw.tsx, src/components/vertical-menu/components.test-pw.tsx, src/components/vertical-menu/vertical-menu.pw.tsx
- Configure Playwright's `getByTestId` locator to find `data-role` tags, given Carbon uses data-role extensively as a test identifier and to match RTL.
- Update testing guide's sections on Playwright and Jest
=> chore(playwright): configure `getByTestId` locator to find `data-role` tags

src/components/loader/loader-test.stories.tsx, src/components/loader/loader.mdx, src/components/loader/loader.stories.tsx
Document an accessible example of how to use `Loader` inside of `Button`. 
Currently no accessible example documentation demonstrating how to correctly use `Loader` inside of `Button`
N/A
Test updated `Inside Button` story using:
- VoiceOver with Safari (MacOS)
- NVDA with Chrome (Windows)
=> docs(loader): document accessible example when used inside of button - FE-5224

src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/filterable-select/filterable-select.component.tsx, src/components/select/filterable-select/filterable-select.spec.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/multi-select/multi-select.component.tsx, src/components/select/multi-select/multi-select.spec.tsx
Filterable-Select: No runtime error should be thrown when the component has just one option.
https://github.com/Sage/carbon/assets/56251247/a3b930d5-21ef-4252-921b-10f837f20273
Multi-Select: No console error should be thrown when the component has just one option.
https://github.com/Sage/carbon/assets/56251247/e9ffb572-c002-452e-a8bd-c89afa3769d0
Filterable-Select: If the component has a single option, a runtime error is thrown when the select textbox is typed in.
https://github.com/Sage/carbon/assets/56251247/c7ae402a-aa5a-4856-a67e-0eebcb406ea0
Multi-Select: If the component has a single option, a console error is thrown when the select textbox is typed in.
N/A 
Filterable-Select: 
- Visit new `Single Option` story in the `Test` folder for Filterable-Select. 
- Type in the Select …
=> fix(filterable-select): ensure no runtime error is triggered when component has a single option - FE-6413

src/components/checkbox/checkbox-test.stories.tsx, src/components/checkbox/checkbox.style.ts, src/components/checkbox/validations.stories.tsx
fix #6683 
Set the `min-width` of the input parent container to 24px for large checkboxes, which prevents the text and checkbox focus border from overlapping. 
The `min-width` of the input parent container is still set to 16px for large checkboxes. This causes the space between longer descriptions and the checkbox to be reduced and the focus border to partially cover the text.
=> fix(checkbox): fix reduced spacing between label and large checkbox

src/components/button-toggle/__snapshots__/button-toggle.spec.tsx.snap, src/components/button-toggle/button-toggle-group/button-toggle-group-test.stories.tsx, src/components/button-toggle/button-toggle-group/button-toggle-group.spec.tsx, src/components/button-toggle/button-toggle.component.tsx
First `ButtonToggle` component in a group is focusable via a mouse click when using Safari. 
First `ButtonToggle` component in a group is not focusable via a mouse click when using Safari. 
No Playwright test has been added to cover this bug because it is a Safari specific bug, so Playwright would not be able to catch this anyway.
- Open the example called  `Default` in `Button Toggle Group -> Test` using Safari. 
- Click the first `ButtonToggle` component. 
- `ButtonToggle` component should be focused.
Might be worth doing a regression check on other browsers too. Just to make sure this fix hasn't unearthed any demons in the other examples in the other browsers.
=> fix(button-toggle): ensure the first button toggle in a group is focusable via mouse click on Safari - FE-6389

src/components/select/filterable-select/components.test-pw.tsx, src/components/select/filterable-select/filterable-select.pw.tsx, src/components/select/select-list/select-list.component.tsx, src/components/select/simple-select/components.test-pw.tsx, src/components/select/simple-select/simple-select.pw.tsx
fix #6669
A selected option no longer remains highlighted after the value is cleared.
A selected option remains highlighted when the value has been cleared. 
**Issue:**
- Go to [controlled](https://carbon.sage.com/?path=/story/select--controlled) story for simple select or [controlled](https://carbon.sage.com/?path=/story/select-filterable--controlled) story for filterable select. 
- Select an option. 
- Open dropdown - see option is highlighted. 
- Click button to clear value.
- Open dropdown - see option is still highlighted. 
**Fix**:
- Go to controlled stories on branch and follow the same steps. 
- See option is no longer highlighted when value is cleared.
=> fix(select): option remaining highlighted after clearing value

playwright/components/flat-table/index.ts, playwright/components/flat-table/locators.ts, src/components/flat-table/flat-table.pw.tsx, src/components/pager/pager.pw.tsx, src/components/select/select.style.ts
fix #6490
The input element no longer extends outside of the `Select` component and inherits the width of the parent container. 
The input element in the dropdown in `Pager` no longer blocks the "First" link. 
The input element within the select textbox extends outside the textbox width in smaller screens. This causes the input element in the dropdown in `Pager` to block the "First" link and open the dropdown instead of following the link.
=> fix(select): input element extends outside textbox in smaller screens

src/components/loader-spinner/loader-spinner-test.stories.tsx, src/components/loader-spinner/loader-spinner.component.tsx, src/components/loader-spinner/loader-spinner.mdx, src/components/loader-spinner/loader-spinner.pw.tsx, src/components/loader-spinner/loader-spinner.spec.tsx, src/components/loader-spinner/loader-spinner.stories.tsx
fix #6694
Consumers can now use the `spinnerLabel` prop to override the default label of `"Loading..."` and provide their own custom string instead
Currently, consumers can only override the default label of `Loading...` by using an `<I18nProvider/ >`
=> feat(loader-spinner): add spinnerLabel prop to override the default loading label with custom text

src/components/advanced-color-picker/advanced-color-picker.mdx, src/components/breadcrumbs/breadcrumbs.mdx, src/components/confirm/confirm.mdx, src/components/decimal/decimal.mdx, src/components/dialog-full-screen/dialog-full-screen.mdx, src/components/dialog/dialog.mdx, src/components/dismissible-box/dismissible-box.mdx, src/components/file-input/file-input.mdx, src/components/flat-table/flat-table.mdx, src/components/heading/heading.mdx, src/components/link/link.mdx, src/components/loader-bar/loader-bar.mdx, src/components/loader-spinner/loader-spinner.mdx, src/components/loader/loader.mdx, src/components/menu/menu.mdx, src/components/numeral-date/numeral-date.mdx, src/components/password/password.mdx, src/components/pod/pod.mdx, src/components/progress-tracker/progress-tracker.mdx, src/components/search/search.mdx, src/components/sidebar/sidebar.mdx, src/components/split-button/split-button.mdx, src/components/step-flow/step-flow.mdx, src/components/textarea/textarea.mdx, src/components/textbox/textbox.mdx, src/components/time/time.mdx, src/components/toast/toast.mdx, src/components/vertical-menu/vertical-menu.mdx
Adds missing translation keys table/translation keys to `Confirm`, `dismissibleBox`, `Heading`, `numeralDate`, `splitButton`
Currently, not all translations are listed in their respective components' docs.
=> Add translation keys to missing stories

src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.style.ts
fix #5784
The `fullWidth` prop how has effect when used in a `Button` rendered as `renderOpenComponent`
Component does not respect `fullWidth` prop in a `Button` set to `renderOpenComponent`. 
[Sandbox of original bug](https://stackblitz.com/edit/parsium-carbon-starter-mhynbq?file=src%2FApp.tsx)
See "WithFullWidthButton" test story for fix.
=> fix(popover-container): allow fullWidth button to be rendered as renderOpenComponent

src/components/text-editor/text-editor.mdx, src/components/text-editor/text-editor.pw.tsx
Adds a guard to only fire onChange when the content is updated
The onChange handle fires whenever the editor div is focused
=> fix(text-editor): ensure that clicking editor does not trigger onChange to be called

src/components/button/button.component.tsx, src/components/card/card-footer/__snapshots__/card-footer.spec.tsx.snap, src/components/link/link.style.ts, src/components/popover-container/popover-container-test.stories.tsx, src/components/search/search.component.tsx
fix #6725
Update `Link` (which are rendered as part of MenuItem) styling is  applied to any open button rendered when `PopoverContainer` is a child of a `MenuItem`
PopoverContainer open button has border added and rounded corners
I've added a `popover-container-test--inside-menu-with-open-button` test story for chromatic to capture any regressions
=> fix(link): ensure styling overrides apply to open button when popover-container renders in menu

src/components/toast/toast-test.stories.tsx, src/components/toast/toast.style.ts, src/components/toast/toast.test.tsx
fix #6730
Remove margin-top from "notice" `Toast`. 
The margin-top on a "notice" `Toast` prevents elements behind it from being clicked.
=> fix(toast): margin-top on notice variant prevents elements being clicked

src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/component.test-pw.tsx, src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu-test.stories.tsx, src/components/menu/menu.pw.tsx, src/components/menu/menu.style.ts
The behaviour has been observed in the following scenarios, as it can be seen in the attached screenshot:
1. when the `MenuItem` renders as a button
2. when the `MenuItem` renders inside the `Submenu` as a button
3. when the `MenuItem` renders inside the `Submenu` as a link
For the first scenario changes have been applied to the `StyledMenuItem` and `StyledMenuItemWrapper` components. For the second and third scenarios the `StyledSubmenuWrapper` has been updated to ensure `StyledMenuItemWrapper` wraps the text and has flexible height, when we are in full screen view.
The `MenuItem` does not wrap the text when it renders as a button or inside of a `Submenu` when it renders as a link or a button.
=> fix: component MenuFullScreen and MenuItem not truncating topic

src/components/split-button/split-button.test.tsx
Removes unnecessary  `describe` and replaces `waitFor` with `act`
Uses waitFor instead of act
=> refactor(split-button): replace uses of waitFor with act

src/components/button-minor/button-minor.component.tsx, src/components/button-minor/button-minor.spec.tsx
Add forward ref to MinorButton
No support for ref on MinorButton
=> feat(button-minor): add forward ref to component

src/components/menu/menu-full-screen/menu-full-screen.style.ts, src/components/menu/menu.config.ts, src/components/menu/menu.pw.tsx, src/components/menu/scrollable-block/scrollable-block.style.ts
To ensure we pass accessibility on scrollbars, we must ensure they cover a 24px space, this implies width of scroll + gap to next interactive component. The black variant of the Menu component uses a Navy tint scrollbar customisation, which we would like to correct the colours of.
fixes FE-5290
- Update colours for scrollbars
- Apply padding between MenuItem and Scrollbar
Chrome: 
Safari: 
- Colours currently don't meet accessibility guidelines
- No padding between MenuItem and Scrollbar
On Mac using Chrome, the scroll bar will have rounded corners. These don't exactly match the designs provided on the ticket but the colours should match.
- Ensure that the examples provided in the `scrollable-submenu` story have the expected styling applied to the scrollbar and the MenuItem's in the …
=> fix(menu): ensure scrollbars meet colour contrast guidelines - FE-5290

src/components/action-popover/action-popover.stories.tsx, src/components/action-popover/action-popover.style.ts
- Right arrow in `ActionPopoverItem` with submenu is aligned with text in safari. 
- Confirm dialog does opens when "Open Confirm Dialog' menu item is clicked in "Opening a Modal" story. 
- Right arrow in `ActionPopoverItem` with submenu not aligned with text in safari. 
- Confirm dialog does not open when "Open Confirm Dialog' menu item is clicked in "Opening a Modal" story. 
- See "Sub Menu Positioned Right" story in Safari.
- See "Opening a Modal" story.
=> fix(action-popover): right arrow in menu item with submenu not aligned with text in safari

src/components/progress-tracker/progress-tracker-test.stories.tsx, src/components/progress-tracker/progress-tracker.spec.tsx, src/components/progress-tracker/progress-tracker.style.ts
Currently the progress tracker's border is being cut off when contained inside a FlexTile component. This applies a `box-sizing` of `border-box` to the inner styled bar. The height has also had to be re-calculated due to a 2px reduction in height because of the `box-sizing` styling. To solve this we have used a `min-height` of `fit-content`
fixes #6779
N/A
- Check for any regressions on `Progress Tracker`
- Added a new story in the test folder called `inside flex tile` which demonstrates this fixed inside of a flex tile.
=> fix(progress-tracker): apply box sizing of border box to the inner styled bar - FE-6672

package-lock.json, package.json
- Remove duplicates of `@testing-library/dom` package, to ensure `@testing-library/react` and `@testing-library/user-event` use the same copy. [Not doing so can lead to bugs](https://testing-library.com/docs/user-event/install).
```shell
$ npm ls @testing-library/dom
├── @testing-library/dom@9.3.4 overridden
├─┬ @testing-library/react@12.1.5
│ └── @testing-library/dom@9.3.4 deduped
├─┬ @testing-library/user-event@14.5.2
│ └── @testing-library/dom@9.3.4 deduped
└─┬ eslint-plugin-jest-dom@5.2.0
└── @testing-library/dom@9.3.4 deduped
```
- Carbon's installed packages contain two copies of `@testing-library/dom`. This means `@testing-library/dom` is not resolved to the same installation, causing bugs such as excessive act warnings:
- …
=> chore: prevent duplication of @testing-library/dom package

src/components/button-toggle/button-toggle-group/button-toggle-group.test.tsx, src/components/date-range/date-range.test.tsx, src/components/date/date.test.tsx, src/components/dialog/dialog.test.tsx, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu.test.tsx, src/components/split-button/split-button.test.tsx
In our RTL tests, remove unnecessary `act` calls previously needed before [this fix](https://github.com/Sage/carbon/pull/6814) was released.
=> chore: remove unnecessary act calls in RTL tests

src/components/breadcrumbs/breadcrumbs-test.stories.tsx, src/components/breadcrumbs/breadcrumbs.pw.tsx, src/components/breadcrumbs/components.test-pw.tsx, src/components/link/link.component.tsx
fix #6808
fix #6688
Ensures that styling updates when focus is lost but no blur is not triggered. This means that when a `Crumb` is clicked and becomes current the focus styling is not persisted.
Part of the Link focus styling is persisted when the link loses focus but no blur event isn't triggered. See linked issue for current behaviour
Test story added for `Breadcrumb` component
=> fix(link): ensure focus styles are removed when underlying element loses focus

src/components/date-range/date-range.test.tsx, src/components/date/date.test.tsx, src/components/textarea/textarea.test.tsx, src/components/textbox/textbox.test.tsx, src/components/tooltip/tooltip.test.tsx
- Use RTL's asynchronous queries for asserting the appearance or disappearance of a tooltip
- Some test cases exist where the appearance/disappearance of a tooltip is not waited for, which causes the test to sometimes fail
=> chore(jest): address test flakiness related to tooltips

src/components/advanced-color-picker/advanced-color-picker-test.stories.tsx, src/components/advanced-color-picker/advanced-color-picker.pw.tsx, src/components/advanced-color-picker/advanced-color-picker.test.tsx, src/components/simple-color-picker/simple-color-picker.component.tsx, src/components/simple-color-picker/simple-color-picker.pw.tsx, src/components/simple-color-picker/simple-color-picker.spec.tsx
Blur should be blocked when switching between colors and fired when the component itself is blurred.
fixes #6850
Blur event should not be fired when switching between colours.
Add deprecation warning to `isBlurBlocked` prop.
Blur event is triggered every time a colour is changed.
N/A
New test story called `OnBlurExample` has been added to `AdvancedColorPickers` test stories. This example allows you to test when the `onBlur` event is fired as it will be logged in the console. 
Blur should only be fired if the component itself is blurred or the component is closed using the `X` button.
=> fix(simple-color-picker, advanced-color-picker): ensure blur blocking works when switching colors - FE-6707

src/__internal__/validations/validation-icon.component.tsx, src/components/date-range/date-range.test.tsx, src/components/date/date.test.tsx, src/components/numeral-date/numeral-date.test.tsx
Mocks tooltip visible tests in Date, DateRange and NumeralDate 
Tooltip visible tests not mocked
=> refactor(date, date-range, numeral-date): mock Tooltip due to latency issues in floating-ui

src/components/link/link.pw.tsx, src/components/link/link.style.ts, src/components/link/link.test.tsx
I have removed the styling tests in RTL for the skip link variant. The tests used `toHaveStyle` assertion with token values and we have come to learn these tests don't really work as they always pass. These styles are better tested in Playwright, which we already had. 
- SkipLink should match the designs provided on the ticket.
- There should not be any other styling regressions with Link.
=> feat(link): update styling of skip link variant - FE-6719

src/components/global-header/global-header.stories.tsx, src/components/link/link.style.ts, src/components/menu/__internal__/submenu/submenu.component.tsx, src/components/menu/__internal__/submenu/submenu.context.tsx, src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/component.test-pw.tsx, src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu-segment-title/menu-segment-title.component.tsx, src/components/menu/menu-segment-title/menu-segment-title.style.ts, src/components/menu/menu-segment-title/menu-segment-title.test.tsx, src/components/menu/menu-test.stories.tsx, src/components/menu/menu.mdx, src/components/menu/menu.pw.tsx, src/components/menu/menu.stories.tsx, src/components/menu/menu.style.ts, src/components/navigation-bar/navigation-bar.style.ts
Adds `submenuMaxWidth` prop to allow setting of `max-width` on the `submenu` child of a `MenuItem`. When the prop is set any submenu items will wrap so they do not overflow the bounds of the container.
Replaces display inline-block with flex and removes height and line-height as it makes the spacing incorrect when the items wrap
Updates how padding is applied so it is set on the button/anchor elements rather than the wrapper
fix #6889
There is no support for setting max width on the submenu elements, child menu-items do not wrap.
Height and line-height are 40px and display is inline-block
Padding is applied to the wrapper element rather than the button/anchor element so that even when it is set to zero the underlying element's padding means there's no visual update …
=> feat(menu-item): add `submenuMaxWidth` prop to allow setting of `max-width` on submenus

src/__internal__/checkable-input/checkable-input.component.tsx, src/components/checkbox/checkbox-group/checkbox-group.component.tsx, src/components/checkbox/checkbox-group/checkbox-group.test.tsx, src/components/checkbox/checkbox-test.stories.tsx, src/components/checkbox/checkbox.component.tsx, src/components/checkbox/checkbox.mdx, src/components/checkbox/checkbox.stories.tsx, src/components/checkbox/checkbox.style.ts, src/components/checkbox/validations.stories.tsx, src/components/numeral-date/numeral-date.mdx, src/components/radio-button/radio-button-group/radio-button-group.component.tsx, src/components/radio-button/radio-button-group/radio-button-group.test.tsx, src/components/radio-button/radio-button-test.stories.tsx, src/components/radio-button/radio-button.component.tsx, src/components/radio-button/radio-button.mdx, src/components/radio-button/radio-button.stories.tsx, src/components/switch/switch.mdx
RadioButton with validationRedesignOptIn:
- Does not render labelHelp tooltip. 
- Does not render fieldHelp.
- Does not render with validation (error/warning) tooltip. 
- Required stars do not appear in a required group's children. 
Checkbox within a group with validationRedesignOptIn:
- Does not render labelHelp tooltip. 
- Does not render fieldHelp.
RadioButton with validationRedesignOptIn:
- Renders labelHelp tooltip. 
- Renders fieldHelp.
- Renders with validation (error/warning) tooltip. 
- Required stars also appear in a required group's children. 
Checkbox within a group with validationRedesignOptIn:
- Renders labelHelp tooltip. 
- Renders fieldHelp.
- Note that individual Checkboxes that aren't in a group can still render labelHelp & fieldHelp with new validation. 
- See this …
=> fix(radio-button, checkbox): prevent labelHelp and fieldHelp from rendering with new validation

playwright/components/loader-star/index.ts, playwright/components/loader-star/locators.ts, src/components/loader-star/components.test-pw.tsx, src/components/loader-star/index.ts, src/components/loader-star/internal/star.component.tsx, src/components/loader-star/internal/star.style.ts, src/components/loader-star/loader-star-test.stories.tsx, src/components/loader-star/loader-star.component.tsx, src/components/loader-star/loader-star.mdx, src/components/loader-star/loader-star.pw.tsx, src/components/loader-star/loader-star.stories.tsx, src/components/loader-star/loader-star.style.ts, src/components/loader-star/loader-star.test.tsx, src/locales/de-de.ts, src/locales/en-gb.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts, src/locales/locale.ts
Create a new component called `Loader Star`. 
**Component by default**
**Component if user prefers `Reduce motion`**
No component called `Loader Star` exists in Carbon.
N/A
- Component should match designs and animation behaviour specified on the ticket.
- Component should display the expected message if the user prefers `Reduce motion`. 
- Ensure that Playwright tests are sufficient for testing the browser behaviour of this component.
=> feat(loader-star): create new loader-star component - FE-6752

src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/menu.pw.tsx, src/components/menu/menu.stories.tsx
Remove min-width when `submenuMaxWidth` is set
`min-width` is set to same value as `submenuMaxWidth` when set
=> fix(menu-item, submenu): remove min-width when submenuMaxWidth prop is set

src/components/menu/__internal__/menu.context.tsx, src/components/vertical-divider/vertical-divider.component.tsx, src/components/vertical-divider/vertical-divider.test.tsx
Adds `aria-hidden` prop to VerticalDivider interface.
Ensure that it cannot be overridden when the divider is in Menu.
aria-hidden is not part of VerticalDivider
=> feat(vertical-divider): add aria-hidden prop but prevent overriding when in menu

src/components/dialog/dialog-test.stories.tsx, src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.config.ts, src/components/dialog/dialog.mdx, src/components/dialog/dialog.stories.tsx, src/components/dialog/dialog.style.ts, src/components/dialog/dialog.test.tsx
Currently, there is no potential `"maximise"` value in the `size` prop.
When `"maximise"` is passed to the `size` prop the dialog now takes up the majority of the viewport. However, a conditional breakpoint has been introduced which dictates how much of the viewport the dialog should take up based on the resolution being above or below `960px`.
**Less than 960px**
**More than 960px**
=> feat(dialog): add the "maximise" value to the `size` prop

.npmignore, .vscode/launch.json, package-lock.json
=> chore: upgrade a transitive dependency

package-lock.json
- Upgrade transitive dependencies
=> chore: upgrade transitive dependencies

.github/workflows/playwright-audit.yml, .github/workflows/playwright.yml, package-lock.json, package.json
- Upgrade the following packages:
- `@playwright/test` to version 1.47
- `@playwright/experimental-ct-react17` to version 1.47
- `@axe-core/playwright` to version 4.10
- Amend GitHub Actions workflows to upgrade Playwright image used 
- `@playwright/test` is on version 1.43
- `@playwright/experimental-ct-react17` is on version 1.43
- `@axe-core/playwright` is on version 4.9
A bug was observed when running `npm run test:ct -- --ui` to run the [Playwright tests in UI mode](https://playwright.dev/docs/test-ui-mode), where the [results and timeline of a run test are wiped immediately after](https://github.com/microsoft/playwright/issues/30718). 
https://github.com/user-attachments/assets/cfe36bed-1e64-4d06-ad52-e3e49da27d07
=> chore: upgrade playwright to v1.47

src/__internal__/checkable-input/checkable-input.component.tsx, src/components/checkbox/checkbox-group/checkbox-group.component.tsx, src/components/checkbox/checkbox-group/checkbox-group.test.tsx, src/components/checkbox/checkbox-test.stories.tsx, src/components/checkbox/checkbox.component.tsx, src/components/checkbox/checkbox.mdx, src/components/checkbox/checkbox.stories.tsx, src/components/checkbox/checkbox.style.ts, src/components/checkbox/validations.stories.tsx, src/components/numeral-date/numeral-date.mdx, src/components/radio-button/radio-button-group/radio-button-group.component.tsx, src/components/radio-button/radio-button-group/radio-button-group.test.tsx, src/components/radio-button/radio-button-test.stories.tsx, src/components/radio-button/radio-button.component.tsx, src/components/radio-button/radio-button.mdx, src/components/radio-button/radio-button.stories.tsx, src/components/switch/switch.mdx
- Reverts the following commits:
- https://github.com/Sage/carbon/commit/2f2f340fcdfca1acb5b72bad6df7299eece3eb3e
- https://github.com/Sage/carbon/commit/c9c4500b7177ffd6151a9a4fe6adbe576c4d2f9c
Support for `labelHelp` and `fieldHelp` props was removed from `Checkbox` and `RadioButton` when using the feature flag `validationRedesignOptIn`
=> fix(checkbox, radio-button): restore support for `labelHelp` and `fieldHelp`

src/components/textarea/textarea-test.stories.tsx, src/components/textarea/textarea.component.tsx, src/components/textarea/textarea.test.tsx
This fix ensures that when the `rows` prop and `expandable` prop are used simultaneously, the textarea component renders with the correct height.
fixes #6961
I have opted to go with a Chromatic snapshot to cover us in the event of any regression happening and reintroducing this bug. 
- Ensure that the new Chromatic snapshot for `With expandable and rows in a dialog with form` is sufficient.
- No other visual or functional regressions with Textarea.
- No other visual or functional regressions with Textarea especially when `minHeight`, `rows` or `expandable` props are used.
=> fix(textarea): ensure that correct height is applied when rows and expandable prop are used together - FE-6810

src/components/form/__internal__/form-summary.style.ts, src/components/form/form-test.stories.tsx, src/components/form/form.component.tsx, src/components/form/form.stories.tsx, src/components/form/form.style.ts, src/components/form/form.test.tsx
fix #6658
Allows the form-footer content to be responsive - the buttons and validation message will wrap in smaller screen sizes. When buttons are `fullWidth` the `rightSideButtons` will now render underneath the `saveButton` instead of above.
Form-footer content does not wrap in smaller screen sizes and overflows outside the page. 
`rightSideButtons` render above the `saveButton` when buttons are `fullWidth`.
=> fix(form): allow form-footer content to be responsive

src/components/textarea/textarea.component.tsx, src/components/textarea/textarea.pw.tsx
Expandable `Textarea` shrinks back to original height when new lines are removed. 
https://github.com/user-attachments/assets/1eec6d1b-97bc-4c5f-866c-75426d705b6d
Expandable `Textarea` increases in height when lines are added but does not shrink back to original height when new lines are removed. 
https://github.com/user-attachments/assets/d4b22b41-425a-405c-866e-0fd304ad709a
- Ensure `rows` and `minHeight` props still work as expected with an expandable `Textarea`.
=> fix(textarea): ensure expandable height shrinks when new lines are removed

package-lock.json, package.json, src/components/select/__internal__/select-list/select-list.component.tsx, src/components/select/__internal__/utils/with-filter.hoc.tsx, src/components/select/option/option.component.tsx, src/components/select/option/option.style.ts, src/components/select/option/option.test.tsx, src/components/select/simple-select/components.test-pw.tsx, src/components/select/simple-select/simple-select-test.stories.tsx, src/components/select/simple-select/simple-select.mdx, src/components/select/simple-select/simple-select.pw.tsx
fix #6978
fix #6939
Upgrades `@tanstack/react-virtual` to `3.10.8`
Updates `Option` interface to allow `value` and `text` to be optional to allow users to compose `children` for complex layouts. This ensures that `SelectList` height is set relatively when a custom option is passed as child so that there is no overflow (scrollbars). When no value is passed the option is treated as non-interactive (can't be clicked or selected) and is styled as such.
`@tanstack/react-virtual` is `3.0.0-beta.68`
Option requires `value` and `text` to be set
=> Select virtualiser tweaks

src/components/action-popover/__internal__/action-popover-utils.tsx, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx, src/components/action-popover/action-popover-test.stories.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.pw.tsx, src/components/action-popover/action-popover.stories.tsx, src/components/action-popover/action-popover.test.tsx, src/components/action-popover/components.test-pw.tsx
Currently, we have a bug whereby when a user presses the up arrow key, the first focusable item in the menu is focused. This appears to be a bug as we have code that specifically handles this behaviour but is overridden elsewhere in the code. This fix ensures that the last focusable item is focused.
fixes #6826
- Pressing the `Up Arrow` key should open the menu and focus the last focusable element.
https://github.com/user-attachments/assets/3505ce95-fa05-4d0b-960a-d61fd529141c
- Pressing the `Up Arrow` key opens the menu and focuses the first focusable element.
https://github.com/user-attachments/assets/d9fa3e32-da09-44ef-bc81-f9e7f9234d70
N/A
- Ensure that the `Up Arrow` key focuses on the last focusable element in the menu. 
- No other functionality-related regressions regarding …
=> fix(action-popover): ensure that opening using the up arrow focuses last focusable element - FE-6793

.storybook/utils/styled-system-props.ts, src/components/global-header/component.test-pw.tsx, src/components/global-header/global-header-test.stories.tsx, src/components/global-header/global-header.stories.tsx, src/components/menu/__internal__/submenu/submenu.style.ts, src/components/menu/component.test-pw.tsx, src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.stories.tsx, src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu-test.stories.tsx, src/components/menu/menu.component.tsx, src/components/menu/menu.mdx, src/components/menu/menu.pw.tsx, src/components/menu/menu.stories.tsx, src/components/menu/menu.style.ts, src/components/navigation-bar/components.test-pw.tsx, src/components/navigation-bar/navigation-bar-test.stories.tsx, src/components/navigation-bar/navigation-bar.pw.tsx, src/components/navigation-bar/navigation-bar.stories.tsx
fix #6934, fix #7000, fix #7010
Ensures that `MenuItem`s flex so that they all have the same height if any wrap their content to new
lines at smaller screen resolutions. Ensures no additional padding is set on `MenuItem` children of
`MenuFullscreen`.
BREAKING CHANGE: `Menu` no longer supports `height`, `minHeight`, `maxHeight`, `size`,
`overflowY` and `display` props. `MenuItem` no longer supports `height`, `minHeight`,
`maxHeight`, `size`, `verticalAlign`, `overflow`, `overflowY`, `overflowX` and
`display` props.
Adds invariant to ensure that the component does not render when `children` are passed but `submenu`
is an empty string
MenuItems do not wrap/flex uniformly
When `submenu` is an empty string the `children` are still rendered but within the parent `MenuItem`
* …
=> Menu fixes

src/components/dialog-full-screen/components.test-pw.tsx, src/components/dialog-full-screen/dialog-full-screen.mdx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog/components.test-pw.tsx, src/components/dialog/dialog.mdx, src/components/dialog/dialog.pw.tsx, src/components/dialog/dialog.stories.tsx, src/components/menu/component.test-pw.tsx, src/components/menu/menu-full-screen/menu-full-screen.component.tsx, src/components/menu/menu.mdx, src/components/menu/menu.pw.tsx, src/components/modal/modal.component.tsx, src/components/sidebar/components.test-pw.tsx, src/components/sidebar/sidebar.mdx, src/components/sidebar/sidebar.pw.tsx, src/components/sidebar/sidebar.stories.tsx, src/hooks/__internal__/useModalManager/useModalManager.ts
fix #6870
Ensures focus is moved back onto the active element before a modal/fullscreen menu is opened. 
Currently, once a modal is closed, focus is typically returned to the document, which can be disorientating for users.
=> fix(menu-full-screen, modal): ensure the call to action element is focused on close

src/__internal__/focus-trap/focus-trap.test.tsx, src/__internal__/utils/helpers/events/events.test.ts, src/components/action-popover/action-popover.test.tsx, src/components/advanced-color-picker/advanced-color-picker.test.tsx, src/components/anchor-navigation/anchor-navigation.test.tsx, src/components/heading/heading.test.tsx, src/components/menu/menu-full-screen/menu-full-screen.test.tsx, src/components/menu/menu.test.tsx, src/components/select/__internal__/select-list/select-list.test.tsx, src/components/simple-color-picker/simple-color-picker.test.tsx
Replaces usage of `toBeFocused` with testing library matcher `toHaveFocus`
`toBeFocused` is still used in some refactored unit test files
=> chore: replace `toBeFocused` with testing library matcher `toHaveFocus`

playwright/components/note/index.ts, src/components/note/note-test.stories.tsx, src/components/note/note.component.tsx, src/components/note/note.mdx, src/components/note/note.stories.tsx, src/components/note/note.style.ts, src/components/note/note.test.tsx
Allows `title` to be a node, avoids a breaking change by rendering a `Typography` component if the `title` is passed as a string.
Also edits the height of the draft editor/draft editor content to avoid a potential visual regression when the title node is larger in size.
Currently, the `title` prop can only be passed as a string
=> fix(note): allow title to be a node & fix potential visual regression

.storybook/main.ts, .storybook/manager-head.html, .storybook/preview-head.html, .storybook/preview.ts, .storybook/sage-docs-theme.ts, .storybook/welcome-page/components-demo/component-heading/component-heading.component.js, .storybook/welcome-page/components-demo/component-heading/component-heading.style.js, .storybook/welcome-page/components-demo/demo/demo-table/demo-table.component.js, .storybook/welcome-page/components-demo/demo/demo.component.js, .storybook/welcome-page/loves-carbon/loves-carbon.component.js, .storybook/welcome-page/loves-carbon/loves-carbon.style.js, .storybook/welcome-page/selling-points/selling-point-panel.component.js, CHANGELOG.md, src/components/breadcrumbs/breadcrumbs.stories.tsx, src/components/card/card.stories.tsx, src/components/definition-list/definition-list.stories.tsx, src/components/drawer/drawer.stories.tsx, src/components/flat-table/flat-table.component.tsx, src/components/flat-table/flat-table.stories.tsx, src/components/flat-table/flat-table.test.tsx, src/components/global-header/global-header.stories.tsx, src/components/icon/icon.stories.tsx, src/components/link/link.stories.tsx, src/components/pages/pages.stories.tsx, src/components/pod/pod.stories.tsx, src/components/popover-container/popover-container.mdx, src/components/step-flow/step-flow.stories.tsx, src/components/vertical-menu/vertical-menu.stories.tsx
The documentation offered by the storybook should be as accessible as possible. This PR aims to implement that by addressing a handful of issues:
- Changes the default secondary colour of the manager to the DS' Sage Green
- Fix the role assigned to the welcome page's headings
- Remove the duplicated `header` elements
- Add ARIA labels
- Add image alt text
- Replace blank table headings
A wide range of stories feature AXE failings, which results in a poor documentation experience for users who e.g. rely on assistive technologies.
The following issues are embedded within Storybook and can't be directly addressed:
- The Create a new story button throws a "Buttons must have discernible text" warning (only in localhost, live build is fine);
- The "Zooming and scaling" failure is due to …
=> docs(storybook): fixes a number of accessibility issues in the documentation

src/components/date-range/date-range.component.tsx, src/components/date-range/date-range.mdx, src/components/date-range/date-range.stories.tsx, src/components/date-range/date-range.test.tsx, src/components/date/__internal__/date-formats/date-formats.test.ts, src/components/date/__internal__/date-formats/index.ts, src/components/date/date-test.stories.tsx, src/components/date/date.component.tsx, src/components/date/date.mdx, src/components/date/date.stories.tsx, src/components/date/date.test.tsx, src/locales/de-de.ts, src/locales/en-ca.ts, src/locales/en-gb.ts, src/locales/en-us.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts, src/locales/locale.ts
A new property has been added to the `Locale` interface for dates to allow customers to override the displayed date formats in both the Date and DateRange inputs
fix #6930 
Provide a mechanism to allow default date formats to be overridden
Currently, users are forced to adhere to the date formats decreed by their chosen locale, with the only option to change being to use a different locale.
Render one of the following component:
**DateInput**
```javascript
<I18nProvider
locale={{
locale: () => "de-DE",
date: {
dateFnsLocale: () => de,
ariaLabels: {
previousMonthButton: () => "Vorheriger Monat",
nextMonthButton: () => "Nächster Monat",
},
dateFormatOverride: "yyyy-M-d",
},
}}
>
<DateInput
label="Date `DE` locale"
value={state}
onChange={handleChange}
/>
</I18nProvider>
```
**DateRange** …
=> feat(date, date-range): provides a mechanism that allows consumers to override the format of dates

src/components/select/__internal__/select-textbox/select-textbox.style.ts, src/components/select/simple-select/simple-select.mdx, src/components/select/simple-select/simple-select.stories.tsx
I have not added any unit tests for the styling tweaks as Chromatic will be the best way to capture these changes as they are purely visual.
Our `transparent` variant of Select matches up with the `subtle` version in the frozen Design System.
- There should be no visual styling regressions with any other type of Select.
- `Transparent` should match the designs provided with this work. 
- There should be no functional changes to the `transparent` variant of Select.
=> feat(select): update styles of transparent variant to align with frozen design system

src/components/carbon-provider/__internal__/new-validation.context.ts, src/components/carbon-provider/carbon-provider.component.tsx, src/components/carbon-provider/carbon-provider.test.tsx
Deprecates both feature flags and each respective flag's previous styling.
Currently, no deprecation warning exists for both feature flags.
=> feat(carbon-provider): add deprecation warning for roundedCornersOptOut & focusRedesignOptOut

src/components/sidebar/__internal__/sidebar-header/sidebar-header.component.tsx, src/components/sidebar/sidebar.test.tsx
When using a screen reader, sidebars are read out as 'Sidebar header Close'. This seems to be because the aria-labelledby targets the id on the sidebar header and not the heading itself. This fix applies the aria-labelledby to the content of the sidebar header component.
fixes #7053
Apply `id` prop to the content of Sidebar's Header component. This is so that only the heading content is read out.
`id` prop is on Sidebar's Header component. This means that the heading content is read out and also the close icon.
N/A
- Ensure that `With heading` example of Sidebar is read out correctly by a screen reader on Mac OS and Windows.
- Check that no other regressions have occurred with Sidebar's functionality or styling due to this change.
=> fix(sidebar): ensure that aria-labelledby is applied to the correct piece of content in the header - FE-6891

src/components/tabs/__internal__/tab-title/tab-title.component.tsx, src/components/tabs/__internal__/tab-title/tab-title.style.ts, src/components/tabs/__internal__/tabs-header/tabs-header.component.tsx, src/components/tabs/__internal__/tabs-header/tabs-header.style.ts, src/components/tabs/tabs.mdx, src/components/tabs/tabs.stories.tsx, src/components/tabs/tabs.test.tsx
The necessary changes have been added to the `TabTitle` and `TabsHeader` components to solve the discrepancies with DS. The tooltip is no longer visible and the attributes `aria-invalid` and `aria-errormessage` are used in order to ensure the screen reader announces that the Tab has invalid content.
Position top:
https://github.com/user-attachments/assets/7ee293d6-1a08-4e08-b650-f2fe44ad2cd6
Position left:
https://github.com/user-attachments/assets/f6bcf213-3dd1-47c2-b6a8-e49fc5da5398
Additional siblings:
https://github.com/user-attachments/assets/3ef67b44-d631-499e-84b6-53900c9e7db2
Custom layout:
https://github.com/user-attachments/assets/f4488570-1970-4696-8386-3ab1096b89cb
The current behaviour which is not aligned can be seen below:
Position top: …
=> fix(tabs): support for post-rebrand validation pattern

src/components/file-input/file-input.pw.tsx
Fixes File-Input test which fails when run locally in Windows.
Test fails when run locally in Windows.
- [] Tested in CodeSandbox/storybook
- [] Add new Playwright test coverage if required
- [] Carbon implementation matches Design System/designs
- [] UI Tests GitHub check reviewed if required
-[] Verify test runs locally on Mac.
=> test(file-input): onchange test windows fix

src/components/select/__internal__/select-textbox/select-textbox.component.tsx, src/components/select/filterable-select/filterable-select-test.stories.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/simple-select/simple-select-test.stories.tsx, src/components/select/simple-select/simple-select.component.tsx
Currently, the aria-describedby attribute is applied to the placeholder span of select-textbox. This fix ensures that the attribute is correctly applied to the select-textbox.
fixes #7057
`aria-describedby` attribute should be applied to the combo box (select-textbox).
`aria-describedby` attribute is being applied to the `span` element of the placeholder inside the select-textbox. This is because the `aria-describedby` attribute is being inadvertently passed via `...rest`
N/A
For Simple-Select, MultiSelect and Filterable.
- Using the `SimpleSelectWithAriaDescribedby` for Simple-Select  and `AriaDescribedbyExample` for Multi and Filterable, ensure that the `aria-describedby` is read aloud by the screen reader when the select-textbox is focused. 
- Ensure no other regressions with regards …
=> fix(select): ensure that aria-describedby is applied to the select-textbox element - FE-6889

src/components/sidebar/__internal__/sidebar-header/sidebar-header.style.ts, src/components/sidebar/sidebar-test.stories.tsx
A recent bug fix in 144.9.1 prevent the sidebar header component from being 100% width when the sidebar also has an onCancel method provided. Thix fix ensures that the sidebar heading element is 100%.
fixes #7090
N/A
- Check that new and updated Chromatic snapshots match the expected styles.
- Ensure that the new `WithStepFlow` example renders the `StepFlow` component full width of the header.
- No other visual or functional regressions were introduced in this work.
=> fix(sidebar): make sidebar-heading element 100% width

src/components/draggable/draggable-container.component.tsx, src/components/draggable/draggable-item/draggable-item.component.tsx, src/components/draggable/draggable-item/draggable-item.style.ts, src/components/draggable/draggable-test.stories.tsx, src/components/draggable/draggable.mdx, src/components/draggable/draggable.stories.tsx
fix #7089
adds the `flexDirection` prop which provides consumers with the means to change the flex-direction css attribute from row to row-reverse or vice versa
Currently, consumers have no control over where the "draggable" icon is placed, and it is always rendered on the right-hand side by default
=> feat(draggable-container): add flexDirection prop

jest.config.ts, playwright/components/tabs/index.ts, src/components/tabs/__internal__/tab-title/tab-title.component.tsx, src/components/tabs/__internal__/tab-title/tab-title.style.ts, src/components/tabs/__internal__/tabs-header/tabs-header.component.tsx, src/components/tabs/__internal__/tabs-header/tabs-header.style.ts, src/components/tabs/__internal__/tabs-header/tabs-header.test.tsx, src/components/tabs/tabs-test.stories.tsx, src/components/tabs/tabs.component.tsx, src/components/tabs/tabs.mdx, src/components/tabs/tabs.pw.tsx, src/components/tabs/tabs.stories.tsx, src/components/tabs/tabs.test.tsx
Improves the Tabs component to ensure that it complies to the new Design System concepts, mainly via scroll removal in favour of button navigation control
Disable horizontal scroll and replace with buttons to allow mouse-only users to be able to navigate the tab list, as per the DS
Users must grab the scroll bar and drag it around if they wish to view obscured tabs. This can be quite difficult for users who e.g. experience tremours in their hands, and no alternative navigation approach is provided.
Using the existing `Tabs` Storybook entry (under the `Responsive` section), resize the screen and ensure that the buttons:
- are shown if there are hidden tabs available to scroll to; or
- are hidden if there are no further tabs to show.
Only horizontal tabs are scrollable. Vertical tabs remain …
=> feat(tabs): align tabs with (frozen) design system

src/__internal__/focus-trap/focus-trap.component.tsx, src/components/popover-container/components.test-pw.tsx, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.pw.tsx, src/components/popover-container/popover-container.test.tsx
This fix ensures that if the last focusable element in a popover container is a radio button, that the tab sequence is not affected once focus is outside of the container
fixes #7067
https://github.com/user-attachments/assets/5343bd1b-345a-4576-95b1-3df40374833a
https://github.com/user-attachments/assets/7e741308-4f29-4d7e-96ae-984f19b466ff
N/A
**Steps to reproduce**
Using the new `With Radio Button` example:
- Press TAB key until you reach the `with Radio children` button.
- Press ENTER to open the popover container.
- Press TAB key until the last element of the list.
- Press TAB key.
- Focus should move to button next to the popover container's opening button.
There should also be no functional regressions or changes to the other `PopoverContainer` examples.
=> fix(popover-container): ensure that tab sequence is not lost when container has radio buttons

package-lock.json, package.json, playwright/components/date-input/index.ts, playwright/components/date-input/locators.ts, src/__internal__/utils/logger/logger.test.ts, src/components/date/__internal__/date-fns-fp/index.ts, src/components/date/__internal__/date-picker/date-picker.component.tsx, src/components/date/__internal__/date-picker/date-picker.test.tsx, src/components/date/__internal__/date-picker/day-picker.style.ts, src/components/date/__internal__/navbar/navbar.component.tsx, src/components/date/__internal__/navbar/navbar.style.ts, src/components/date/__internal__/utils.test.ts, src/components/date/__internal__/utils.ts, src/components/date/__internal__/weekday/weekday.style.ts, src/components/date/__internal__/weekday/weekday.test.tsx, src/components/date/date.component.tsx, src/components/date/date.mdx, src/components/date/date.pw.tsx, src/components/date/date.stories.tsx, src/components/date/date.test.tsx
Upgrades react-day-picker to remove the dependency on React 18
=> feat(date-input, date-range): upgrade react-day-picker to v9

src/components/decimal/decimal.component.tsx, src/components/decimal/decimal.test.tsx, src/components/grouped-character/grouped-character.component.tsx, src/components/grouped-character/grouped-character.test.tsx
- `Decimal` - deprecates `onKeyPress` prop.
- `GroupedCharacter` - replaces use of `onKeyPress` with `onKeyDown`. 
- `Decimal` - has `onKeyPress` prop.
- `GroupedCharacter` - uses `onKeyPress` internally.
=> feat(decimal, grouped-character): deprecate onKeyPress

src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu-segment-title/menu-segment-title.component.tsx, src/components/menu/menu-segment-title/menu-segment-title.context.tsx, src/components/menu/menu-segment-title/menu-segment-title.style.ts, src/components/menu/menu-segment-title/menu-segment-title.test.tsx, src/components/menu/menu.mdx, src/components/menu/menu.stories.tsx
Adds context to `MenuSegmentTitle` which allows `MenuItem` to know if the wrapping parent element is a `MenuSegmentTitle` and if so, override the colouring. Additional changes have also been implemented to ensure that this only happens when `MenuFullscreen` is used - normal `Menu` items are unaffected.
When used as a child of `MenuSegmentTitle` with the `alternate` variant, the wrong colouring is applied to `MenuItem`
Resolves [6789](https://github.com/Sage/carbon/issues/6789)
Use the new Menu Storybook entry to verify the changes work and do not impact other menus
=> feat(menu-fullscreen): fix colours when MenuItem used as child of MenuSegmentTitle

src/components/vertical-menu/components.test-pw.tsx, src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.component.tsx, src/components/vertical-menu/vertical-menu.pw.tsx, src/components/vertical-menu/vertical-menu.stories.tsx
fixes: #7073 
The vertical menu full screen is now using the `useModalManager` in order to register and a modal. This permits us to interact with the menu when we also have a dialog opened in the background.
https://github.com/user-attachments/assets/9d9eeb4b-0485-454c-b5eb-56ce7a45beac
https://github.com/user-attachments/assets/3d95d901-26d1-4932-9b53-2dfde2f3f990
If there is both a vertical menu full screen and a dialog opened, due to the modal manager interaction with the vertical menu is blocked. Since the vertical menu is on top of the dialog, the user can not close the dialog and all mouse interaction with the menu is blocked.
https://github.com/user-attachments/assets/ad0576b7-92cd-4794-90fb-cfbca77edf3e
=> fix(vertical-menu-full-screen): register Fullscreen subcomponent as a Carbon modal

src/components/select/multi-select/components.test-pw.tsx, src/components/select/multi-select/multi-select-test.stories.tsx, src/components/select/multi-select/multi-select.component.tsx, src/components/select/multi-select/multi-select.mdx, src/components/select/multi-select/multi-select.pw.tsx, src/components/select/multi-select/multi-select.stories.tsx, src/components/select/multi-select/multi-select.test.tsx
fix #6752
adds the `onListScrollBottom` callback to `MultiSelect`, to be called when a user scrolls to the bottom of the select list
Currently,  there is no `onListScrollBottom` callback on `MultiSelect`
=> feat(multi-select): add onListScrollBottom 

src/components/action-popover/action-popover-menu-button/action-popover-menu-button.component.tsx, src/components/action-popover/action-popover-test.stories.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.mdx, src/components/action-popover/action-popover.stories.tsx, src/components/action-popover/action-popover.test.tsx
fix #7107
- Add aria-labelledby and aria-describedby props to ActionPopover. 
- Ensure that aria attributes are set on ActionPopoverMenuButton when `ariaAttributes` are passed using `renderButton` prop. 
- ActionPopover does not support aria-labelledby and aria-describedby attributes. 
- When `ariaAttributes` is passed to ActionPopoverMenuButton using the `renderButton` prop, the aria attributes are not set on the button. 
- See new test story "With aria attributes"
=> feat(action-popover): add aria-labelledby and aria-describedby props

src/components/advanced-color-picker/advanced-color-picker.component.tsx, src/components/advanced-color-picker/advanced-color-picker.mdx, src/components/advanced-color-picker/advanced-color-picker.pw.tsx, src/components/advanced-color-picker/advanced-color-picker.stories.tsx, src/components/dialog-full-screen/dialog-full-screen.component.tsx, src/components/dialog-full-screen/dialog-full-screen.mdx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/dialog-full-screen/dialog-full-screen.stories.tsx, src/components/dialog/components.test-pw.tsx, src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.mdx, src/components/dialog/dialog.pw.tsx, src/components/dialog/dialog.stories.tsx, src/components/modal/modal.component.tsx, src/components/modal/modal.test.tsx, src/components/sidebar/components.test-pw.tsx, src/components/sidebar/sidebar.component.tsx, src/components/sidebar/sidebar.mdx, src/components/sidebar/sidebar.pw.tsx, src/components/sidebar/sidebar.stories.tsx, src/components/vertical-menu/components.test-pw.tsx, src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.component.tsx, src/components/vertical-menu/vertical-menu.pw.tsx
fix #7085 
Adds the `restoreFocusOnClose` prop to all components that use `useModalManager` or render the `Modal` component in their component hierarchy. Some components have received the prop from extending other props tables and spreading rest, others have had to be added manually. 
All components effected:
1. Modal
2. Dialog
3. Confirm
4. Alert
5. AdvancedColorPicker
6. DialogFullScreen
7. Sidebar
This prop will allow consumers to opt out of the default behaviour, which currently re-focuses all elements which were focused previously before a modal based component was opened.
Currently, all modal based components re-focuses the previous active element with no ability to opt out of said behaviour.
=> feat: add restoreFocusOnClose prop to modal based components

src/components/box/box.component.tsx, src/components/box/box.pw.tsx, src/components/box/box.style.ts, src/components/box/box.test.tsx, src/components/dismissible-box/dismissible-box.pw.tsx
The `height`, `width`, `opacity` and `color` are not being passed directly to the `StyledBox` component but instead are placed in the `cssProps` object, and then they are used inside the `StyledBox`. This prevents the props from being applied to the HTML node directly.
Playwright tests that were checking for the attribute being present on the node have been amended since the attribute is no longer present. 
The `height`, `width`, `opacity` and `color`  props are passed directly to the `StyledBox` component which applies them directly to the HTML node.
=> fix(box): css style properties passed as HTML attributes

src/components/step-flow/step-flow-test.stories.tsx, src/components/step-flow/step-flow.component.tsx, src/components/step-flow/step-flow.test.tsx
Aria props are destructured and present in the documentation for `Step Flow`
Aria props are not destructured. They are present due to `...rest` being spread on the component. Due to this, they do not appear in the Storybook documentation for the component under the `Props` section. 
N/A
New test stories have been created to demonstrate the newly added aria props. These stories are:
- Default with aria-label
- Default with aria-labelledby
- Default with aria-describedby
You should be able to see these attributes in the DOM, on the element for Step Flow. 
There should also be no other functional or styling regressions due to this change.
=> feat(step-flow): add aria props to component - FE-7013

src/components/accordion/accordion.pw.tsx, src/components/action-popover/action-popover.pw.tsx, src/components/box/box.pw.tsx, src/components/card/card.pw.tsx, src/components/date-range/date-range.pw.tsx, src/components/detail/detail.pw.tsx, src/components/file-input/file-input.pw.tsx, src/components/heading/heading.pw.tsx, src/components/hr/hr.pw.tsx, src/components/pages/pages.pw.tsx, src/components/popover-container/popover-container.pw.tsx, src/components/radio-button/radio-button.pw.tsx, src/components/search/search.pw.tsx, src/components/select/filterable-select/filterable-select.pw.tsx, src/components/select/multi-select/multi-select.pw.tsx, src/components/select/simple-select/simple-select.pw.tsx, src/components/sidebar/sidebar.pw.tsx, src/components/simple-color-picker/simple-color-picker.pw.tsx, src/components/tile-select/tile-select.pw.tsx, src/components/tile/tile.pw.tsx, src/components/vertical-menu/vertical-menu.pw.tsx
I have removed all unnecessary 'awaits' on where the values or are not asynchronous in our Playwright tests.
Currently our Playwright tests contain numerous unnecessary 'awaits' on where the values or are not asynchronous.
=> test: remove unnecessary awaits

src/components/menu/menu.style.ts
Ensure list style on MenuItem is none. 
Default list style on MenuItem still appears in Safari. 
https://github.com/user-attachments/assets/d5263a70-dd29-4d64-8b85-338088aab6ab
Go to https://carbon.sage.com/?path=/story/menu--scrollable-submenu-with-parent in Safari.
=> fix(menu-item): ensure list style is none in Safari

src/components/date/__internal__/date-picker/day-picker.style.ts, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.style.ts
fix #7137
date-picker renders above a PopoverContainer's popover. 
date-picker renders behind a PopoverContainer's popover. 
- Manual testing needed to check regressions when using other popups/modals with these components.
=> fix(popover-container): prevent DatePicker from rendering behind the popover

src/components/date-range/date-range-test.stories.tsx, src/components/date-range/date-range.component.tsx, src/components/date-range/date-range.test.tsx, src/components/date/__internal__/date-picker/date-picker.component.tsx, src/components/date/date.component.tsx
fixes: #7116
When the `DateRange` component is used an accessibility violation is reported by the Axe Dev Tool scan, more precisely: _All page content should be contained by landmarks_
In order to solve this the `role='region'` has been used to group the elements from the `DatePicker` along with the possibility to add either `aria-label` or `aria-labelledby` in order to describe the purpose or content for the region.
The `DatePicker` component is used an accessibility violation is reported by the Axe Dev Tool scan, more precisely: _All page content should be contained by landmarks_ as it can be seen in the screenshot below:
1. Open: https://carbon.sage.com/iframe.html?globals=&args=&id=date-range--default-story&viewMode=story in a new tab
2. Run an Axe Dev Tools full page scan , making …
=> fix(date-range): date range axe issue

src/components/search/search.component.tsx, src/components/search/search.test.tsx
fixes: #7147
When a button includes an `aria-label` attribute, screen readers prioritize the `aria-label` text over any visible content inside the button. This means the `aria-label` effectively replaces the visible text for accessibility purposes. If no `aria-label` attribute is present, it defaults to reading the button's visible text or any accessible content within it.
With this in mind, I’ve removed the default value of  `"search button"` for the `searchButtonAriaLabel` prop and opted to use the button’s visible text instead. 
This approach ensures that, in the absence of a specified value for `searchButtonAriaLabel`, the screen reader will read the button text by default. However, if a more explicit description is required, developers can set the `searchButtonAriaLabel` prop, and …
=> fix(search): search button has a default aria label

src/components/popover-container/index.ts, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.mdx, src/components/popover-container/popover-container.stories.tsx, src/components/popover-container/popover-container.style.ts, src/components/popover-container/popover-container.test.tsx, src/hooks/__internal__/useFocusPortalContent/useFocusPortalContent.tsx
fix #7133 
- The popover dialog gains focus when opened to allow screen readers to access the popup. 
- Adds `hasFullWidth` prop to enable fullWidth Button behaviour optionally. 
- Expose `focusButton` method to enable consumers to programatically focus the open button.
- Ensure Form within a PopoverContainer had expected overflow styling and stickyFooter has correct border-radius. 
- The component renders in a Portal and cannot be accessed by screen reader commands. 
- Component has 100% width causing other elements to render below it. 
- Form within a PopoverContainer does not have overflow styling.
=> fix(popover-container): ensure component is accessible by screen readers

src/components/form/form-test.stories.tsx, src/components/form/form.style.ts
When using a Time component within a Form, the separator is incorrectly positioned. This fix ensures that the height of the Time component is calculated correctly and that margin-bottom is not applied twice, thus ensuring the separator is rendered correctly in the centre position.
fixes #7164
I have created this as a non-draft PR because I needed to see if the Chromatic snapshots are as expected.
- Check that you're happy that the new Chromatic snapshot sufficiently captures what is required to avoid potential regressions in the future.
- No other styling regressions relating to Form.
=> fix(form): ensure that additional margin-bottom is not applied to Time component - FE-7054

playwright/index.tsx, src/components/date/__internal__/date-picker/date-picker.component.tsx, src/components/date/__internal__/date-picker/date-picker.test.tsx, src/components/date/date.pw.tsx
The Navbar of the date picker component no longer re-renders when the rest of the component updates
fix #7158
Prevent the  month navigation buttons from losing focus when activated via keyboard
The buttons of the navigation bar in the Date Picker lose focus when activated using keyboard controls
Use the Storybook examples to ensure that the buttons don't lose focus when navigating between months using the keyboard
=> feat(date): fix focus loss when using navbar with keyboard

src/components/form/form-test.stories.tsx, src/components/form/form.style.ts
This fix ensures that the NumeralDate component does not have margin-bottom styles applied twice when used inside a form.
fixes #7171
I created this PR as a non-draft version initially to check that the Chromatic snapshot is correct before it gets to the QA stage. 
- Check that the newly created Chromatic snapshot captures what we need to mitigate a styling regression in the future.
- No other functional or styling regressions relating to Form.
=> fix(form): ensure that additional margin-bottom is not applied to NumeralDate component - FE-7057

src/components/accordion/accordion.mdx, src/components/accordion/accordion.stories.tsx
Update the documented examples to be a11y-compliant
Documented examples of Accordion which render mutliple instances with content throw an a11y violation indicating non-unique landmarks
Run AXE DevTools against any of the Accordion Storybook examples with more than one collapsed accordion on it. Regardless of open/closed state, no error should be flagged
=> docs(accordion): update documentation examples to ensure a11y compliance

docs/using-draft-js.mdx, docs/validations.mdx, src/components/box/box.component.tsx, src/components/checkbox/checkbox.mdx, src/components/confirm/confirm.mdx, src/components/date-range/date-range.mdx, src/components/definition-list/definition-list.mdx, src/components/dialog-full-screen/dialog-full-screen.mdx, src/components/drawer/drawer.stories.tsx, src/components/message/message.mdx, src/components/settings-row/settings-row.mdx, src/components/sidebar/sidebar.mdx, src/components/split-button/split-button.mdx, src/components/switch/switch.mdx, src/components/tabs/tabs.mdx
- Prevent uncontrolled error in `Drawer` when using `expanded` prop in controls.
- Fix broken links in storybook docs. 
- Remove mention of roundedCornerOptOut flag in Box prop descriptions. 
- In `Drawer` storybook examples, setting `expanded` prop in controls causes uncontrolled error. 
- Some links in storybook docs are broken. 
- RoundedCornerOptOut mentioned in Box prop description.
=> docs(drawer): fix expanded uncontrolled error with controls

src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.pw.tsx
fix #6023 
adding modal props to Dialog and pass enableBackgroundUI
=> fix(dialog): ensure enableBackgroundUI is passed to Modal

src/__internal__/fieldset/fieldset.component.tsx, src/__internal__/fieldset/fieldset.style.ts, src/__internal__/fieldset/fieldset.test.tsx, src/components/checkbox/checkbox-group/checkbox-group.component.tsx, src/components/form/form.stories.tsx, src/components/numeral-date/numeral-date-test.stories.tsx, src/components/numeral-date/numeral-date.component.tsx, src/components/numeral-date/numeral-date.pw.tsx, src/components/numeral-date/numeral-date.style.ts, src/components/numeral-date/numeral-date.test.tsx, src/components/radio-button/radio-button-group/radio-button-group.component.tsx, src/components/textbox/textbox-test.stories.tsx, src/components/time/time-test.stories.tsx, src/components/time/time.component.tsx, src/components/time/time.stories.tsx, src/components/time/time.style.ts
- Add support for `labelAlign` prop for non-inline label in NumeralDate.
- Add `labelAlign` prop to Time.
- Add `fieldLabelsAlign` prop to NumeralDate and Time to allow left/right alignment of field labels. 
- Ensure inline labels in NumeralDate display as expected in Safari:
- NumeralDate has `labelAlign` prop that has no effect with non-inline labels. 
- Time does not have `labelAlign` prop. 
- NumeralDate with inline label does not display as expected in Safari.
=> feat(numeral-date, time): add support for labelAlign on non-inline labels

src/components/portrait/__internal__/utils.test.ts, src/components/portrait/__internal__/utils.ts, src/components/portrait/portrait-test.stories.tsx, src/components/portrait/portrait.component.tsx, src/components/portrait/portrait.mdx, src/components/portrait/portrait.pw.tsx, src/components/portrait/portrait.stories.tsx, src/components/portrait/portrait.style.tsx, src/components/portrait/portrait.test.tsx, src/components/profile/profile.component.tsx, src/components/profile/profile.mdx, src/components/profile/profile.stories.tsx, src/components/profile/profile.test.tsx, src/components/switch/switch.component.tsx
- Add a prop to `Portrait` that allows developers to specify their own custom background colour via hex code;
- Add utilities to the codebase to take the given hex code and generate an appropriate, accessible foreground colour to ensure that any colour can be used without e.g. contrast or luminance issues.
- Allow users to override the foreground colour with their own (only if `backgroundColor` is specified), to support particular branding requirements (e.g. using company colours for initials)
Customers have a choice of two colour modes for the `Portrait` component (and by association, the `Profile` component) which effectively boils down to "light" and "dark" variants.
The functions that calculate the contrast and luminance values were provided by Co-Pilot and then modified to be …
=> feat(portrait, profile): allow custom background/foregound colours for the Portrait and Profile components

src/components/hr/hr.component.tsx, src/components/hr/hr.mdx, src/components/hr/hr.pw.tsx, src/components/hr/hr.stories.tsx, src/components/hr/hr.style.ts, src/components/hr/hr.test.tsx
=> feat(hr): add height prop

src/components/action-popover/__internal__/action-popover-utils.tsx, src/components/action-popover/action-popover-menu-button/action-popover-menu-button.component.tsx, src/components/action-popover/action-popover-test.stories.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.test.tsx
fixes: #7143
If the button passed to `renderButton` prop contains a child of type `string` we will not add an `aria-label` attribute and the text reader will read the text from the open button.
If the button does not contain a child of type `string` it will receive a default `aria-label` based on the current locale.
Currently a default `aria-label` is applied regardless if the open button contains or not any text.
1. Open the storybook
2. Go to Action Popover -> Custom Menu Button story (action-popover--custom-menu-button)
3. When the first button is focused the screen reader will read the button text: "menu"
Inspecting the button you can see that the <button> element does not have the aria-label="actions" attribute, because the button contains a text.
4. When the second button is focused …
=> fix(action-popover): aria label has default value despite visible text on open button

src/__internal__/input-icon-toggle/input-icon-toggle.component.tsx, src/components/menu/menu-item/menu-item.component.tsx, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu-test.stories.tsx, src/components/menu/menu.pw.tsx, src/components/search/search.component.tsx, src/components/search/search.pw.tsx, src/components/search/search.test.tsx, src/components/textbox/textbox.pw.tsx
Users can clear the text of the search box using the keyboard/voice commands; as such, the clear button in the search input is being read out to non-visual users unnecessarily and can be removed from the tab order. It also does not need to be focusable. In order to enhance this component further, functionality has been introduced to allow users to clear the Search field with the Escape key, which is standard practice across the web.
Resolves #7170
- Remove the clear button from the tab order;
- Add the `aria-hidden` attribute to the clear button;
- Enable support for clearing the input via the Escape key
https://github.com/user-attachments/assets/8fa5ca88-9596-40e8-ab6f-adb915c2356d
https://github.com/user-attachments/assets/c3d4c682-ef23-4267-bd0f-43da4bd8a429
The "clear" icon is …
=> feat(search, menu-item): Search accessibility updates

src/components/dialog/dialog.mdx, src/components/dialog/dialog.stories.tsx, src/components/form/form.stories.tsx
Makes respective textareas in `Form` (different spacing) & `Dialog` (using handles) story examples controlled. Also ensures the using handle example on `Dialog` is documented correctly.
Currently, the handle example on `Dialog` does not display on docs navigation & textarea is uncontrolled. Textarea is also uncontrolled in different spacing example in `Form` docs.
=> docs(dialog, form): make respective textareas controlled 

src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu.pw.tsx
Hover styling in Safari:
Focus and hovered styling in Safari:
Less than ideal styling currently in Safari:
N/A
Using Safari: 
- Navigate to `Menu` -> `Test` -> `as link with alternate variant`.
- Click and hover over the `Notification` menu-item. 
- Focus styling and hover styling should be correctly applied.
On all browsers:
- Check that no regressions have occurred to any button styling in menu-items.
=> fix(menu): ensure that the correct focus and hover styling is applied to popover-container button - FE-7061

src/components/dialog-full-screen/content.style.ts, src/components/dialog-full-screen/dialog-full-screen.component.tsx, src/components/dialog-full-screen/dialog-full-screen.style.ts, src/components/dialog-full-screen/dialog-full-screen.test.tsx, src/components/pages/page/page.component.tsx, src/components/pages/pages-test.stories.tsx, src/components/pages/pages.test.tsx
https://github.com/Sage/carbon/issues/5460
https://github.com/user-attachments/assets/fe345453-4408-4289-a363-556272b5249e
=> fix(heading): maintain layout when title prop is set to null

src/components/accordion/accordion.component.tsx, src/components/accordion/accordion.mdx, src/components/accordion/accordion.pw.tsx, src/components/accordion/accordion.stories.tsx, src/components/accordion/accordion.test.tsx
fix #7202
Ensure a custom heading provided via the title prop is not wrapped in a `<h3>` tag.
When a consumer passes a custom header as a React node via Accordion's title prop, the node is wrapped within a `<h3>` tag. This causes the Axe violation "Heading levels should only increase by one" if a consumer doesn't have a `<h2>` defined earlier in the document.
=> fix(accordion): ensure custom title is not wrapped in a heading tag when provided

src/components/portrait/portrait.component.tsx
Ensure `Portrait` prop table correctly dislays:
`Portrait` prop table is missing from its docs:
After investigating, the issue appears to be caused by a bug in the Storybook plugin we use for parsing React components, `react-docgen-typescript` ([link to docs](https://storybook.js.org/docs/api/arg-types#automatic-argtype-inference)).
Debugging revealed that changing the Portrait component to a named export within its `*.component.tsx` file fixes the issue, with the component's storybook metadata correctly containing the generated arg types. This seems to signify a bug with the plugin's parsing ability.
=> docs(portrait): resolve missing prop table in storybook docs

src/components/content/content.style.ts
The margin between the content title and the content body is 24px;
The margin between the content title and the content body is 30px;
=> feat(content): reduce margin of content body to 24px when inline

CHANGELOG.md, docs/usage.mdx
- Update old React v17 import in "Usage" docs
- Make breaking change to `react-dnd` as part of v148.0.0 clearer in the changelog
=> docs: update old React v17 import in usage guide

package-lock.json, package.json
Remove the offending package
The `@octokit/rest` package was reintroduced when the new Text Editor work was merged, however it is no longer required.
=> fix(packages): re-remove reintroduced octokit dependency

src/components/accordion/accordion-test.stories.tsx, src/components/accordion/accordion.style.ts
fix #7203
adds a padding-right to the accordion heading container, so ample space is provided between a subtitle and the accordion chevron
Currently, there is not enough space between the subtitle and the accordion chevron, so if there is a long subtitle or the accordion has a set width there will not be enough space between the two.
=> fix(accordion): add padding-right to accordion heading container

src/components/text-editor/text-editor-test.stories.tsx, src/components/text-editor/text-editor.component.tsx, src/components/text-editor/text-editor.pw.tsx, src/components/text-editor/text-editor.style.ts
- Ensure that margin props are correctly applied to the component.
- Apply `tagComponent`
- Margin props are specified but are not applied to the component.
- tagComponent is not applied to the component.
N/A
- Ensure that margin is applied to `TextEditor` as expected.
- Ensure that no other visual regressions have occurred because of this change.
=> fix(text-editor): ensure that margin props are applied to component - FE-7104

.eslintrc, jest.config.ts, package-lock.json, package.json, src/__internal__/dom/globals.server.test.ts, src/__internal__/dom/globals.test.ts, src/__internal__/dom/globals.ts, src/__spec_helper__/mock-element-scrollto.ts, src/__spec_helper__/mock-match-media.ts, src/__spec_helper__/mock-resize-observer.ts, src/components/flat-table/flat-table-row/flat-table-row.style.ts, src/components/icon/icon.style.ts, src/components/menu/menu-full-screen/menu-full-screen.component.tsx, src/components/modal/__internal__/modal-manager.server.test.tsx, src/components/modal/__internal__/modal-manager.ts, src/components/modal/modal.component.tsx, src/components/vertical-menu/vertical-menu-full-screen/vertical-menu-full-screen.component.tsx, src/hooks/__internal__/useScrollBlock/scroll-block-manager.server.test.ts, src/hooks/__internal__/useScrollBlock/scroll-block-manager.ts
This PR supports applications to use SSR with React 18 by checking for `window`, `document`, and `navigator` object availability in places that aren't supported during SSR.
I needed these changes to make our admin portal + react-router@7's new routing API work.
Additionally, I added an ESLint to prevent accidental usage of global objects during React rendering. I went with that instead of the restricted syntax lint rule because that lint rule would require checking for `window` existence when we know it exists (in `useEffect`s, etc.).
FE-7103
=> feat: support server-side rendering

package-lock.json, src/components/adaptive-sidebar/__internal__/utils.ts, src/components/adaptive-sidebar/adaptive-sidebar-test.stories.tsx, src/components/adaptive-sidebar/adaptive-sidebar.component.tsx, src/components/adaptive-sidebar/adaptive-sidebar.mdx, src/components/adaptive-sidebar/adaptive-sidebar.pw.tsx, src/components/adaptive-sidebar/adaptive-sidebar.stories.tsx, src/components/adaptive-sidebar/adaptive-sidebar.style.ts, src/components/adaptive-sidebar/adaptive-sidebar.test.tsx, src/components/adaptive-sidebar/components.test-pw.tsx, src/components/adaptive-sidebar/index.ts, src/components/box/box.component.tsx, src/components/sidebar/sidebar.component.tsx
implements a sidebar component to be used for Help and Chat purposes
Implement an adaptive sidebar, which can be used as a sibling component to display toggled elements alongside existing layouts
Customers are restricted to the modal Sidebar component, which removes interaction from the screen and hides information, or the Drawer component which would require changes to keep it working as is currently implemented whilst also supporting the new styles, etc.
=> feat(adaptive-sidebar): Implements adaptive sidebar

src/components/form/form-test.stories.tsx, src/locales/en-gb.ts
=> fix(form): correct pluralisation on form summary when single error and warning

src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.component.tsx, src/components/text-editor/__internal__/plugins/Toolbar/buttons/bold.component.tsx, src/components/text-editor/__internal__/plugins/Toolbar/buttons/italic.component.tsx, src/components/text-editor/__internal__/plugins/Toolbar/buttons/list.component.tsx, src/components/text-editor/text-editor.pw.tsx, src/components/text-editor/text-editor.test.tsx
The formatting is applied and any newly-added text is formatted in the correct way
When using the command buttons to format text without any selections present, focus snaps to the text editor but no Bold/Italic formatting appears when text is entered.
Using the default story, click either the Bold or Italic buttons and then type some text into the editor. The formatting should be applied. Click the button again and then continue typing; no further formatting should be applied.
=> fix(text-editor): fixes the formatting buttons when clicked to toggle without text selections

src/components/button/button-types.style.ts, src/components/button/button.component.tsx, src/components/button/button.mdx, src/components/button/button.pw.tsx, src/components/button/button.stories.tsx, src/components/button/button.style.ts, src/components/button/button.test.tsx, src/components/button/components.test-pw.tsx
As part of the work for the Help and Support sidebar, we need to add an option for secondary buttons to make them use a white border/text with transparent background.
The `Dark Background` stories of `Button` have also been updated to actually have a dark background to show the buttons against...
The current styling options available for the `secondary` button type do not allow for the required white styling to be used.
View the new `Secondary/White` story under `Button`
=> [Button] additional secondary style

src/components/tile/tile.component.tsx, src/components/tile/tile.config.ts, src/components/tile/tile.mdx, src/components/tile/tile.stories.tsx, src/components/tile/tile.style.ts, src/components/tile/tile.test.tsx
Changes the highlight variants to better fit the `Tile` and align with DS designs (small, default and large roundness pictured)
Adds the `"important"` variant which is available via the `highlightVariant` prop
Currently, there is no `"important"` variant available via the `highlightVariant` prop and the highlight variants available on `Tile` are not aligned with the design system.
=> feat(tile): add important highlight variant

src/components/decimal/decimal.test.tsx
- Update `Decimal` test that asserts decimal formatting
- A `Decimal` test consistently fails in Node 20.19.0 onwards. This is due to [an update made to Node's version of the ICU library](https://github.com/nodejs/node/commit/d69107f5a8), which is used by Node's JavaScript engine for internationalisation.
=> test(decimal): fix failing test due to Node 20.19.0 change

src/components/adaptive-sidebar/adaptive-sidebar.stories.tsx, src/components/form/form.stories.tsx, src/components/hr/hr-test.stories.tsx, src/components/hr/hr.mdx, src/components/hr/hr.stories.tsx, src/components/hr/hr.style.ts
I have forgone adding a unit or PW test for this change as I think a Chromatic snapshot captures this change best.
There should be no styling regressions with this component due to this change.
=> fix(hr): make width 100% - FE-6662

src/components/dialog/dialog-test.stories.tsx, src/components/dialog/dialog.component.tsx, src/components/dialog/dialog.mdx, src/components/dialog/dialog.stories.tsx, src/components/dialog/dialog.style.ts, src/components/dialog/dialog.test.tsx
Add the "ai" highlight variant to showcase the AI gradient
Currently no Highlight Variant capabilities on the Dialog component
Added Highlight Variant to test story to allow switching between Default (no visual highlight) and AI variants
=> feat(dialog): add highlight variant prop to dialog

.storybook/main.ts, package.json
- Introduce new npm command `start:strict-mode` to enable React Strict Mode when launching Storybook. This would allow us to catch bugs caused by accidentally impure code.
=> build(storybook): introduce command to enable React Strict Mode for all stories

src/components/text-editor/__internal__/index.ts, src/components/text-editor/__internal__/plugins/Toolbar/buttons/save.component.tsx, src/components/text-editor/__internal__/plugins/Toolbar/toolbar.component.tsx, src/components/text-editor/__internal__/read-only-rte.component.tsx, src/components/text-editor/index.ts, src/components/text-editor/text-editor-test.stories.tsx, src/components/text-editor/text-editor.component.tsx, src/components/text-editor/text-editor.mdx, src/components/text-editor/text-editor.pw.tsx, src/components/text-editor/text-editor.stories.tsx, src/components/text-editor/utils.ts
fix #7285
Adds a new argument to the `onChange` callback type so that it can be called with the string value and the HTML and JSON formatted values.
Moves the `createFromHTML` and `createEmpty` utils out of the `__internal__` directory as they are exported from the main index file
The `onChange` callback is only called with the unformatted string value
The `createFromHTML` and `createEmpty` utils are part of the `__internal__` directory.
I have added a test story that renders the HTML and JSON values below the editor `text-editor-test--on-change-formatted-values`
=> feat(text-editor): add support for `onChange` callback also being called with json and html values

.github/ISSUE_TEMPLATE/bug_report.yml
- include a note to add the full version number as opposed to just 'latest'
- many issues are being raised with only 'latest' which is causing issues when reviewing older issues where 'latest' doesn't mean much to the team anymore
=> chore(github): update carbon version placeholder to request full version number

playwright/support/constants.ts, src/components/anchor-navigation/anchor-navigation.pw.tsx, src/components/dialog-full-screen/dialog-full-screen.pw.tsx, src/components/form/form.pw.tsx, src/components/help/help.pw.tsx, src/components/icon/icon.pw.tsx, src/components/numeral-date/numeral-date.pw.tsx
Enable all possible AXE checks in non-slipped PW tests 
Quite a few non-skipped AXE PW tests have an exception due to colour-contrast checks, or due to flaky focus behaviour.
All PW CI jobs should pass without flaking.
=> test: enabled eligible accessibility tests in playwright - FE-7118

src/components/grouped-character/grouped-character.component.tsx, src/components/grouped-character/grouped-character.test.tsx
When `Delete` key is pressed in `GroupedCharacter`:
- moves one position forward when cursor is before a separator
- maintains the position when cursor is after a separator
https://github.com/user-attachments/assets/02595c0f-43cd-4707-b21a-4779d7e06666
When `Backspace` is pressed in `GroupedCharacter` the cursor moves one position if character is after separator:
(will still remove the separator character if it is at the end of the value)
https://github.com/user-attachments/assets/37e36410-dfdf-4b32-8548-258177d2aee4
When `Delete` key is pressed in `GroupedCharacter`:
- has no effect when cursor is before separator
- moves back a position when cursor is after the separator
https://github.com/user-attachments/assets/f03104b9-775f-4292-a5e8-3b0fd2ea1293
When `Backspace` is pressed in …
=> fix(grouped-character): ensure Delete key works as expected

playwright/components/pager/locators.ts, src/components/flat-table/flat-table.stories.tsx, src/components/pager/__internal__/pager-navigation.component.tsx, src/components/pager/pager-test.stories.tsx, src/components/pager/pager.component.tsx, src/components/pager/pager.mdx, src/components/pager/pager.pw.tsx, src/components/pager/pager.stories.tsx, src/components/pager/pager.style.ts, src/components/pager/pager.test.tsx
fix #7184
fix #5704
Adds `smallScreenBreakpoint` prop that allows consumers to wrap (if dropdown and/or total elements are rendered) and reduce spacing around the elements within `Pager`:
- Content in `Pager` overflows in small viewports:
=> feat(pager): add small screen styling 

src/components/flat-table/flat-table-row-header/flat-table-row-header.style.ts, src/components/flat-table/flat-table-test.stories.tsx
fix #6774
Update Icon size to 20px in expandable `FlatTableRowHeader`.
Icon size is overridden to 16px in expandable `FlatTableRowHeader`.  
See new test story `ExpandableWithActionPopover`.
=> fix(flat-table-row-header): correct icon size for expandable rows

docs/i18n.mdx, src/components/message/message.component.tsx, src/components/message/message.mdx, src/components/message/message.test.tsx, src/hooks/__internal__/useLocale/useLocale.test.tsx, src/locales/de-de.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts, src/locales/locale.ts
Adds non en-gb translation support for the AI variant in `Message`
Currently, no non en-gb translation support for the AI variant in `Message`
=> feat(message): add de-DE, es-ES, fr-CA and fr-FR locale support for the ai variant

src/components/note/note.component.tsx, src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.component.tsx, src/components/text-editor/__internal__/plugins/ContentEditor/content-editor.style.ts, src/components/text-editor/__internal__/plugins/LinkPreviewer/link-previewer.component.tsx, src/components/text-editor/__internal__/plugins/LinkPreviewer/link-previewer.style.ts, src/components/text-editor/__internal__/plugins/Toolbar/toolbar.component.tsx, src/components/text-editor/__internal__/plugins/Toolbar/toolbar.style.ts, src/components/text-editor/components.test-pw.tsx, src/components/text-editor/text-editor.component.tsx, src/components/text-editor/text-editor.context.ts, src/components/text-editor/text-editor.mdx, src/components/text-editor/text-editor.pw.tsx, src/components/text-editor/text-editor.stories.tsx, src/components/text-editor/text-editor.style.ts, src/components/text-editor/text-editor.test.tsx, src/locales/de-de.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts
adds the `header` and `footer` props, both accept valid react nodes, providing consumers with the ability to pass any elements to assist with control, labelling or additional context above and/or below the editor. The Text editor toolbar has also been moved above the editor, and now has a white background to match recent designs
**Toolbar moved above the editor, background colour changed from grey -> white**
**Added support for a `header` prop which accepts a valid node, passed node(s) are then wrapped and rendered above the editor** 
**Added support for a `footer` prop which accepts a valid node, passed node(s) are then wrapped and rendered below the editor** 
**Toolbar is below the editor, has a grey background colour**
**No support for header/footer custom rendering**
=> feat(text-editor): add header and footer support and align with DS

src/components/select/filterable-select/filterable-select.stories.tsx, src/components/select/simple-select/simple-select.mdx, src/components/select/simple-select/simple-select.stories.tsx
fix #5588
Amend `CustomOptionChildren` storybook example to document how `leftChildren` prop can be used to display an Icon within the input field. 
No documented example in Select docs to show how an Icon can be displayed within the input field.
=> docs(select): document how to use leftChildren prop to display an Icon in the input field

src/__internal__/fieldset/fieldset.component.tsx, src/__internal__/fieldset/fieldset.style.ts, src/__internal__/label/label.component.tsx, src/__internal__/label/label.style.ts, src/components/fieldset/fieldset.component.tsx, src/components/fieldset/fieldset.style.ts, src/locales/de-de.ts, src/locales/en-gb.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts, src/locales/locale.ts
add `de-DE`, `es-ES`, `fr-CA`, `fr-FR` locale support for the optional indicators on `Fieldset` (internal & external) and `Label`
Currently, a hard coded en-GB value for optional is only available, regardless of selected locale
=>  feat(fieldset, label): add de-DE, es-ES, fr-CA, fr-FR locale support for the optional indicators

src/components/loader-bar/loader-bar.component.tsx, src/components/loader-bar/loader-bar.test.tsx, src/components/loader-spinner/loader-spinner.component.tsx, src/components/loader-spinner/loader-spinner.test.tsx, src/components/loader-star/loader-star.component.tsx, src/components/loader-star/loader-star.test.tsx, src/components/loader/loader-square.style.ts, src/components/loader/loader-square.test.tsx, src/components/loader/loader.component.tsx, src/components/loader/loader.test.tsx, src/components/switch/__internal__/switch-slider-panel.test.tsx, src/hooks/useMediaQuery/useMediaQuery.ts
fixes #7240
https://github.com/user-attachments/assets/73d222ff-f8be-45b2-a88d-0fbce17cdcf2
https://github.com/user-attachments/assets/91364182-0fc0-4ae9-96e0-14542e4acb34
Initialises `useMediaQuery` as `undefined` to prevent reduced motion `loading` text from rendering when browser motion preferences are yet to be detected when there is latency on the network or a slow page reload
When there is network latency they reduced motion `loading` text flashes on screen as the browser motion preference is yet to be determined and `useMediaQuery` has an initial value of false.
In useMediaQuery hook useLayoutEffect has been used to make use the matchMedia value is set synchronously before the browser painting. 
Pick any Loader story and set the browser network to 4G or worse and refresh the page, …
=> fix:  ensure there is no flash of reduce motion text in Loader components when page is reloaded

package-lock.json, package.json
Locks `react-day-picker` to v9.3 range as unit tests are failing in later versions
`react-day-picker` is only restricted to v9 major version range
=> chore: restrict react-day-picker to 9.3 range

package-lock.json, package.json
- Bump `vite` from version 6.2.6 to 6.3.4
=> chore(dep-devs): bump vite to version 6.3.4

src/components/button/button.component.tsx
handleClick function inside Button component was introduced to:
* First, manually call internalRef.focus().
* Then, invoke either the SplitButton's onChildButtonClick handler (if the button is inside a SplitButton) or the normal onClick prop.
The Button no longer directly uses the provided onClick inside the JSX; it wraps it with the handleClick.
Buttons properly receive focus on mouse clicks in Safari, which does not automatically focus buttons after mouse interactions by default.
Focus behaviour via keyboard (Tab navigation) remains unchanged.
SplitButton children, which rely on onChildButtonClick, are also automatically covered because the new handleClick preserves the correct event forwarding.
Components like ButtonBar component, which renders child Buttons, and the Button component …
=> fix(button): ensure button focuses on click for Safari compatibility

playwright/components/vertical-menu/responsive-vertical-menu/index.ts, playwright/components/vertical-menu/responsive-vertical-menu/locators.ts, src/components/vertical-menu/index.ts, src/components/vertical-menu/responsive-vertical-menu/__internal__/depth.context.tsx, src/components/vertical-menu/responsive-vertical-menu/__internal__/focus.context.tsx, src/components/vertical-menu/responsive-vertical-menu/components.test-pw.tsx, src/components/vertical-menu/responsive-vertical-menu/index.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/index.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.style.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/index.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.style.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-test.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.context.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.mdx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.pw.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.style.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.test.tsx
This PR adds a new component under Vertical Menu: `ResponsiveVerticalMenu`. This is a two-column menu which is powered by React's Context API and manages complex focus ordering and depth awareness. It is also responsive, switching to a modal sidebar whilst maintaining functionality and structure.
There is currently no vertical menu option available to consumers that supports complex menu structures with many items.
A Storybook example has been provided under VerticalMenu > Responsive > Test that can be used to test the functionality.
=> feat(vertical-menu): implements updates required for Global Nav v2

src/components/switch/__internal__/switch-slider.style.ts
fix #7326
Correct z-index to be lower than the input so that `Switch` is clickable. 
`Switch` components in consuming projects using styled-components v4 are not clickable. 
The style above `z-index: 2;` in switch-slider style file was missing semi-colon and causing this style to not be applied in any projects using using styled-components v5, this was missed as v5 does not handle missing semi-colons. 
In projects using v4, the style is being applied, causing the slider to render over the input.
=> fix(switch): correct z-index in switch-slider

src/components/password/password.component.tsx, src/components/password/password.mdx, src/locales/en-gb.ts, src/locales/locale.ts
fix #7329
Adds `buttonLabelHide`, `buttonLabelShow`, `ariaLabelHide` and `ariaLabelShow` translation keys to `Password`.
Hide/Show button in `Password` has no translations.
=> feat(password): add translation keys for Hide/Show button

package-lock.json, package.json, src/components/decimal/decimal.component.tsx, src/components/decimal/decimal.test.tsx
Decimal should render as expected when using React's strict mode.
Invariant warning of `...switch from uncontrolled to controlled (or vice versa)...` is displayed when Decimal is rendered using React's strict mode.
We decided that we would upgrade RTL during this work so that we could use the `reactStrictMode` render option. Prior to this the solution was the change the global config value of `reactStrictMode: false` to `true` for the test. In v16.3.0 of RTL the `reactStrictMode` render option was released and it is something we can utilise in other unit tests concerning strict mode behaviour. 
To boot up Storybook locally in `Strict Mode`, please run the cmd `npm run start:strict-mode`. Decimal should also be checked without strict mode too. 
- There should be no functional regressions …
=> fix(decimal): ensure invariant message is not thrown when using strict mode - FE-7198

src/components/text-editor/__internal__/plugins/Toolbar/toolbar.test.tsx, src/components/text-editor/index.ts, src/components/text-editor/text-editor.component.tsx, src/components/text-editor/text-editor.mdx, src/components/text-editor/text-editor.stories.tsx, src/components/text-editor/text-editor.test.tsx
fixes #7320 
`TextEditor` now accepts a `forwardRef`, and an imperative handle has been introduced which provides consumers with access to a focus method only.
Tests have been added to establish a baseline for `onChange` behaviour being triggered by toolbar buttons.
`TextEditor` no longer supports a `forwardRef` since its conversion to Lexical, but some consumers rely on passing a ref for programmatic focus control.
Also clicks on toolbar buttons result in `onChange` being triggered, due  previous changes, however there are no tests added to test against this behaviour.
The new programmatic focus story on `TextEditor` should be sufficient enough to test that the new imperative handle does indeed result in the TextEditor being focused
=> feat(text-editor): add programmatic focus support for the text editor

src/components/text-editor/text-editor.component.tsx, src/components/text-editor/text-editor.mdx, src/components/text-editor/text-editor.stories.tsx, src/components/text-editor/text-editor.test.tsx
fixes: #7261
A new optional plugin `customPlugins` has been added to the `TextEditor` which will allow the user to provide their own plugins.
https://github.com/user-attachments/assets/c95be12d-9a48-4ed7-b6e5-a36820a9a36b
The users can not inject their own plugins into the `TextEditor`
=> fix(text-editor): allow custom plugins to be passed to the text editor

src/components/action-popover/__internal__/action-popover.context.ts, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover-menu/action-popover-menu.component.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.pw.tsx, src/components/action-popover/action-popover.style.ts, src/components/action-popover/action-popover.test.tsx
Reduce the amount of internal prop drilling between `ActionPopover` and its subcomponents, by refactoring styling logic to only use CSS where possible.
`ActionPopover` and its subcomponents use a combination of JavaScript and CSS code for handling visuals, such as:
- Controlling the horizontal alignment of each menu item's icons and text
- Controlling the vertical position of a submenu
Comparing `ActionPopover` stories to their production counterparts, verify no regressions have been made to the following:
- Component visuals
- Component behaviour
- Axe scan results
- Screen reader behaviour (test with Safari and macOS VoiceOver, or NVDA and Chrome).
=> refactor(action-popover): simplify styling logic to reduce amount of internal prop drilling

package-lock.json, package.json, src/components/icon/icon-test.stories.tsx, src/components/icon/icon.style.ts, src/components/icon/icon.test.tsx, src/components/pill/pill-test.stories.tsx, src/components/pill/pill.mdx, src/components/pill/pill.pw.tsx, src/components/pill/pill.stories.tsx, src/components/pill/pill.style.ts, src/components/pill/pill.test.tsx, src/components/portrait/__internal__/get-colors.test.ts, src/components/portrait/__internal__/get-colors.ts, src/components/portrait/portrait.style.tsx, src/components/portrait/portrait.test.tsx, src/style/utils/get-accessible-foreground-color.test.ts, src/style/utils/get-accessible-foreground-color.ts, src/style/utils/get-hex-value.test.ts, src/style/utils/get-hex-value.ts
- Remove `polished` dependency. 
- Replace `shade` with CSS. 
- Replace `meetsConstrastGuidelines` with our own custom utils. 
- When using custom colours on Pill, text colour should pass colour contrast checks
- Icon and Pill components use `shade` from polished to determine colours on hover when a custom one is provided. 
- Pill uses `meetsContrastGuidelines` from polished to determine the text and close icon colour when a custom `borderColor` is provided. 
- Some content (text) colours calculated by polished cause colour contrast fails:
=> refactor: replace polished with custom utils

src/components/icon/icon.component.tsx
Remove React key that is no longer needed
`Icon` currently causes React v18.3.0 to log the following warning:
```
Warning: A props object containing a "key" prop is being spread into JSX
```
=> fix(icon): address react 18.3.0 warning regarding spreading keys

src/components/popover-container/popover-container.component.tsx
fixes: #7350
Removed the `aria-hidden` from the tab guards to prevent any accessibility violations.
Currently `tabindex="0"` makes the element focusable and included in the tab order while `aria-hidden="true"` indicates to assistive technologies (like screen readers) that the element should be ignored. This can lead to confusing keyboard navigation  and accessibility violations.
1. Open the popover container storybook page
2. Inspect the container
3. The tab-guard-top and tab-guard-bottom elements should not have the `aria-hidden` attribute.
=> fix(popover-container): aria hidden elements must not be focusable

src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.style.ts
Ensure that both responsive and non-responsive view modes applied the bottom margin to the final item to ensure that scrolling can always occur and that all items are reachable
It is not possible in responsive mode to scroll beyond the final item in a responsive vertical menu, which can lead to the last item being beyond the reach of users
Use the `Test > Default` story under `Vertical Menu > Responsive` and use the browser's device emulator to a small device e.g. an iPhone SE 2nd Gen (or a device running at a resolution of 375x667). Open the menu and ensure that the `Give feedback` menu item is always able to be viewed when scrolling occurs.
=> fix(responsive-vertical-menu): fix issue that stopped off-screen menu items from scrolling into view

src/locales/de-de.ts, src/locales/es-es.ts, src/locales/fr-ca.ts, src/locales/fr-fr.ts
adds `de-DE`, `es-ES`, `fr-CA` and `fr-FR` show/hide related translations
Currently, there is no support for `de-DE`, `es-ES`, `fr-CA` and `fr-FR` show/hide related translations
=> feat(password): add de-DE, es-ES, fr-CA and fr-FR show/hide related translations

src/components/menu/__internal__/submenu/submenu.component.tsx, src/components/menu/menu-item/menu-item.test.tsx, src/components/menu/menu.pw.tsx, src/components/multi-action-button/components.test-pw.tsx, src/components/multi-action-button/multi-action-button.component.tsx, src/components/multi-action-button/multi-action-button.pw.tsx, src/components/multi-action-button/multi-action-button.style.ts, src/components/multi-action-button/multi-action-button.test.tsx, src/components/split-button/split-button-children.style.ts, src/components/split-button/split-button.component.tsx, src/components/split-button/split-button.pw.tsx, src/components/split-button/split-button.test.tsx, src/hooks/__internal__/useChildButtons/useChildButtons.tsx
fix #7264
`Menu`, `MultiActionButton` and `SplitButton`: 
- Maintain focus on toggle button/parent item on submenu open. 
- Do not open submenu with ArrowUp.
- Close submenu with Enter/Space on toggle button/parent item.
`MultiActionButton` and `SplitButton`:
- Closes submenu with Enter/Space or click on toggle button.
- Remove `aria-haspopup` and `add aria-controls` to toggle button.
- Focus border is not covered by hover style on menu buttons.
`Menu`, `MultiActionButton` and `SplitButton`: 
- Focus first menu item on submenu open. 
- Open submenu with ArrowUp.
`MultiActionButton` and `SplitButton`:
- Has `aria-haspopup` on toggle button.
- Focus border is covered by hover style on menu buttons.
All components should:
- Open the submenu with Enter/Space/ArrowDown/Click.
- Close the …
=> fix(menu, multi-action-button, split-button): remove focus first list item on menu-popup open

src/components/date/components.test-pw.tsx, src/components/decimal/decimal-test.stories.tsx, src/components/grouped-character/grouped-character-test.stories.tsx, src/components/number/number-test.stories.tsx, src/components/textbox/textbox-test.stories.tsx, src/components/textbox/utils.ts
The `textbox-test.stories.tsx` file was exporting three helper functions that were incorrectly interpreted as stories and added to the Textbox test stories. However, attempting to load them caused errors. To fix this, the functions were moved to a separate utils file, and the exports were updated accordingly.
Three helper functions exports are incorrectly interpreted as stories and added to the Textbox test stories.
1. Load the Textbox test stories
2. The stories for the helper functions should no longer be present.
=> fix(textbox): test stories load to error

src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.test.tsx
If the menu loses focus during a resize event, the `handleBlur` handler is prevented from closing the menu. This should only be prevented during a resize because the menu should close when losing focus during keyboard navigation.
To achieve this, a new resize event listener has been added. We track whether a resize is in progress by setting a flag (`isResizingRef`) to true in the resize event handler, and resetting it to false using a debounced `setTimeout` after `100ms` of no resize activity. This allows us to detect when the user is actively resizing the window.
In the `handleBlur` logic, we check this flag. If a blur occurs while `isResizingRef` is `true`, we skip closing the menu. This prevents unwanted closures caused by temporary focus shifts during layout reflows or DOM changes …
=> fix(responsive-vertial-menu): menu closes when shrinking the size

src/components/vertical-menu/responsive-vertical-menu/components.test-pw.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-divider/responsive-vertical-menu-divider.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.style.ts, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.context.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.style.ts
fix #7374
- `ResponsiveVerticalMenu` is announced as lists of items when using screen readers. 
- `ResponsiveVerticalMenuItem`s extend the correct length and are aligned on the right when in responsive mode. 
- When `box-sizing: border-box;` style is applied to `ResponsiveVerticalMenu` through a universal selector, the header containing the close button in responsive mode matches the width of the menu:
- `ResponsiveVerticalMenu` is not announced as lists of items when using a screen reader. 
- `ResponsiveVerticalMenuItem`s in a tertiary submenu extended beyond adjacent items in responsive mode.
- When `box-sizing: border-box;` style is applied to `ResponsiveVerticalMenu` through a universal selector, the header containing the close button in responsive mode no longer matches the width of …
=> fix(responsive-vertical-menu): ensure items are rendered within an unordered list

playwright/components/note/index.ts, src/components/note/note.component.tsx, src/components/note/note.test.tsx
title prop in Note component renders using Typography with `variant="h3"`
Styling for H3 for a title prop is being overwritten in a Note component within `with title` story.
=> fix(note): render title semantically with h3 when passed as text

.vscode/settings.json
- Remove legacy config rule in the repo settings for the ESLint VSCode extension
- A legacy config rule, which appears to be removed in ESLint v9, is causing the ESLint VSCode extension to fail each time it runs over files:
```
[Error - 10:17:49] An unexpected error occurred:
[Error - 10:17:49] Error: Invalid Options:
- Unknown options: extensions
- 'extensions' has been removed.
```
=> chore(eslint): remove legacy config rule for vscode extension

package.json
adds `exports` to `package.json` file to allow `npm link` to work from root of carbon
`types` just points to lib ones for now, it's the same file as in `esm`, future work will move this to a shared location to remove duplication
currently npm link only works when called within the `esm` directory as `lib` has it's own `package.json` to support the module aliasing is consumers use `import`
- add a `foo` prop to `ButtonProps` or some other interface in Carbon
- create a project in stackblitz and export it so you can run locally
- `npm install` to install node_modules to the consuming project
- in carbon repo root create the symlink -> `npm link`
- in the consuming project, point the carbon dep at the symlink -> `npm link carbon-react`
- import the component you updated and confirm you can …
=> chore: add exports property to package.json to support npm link from root of project

package-lock.json, package.json
Bumps `typescript` to 5.8.3
Updates:
- @typescript-eslint/parser
- @typescript-eslint/eslint-plugin
- @types/node @types/react
- @types/react-dom
- ts-node
- ts-jest
Typescript is on 5.3 and other dependencies are not on latest
=> chore(typescript): upgrade dependency to latest version (5.8.3)

src/components/button/button-test.stories.tsx, src/style/utils/add-focus-styling.ts
Clicking buttons adds the focus border, which causes Chrome to recalculate element positions and scroll the window. This does not occur in other browsers. This has been fixed by removing the use of "webkit-appreance" in the focus styling.
fix #7412
Investigations showed that the cause of this was the `webkit-appearance` property in the focus styling CSS definition. Removing this aligns Chrome with the other browsers.
When clicking buttons, the page jumps/scrolls, mostly to where you would expect it to if you were using tab keyboard and selected the element in that fashion. This only occurs in Chrome; all other browsers are unaffected.
A Storybook test story has been added to cover this: `Button Focuses Without Scrolling`. To replicate the issue:
- Open said story; 
- Scroll the page until …
=> fix(button, button-minor): fixes a scrolling bug in Chrome when clicking buttons

package.json
Reverts changes to package.json exports
The exports in package.json prevent importing `components`
I'm going to cut a beta to confirm this works before merging
=> fix: revert updates to package.json exports

src/components/date/date-interaction.stories.tsx
The date input is relative, so it can change visually if e.g. today is in the current month, which impacts the snapshots
Set all date interaction values to use a date in the past to ensure nothing visually changes
Chromatic snapshots change if the current date is highlighted within the active month shown in the calendar.
=> docs(date): adjust date interaction stories to prevent failings

src/components/action-popover/__internal__/action-popover.context.ts, src/components/action-popover/action-popover-item/action-popover-item.component.tsx, src/components/action-popover/action-popover.component.tsx, src/components/action-popover/action-popover.pw.tsx, src/components/action-popover/components.test-pw.tsx
We are now maintaining the selected submenu in the action popover context. On state update, we compare the current value and automatically close any submenus that don't match, ensuring only one submenu remains open at a time regardless if it was opened by click event or keyboard event.
https://github.com/user-attachments/assets/8bd5a306-567f-43a9-86c1-26700281147a
Currently if a submenu is opened by keyboard event, and you open a new submenu by mouse event, the first submenu is not closed.
https://github.com/user-attachments/assets/90ae0580-57f4-49c6-aa60-aabec2283f20
1. Go to the default action popover storybook
2. Open the first action popover using the keyboard
3. Use the keyboard to navigate to the first submenu and open it
4. Hover the second submenu with the mouse
5. Click the …
=> fix(action-popover): submenu stays open when another submenu is clicked

src/components/switch/switch-test.stories.tsx, src/components/switch/switch.component.tsx, src/components/switch/switch.style.ts, src/components/switch/switch.test.tsx
fix #7411
`labelHelp` (hint text) has no width restrictions
`labelWidth` can be used to set label and hint text width when `labelInline` is true:
When `reverse` is false, input is aligned to the right and label and hint text are aligned
`labelHelp` (hint text) has max-width of "160px" that cannot be changed
When `reverse` is false, input does not align to the right and label and hint text are not aligned
Controls have been added to `Validation` and `New Validation` test stories, container with limited width has been added to `New Validation Inline` to demonstrate text wrapping. Snapshots for these stories have been enabled.
- Check no width restrictions are set on label or hintText when label is not inline.
- When label is inline, no width should be applied by default.
- `labelWidth` prop …
=> fix(switch): ensure inline hint text takes full width of label container

src/components/password/password-interaction.stories.tsx
Add Play Functions for `Password`.
There are currently no Play Functions  for the `Password` component.
Ensure interactions play as expected without error.
=> test(password): add play functions

src/components/link/link-test.stories.tsx, src/components/link/link.component.tsx, src/components/link/link.mdx, src/components/link/link.pw.tsx, src/components/link/link.stories.tsx, src/components/link/link.style.ts, src/components/link/link.test.tsx
Adds the subtle variant to `Link`, also adds the `underline` prop, which when set to `"false"` removes `text-decoration: underline` from the component.
A test story has also been added to create a baseline for the use of both props when used simultaneously.
N/A
=> feat(link): add subtle variant & underline prop

src/components/box/box.component.tsx, src/components/box/box.style.ts, src/components/box/box.test.tsx, src/components/hr/hr.component.tsx, src/components/hr/hr.mdx, src/components/hr/hr.stories.tsx, src/components/hr/hr.style.ts, src/components/hr/hr.test.tsx, src/components/link/link.style.ts, src/components/menu/menu-item/menu-item.style.ts, src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.mdx, src/components/popover-container/popover-container.stories.tsx, src/components/popover-container/popover-container.style.ts, src/components/popover-container/popover-container.test.tsx
Adds the `type` prop with a `"inverse"` option to `Hr`
Adds the center positon to `PopoverContainer`
Adds the `borderRadius` prop to `PopoverContainer`
Adds the `offset` prop to `PopoverContainer`
Adds the `data-popover-container-button` to `renderOpenComponent`'s to prop interface
Adds multiple border radius value support to `Box`
Adds conditional rendering for the `title` prop on `PopoverContainer`
adds a test story for the primary open button responsive example
No `type` prop on `Hr`
No ability to center the `PopoverContainer`
No ability to set a border radius on `PopoverContainer`
No ability to add an offset to `PopoverContainer`
An empty title container is rendered even when `title` is not passed
Only one border radius value can be used on `Box`
`data-popover-container-button` is not …
=> feat(popover-container): various design updates

src/components/badge/badge-test.stories.tsx, src/components/badge/badge.component.tsx, src/components/badge/badge.mdx, src/components/badge/badge.pw.tsx, src/components/badge/badge.stories.tsx, src/components/badge/badge.style.ts, src/components/badge/badge.test.tsx, src/components/badge/components.test-pw.tsx, src/components/tabs/__internal__/tab-title/tab-title.component.tsx
Align `Badge` component with the new beta DS:
- Deprecate `onClick`, `aria-label` and `color` props. 
- Make `children` optional to render `Badge` as a standalone component.
- Allow `counter` prop to accept number or string values - numbers greater than `1000` will display as `999+`, strings longer than 4 characters will be trimmed (e.g. `12345` will display `1234`). 
- Add `size` prop which accepts "small", "medium" and "large".
- Add `variant` prop which accepts "typical" and "subtle" variants. 
- Add `inverse` prop to apply inverse styles to badge. 
`Badge` component is not in line with the new beta DS.
All stories should support controls for testing purposes - "Default" test story has controls to set `counterAsString` and `counterAsNumber`.
- Counter should not be displayed in small …
=> feat(badge): align with beta DS

src/components/vertical-menu/responsive-vertical-menu/__internal__/focus.context.tsx, src/components/vertical-menu/responsive-vertical-menu/components.test-pw.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-interaction.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-test.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.context.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.mdx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.pw.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.stories.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.test.tsx
- Moves secondary menu element to be a child of the primary menu instead of a sibling to ensure correct screen reader behaviour. 
https://github.com/user-attachments/assets/16964dbf-a351-4551-890d-3b684526f109
- Children of last tertiary item in secondary menu are accessible via Tab.
https://github.com/user-attachments/assets/119d70fb-7a27-40c4-bff3-f24f88652dea
- Secondary menu element is a sibling of the primary menu, meaning screen readers will navigate through all of the items within the primary menu before moving onto the secondary.
https://github.com/user-attachments/assets/6bc6434d-91a9-4210-8335-fb0264610cf2
- Children of last tertiary item in secondary menu are not accessible via Tab.
https://github.com/user-attachments/assets/6ab6924e-6859-46b9-a062-45dcaf28f3fe
Additional …
=> fix(responsive-vertical-menu): ensure secondary menu is a child of primary

src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu-item/responsive-vertical-menu-item.component.tsx, src/components/vertical-menu/responsive-vertical-menu/responsive-vertical-menu.component.tsx
- Adjust menu items to only report their expansion status if not responsive **and** at depth level of 0;
- Remove `aria-haspopup` entirely, as it adds no real value given the menu semantics.
- In responsive mode, the top-level menu headings still retain their `expanded` mark-up despite no longer being expandable/collapsible
- `aria-haspopup` conveys that the responsive menu is an actual menu, whereas it is a menu in name only (functionally it's more akin to `nav`)
Using Safari and VO:
- Open a responsive menu story with nested items and switch to responsive mode;
- Tab onto the launcher button and ensure it is announced as such (i.e. as a button, not a dialogue, web popup, etc.);
- Using the keyboard, navigate focus to the top-level item and ensure that it is not flagged as `expanded`.
=> fix(responsive-vertical-menu): fixes how screen readers announce the menu

src/components/card/card-footer/card-footer.style.ts
Updates the link style for the `Card` footer, following audit changes to the `Link `component
Links in the `Card` footer have a `fontWeight` applied.
Check the link styling in the Card footer is no longer bold and no regressions have been introduced.
=> fix(card): fix link styling in card footer

src/components/date-range/date-range-interactions.stories.tsx
Story relies on `handleOnKeyDown`, so onBlur is not fired, when switching between two fields.
DateRange calls `onBlur` even when the user is just switching between the start and end inputs
=> test(date-range): change date to avoid incorrect snapshot change

src/components/link/link.stories.tsx
This piece of work adds a `subtle` variant example to variants docs of the Link component
fixes #7489
- Adds a `subtle` example of Link to the `Variants` part of the documentations.
- Fix an issue in Firefox where the `br` tags aren't applied, causing no space between the examples.
- A `subtle` variant example is only included in the `Dark Background` part of the docs.
- Firefox has an issue where the `br` tags aren't applied, causing no space between the examples/
N/A
- An additional example should be displayed in the `Variants` examples. This is example should be the `subtle` variant and it should be appear against a dark background. 
- There should be no other regressions relating to the Link documentation and no new AXE accessibility violations. 
- Ensure that the updated Chromatic …
=> docs(link): add subtle to variant examples - FE-7453

src/components/menu/menu-item/menu-item.style.ts, src/components/menu/menu-test.stories.tsx
We have had an issue reported where the CSS seems to be loading in an incorrect order. The solution to this is to increase the specificity of the CSS we need applying.
fixes #7497
Increase specificity of `padding: 11px 16px` styling code so that it is consistently applied.
We have had a case where `padding: 11px 16px` styling has been overriden with `padding: 0px` causing a visual issue.
This issue is very difficult to recreate as it relies on the browser loading the CSS in an order where `padding: 0px` takes precedence. 
There should be no visual regressions to menu-item styling.
=> fix(menu-item): increase specificity for links that don't contain buttons - FE-7456

src/components/pill/pill-test.stories.tsx, src/components/pill/pill.pw.tsx, src/components/pill/pill.stories.tsx, src/components/pill/pill.style.ts, src/components/pill/pill.test.tsx, src/components/select/multi-select/multi-select-test.stories.tsx
fix #7530
Long words within `Pill` wrap and do not overflow the container. 
`Pill` with a very long word overflows Pill when width is constrained.
=> fix(pill): ensure long words do not overflow

src/components/dialog/dialog-test.stories.tsx, src/components/dialog/dialog.style.ts, src/components/dialog/dialog.test.tsx, src/components/sidebar/sidebar.style.ts, src/components/sidebar/sidebar.test.tsx
When the `Dialog` is in full screen, the backgroudn color is white (`var(--colorsUtilityYang100)`). If the prop `greybackground` is set to true the background color changes to grey (`var(--colorsUtilityMajor025)`).
The `Sidebar` component background color has been updated from grey (var(--colorsUtilityMajor025)) to white (var(--colorsUtilityYang100)).
When the `Dialog` has full screen set to true the background is hardcoded to grey and there is no way for the user to change this. 
The `Sidebar` component uses by default a grey background.
=> fix(dialog,sidebar): background color not defaulting to white

src/components/popover-container/popover-container-test.stories.tsx, src/components/popover-container/popover-container.component.tsx, src/components/popover-container/popover-container.test.tsx
fix #7549
Ensures `onClose` is only called when the container element is in an open state.
The `onClose` callback is called when use presses escape key but popover is closed
Test story added for QA
=> fix(popover-container): ensure onClose is only called when container is an open state

docs/i18n.mdx, src/components/grouped-character/grouped-character.mdx, src/components/number/number.mdx, src/components/password/password.mdx, src/components/text-editor/text-editor.mdx, src/components/vertical-menu/vertical-menu.mdx
i18n docs are now super good  (adds missing translation keys table to respective components, fixes broken links in our i18n keys table and improves accessibility via improved announcements for AT)
i18n docs weren't super good
=> docs: i18n improvements 

src/__internal__/character-count/character-count.component.tsx, src/__internal__/character-count/character-count.style.ts, src/__internal__/character-count/character-count.test.tsx, src/__internal__/fieldset/fieldset.component.tsx, src/__internal__/fieldset/fieldset.style.ts, src/__internal__/fieldset/fieldset.test.tsx, src/__internal__/hint-text/hint-text.component.tsx, src/__internal__/hint-text/hint-text.style.tsx, src/__internal__/hint-text/hint-text.test.tsx, src/__internal__/label/label.component.tsx, src/__internal__/label/label.style.ts, src/__internal__/label/label.test.tsx, src/__internal__/validation-message/validation-message.component.tsx, src/__internal__/validation-message/validation-message.style.ts, src/__internal__/validation-message/validation-message.test.tsx
Adds `isLarge` prop to internal `Label`, `HintText`, `ValidationMessage`, `CharacterCount` and `Fieldset` components to set 16px font-size for "large" sizes. 
Font-size of `Label`, `HintText`, `ValidationMessage`, `CharacterCount` and `Fieldset` is always 14px.
=> chore: add isLarge prop to internal components

src/components/multi-action-button/multi-action-button-test.stories.tsx, src/components/multi-action-button/multi-action-button.test.tsx, src/components/split-button/split-button.test.tsx, src/hooks/__internal__/useChildButtons/useChildButtons.tsx, src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.test.tsx, src/hooks/__internal__/useMenuKeyboardNavigation/useMenuKeyboardNavigation.ts
addresses #7531
- Observe the popup element itself to detect when it loses focus, and close it if so. Ensures that click events on child buttons fire correctly, regardless of where the component resides on the page.
https://github.com/user-attachments/assets/890ae9c4-903b-4121-8438-bf5edf0fca92
- In Safari, when a `MultiActionButton` is within a `Dialog`, clicking a child button inside the popup doesn't fire a click event. This is caused by Safari's event timing combined with our use of window-level blur listeners.
https://github.com/user-attachments/assets/8e9d84ca-dd48-4344-90e1-69b57f8cb046
For Safari, Chrome, Edge and Firefox, check the following behaviour within the new "Within Dialog" test story for `MultiActionButton`. Compare behaviour to the original [bug …
=> fix(multi-action-button): prevent popup closing too early

src/__spec_helper__/__internal__/test-utils.ts, src/components/badge/badge.test.tsx, src/components/textarea/textarea.test.tsx
Create a new helper util for testing: `assertDeprecationWarning`. This can be used in place of e.g.:
Example:
```ts
test("should log a deprecation warning for onClick prop", () => {
assertDeprecationWarning({
component: <Badge onClick={() => {}} />,
deprecationMessage:
"The `onClick` prop in `Badge` is deprecated and will soon be removed.",
});
});
```
The helper also takes a third option, `method`, which can be used to test `Logger.warn` and `Logger.error`. `Logger.deprecate` is used as the default option if this is not set.
There are a number of test scenarios that use variations on a similar approach to test that the deprecation warnings from `Logger`, but the implementation is inconsistent.
Example:
```ts
test("should log a deprecation warning for onClick prop", () => {
const …
```
=> test(test-utils): adds a helper to replace Logger deprecation checks
